namespace CUS_INV
{
    partial class frmViewInvLotHistory
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer2 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer2 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer3 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer3 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer4 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer4 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer1 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer1 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer5 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer5 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer6 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer6 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer7 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer7 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer8 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer8 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer11 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer11 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer12 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer12 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer9 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer9 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer10 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer10 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer13 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer13 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer14 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer14 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer15 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer15 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer16 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer16 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer17 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer17 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer18 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer18 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer19 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer19 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer20 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer20 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer21 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer21 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer22 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer22 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer23 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer23 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer24 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer24 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer25 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer25 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer26 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer26 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer27 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer27 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer28 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer28 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer29 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer29 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer30 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer30 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer31 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer31 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer32 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer32 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            FarPoint.Win.Spread.DefaultFocusIndicatorRenderer defaultFocusIndicatorRenderer1 = new FarPoint.Win.Spread.DefaultFocusIndicatorRenderer();
            FarPoint.Win.Spread.DefaultScrollBarRenderer defaultScrollBarRenderer1 = new FarPoint.Win.Spread.DefaultScrollBarRenderer();
            FarPoint.Win.Spread.NamedStyle namedStyle1 = new FarPoint.Win.Spread.NamedStyle("Style4");
            FarPoint.Win.Spread.CellType.FilterBarCellType filterBarCellType1 = new FarPoint.Win.Spread.CellType.FilterBarCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle2 = new FarPoint.Win.Spread.NamedStyle("Style5");
            FarPoint.Win.Spread.NamedStyle namedStyle3 = new FarPoint.Win.Spread.NamedStyle("DataAreaDefault");
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType1 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle4 = new FarPoint.Win.Spread.NamedStyle("Style1");
            FarPoint.Win.BevelBorder bevelBorder1 = new FarPoint.Win.BevelBorder(FarPoint.Win.BevelBorderType.Lowered);
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType2 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle5 = new FarPoint.Win.Spread.NamedStyle("FilterBarDefault");
            FarPoint.Win.Spread.CellType.FilterBarCellType filterBarCellType2 = new FarPoint.Win.Spread.CellType.FilterBarCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle6 = new FarPoint.Win.Spread.NamedStyle("HeaderDefault");
            FarPoint.Win.Spread.NamedStyle namedStyle7 = new FarPoint.Win.Spread.NamedStyle("Style3");
            FarPoint.Win.Spread.NamedStyle namedStyle8 = new FarPoint.Win.Spread.NamedStyle("RowHeaderDefault");
            FarPoint.Win.Spread.NamedStyle namedStyle9 = new FarPoint.Win.Spread.NamedStyle("Style2");
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType3 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.SpreadSkin spreadSkin1 = new FarPoint.Win.Spread.SpreadSkin();
            FarPoint.Win.Spread.DefaultScrollBarRenderer defaultScrollBarRenderer2 = new FarPoint.Win.Spread.DefaultScrollBarRenderer();
            FarPoint.Win.Spread.StatusBarSkin statusBarSkin1 = new FarPoint.Win.Spread.StatusBarSkin();
            FarPoint.Win.Spread.DefaultScrollBarRenderer defaultScrollBarRenderer3 = new FarPoint.Win.Spread.DefaultScrollBarRenderer();
            FarPoint.Win.BevelBorder bevelBorder2 = new FarPoint.Win.BevelBorder(FarPoint.Win.BevelBorderType.Lowered);
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType1 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType2 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType3 = new FarPoint.Win.Spread.CellType.NumberCellType();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            this.txtInvLotID = new System.Windows.Forms.TextBox();
            this.lblInvLotId = new System.Windows.Forms.Label();
            this.grpInvLotList = new Infragistics.Win.Misc.UltraGroupBox();
            this.spdInvLotList = new FarPoint.Win.Spread.FpSpread();
            this.spdInvLotList_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.btnExcel = new Infragistics.Win.Misc.UltraButton();
            this.pnlStsCond.SuspendLayout();
            this.pnlMID.SuspendLayout();
            this.pnlBottom.SuspendLayout();
            this.pnlCenter.SuspendLayout();
            this.pnlTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grpInvLotList)).BeginInit();
            this.grpInvLotList.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.spdInvLotList)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdInvLotList_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // pnlStsCond
            // 
            this.pnlStsCond.Controls.Add(this.txtInvLotID);
            this.pnlStsCond.Controls.Add(this.lblInvLotId);
            this.pnlStsCond.Controls.SetChildIndex(this.pnlStsCond3, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.pnlStsCond2, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.lblInvLotId, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.txtInvLotID, 0);
            // 
            // pnlMID
            // 
            this.pnlMID.Controls.Add(this.grpInvLotList);
            this.pnlMID.Controls.SetChildIndex(this.lblFormName, 0);
            this.pnlMID.Controls.SetChildIndex(this.pnlStsCond, 0);
            this.pnlMID.Controls.SetChildIndex(this.lblDirectQuery, 0);
            this.pnlMID.Controls.SetChildIndex(this.grpInvLotList, 0);
            // 
            // lblFormName
            // 
            this.lblFormName.Size = new System.Drawing.Size(276, 37);
            this.lblFormName.Text = "View Inv Lot History";
            // 
            // btnView
            // 
            this.btnView.Click += new System.EventHandler(this.btnView_Click);
            // 
            // pnlBottom
            // 
            this.pnlBottom.Controls.Add(this.btnExcel);
            this.pnlBottom.Controls.SetChildIndex(this.btnClose, 0);
            this.pnlBottom.Controls.SetChildIndex(this.btnView, 0);
            this.pnlBottom.Controls.SetChildIndex(this.btnExcel, 0);
            // 
            // pnlTop
            // 
            this.pnlTop.Size = new System.Drawing.Size(1239, 0);
            // 
            // lblFormTitle
            // 
            this.lblFormTitle.Size = new System.Drawing.Size(1235, 0);
            this.lblFormTitle.Text = "ViewForm01";
            columnHeaderRenderer2.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer2.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer2.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer2.Name = "columnHeaderRenderer2";
            columnHeaderRenderer2.PictureZoomEffect = false;
            columnHeaderRenderer2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer2.TextRotationAngle = 0D;
            columnHeaderRenderer2.ZoomFactor = 1F;
            rowHeaderRenderer2.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer2.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer2.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer2.Name = "rowHeaderRenderer2";
            rowHeaderRenderer2.PictureZoomEffect = false;
            rowHeaderRenderer2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer2.TextRotationAngle = 0D;
            rowHeaderRenderer2.ZoomFactor = 1F;
            columnHeaderRenderer3.Name = "columnHeaderRenderer3";
            columnHeaderRenderer3.PictureZoomEffect = false;
            columnHeaderRenderer3.TextRotationAngle = 0D;
            columnHeaderRenderer3.ZoomFactor = 1F;
            rowHeaderRenderer3.Name = "rowHeaderRenderer3";
            rowHeaderRenderer3.PictureZoomEffect = false;
            rowHeaderRenderer3.TextRotationAngle = 0D;
            rowHeaderRenderer3.ZoomFactor = 1F;
            columnHeaderRenderer4.Name = "columnHeaderRenderer4";
            columnHeaderRenderer4.PictureZoomEffect = false;
            columnHeaderRenderer4.TextRotationAngle = 0D;
            columnHeaderRenderer4.ZoomFactor = 1F;
            rowHeaderRenderer4.Name = "rowHeaderRenderer4";
            rowHeaderRenderer4.PictureZoomEffect = false;
            rowHeaderRenderer4.TextRotationAngle = 0D;
            rowHeaderRenderer4.ZoomFactor = 1F;
            columnHeaderRenderer1.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer1.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer1.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer1.Name = "columnHeaderRenderer1";
            columnHeaderRenderer1.PictureZoomEffect = false;
            columnHeaderRenderer1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer1.TextRotationAngle = 0D;
            columnHeaderRenderer1.ZoomFactor = 1F;
            rowHeaderRenderer1.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer1.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer1.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer1.Name = "rowHeaderRenderer1";
            rowHeaderRenderer1.PictureZoomEffect = false;
            rowHeaderRenderer1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer1.TextRotationAngle = 0D;
            rowHeaderRenderer1.ZoomFactor = 1F;
            columnHeaderRenderer5.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer5.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer5.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer5.Name = "columnHeaderRenderer5";
            columnHeaderRenderer5.PictureZoomEffect = false;
            columnHeaderRenderer5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer5.TextRotationAngle = 0D;
            columnHeaderRenderer5.ZoomFactor = 1F;
            rowHeaderRenderer5.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer5.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer5.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer5.Name = "rowHeaderRenderer5";
            rowHeaderRenderer5.PictureZoomEffect = false;
            rowHeaderRenderer5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer5.TextRotationAngle = 0D;
            rowHeaderRenderer5.ZoomFactor = 1F;
            columnHeaderRenderer6.Name = "columnHeaderRenderer6";
            columnHeaderRenderer6.PictureZoomEffect = false;
            columnHeaderRenderer6.TextRotationAngle = 0D;
            columnHeaderRenderer6.ZoomFactor = 1F;
            rowHeaderRenderer6.Name = "rowHeaderRenderer6";
            rowHeaderRenderer6.PictureZoomEffect = false;
            rowHeaderRenderer6.TextRotationAngle = 0D;
            rowHeaderRenderer6.ZoomFactor = 1F;
            columnHeaderRenderer7.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer7.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer7.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer7.Name = "columnHeaderRenderer7";
            columnHeaderRenderer7.PictureZoomEffect = false;
            columnHeaderRenderer7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer7.TextRotationAngle = 0D;
            columnHeaderRenderer7.ZoomFactor = 1F;
            rowHeaderRenderer7.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer7.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer7.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer7.Name = "rowHeaderRenderer7";
            rowHeaderRenderer7.PictureZoomEffect = false;
            rowHeaderRenderer7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer7.TextRotationAngle = 0D;
            rowHeaderRenderer7.ZoomFactor = 1F;
            columnHeaderRenderer8.Name = "columnHeaderRenderer8";
            columnHeaderRenderer8.PictureZoomEffect = false;
            columnHeaderRenderer8.TextRotationAngle = 0D;
            columnHeaderRenderer8.ZoomFactor = 1F;
            rowHeaderRenderer8.Name = "rowHeaderRenderer8";
            rowHeaderRenderer8.PictureZoomEffect = false;
            rowHeaderRenderer8.TextRotationAngle = 0D;
            rowHeaderRenderer8.ZoomFactor = 1F;
            columnHeaderRenderer11.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer11.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer11.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer11.Name = "columnHeaderRenderer11";
            columnHeaderRenderer11.PictureZoomEffect = false;
            columnHeaderRenderer11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer11.TextRotationAngle = 0D;
            columnHeaderRenderer11.ZoomFactor = 1F;
            rowHeaderRenderer11.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer11.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer11.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer11.Name = "rowHeaderRenderer11";
            rowHeaderRenderer11.PictureZoomEffect = false;
            rowHeaderRenderer11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer11.TextRotationAngle = 0D;
            rowHeaderRenderer11.ZoomFactor = 1F;
            columnHeaderRenderer12.Name = "columnHeaderRenderer12";
            columnHeaderRenderer12.PictureZoomEffect = false;
            columnHeaderRenderer12.TextRotationAngle = 0D;
            columnHeaderRenderer12.ZoomFactor = 1F;
            rowHeaderRenderer12.Name = "rowHeaderRenderer12";
            rowHeaderRenderer12.PictureZoomEffect = false;
            rowHeaderRenderer12.TextRotationAngle = 0D;
            rowHeaderRenderer12.ZoomFactor = 1F;
            columnHeaderRenderer9.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer9.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer9.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer9.Name = "columnHeaderRenderer9";
            columnHeaderRenderer9.PictureZoomEffect = false;
            columnHeaderRenderer9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer9.TextRotationAngle = 0D;
            columnHeaderRenderer9.ZoomFactor = 1F;
            rowHeaderRenderer9.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer9.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer9.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer9.Name = "rowHeaderRenderer9";
            rowHeaderRenderer9.PictureZoomEffect = false;
            rowHeaderRenderer9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer9.TextRotationAngle = 0D;
            rowHeaderRenderer9.ZoomFactor = 1F;
            columnHeaderRenderer10.Name = "columnHeaderRenderer10";
            columnHeaderRenderer10.PictureZoomEffect = false;
            columnHeaderRenderer10.TextRotationAngle = 0D;
            columnHeaderRenderer10.ZoomFactor = 1F;
            rowHeaderRenderer10.Name = "rowHeaderRenderer10";
            rowHeaderRenderer10.PictureZoomEffect = false;
            rowHeaderRenderer10.TextRotationAngle = 0D;
            rowHeaderRenderer10.ZoomFactor = 1F;
            columnHeaderRenderer13.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer13.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer13.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer13.Name = "columnHeaderRenderer13";
            columnHeaderRenderer13.PictureZoomEffect = false;
            columnHeaderRenderer13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer13.TextRotationAngle = 0D;
            columnHeaderRenderer13.ZoomFactor = 1F;
            rowHeaderRenderer13.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer13.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer13.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer13.Name = "rowHeaderRenderer13";
            rowHeaderRenderer13.PictureZoomEffect = false;
            rowHeaderRenderer13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer13.TextRotationAngle = 0D;
            rowHeaderRenderer13.ZoomFactor = 1F;
            columnHeaderRenderer14.Name = "columnHeaderRenderer14";
            columnHeaderRenderer14.PictureZoomEffect = false;
            columnHeaderRenderer14.TextRotationAngle = 0D;
            columnHeaderRenderer14.ZoomFactor = 1F;
            rowHeaderRenderer14.Name = "rowHeaderRenderer14";
            rowHeaderRenderer14.PictureZoomEffect = false;
            rowHeaderRenderer14.TextRotationAngle = 0D;
            rowHeaderRenderer14.ZoomFactor = 1F;
            columnHeaderRenderer15.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer15.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer15.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer15.Name = "columnHeaderRenderer15";
            columnHeaderRenderer15.PictureZoomEffect = false;
            columnHeaderRenderer15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer15.TextRotationAngle = 0D;
            columnHeaderRenderer15.ZoomFactor = 1F;
            rowHeaderRenderer15.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer15.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer15.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer15.Name = "rowHeaderRenderer15";
            rowHeaderRenderer15.PictureZoomEffect = false;
            rowHeaderRenderer15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer15.TextRotationAngle = 0D;
            rowHeaderRenderer15.ZoomFactor = 1F;
            columnHeaderRenderer16.Name = "columnHeaderRenderer16";
            columnHeaderRenderer16.PictureZoomEffect = false;
            columnHeaderRenderer16.TextRotationAngle = 0D;
            columnHeaderRenderer16.ZoomFactor = 1F;
            rowHeaderRenderer16.Name = "rowHeaderRenderer16";
            rowHeaderRenderer16.PictureZoomEffect = false;
            rowHeaderRenderer16.TextRotationAngle = 0D;
            rowHeaderRenderer16.ZoomFactor = 1F;
            columnHeaderRenderer17.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer17.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer17.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer17.Name = "columnHeaderRenderer17";
            columnHeaderRenderer17.PictureZoomEffect = false;
            columnHeaderRenderer17.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer17.TextRotationAngle = 0D;
            columnHeaderRenderer17.ZoomFactor = 1F;
            rowHeaderRenderer17.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer17.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer17.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer17.Name = "rowHeaderRenderer17";
            rowHeaderRenderer17.PictureZoomEffect = false;
            rowHeaderRenderer17.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer17.TextRotationAngle = 0D;
            rowHeaderRenderer17.ZoomFactor = 1F;
            columnHeaderRenderer18.Name = "columnHeaderRenderer18";
            columnHeaderRenderer18.PictureZoomEffect = false;
            columnHeaderRenderer18.TextRotationAngle = 0D;
            columnHeaderRenderer18.ZoomFactor = 1F;
            rowHeaderRenderer18.Name = "rowHeaderRenderer18";
            rowHeaderRenderer18.PictureZoomEffect = false;
            rowHeaderRenderer18.TextRotationAngle = 0D;
            rowHeaderRenderer18.ZoomFactor = 1F;
            columnHeaderRenderer19.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer19.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer19.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer19.Name = "columnHeaderRenderer19";
            columnHeaderRenderer19.PictureZoomEffect = false;
            columnHeaderRenderer19.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer19.TextRotationAngle = 0D;
            columnHeaderRenderer19.ZoomFactor = 1F;
            rowHeaderRenderer19.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer19.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer19.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer19.Name = "rowHeaderRenderer19";
            rowHeaderRenderer19.PictureZoomEffect = false;
            rowHeaderRenderer19.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer19.TextRotationAngle = 0D;
            rowHeaderRenderer19.ZoomFactor = 1F;
            columnHeaderRenderer20.Name = "columnHeaderRenderer20";
            columnHeaderRenderer20.PictureZoomEffect = false;
            columnHeaderRenderer20.TextRotationAngle = 0D;
            columnHeaderRenderer20.ZoomFactor = 1F;
            rowHeaderRenderer20.Name = "rowHeaderRenderer20";
            rowHeaderRenderer20.PictureZoomEffect = false;
            rowHeaderRenderer20.TextRotationAngle = 0D;
            rowHeaderRenderer20.ZoomFactor = 1F;
            columnHeaderRenderer21.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer21.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer21.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer21.Name = "columnHeaderRenderer21";
            columnHeaderRenderer21.PictureZoomEffect = false;
            columnHeaderRenderer21.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer21.TextRotationAngle = 0D;
            columnHeaderRenderer21.ZoomFactor = 1F;
            rowHeaderRenderer21.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer21.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer21.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer21.Name = "rowHeaderRenderer21";
            rowHeaderRenderer21.PictureZoomEffect = false;
            rowHeaderRenderer21.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer21.TextRotationAngle = 0D;
            rowHeaderRenderer21.ZoomFactor = 1F;
            columnHeaderRenderer22.Name = "columnHeaderRenderer22";
            columnHeaderRenderer22.PictureZoomEffect = false;
            columnHeaderRenderer22.TextRotationAngle = 0D;
            columnHeaderRenderer22.ZoomFactor = 1F;
            rowHeaderRenderer22.Name = "rowHeaderRenderer22";
            rowHeaderRenderer22.PictureZoomEffect = false;
            rowHeaderRenderer22.TextRotationAngle = 0D;
            rowHeaderRenderer22.ZoomFactor = 1F;
            columnHeaderRenderer23.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer23.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer23.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer23.Name = "columnHeaderRenderer23";
            columnHeaderRenderer23.PictureZoomEffect = false;
            columnHeaderRenderer23.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer23.TextRotationAngle = 0D;
            columnHeaderRenderer23.ZoomFactor = 1F;
            rowHeaderRenderer23.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer23.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer23.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer23.Name = "rowHeaderRenderer23";
            rowHeaderRenderer23.PictureZoomEffect = false;
            rowHeaderRenderer23.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer23.TextRotationAngle = 0D;
            rowHeaderRenderer23.ZoomFactor = 1F;
            columnHeaderRenderer24.Name = "columnHeaderRenderer24";
            columnHeaderRenderer24.PictureZoomEffect = false;
            columnHeaderRenderer24.TextRotationAngle = 0D;
            columnHeaderRenderer24.ZoomFactor = 1F;
            rowHeaderRenderer24.Name = "rowHeaderRenderer24";
            rowHeaderRenderer24.PictureZoomEffect = false;
            rowHeaderRenderer24.TextRotationAngle = 0D;
            rowHeaderRenderer24.ZoomFactor = 1F;
            columnHeaderRenderer25.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer25.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer25.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer25.Name = "columnHeaderRenderer25";
            columnHeaderRenderer25.PictureZoomEffect = false;
            columnHeaderRenderer25.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer25.TextRotationAngle = 0D;
            columnHeaderRenderer25.ZoomFactor = 1F;
            rowHeaderRenderer25.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer25.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer25.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer25.Name = "rowHeaderRenderer25";
            rowHeaderRenderer25.PictureZoomEffect = false;
            rowHeaderRenderer25.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer25.TextRotationAngle = 0D;
            rowHeaderRenderer25.ZoomFactor = 1F;
            columnHeaderRenderer26.Name = "columnHeaderRenderer26";
            columnHeaderRenderer26.PictureZoomEffect = false;
            columnHeaderRenderer26.TextRotationAngle = 0D;
            columnHeaderRenderer26.ZoomFactor = 1F;
            rowHeaderRenderer26.Name = "rowHeaderRenderer26";
            rowHeaderRenderer26.PictureZoomEffect = false;
            rowHeaderRenderer26.TextRotationAngle = 0D;
            rowHeaderRenderer26.ZoomFactor = 1F;
            columnHeaderRenderer27.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer27.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer27.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer27.Name = "columnHeaderRenderer27";
            columnHeaderRenderer27.PictureZoomEffect = false;
            columnHeaderRenderer27.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer27.TextRotationAngle = 0D;
            columnHeaderRenderer27.ZoomFactor = 1F;
            rowHeaderRenderer27.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer27.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer27.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer27.Name = "rowHeaderRenderer27";
            rowHeaderRenderer27.PictureZoomEffect = false;
            rowHeaderRenderer27.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer27.TextRotationAngle = 0D;
            rowHeaderRenderer27.ZoomFactor = 1F;
            columnHeaderRenderer28.Name = "columnHeaderRenderer28";
            columnHeaderRenderer28.PictureZoomEffect = false;
            columnHeaderRenderer28.TextRotationAngle = 0D;
            columnHeaderRenderer28.ZoomFactor = 1F;
            rowHeaderRenderer28.Name = "rowHeaderRenderer28";
            rowHeaderRenderer28.PictureZoomEffect = false;
            rowHeaderRenderer28.TextRotationAngle = 0D;
            rowHeaderRenderer28.ZoomFactor = 1F;
            columnHeaderRenderer29.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer29.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer29.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer29.Name = "columnHeaderRenderer29";
            columnHeaderRenderer29.PictureZoomEffect = false;
            columnHeaderRenderer29.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer29.TextRotationAngle = 0D;
            columnHeaderRenderer29.ZoomFactor = 1F;
            rowHeaderRenderer29.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer29.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer29.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer29.Name = "rowHeaderRenderer29";
            rowHeaderRenderer29.PictureZoomEffect = false;
            rowHeaderRenderer29.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer29.TextRotationAngle = 0D;
            rowHeaderRenderer29.ZoomFactor = 1F;
            columnHeaderRenderer30.Name = "columnHeaderRenderer30";
            columnHeaderRenderer30.PictureZoomEffect = false;
            columnHeaderRenderer30.TextRotationAngle = 0D;
            columnHeaderRenderer30.ZoomFactor = 1F;
            rowHeaderRenderer30.Name = "rowHeaderRenderer30";
            rowHeaderRenderer30.PictureZoomEffect = false;
            rowHeaderRenderer30.TextRotationAngle = 0D;
            rowHeaderRenderer30.ZoomFactor = 1F;
            columnHeaderRenderer31.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer31.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer31.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer31.Name = "columnHeaderRenderer31";
            columnHeaderRenderer31.PictureZoomEffect = false;
            columnHeaderRenderer31.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer31.TextRotationAngle = 0D;
            columnHeaderRenderer31.ZoomFactor = 1F;
            rowHeaderRenderer31.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer31.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer31.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer31.Name = "rowHeaderRenderer31";
            rowHeaderRenderer31.PictureZoomEffect = false;
            rowHeaderRenderer31.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer31.TextRotationAngle = 0D;
            rowHeaderRenderer31.ZoomFactor = 1F;
            columnHeaderRenderer32.Name = "columnHeaderRenderer32";
            columnHeaderRenderer32.PictureZoomEffect = false;
            columnHeaderRenderer32.TextRotationAngle = 0D;
            columnHeaderRenderer32.ZoomFactor = 1F;
            rowHeaderRenderer32.Name = "rowHeaderRenderer32";
            rowHeaderRenderer32.PictureZoomEffect = false;
            rowHeaderRenderer32.TextRotationAngle = 0D;
            rowHeaderRenderer32.ZoomFactor = 1F;
            // 
            // txtInvLotID
            // 
            this.txtInvLotID.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.txtInvLotID.Location = new System.Drawing.Point(109, 19);
            this.txtInvLotID.Name = "txtInvLotID";
            this.txtInvLotID.Size = new System.Drawing.Size(277, 26);
            this.txtInvLotID.TabIndex = 261;
            this.txtInvLotID.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtInvLotID_KeyDown);
            // 
            // lblInvLotId
            // 
            this.lblInvLotId.AutoSize = true;
            this.lblInvLotId.BackColor = System.Drawing.Color.White;
            this.lblInvLotId.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.lblInvLotId.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblInvLotId.ForeColor = System.Drawing.Color.Black;
            this.lblInvLotId.Location = new System.Drawing.Point(11, 24);
            this.lblInvLotId.Name = "lblInvLotId";
            this.lblInvLotId.Size = new System.Drawing.Size(72, 16);
            this.lblInvLotId.TabIndex = 260;
            this.lblInvLotId.Text = "Inv Lot ID";
            this.lblInvLotId.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // grpInvLotList
            // 
            this.grpInvLotList.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.None;
            appearance1.BackColor = System.Drawing.Color.White;
            appearance1.BackColor2 = System.Drawing.Color.White;
            this.grpInvLotList.ContentAreaAppearance = appearance1;
            this.grpInvLotList.Controls.Add(this.spdInvLotList);
            this.grpInvLotList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpInvLotList.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            appearance2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(59)))), ((int)(((byte)(98)))));
            appearance2.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(59)))), ((int)(((byte)(98)))));
            appearance2.ForeColor = System.Drawing.Color.White;
            this.grpInvLotList.HeaderAppearance = appearance2;
            this.grpInvLotList.Location = new System.Drawing.Point(10, 120);
            this.grpInvLotList.Margin = new System.Windows.Forms.Padding(5);
            this.grpInvLotList.Name = "grpInvLotList";
            this.grpInvLotList.Size = new System.Drawing.Size(1219, 670);
            this.grpInvLotList.TabIndex = 245;
            this.grpInvLotList.Text = "Inv Lot History List";
            // 
            // spdInvLotList
            // 
            this.spdInvLotList.AccessibleDescription = "spdWorkOrder, Sheet1, Row 0, Column 0, ";
            this.spdInvLotList.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.spdInvLotList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.spdInvLotList.FocusRenderer = defaultFocusIndicatorRenderer1;
            this.spdInvLotList.HorizontalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdInvLotList.HorizontalScrollBar.Name = "";
            this.spdInvLotList.HorizontalScrollBar.Renderer = defaultScrollBarRenderer1;
            this.spdInvLotList.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdInvLotList.Location = new System.Drawing.Point(1, 19);
            this.spdInvLotList.Margin = new System.Windows.Forms.Padding(0);
            this.spdInvLotList.Name = "spdInvLotList";
            namedStyle1.BackColor = System.Drawing.SystemColors.Control;
            filterBarCellType1.FormatString = "";
            namedStyle1.CellType = filterBarCellType1;
            namedStyle1.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle1.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle1.Locked = false;
            namedStyle1.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle1.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle1.Renderer = filterBarCellType1;
            namedStyle1.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle1.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle2.BackColor = System.Drawing.Color.Aqua;
            namedStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle2.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle2.Locked = false;
            namedStyle2.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle2.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle2.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle2.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle3.BackColor = System.Drawing.SystemColors.Window;
            namedStyle3.CellType = generalCellType1;
            namedStyle3.ForeColor = System.Drawing.SystemColors.WindowText;
            namedStyle3.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle3.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle3.Renderer = generalCellType1;
            namedStyle3.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle3.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            namedStyle4.Border = bevelBorder1;
            namedStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            namedStyle4.ForeColor = System.Drawing.Color.White;
            namedStyle4.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle4.Locked = false;
            namedStyle4.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle4.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle4.Renderer = generalCellType2;
            namedStyle4.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle4.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle5.BackColor = System.Drawing.SystemColors.Control;
            filterBarCellType2.FormatString = "";
            namedStyle5.CellType = filterBarCellType2;
            namedStyle5.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle5.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle5.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle5.Renderer = filterBarCellType2;
            namedStyle5.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle5.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle6.BackColor = System.Drawing.SystemColors.Control;
            namedStyle6.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle6.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle6.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle6.Renderer = columnHeaderRenderer32;
            namedStyle6.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle6.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle7.BackColor = System.Drawing.SystemColors.Control;
            namedStyle7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            namedStyle7.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle7.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle7.Locked = false;
            namedStyle7.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle7.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle7.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle7.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle8.BackColor = System.Drawing.SystemColors.Control;
            namedStyle8.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle8.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle8.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle8.Renderer = rowHeaderRenderer32;
            namedStyle8.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle8.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle9.BackColor = System.Drawing.Color.White;
            namedStyle9.CellType = generalCellType3;
            namedStyle9.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            namedStyle9.ForeColor = System.Drawing.Color.Black;
            namedStyle9.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle9.Locked = false;
            namedStyle9.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle9.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle9.Renderer = generalCellType3;
            namedStyle9.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle9.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.spdInvLotList.NamedStyles.AddRange(new FarPoint.Win.Spread.NamedStyle[] {
            namedStyle1,
            namedStyle2,
            namedStyle3,
            namedStyle4,
            namedStyle5,
            namedStyle6,
            namedStyle7,
            namedStyle8,
            namedStyle9});
            this.spdInvLotList.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.spdInvLotList_Sheet1});
            this.spdInvLotList.Size = new System.Drawing.Size(1217, 650);
            spreadSkin1.ColumnFooterDefaultStyle = namedStyle6;
            spreadSkin1.ColumnHeaderDefaultStyle = namedStyle4;
            spreadSkin1.CornerDefaultStyle = namedStyle8;
            spreadSkin1.DefaultStyle = namedStyle9;
            spreadSkin1.FilterBarDefaultStyle = namedStyle5;
            spreadSkin1.FilterBarHeaderDefaultStyle = namedStyle8;
            spreadSkin1.FocusRenderer = defaultFocusIndicatorRenderer1;
            spreadSkin1.Name = "사용1";
            spreadSkin1.RowHeaderDefaultStyle = namedStyle7;
            spreadSkin1.ScrollBarRenderer = defaultScrollBarRenderer2;
            spreadSkin1.SelectionRenderer = new FarPoint.Win.Spread.DefaultSelectionRenderer();
            statusBarSkin1.BackColor = System.Drawing.SystemColors.Control;
            statusBarSkin1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            statusBarSkin1.ForeColor = System.Drawing.SystemColors.ControlText;
            statusBarSkin1.Name = "Classic";
            statusBarSkin1.ZoomButtonHoverColor = System.Drawing.SystemColors.ButtonHighlight;
            statusBarSkin1.ZoomSliderColor = System.Drawing.SystemColors.ControlDarkDark;
            statusBarSkin1.ZoomSliderHoverColor = System.Drawing.SystemColors.ControlDark;
            statusBarSkin1.ZoomSliderTrackColor = System.Drawing.SystemColors.ControlDarkDark;
            spreadSkin1.StatusBarSkin = statusBarSkin1;
            this.spdInvLotList.Skin = spreadSkin1;
            this.spdInvLotList.TabIndex = 251;
            this.spdInvLotList.TabStop = false;
            this.spdInvLotList.VerticalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdInvLotList.VerticalScrollBar.Name = "";
            this.spdInvLotList.VerticalScrollBar.Renderer = defaultScrollBarRenderer3;
            this.spdInvLotList.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdInvLotList.CellClick += new FarPoint.Win.Spread.CellClickEventHandler(this.spdInvLotList_CellClick);
            // 
            // spdInvLotList_Sheet1
            // 
            this.spdInvLotList_Sheet1.Reset();
            this.spdInvLotList_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.spdInvLotList_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.spdInvLotList_Sheet1.ColumnCount = 54;
            this.spdInvLotList_Sheet1.RowCount = 0;
            this.spdInvLotList_Sheet1.ActiveColumnIndex = -1;
            this.spdInvLotList_Sheet1.ActiveRowIndex = -1;
            this.spdInvLotList_Sheet1.ColumnFooter.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdInvLotList_Sheet1.ColumnFooter.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdInvLotList_Sheet1.ColumnFooter.DefaultStyle.Parent = "HeaderDefault";
            this.spdInvLotList_Sheet1.ColumnFooter.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "Inv Lot Id";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "Hist Seq";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "Tran Code";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "Tran Time";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "Inv Lot Status";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "Inv Lot Priority";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "Mat Id";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 7).Value = "Mat Ver";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 8).Value = "Mat Desc";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 9).Value = "Qty";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 10).Value = "Unit";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 11).Value = "Vendor ID";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 12).Value = "Vendor Site ID";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 13).Value = "Vendor Lot Id";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 14).Value = "Department";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 15).Value = "WorkPlace";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 16).Value = "Warehouse";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 17).Value = "Warehouse Desc";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 18).Value = "Recv Date";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 19).Value = "Recv Qty";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 20).Value = "Delete Flag";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 21).Value = "Delete Code";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 22).Value = "Delete Time";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 23).Value = "Hold Flag";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 24).Value = "Hold Center";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 25).Value = "Insp Flag";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 26).Value = "Insp Id";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 27).Value = "Insp Result Flag";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 28).Value = "Mold Model";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 29).Value = "Mold Type";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 30).Value = "Inv Cmf 3";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 31).Value = "Kitting ID";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 32).Value = "Etc In Type";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 33).Value = "Etc Out Type";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 34).Value = "Out Date";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 35).Value = "Load Flag";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 36).Value = "Lot ID";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 37).Value = "Res ID";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 38).Value = "Order ID";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 39).Value = "Load WorkPlace";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 40).Value = "Load Oper";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 41).Value = "Inv Cmf 10";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 42).Value = "Org Inv Lot Id";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 43).Value = "Old Mat Id";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 44).Value = "Old Mat Desc";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 45).Value = "Old Department";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 46).Value = "Old WorkPlace";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 47).Value = "Old Warehouse";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 48).Value = "Old Qty";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 49).Value = "Old Unit";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 50).Value = "Create Time";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 51).Value = "Update Time";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 52).Value = "Hist Del Flag";
            this.spdInvLotList_Sheet1.ColumnHeader.Cells.Get(0, 53).Value = "Tran User Id";
            this.spdInvLotList_Sheet1.ColumnHeader.DefaultStyle.Border = bevelBorder2;
            this.spdInvLotList_Sheet1.ColumnHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdInvLotList_Sheet1.ColumnHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdInvLotList_Sheet1.ColumnHeader.DefaultStyle.Parent = "Style1";
            this.spdInvLotList_Sheet1.ColumnHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.ColumnHeader.Rows.Get(0).Height = 25F;
            this.spdInvLotList_Sheet1.Columns.Get(0).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(0).Label = "Inv Lot Id";
            this.spdInvLotList_Sheet1.Columns.Get(0).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(0).Width = 87F;
            this.spdInvLotList_Sheet1.Columns.Get(1).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdInvLotList_Sheet1.Columns.Get(1).Label = "Hist Seq";
            this.spdInvLotList_Sheet1.Columns.Get(1).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(2).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(2).Label = "Tran Code";
            this.spdInvLotList_Sheet1.Columns.Get(2).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(2).Width = 97F;
            this.spdInvLotList_Sheet1.Columns.Get(3).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(3).Label = "Tran Time";
            this.spdInvLotList_Sheet1.Columns.Get(3).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(3).Width = 74F;
            this.spdInvLotList_Sheet1.Columns.Get(4).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(4).Label = "Inv Lot Status";
            this.spdInvLotList_Sheet1.Columns.Get(4).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(4).Width = 95F;
            this.spdInvLotList_Sheet1.Columns.Get(5).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(5).Label = "Inv Lot Priority";
            this.spdInvLotList_Sheet1.Columns.Get(5).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(5).Width = 100F;
            this.spdInvLotList_Sheet1.Columns.Get(6).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(6).Label = "Mat Id";
            this.spdInvLotList_Sheet1.Columns.Get(6).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(6).Width = 75F;
            this.spdInvLotList_Sheet1.Columns.Get(7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdInvLotList_Sheet1.Columns.Get(7).Label = "Mat Ver";
            this.spdInvLotList_Sheet1.Columns.Get(8).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(8).Label = "Mat Desc";
            this.spdInvLotList_Sheet1.Columns.Get(8).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(8).Width = 107F;
            this.spdInvLotList_Sheet1.Columns.Get(9).AllowAutoSort = true;
            numberCellType1.DecimalPlaces = 5;
            numberCellType1.ShowSeparator = true;
            this.spdInvLotList_Sheet1.Columns.Get(9).CellType = numberCellType1;
            this.spdInvLotList_Sheet1.Columns.Get(9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdInvLotList_Sheet1.Columns.Get(9).Label = "Qty";
            this.spdInvLotList_Sheet1.Columns.Get(9).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(10).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(10).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdInvLotList_Sheet1.Columns.Get(10).Label = "Unit";
            this.spdInvLotList_Sheet1.Columns.Get(10).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(10).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(11).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(11).Label = "Vendor ID";
            this.spdInvLotList_Sheet1.Columns.Get(11).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(11).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(11).Width = 91F;
            this.spdInvLotList_Sheet1.Columns.Get(12).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(12).Label = "Vendor Site ID";
            this.spdInvLotList_Sheet1.Columns.Get(12).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(12).Width = 125F;
            this.spdInvLotList_Sheet1.Columns.Get(13).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(13).Label = "Vendor Lot Id";
            this.spdInvLotList_Sheet1.Columns.Get(13).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(13).Width = 94F;
            this.spdInvLotList_Sheet1.Columns.Get(14).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(14).Label = "Department";
            this.spdInvLotList_Sheet1.Columns.Get(14).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(14).Width = 104F;
            this.spdInvLotList_Sheet1.Columns.Get(15).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(15).Label = "WorkPlace";
            this.spdInvLotList_Sheet1.Columns.Get(15).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(15).Width = 97F;
            this.spdInvLotList_Sheet1.Columns.Get(16).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(16).Label = "Warehouse";
            this.spdInvLotList_Sheet1.Columns.Get(16).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(16).Width = 107F;
            this.spdInvLotList_Sheet1.Columns.Get(17).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(17).Label = "Warehouse Desc";
            this.spdInvLotList_Sheet1.Columns.Get(17).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(17).Width = 134F;
            this.spdInvLotList_Sheet1.Columns.Get(18).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(18).Label = "Recv Date";
            this.spdInvLotList_Sheet1.Columns.Get(18).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(18).Width = 74F;
            this.spdInvLotList_Sheet1.Columns.Get(19).AllowAutoSort = true;
            numberCellType2.DecimalPlaces = 5;
            numberCellType2.ShowSeparator = true;
            this.spdInvLotList_Sheet1.Columns.Get(19).CellType = numberCellType2;
            this.spdInvLotList_Sheet1.Columns.Get(19).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdInvLotList_Sheet1.Columns.Get(19).Label = "Recv Qty";
            this.spdInvLotList_Sheet1.Columns.Get(19).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(19).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(19).Width = 64F;
            this.spdInvLotList_Sheet1.Columns.Get(20).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(20).Label = "Delete Flag";
            this.spdInvLotList_Sheet1.Columns.Get(20).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(20).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(20).Width = 83F;
            this.spdInvLotList_Sheet1.Columns.Get(21).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(21).Label = "Delete Code";
            this.spdInvLotList_Sheet1.Columns.Get(21).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(21).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(21).Width = 88F;
            this.spdInvLotList_Sheet1.Columns.Get(22).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(22).Label = "Delete Time";
            this.spdInvLotList_Sheet1.Columns.Get(22).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(22).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(22).Width = 87F;
            this.spdInvLotList_Sheet1.Columns.Get(23).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(23).Label = "Hold Flag";
            this.spdInvLotList_Sheet1.Columns.Get(23).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(23).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(23).Width = 71F;
            this.spdInvLotList_Sheet1.Columns.Get(24).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(24).Label = "Hold Center";
            this.spdInvLotList_Sheet1.Columns.Get(24).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(24).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(24).Width = 85F;
            this.spdInvLotList_Sheet1.Columns.Get(25).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(25).Label = "Insp Flag";
            this.spdInvLotList_Sheet1.Columns.Get(25).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(25).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(25).Width = 68F;
            this.spdInvLotList_Sheet1.Columns.Get(26).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(26).Label = "Insp Id";
            this.spdInvLotList_Sheet1.Columns.Get(26).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(26).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(27).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(27).Label = "Insp Result Flag";
            this.spdInvLotList_Sheet1.Columns.Get(27).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(27).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(27).Width = 113F;
            this.spdInvLotList_Sheet1.Columns.Get(28).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(28).Label = "Mold Model";
            this.spdInvLotList_Sheet1.Columns.Get(28).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(28).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(28).Width = 85F;
            this.spdInvLotList_Sheet1.Columns.Get(29).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(29).Label = "Mold Type";
            this.spdInvLotList_Sheet1.Columns.Get(29).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(29).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(29).Width = 75F;
            this.spdInvLotList_Sheet1.Columns.Get(30).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(30).Label = "Inv Cmf 3";
            this.spdInvLotList_Sheet1.Columns.Get(30).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(30).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(30).Width = 66F;
            this.spdInvLotList_Sheet1.Columns.Get(31).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(31).Label = "Kitting ID";
            this.spdInvLotList_Sheet1.Columns.Get(31).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(31).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(31).Width = 68F;
            this.spdInvLotList_Sheet1.Columns.Get(32).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(32).Label = "Etc In Type";
            this.spdInvLotList_Sheet1.Columns.Get(32).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(32).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(32).Width = 79F;
            this.spdInvLotList_Sheet1.Columns.Get(33).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(33).Label = "Etc Out Type";
            this.spdInvLotList_Sheet1.Columns.Get(33).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(33).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(33).Width = 89F;
            this.spdInvLotList_Sheet1.Columns.Get(34).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(34).Label = "Out Date";
            this.spdInvLotList_Sheet1.Columns.Get(34).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(34).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(34).Width = 65F;
            this.spdInvLotList_Sheet1.Columns.Get(35).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(35).Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.spdInvLotList_Sheet1.Columns.Get(35).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdInvLotList_Sheet1.Columns.Get(35).Label = "Load Flag";
            this.spdInvLotList_Sheet1.Columns.Get(35).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(35).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(35).Width = 96F;
            this.spdInvLotList_Sheet1.Columns.Get(36).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(36).Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.spdInvLotList_Sheet1.Columns.Get(36).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdInvLotList_Sheet1.Columns.Get(36).Label = "Lot ID";
            this.spdInvLotList_Sheet1.Columns.Get(36).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(36).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(37).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(37).Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.spdInvLotList_Sheet1.Columns.Get(37).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdInvLotList_Sheet1.Columns.Get(37).Label = "Res ID";
            this.spdInvLotList_Sheet1.Columns.Get(37).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(37).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(38).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(38).Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.spdInvLotList_Sheet1.Columns.Get(38).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdInvLotList_Sheet1.Columns.Get(38).Label = "Order ID";
            this.spdInvLotList_Sheet1.Columns.Get(38).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(38).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(38).Width = 81F;
            this.spdInvLotList_Sheet1.Columns.Get(39).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(39).Label = "Load WorkPlace";
            this.spdInvLotList_Sheet1.Columns.Get(39).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(39).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(39).Width = 122F;
            this.spdInvLotList_Sheet1.Columns.Get(40).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(40).Label = "Load Oper";
            this.spdInvLotList_Sheet1.Columns.Get(40).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(40).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(40).Width = 117F;
            this.spdInvLotList_Sheet1.Columns.Get(41).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(41).Label = "Inv Cmf 10";
            this.spdInvLotList_Sheet1.Columns.Get(41).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(41).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(41).Width = 76F;
            this.spdInvLotList_Sheet1.Columns.Get(42).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(42).Label = "Org Inv Lot Id";
            this.spdInvLotList_Sheet1.Columns.Get(42).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(42).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(42).Width = 126F;
            this.spdInvLotList_Sheet1.Columns.Get(43).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(43).Label = "Old Mat Id";
            this.spdInvLotList_Sheet1.Columns.Get(43).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(43).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(43).Width = 100F;
            this.spdInvLotList_Sheet1.Columns.Get(44).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(44).Label = "Old Mat Desc";
            this.spdInvLotList_Sheet1.Columns.Get(44).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(44).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(44).Width = 121F;
            this.spdInvLotList_Sheet1.Columns.Get(45).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(45).Label = "Old Department";
            this.spdInvLotList_Sheet1.Columns.Get(45).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(45).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(45).Width = 120F;
            this.spdInvLotList_Sheet1.Columns.Get(46).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(46).Label = "Old WorkPlace";
            this.spdInvLotList_Sheet1.Columns.Get(46).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(46).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(46).Width = 123F;
            this.spdInvLotList_Sheet1.Columns.Get(47).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(47).Label = "Old Warehouse";
            this.spdInvLotList_Sheet1.Columns.Get(47).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(47).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(47).Width = 118F;
            this.spdInvLotList_Sheet1.Columns.Get(48).AllowAutoSort = true;
            numberCellType3.DecimalPlaces = 5;
            numberCellType3.ShowSeparator = true;
            this.spdInvLotList_Sheet1.Columns.Get(48).CellType = numberCellType3;
            this.spdInvLotList_Sheet1.Columns.Get(48).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdInvLotList_Sheet1.Columns.Get(48).Label = "Old Qty";
            this.spdInvLotList_Sheet1.Columns.Get(48).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(48).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(48).Width = 78F;
            this.spdInvLotList_Sheet1.Columns.Get(49).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(49).Label = "Old Unit";
            this.spdInvLotList_Sheet1.Columns.Get(49).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(49).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(49).Width = 83F;
            this.spdInvLotList_Sheet1.Columns.Get(50).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(50).Label = "Create Time";
            this.spdInvLotList_Sheet1.Columns.Get(50).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(50).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(50).Width = 130F;
            this.spdInvLotList_Sheet1.Columns.Get(51).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(51).Label = "Update Time";
            this.spdInvLotList_Sheet1.Columns.Get(51).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(51).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(51).Width = 132F;
            this.spdInvLotList_Sheet1.Columns.Get(52).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(52).Label = "Hist Del Flag";
            this.spdInvLotList_Sheet1.Columns.Get(52).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(52).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(52).Width = 92F;
            this.spdInvLotList_Sheet1.Columns.Get(53).AllowAutoSort = true;
            this.spdInvLotList_Sheet1.Columns.Get(53).Label = "Tran User Id";
            this.spdInvLotList_Sheet1.Columns.Get(53).Locked = true;
            this.spdInvLotList_Sheet1.Columns.Get(53).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdInvLotList_Sheet1.Columns.Get(53).Width = 88F;
            this.spdInvLotList_Sheet1.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdInvLotList_Sheet1.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdInvLotList_Sheet1.DefaultStyle.Parent = "Style2";
            this.spdInvLotList_Sheet1.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdInvLotList_Sheet1.EnhancedFilterSortingMode = FarPoint.Win.Spread.EnhancedFilterSortingMode.Text;
            this.spdInvLotList_Sheet1.FilterBar.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdInvLotList_Sheet1.FilterBar.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdInvLotList_Sheet1.FilterBar.DefaultStyle.Parent = "FilterBarDefault";
            this.spdInvLotList_Sheet1.FilterBar.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdInvLotList_Sheet1.FilterBarHeaderStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdInvLotList_Sheet1.FilterBarHeaderStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdInvLotList_Sheet1.FilterBarHeaderStyle.Parent = "RowHeaderDefault";
            this.spdInvLotList_Sheet1.FilterBarHeaderStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdInvLotList_Sheet1.GrayAreaBackColor = System.Drawing.Color.White;
            this.spdInvLotList_Sheet1.NullBackColor = System.Drawing.Color.White;
            this.spdInvLotList_Sheet1.OperationMode = FarPoint.Win.Spread.OperationMode.ReadOnly;
            this.spdInvLotList_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.spdInvLotList_Sheet1.RowHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdInvLotList_Sheet1.RowHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdInvLotList_Sheet1.RowHeader.DefaultStyle.Parent = "Style3";
            this.spdInvLotList_Sheet1.RowHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdInvLotList_Sheet1.RowHeader.Visible = false;
            this.spdInvLotList_Sheet1.Rows.Default.Height = 25F;
            this.spdInvLotList_Sheet1.SheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdInvLotList_Sheet1.SheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdInvLotList_Sheet1.SheetCornerStyle.Parent = "RowHeaderDefault";
            this.spdInvLotList_Sheet1.SheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdInvLotList_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // btnExcel
            // 
            appearance19.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            appearance19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            appearance19.FontData.BoldAsString = "True";
            appearance19.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            this.btnExcel.Appearance = appearance19;
            this.btnExcel.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExcel.Location = new System.Drawing.Point(12, 10);
            this.btnExcel.Name = "btnExcel";
            this.btnExcel.Size = new System.Drawing.Size(100, 30);
            this.btnExcel.TabIndex = 275;
            this.btnExcel.Text = "Excel";
            this.btnExcel.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.btnExcel.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.btnExcel.Click += new System.EventHandler(this.btnExcel_Click);
            // 
            // frmViewInvLotHistory
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1239, 840);
            this.Name = "frmViewInvLotHistory";
            this.Text = "View Inv Lot History";
            this.Load += new System.EventHandler(this.frmViewInvLotHistory_Load);
            this.pnlStsCond.ResumeLayout(false);
            this.pnlStsCond.PerformLayout();
            this.pnlMID.ResumeLayout(false);
            this.pnlMID.PerformLayout();
            this.pnlBottom.ResumeLayout(false);
            this.pnlCenter.ResumeLayout(false);
            this.pnlTop.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grpInvLotList)).EndInit();
            this.grpInvLotList.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.spdInvLotList)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdInvLotList_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        public System.Windows.Forms.TextBox txtInvLotID;
        public System.Windows.Forms.Label lblInvLotId;
        private Infragistics.Win.Misc.UltraGroupBox grpInvLotList;
        private FarPoint.Win.Spread.FpSpread spdInvLotList;
        private FarPoint.Win.Spread.SheetView spdInvLotList_Sheet1;
        protected Infragistics.Win.Misc.UltraButton btnExcel;
    }
}