namespace CUS_INV
{
    partial class frmViewShipLotRawMaterialList
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer2 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer2 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer3 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer3 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer4 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer4 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer1 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer1 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer5 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer5 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer6 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer6 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer7 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer7 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer8 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer8 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer11 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer11 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer12 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer12 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer9 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer9 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer10 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer10 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer13 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer13 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer14 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer14 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer15 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer15 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer16 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer16 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer17 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer17 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer18 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer18 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer19 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer19 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer20 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer20 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer21 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer21 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer22 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer22 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer23 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer23 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer24 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer24 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer25 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer25 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer26 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer26 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer27 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer27 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer28 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer28 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer29 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer29 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer30 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer30 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer31 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer31 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer32 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer32 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer33 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer33 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer34 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer34 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer35 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer35 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer36 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer36 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            FarPoint.Win.Spread.DefaultFocusIndicatorRenderer defaultFocusIndicatorRenderer1 = new FarPoint.Win.Spread.DefaultFocusIndicatorRenderer();
            FarPoint.Win.Spread.DefaultScrollBarRenderer defaultScrollBarRenderer1 = new FarPoint.Win.Spread.DefaultScrollBarRenderer();
            FarPoint.Win.Spread.NamedStyle namedStyle1 = new FarPoint.Win.Spread.NamedStyle("Style4");
            FarPoint.Win.Spread.CellType.FilterBarCellType filterBarCellType1 = new FarPoint.Win.Spread.CellType.FilterBarCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle2 = new FarPoint.Win.Spread.NamedStyle("Style5");
            FarPoint.Win.Spread.NamedStyle namedStyle3 = new FarPoint.Win.Spread.NamedStyle("DataAreaDefault");
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType1 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle4 = new FarPoint.Win.Spread.NamedStyle("Style1");
            FarPoint.Win.BevelBorder bevelBorder1 = new FarPoint.Win.BevelBorder(FarPoint.Win.BevelBorderType.Lowered);
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType2 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle5 = new FarPoint.Win.Spread.NamedStyle("FilterBarDefault");
            FarPoint.Win.Spread.CellType.FilterBarCellType filterBarCellType2 = new FarPoint.Win.Spread.CellType.FilterBarCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle6 = new FarPoint.Win.Spread.NamedStyle("HeaderDefault");
            FarPoint.Win.Spread.NamedStyle namedStyle7 = new FarPoint.Win.Spread.NamedStyle("Style3");
            FarPoint.Win.Spread.NamedStyle namedStyle8 = new FarPoint.Win.Spread.NamedStyle("RowHeaderDefault");
            FarPoint.Win.Spread.NamedStyle namedStyle9 = new FarPoint.Win.Spread.NamedStyle("Style2");
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType3 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.SpreadSkin spreadSkin1 = new FarPoint.Win.Spread.SpreadSkin();
            FarPoint.Win.Spread.DefaultScrollBarRenderer defaultScrollBarRenderer2 = new FarPoint.Win.Spread.DefaultScrollBarRenderer();
            FarPoint.Win.Spread.StatusBarSkin statusBarSkin1 = new FarPoint.Win.Spread.StatusBarSkin();
            FarPoint.Win.Spread.DefaultScrollBarRenderer defaultScrollBarRenderer3 = new FarPoint.Win.Spread.DefaultScrollBarRenderer();
            FarPoint.Win.BevelBorder bevelBorder2 = new FarPoint.Win.BevelBorder(FarPoint.Win.BevelBorderType.Lowered);
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType1 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType2 = new FarPoint.Win.Spread.CellType.NumberCellType();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            this.txtLotID = new System.Windows.Forms.TextBox();
            this.lblLotId = new System.Windows.Forms.Label();
            this.grpRawMatList = new Infragistics.Win.Misc.UltraGroupBox();
            this.spdRawMatList = new FarPoint.Win.Spread.FpSpread();
            this.spdRawMatList_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.btnExcel = new Infragistics.Win.Misc.UltraButton();
            this.pnlStsCond.SuspendLayout();
            this.pnlMID.SuspendLayout();
            this.pnlBottom.SuspendLayout();
            this.pnlCenter.SuspendLayout();
            this.pnlTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grpRawMatList)).BeginInit();
            this.grpRawMatList.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.spdRawMatList)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdRawMatList_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // pnlStsCond
            // 
            this.pnlStsCond.Controls.Add(this.txtLotID);
            this.pnlStsCond.Controls.Add(this.lblLotId);
            this.pnlStsCond.Controls.SetChildIndex(this.pnlStsCond3, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.pnlStsCond2, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.lblLotId, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.txtLotID, 0);
            // 
            // pnlMID
            // 
            this.pnlMID.Controls.Add(this.grpRawMatList);
            this.pnlMID.Controls.SetChildIndex(this.lblFormName, 0);
            this.pnlMID.Controls.SetChildIndex(this.pnlStsCond, 0);
            this.pnlMID.Controls.SetChildIndex(this.lblDirectQuery, 0);
            this.pnlMID.Controls.SetChildIndex(this.grpRawMatList, 0);
            // 
            // lblFormName
            // 
            this.lblFormName.Size = new System.Drawing.Size(422, 37);
            this.lblFormName.Text = "View Ship Lot Raw Material List";
            // 
            // btnView
            // 
            this.btnView.Click += new System.EventHandler(this.btnView_Click);
            // 
            // pnlBottom
            // 
            this.pnlBottom.Controls.Add(this.btnExcel);
            this.pnlBottom.Controls.SetChildIndex(this.btnClose, 0);
            this.pnlBottom.Controls.SetChildIndex(this.btnView, 0);
            this.pnlBottom.Controls.SetChildIndex(this.btnExcel, 0);
            // 
            // pnlTop
            // 
            this.pnlTop.Size = new System.Drawing.Size(1239, 0);
            // 
            // lblFormTitle
            // 
            this.lblFormTitle.Size = new System.Drawing.Size(1235, 0);
            this.lblFormTitle.Text = "ViewForm01";
            columnHeaderRenderer2.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer2.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer2.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer2.Name = "columnHeaderRenderer2";
            columnHeaderRenderer2.PictureZoomEffect = false;
            columnHeaderRenderer2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer2.TextRotationAngle = 0D;
            columnHeaderRenderer2.ZoomFactor = 1F;
            rowHeaderRenderer2.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer2.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer2.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer2.Name = "rowHeaderRenderer2";
            rowHeaderRenderer2.PictureZoomEffect = false;
            rowHeaderRenderer2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer2.TextRotationAngle = 0D;
            rowHeaderRenderer2.ZoomFactor = 1F;
            columnHeaderRenderer3.Name = "columnHeaderRenderer3";
            columnHeaderRenderer3.PictureZoomEffect = false;
            columnHeaderRenderer3.TextRotationAngle = 0D;
            columnHeaderRenderer3.ZoomFactor = 1F;
            rowHeaderRenderer3.Name = "rowHeaderRenderer3";
            rowHeaderRenderer3.PictureZoomEffect = false;
            rowHeaderRenderer3.TextRotationAngle = 0D;
            rowHeaderRenderer3.ZoomFactor = 1F;
            columnHeaderRenderer4.Name = "columnHeaderRenderer4";
            columnHeaderRenderer4.PictureZoomEffect = false;
            columnHeaderRenderer4.TextRotationAngle = 0D;
            columnHeaderRenderer4.ZoomFactor = 1F;
            rowHeaderRenderer4.Name = "rowHeaderRenderer4";
            rowHeaderRenderer4.PictureZoomEffect = false;
            rowHeaderRenderer4.TextRotationAngle = 0D;
            rowHeaderRenderer4.ZoomFactor = 1F;
            columnHeaderRenderer1.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer1.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer1.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer1.Name = "columnHeaderRenderer1";
            columnHeaderRenderer1.PictureZoomEffect = false;
            columnHeaderRenderer1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer1.TextRotationAngle = 0D;
            columnHeaderRenderer1.ZoomFactor = 1F;
            rowHeaderRenderer1.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer1.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer1.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer1.Name = "rowHeaderRenderer1";
            rowHeaderRenderer1.PictureZoomEffect = false;
            rowHeaderRenderer1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer1.TextRotationAngle = 0D;
            rowHeaderRenderer1.ZoomFactor = 1F;
            columnHeaderRenderer5.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer5.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer5.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer5.Name = "columnHeaderRenderer5";
            columnHeaderRenderer5.PictureZoomEffect = false;
            columnHeaderRenderer5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer5.TextRotationAngle = 0D;
            columnHeaderRenderer5.ZoomFactor = 1F;
            rowHeaderRenderer5.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer5.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer5.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer5.Name = "rowHeaderRenderer5";
            rowHeaderRenderer5.PictureZoomEffect = false;
            rowHeaderRenderer5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer5.TextRotationAngle = 0D;
            rowHeaderRenderer5.ZoomFactor = 1F;
            columnHeaderRenderer6.Name = "columnHeaderRenderer6";
            columnHeaderRenderer6.PictureZoomEffect = false;
            columnHeaderRenderer6.TextRotationAngle = 0D;
            columnHeaderRenderer6.ZoomFactor = 1F;
            rowHeaderRenderer6.Name = "rowHeaderRenderer6";
            rowHeaderRenderer6.PictureZoomEffect = false;
            rowHeaderRenderer6.TextRotationAngle = 0D;
            rowHeaderRenderer6.ZoomFactor = 1F;
            columnHeaderRenderer7.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer7.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer7.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer7.Name = "columnHeaderRenderer7";
            columnHeaderRenderer7.PictureZoomEffect = false;
            columnHeaderRenderer7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer7.TextRotationAngle = 0D;
            columnHeaderRenderer7.ZoomFactor = 1F;
            rowHeaderRenderer7.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer7.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer7.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer7.Name = "rowHeaderRenderer7";
            rowHeaderRenderer7.PictureZoomEffect = false;
            rowHeaderRenderer7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer7.TextRotationAngle = 0D;
            rowHeaderRenderer7.ZoomFactor = 1F;
            columnHeaderRenderer8.Name = "columnHeaderRenderer8";
            columnHeaderRenderer8.PictureZoomEffect = false;
            columnHeaderRenderer8.TextRotationAngle = 0D;
            columnHeaderRenderer8.ZoomFactor = 1F;
            rowHeaderRenderer8.Name = "rowHeaderRenderer8";
            rowHeaderRenderer8.PictureZoomEffect = false;
            rowHeaderRenderer8.TextRotationAngle = 0D;
            rowHeaderRenderer8.ZoomFactor = 1F;
            columnHeaderRenderer11.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer11.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer11.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer11.Name = "columnHeaderRenderer11";
            columnHeaderRenderer11.PictureZoomEffect = false;
            columnHeaderRenderer11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer11.TextRotationAngle = 0D;
            columnHeaderRenderer11.ZoomFactor = 1F;
            rowHeaderRenderer11.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer11.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer11.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer11.Name = "rowHeaderRenderer11";
            rowHeaderRenderer11.PictureZoomEffect = false;
            rowHeaderRenderer11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer11.TextRotationAngle = 0D;
            rowHeaderRenderer11.ZoomFactor = 1F;
            columnHeaderRenderer12.Name = "columnHeaderRenderer12";
            columnHeaderRenderer12.PictureZoomEffect = false;
            columnHeaderRenderer12.TextRotationAngle = 0D;
            columnHeaderRenderer12.ZoomFactor = 1F;
            rowHeaderRenderer12.Name = "rowHeaderRenderer12";
            rowHeaderRenderer12.PictureZoomEffect = false;
            rowHeaderRenderer12.TextRotationAngle = 0D;
            rowHeaderRenderer12.ZoomFactor = 1F;
            columnHeaderRenderer9.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer9.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer9.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer9.Name = "columnHeaderRenderer9";
            columnHeaderRenderer9.PictureZoomEffect = false;
            columnHeaderRenderer9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer9.TextRotationAngle = 0D;
            columnHeaderRenderer9.ZoomFactor = 1F;
            rowHeaderRenderer9.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer9.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer9.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer9.Name = "rowHeaderRenderer9";
            rowHeaderRenderer9.PictureZoomEffect = false;
            rowHeaderRenderer9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer9.TextRotationAngle = 0D;
            rowHeaderRenderer9.ZoomFactor = 1F;
            columnHeaderRenderer10.Name = "columnHeaderRenderer10";
            columnHeaderRenderer10.PictureZoomEffect = false;
            columnHeaderRenderer10.TextRotationAngle = 0D;
            columnHeaderRenderer10.ZoomFactor = 1F;
            rowHeaderRenderer10.Name = "rowHeaderRenderer10";
            rowHeaderRenderer10.PictureZoomEffect = false;
            rowHeaderRenderer10.TextRotationAngle = 0D;
            rowHeaderRenderer10.ZoomFactor = 1F;
            columnHeaderRenderer13.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer13.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer13.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer13.Name = "columnHeaderRenderer13";
            columnHeaderRenderer13.PictureZoomEffect = false;
            columnHeaderRenderer13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer13.TextRotationAngle = 0D;
            columnHeaderRenderer13.ZoomFactor = 1F;
            rowHeaderRenderer13.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer13.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer13.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer13.Name = "rowHeaderRenderer13";
            rowHeaderRenderer13.PictureZoomEffect = false;
            rowHeaderRenderer13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer13.TextRotationAngle = 0D;
            rowHeaderRenderer13.ZoomFactor = 1F;
            columnHeaderRenderer14.Name = "columnHeaderRenderer14";
            columnHeaderRenderer14.PictureZoomEffect = false;
            columnHeaderRenderer14.TextRotationAngle = 0D;
            columnHeaderRenderer14.ZoomFactor = 1F;
            rowHeaderRenderer14.Name = "rowHeaderRenderer14";
            rowHeaderRenderer14.PictureZoomEffect = false;
            rowHeaderRenderer14.TextRotationAngle = 0D;
            rowHeaderRenderer14.ZoomFactor = 1F;
            columnHeaderRenderer15.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer15.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer15.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer15.Name = "columnHeaderRenderer15";
            columnHeaderRenderer15.PictureZoomEffect = false;
            columnHeaderRenderer15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer15.TextRotationAngle = 0D;
            columnHeaderRenderer15.ZoomFactor = 1F;
            rowHeaderRenderer15.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer15.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer15.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer15.Name = "rowHeaderRenderer15";
            rowHeaderRenderer15.PictureZoomEffect = false;
            rowHeaderRenderer15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer15.TextRotationAngle = 0D;
            rowHeaderRenderer15.ZoomFactor = 1F;
            columnHeaderRenderer16.Name = "columnHeaderRenderer16";
            columnHeaderRenderer16.PictureZoomEffect = false;
            columnHeaderRenderer16.TextRotationAngle = 0D;
            columnHeaderRenderer16.ZoomFactor = 1F;
            rowHeaderRenderer16.Name = "rowHeaderRenderer16";
            rowHeaderRenderer16.PictureZoomEffect = false;
            rowHeaderRenderer16.TextRotationAngle = 0D;
            rowHeaderRenderer16.ZoomFactor = 1F;
            columnHeaderRenderer17.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer17.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer17.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer17.Name = "columnHeaderRenderer17";
            columnHeaderRenderer17.PictureZoomEffect = false;
            columnHeaderRenderer17.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer17.TextRotationAngle = 0D;
            columnHeaderRenderer17.ZoomFactor = 1F;
            rowHeaderRenderer17.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer17.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer17.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer17.Name = "rowHeaderRenderer17";
            rowHeaderRenderer17.PictureZoomEffect = false;
            rowHeaderRenderer17.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer17.TextRotationAngle = 0D;
            rowHeaderRenderer17.ZoomFactor = 1F;
            columnHeaderRenderer18.Name = "columnHeaderRenderer18";
            columnHeaderRenderer18.PictureZoomEffect = false;
            columnHeaderRenderer18.TextRotationAngle = 0D;
            columnHeaderRenderer18.ZoomFactor = 1F;
            rowHeaderRenderer18.Name = "rowHeaderRenderer18";
            rowHeaderRenderer18.PictureZoomEffect = false;
            rowHeaderRenderer18.TextRotationAngle = 0D;
            rowHeaderRenderer18.ZoomFactor = 1F;
            columnHeaderRenderer19.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer19.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer19.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer19.Name = "columnHeaderRenderer19";
            columnHeaderRenderer19.PictureZoomEffect = false;
            columnHeaderRenderer19.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer19.TextRotationAngle = 0D;
            columnHeaderRenderer19.ZoomFactor = 1F;
            rowHeaderRenderer19.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer19.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer19.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer19.Name = "rowHeaderRenderer19";
            rowHeaderRenderer19.PictureZoomEffect = false;
            rowHeaderRenderer19.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer19.TextRotationAngle = 0D;
            rowHeaderRenderer19.ZoomFactor = 1F;
            columnHeaderRenderer20.Name = "columnHeaderRenderer20";
            columnHeaderRenderer20.PictureZoomEffect = false;
            columnHeaderRenderer20.TextRotationAngle = 0D;
            columnHeaderRenderer20.ZoomFactor = 1F;
            rowHeaderRenderer20.Name = "rowHeaderRenderer20";
            rowHeaderRenderer20.PictureZoomEffect = false;
            rowHeaderRenderer20.TextRotationAngle = 0D;
            rowHeaderRenderer20.ZoomFactor = 1F;
            columnHeaderRenderer21.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer21.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer21.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer21.Name = "columnHeaderRenderer21";
            columnHeaderRenderer21.PictureZoomEffect = false;
            columnHeaderRenderer21.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer21.TextRotationAngle = 0D;
            columnHeaderRenderer21.ZoomFactor = 1F;
            rowHeaderRenderer21.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer21.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer21.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer21.Name = "rowHeaderRenderer21";
            rowHeaderRenderer21.PictureZoomEffect = false;
            rowHeaderRenderer21.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer21.TextRotationAngle = 0D;
            rowHeaderRenderer21.ZoomFactor = 1F;
            columnHeaderRenderer22.Name = "columnHeaderRenderer22";
            columnHeaderRenderer22.PictureZoomEffect = false;
            columnHeaderRenderer22.TextRotationAngle = 0D;
            columnHeaderRenderer22.ZoomFactor = 1F;
            rowHeaderRenderer22.Name = "rowHeaderRenderer22";
            rowHeaderRenderer22.PictureZoomEffect = false;
            rowHeaderRenderer22.TextRotationAngle = 0D;
            rowHeaderRenderer22.ZoomFactor = 1F;
            columnHeaderRenderer23.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer23.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer23.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer23.Name = "columnHeaderRenderer23";
            columnHeaderRenderer23.PictureZoomEffect = false;
            columnHeaderRenderer23.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer23.TextRotationAngle = 0D;
            columnHeaderRenderer23.ZoomFactor = 1F;
            rowHeaderRenderer23.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer23.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer23.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer23.Name = "rowHeaderRenderer23";
            rowHeaderRenderer23.PictureZoomEffect = false;
            rowHeaderRenderer23.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer23.TextRotationAngle = 0D;
            rowHeaderRenderer23.ZoomFactor = 1F;
            columnHeaderRenderer24.Name = "columnHeaderRenderer24";
            columnHeaderRenderer24.PictureZoomEffect = false;
            columnHeaderRenderer24.TextRotationAngle = 0D;
            columnHeaderRenderer24.ZoomFactor = 1F;
            rowHeaderRenderer24.Name = "rowHeaderRenderer24";
            rowHeaderRenderer24.PictureZoomEffect = false;
            rowHeaderRenderer24.TextRotationAngle = 0D;
            rowHeaderRenderer24.ZoomFactor = 1F;
            columnHeaderRenderer25.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer25.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer25.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer25.Name = "columnHeaderRenderer25";
            columnHeaderRenderer25.PictureZoomEffect = false;
            columnHeaderRenderer25.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer25.TextRotationAngle = 0D;
            columnHeaderRenderer25.ZoomFactor = 1F;
            rowHeaderRenderer25.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer25.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer25.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer25.Name = "rowHeaderRenderer25";
            rowHeaderRenderer25.PictureZoomEffect = false;
            rowHeaderRenderer25.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer25.TextRotationAngle = 0D;
            rowHeaderRenderer25.ZoomFactor = 1F;
            columnHeaderRenderer26.Name = "columnHeaderRenderer26";
            columnHeaderRenderer26.PictureZoomEffect = false;
            columnHeaderRenderer26.TextRotationAngle = 0D;
            columnHeaderRenderer26.ZoomFactor = 1F;
            rowHeaderRenderer26.Name = "rowHeaderRenderer26";
            rowHeaderRenderer26.PictureZoomEffect = false;
            rowHeaderRenderer26.TextRotationAngle = 0D;
            rowHeaderRenderer26.ZoomFactor = 1F;
            columnHeaderRenderer27.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer27.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer27.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer27.Name = "columnHeaderRenderer27";
            columnHeaderRenderer27.PictureZoomEffect = false;
            columnHeaderRenderer27.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer27.TextRotationAngle = 0D;
            columnHeaderRenderer27.ZoomFactor = 1F;
            rowHeaderRenderer27.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer27.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer27.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer27.Name = "rowHeaderRenderer27";
            rowHeaderRenderer27.PictureZoomEffect = false;
            rowHeaderRenderer27.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer27.TextRotationAngle = 0D;
            rowHeaderRenderer27.ZoomFactor = 1F;
            columnHeaderRenderer28.Name = "columnHeaderRenderer28";
            columnHeaderRenderer28.PictureZoomEffect = false;
            columnHeaderRenderer28.TextRotationAngle = 0D;
            columnHeaderRenderer28.ZoomFactor = 1F;
            rowHeaderRenderer28.Name = "rowHeaderRenderer28";
            rowHeaderRenderer28.PictureZoomEffect = false;
            rowHeaderRenderer28.TextRotationAngle = 0D;
            rowHeaderRenderer28.ZoomFactor = 1F;
            columnHeaderRenderer29.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer29.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer29.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer29.Name = "columnHeaderRenderer29";
            columnHeaderRenderer29.PictureZoomEffect = false;
            columnHeaderRenderer29.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer29.TextRotationAngle = 0D;
            columnHeaderRenderer29.ZoomFactor = 1F;
            rowHeaderRenderer29.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer29.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer29.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer29.Name = "rowHeaderRenderer29";
            rowHeaderRenderer29.PictureZoomEffect = false;
            rowHeaderRenderer29.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer29.TextRotationAngle = 0D;
            rowHeaderRenderer29.ZoomFactor = 1F;
            columnHeaderRenderer30.Name = "columnHeaderRenderer30";
            columnHeaderRenderer30.PictureZoomEffect = false;
            columnHeaderRenderer30.TextRotationAngle = 0D;
            columnHeaderRenderer30.ZoomFactor = 1F;
            rowHeaderRenderer30.Name = "rowHeaderRenderer30";
            rowHeaderRenderer30.PictureZoomEffect = false;
            rowHeaderRenderer30.TextRotationAngle = 0D;
            rowHeaderRenderer30.ZoomFactor = 1F;
            columnHeaderRenderer31.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer31.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer31.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer31.Name = "columnHeaderRenderer31";
            columnHeaderRenderer31.PictureZoomEffect = false;
            columnHeaderRenderer31.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer31.TextRotationAngle = 0D;
            columnHeaderRenderer31.ZoomFactor = 1F;
            rowHeaderRenderer31.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer31.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer31.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer31.Name = "rowHeaderRenderer31";
            rowHeaderRenderer31.PictureZoomEffect = false;
            rowHeaderRenderer31.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer31.TextRotationAngle = 0D;
            rowHeaderRenderer31.ZoomFactor = 1F;
            columnHeaderRenderer32.Name = "columnHeaderRenderer32";
            columnHeaderRenderer32.PictureZoomEffect = false;
            columnHeaderRenderer32.TextRotationAngle = 0D;
            columnHeaderRenderer32.ZoomFactor = 1F;
            rowHeaderRenderer32.Name = "rowHeaderRenderer32";
            rowHeaderRenderer32.PictureZoomEffect = false;
            rowHeaderRenderer32.TextRotationAngle = 0D;
            rowHeaderRenderer32.ZoomFactor = 1F;
            columnHeaderRenderer33.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer33.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer33.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer33.Name = "columnHeaderRenderer33";
            columnHeaderRenderer33.PictureZoomEffect = false;
            columnHeaderRenderer33.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer33.TextRotationAngle = 0D;
            columnHeaderRenderer33.ZoomFactor = 1F;
            rowHeaderRenderer33.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer33.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer33.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer33.Name = "rowHeaderRenderer33";
            rowHeaderRenderer33.PictureZoomEffect = false;
            rowHeaderRenderer33.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer33.TextRotationAngle = 0D;
            rowHeaderRenderer33.ZoomFactor = 1F;
            columnHeaderRenderer34.Name = "columnHeaderRenderer34";
            columnHeaderRenderer34.PictureZoomEffect = false;
            columnHeaderRenderer34.TextRotationAngle = 0D;
            columnHeaderRenderer34.ZoomFactor = 1F;
            rowHeaderRenderer34.Name = "rowHeaderRenderer34";
            rowHeaderRenderer34.PictureZoomEffect = false;
            rowHeaderRenderer34.TextRotationAngle = 0D;
            rowHeaderRenderer34.ZoomFactor = 1F;
            columnHeaderRenderer35.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer35.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer35.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer35.Name = "columnHeaderRenderer35";
            columnHeaderRenderer35.PictureZoomEffect = false;
            columnHeaderRenderer35.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer35.TextRotationAngle = 0D;
            columnHeaderRenderer35.ZoomFactor = 1F;
            rowHeaderRenderer35.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer35.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer35.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer35.Name = "rowHeaderRenderer35";
            rowHeaderRenderer35.PictureZoomEffect = false;
            rowHeaderRenderer35.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer35.TextRotationAngle = 0D;
            rowHeaderRenderer35.ZoomFactor = 1F;
            columnHeaderRenderer36.Name = "columnHeaderRenderer36";
            columnHeaderRenderer36.PictureZoomEffect = false;
            columnHeaderRenderer36.TextRotationAngle = 0D;
            columnHeaderRenderer36.ZoomFactor = 1F;
            rowHeaderRenderer36.Name = "rowHeaderRenderer36";
            rowHeaderRenderer36.PictureZoomEffect = false;
            rowHeaderRenderer36.TextRotationAngle = 0D;
            rowHeaderRenderer36.ZoomFactor = 1F;
            // 
            // txtLotID
            // 
            this.txtLotID.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.txtLotID.Location = new System.Drawing.Point(109, 19);
            this.txtLotID.Name = "txtLotID";
            this.txtLotID.Size = new System.Drawing.Size(277, 26);
            this.txtLotID.TabIndex = 261;
            this.txtLotID.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtInvLotID_KeyDown);
            // 
            // lblLotId
            // 
            this.lblLotId.AutoSize = true;
            this.lblLotId.BackColor = System.Drawing.Color.White;
            this.lblLotId.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.lblLotId.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblLotId.ForeColor = System.Drawing.Color.Black;
            this.lblLotId.Location = new System.Drawing.Point(11, 24);
            this.lblLotId.Name = "lblLotId";
            this.lblLotId.Size = new System.Drawing.Size(48, 16);
            this.lblLotId.TabIndex = 260;
            this.lblLotId.Text = "Lot ID";
            this.lblLotId.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // grpRawMatList
            // 
            this.grpRawMatList.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.None;
            appearance1.BackColor = System.Drawing.Color.White;
            appearance1.BackColor2 = System.Drawing.Color.White;
            this.grpRawMatList.ContentAreaAppearance = appearance1;
            this.grpRawMatList.Controls.Add(this.spdRawMatList);
            this.grpRawMatList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpRawMatList.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            appearance2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(59)))), ((int)(((byte)(98)))));
            appearance2.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(59)))), ((int)(((byte)(98)))));
            appearance2.ForeColor = System.Drawing.Color.White;
            this.grpRawMatList.HeaderAppearance = appearance2;
            this.grpRawMatList.Location = new System.Drawing.Point(10, 120);
            this.grpRawMatList.Margin = new System.Windows.Forms.Padding(5);
            this.grpRawMatList.Name = "grpRawMatList";
            this.grpRawMatList.Size = new System.Drawing.Size(1219, 670);
            this.grpRawMatList.TabIndex = 245;
            this.grpRawMatList.Text = "Inv Lot List";
            // 
            // spdRawMatList
            // 
            this.spdRawMatList.AccessibleDescription = "spdRawMatList, Sheet1";
            this.spdRawMatList.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.spdRawMatList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.spdRawMatList.FocusRenderer = defaultFocusIndicatorRenderer1;
            this.spdRawMatList.HorizontalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdRawMatList.HorizontalScrollBar.Name = "";
            this.spdRawMatList.HorizontalScrollBar.Renderer = defaultScrollBarRenderer1;
            this.spdRawMatList.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdRawMatList.Location = new System.Drawing.Point(1, 19);
            this.spdRawMatList.Margin = new System.Windows.Forms.Padding(0);
            this.spdRawMatList.Name = "spdRawMatList";
            namedStyle1.BackColor = System.Drawing.SystemColors.Control;
            filterBarCellType1.FormatString = "";
            namedStyle1.CellType = filterBarCellType1;
            namedStyle1.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle1.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle1.Locked = false;
            namedStyle1.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle1.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle1.Renderer = filterBarCellType1;
            namedStyle1.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle1.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle2.BackColor = System.Drawing.Color.Aqua;
            namedStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle2.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle2.Locked = false;
            namedStyle2.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle2.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle2.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle2.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle3.BackColor = System.Drawing.SystemColors.Window;
            namedStyle3.CellType = generalCellType1;
            namedStyle3.ForeColor = System.Drawing.SystemColors.WindowText;
            namedStyle3.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle3.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle3.Renderer = generalCellType1;
            namedStyle3.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle3.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            namedStyle4.Border = bevelBorder1;
            namedStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            namedStyle4.ForeColor = System.Drawing.Color.White;
            namedStyle4.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle4.Locked = false;
            namedStyle4.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle4.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle4.Renderer = generalCellType2;
            namedStyle4.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle4.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle5.BackColor = System.Drawing.SystemColors.Control;
            filterBarCellType2.FormatString = "";
            namedStyle5.CellType = filterBarCellType2;
            namedStyle5.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle5.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle5.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle5.Renderer = filterBarCellType2;
            namedStyle5.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle5.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle6.BackColor = System.Drawing.SystemColors.Control;
            namedStyle6.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle6.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle6.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle6.Renderer = columnHeaderRenderer36;
            namedStyle6.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle6.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle7.BackColor = System.Drawing.SystemColors.Control;
            namedStyle7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            namedStyle7.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle7.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle7.Locked = false;
            namedStyle7.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle7.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle7.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle7.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle8.BackColor = System.Drawing.SystemColors.Control;
            namedStyle8.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle8.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle8.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle8.Renderer = rowHeaderRenderer36;
            namedStyle8.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle8.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle9.BackColor = System.Drawing.Color.White;
            namedStyle9.CellType = generalCellType3;
            namedStyle9.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            namedStyle9.ForeColor = System.Drawing.Color.Black;
            namedStyle9.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle9.Locked = false;
            namedStyle9.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle9.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle9.Renderer = generalCellType3;
            namedStyle9.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle9.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.spdRawMatList.NamedStyles.AddRange(new FarPoint.Win.Spread.NamedStyle[] {
            namedStyle1,
            namedStyle2,
            namedStyle3,
            namedStyle4,
            namedStyle5,
            namedStyle6,
            namedStyle7,
            namedStyle8,
            namedStyle9});
            this.spdRawMatList.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.spdRawMatList_Sheet1});
            this.spdRawMatList.Size = new System.Drawing.Size(1217, 650);
            spreadSkin1.ColumnFooterDefaultStyle = namedStyle6;
            spreadSkin1.ColumnHeaderDefaultStyle = namedStyle4;
            spreadSkin1.CornerDefaultStyle = namedStyle8;
            spreadSkin1.DefaultStyle = namedStyle9;
            spreadSkin1.FilterBarDefaultStyle = namedStyle5;
            spreadSkin1.FilterBarHeaderDefaultStyle = namedStyle8;
            spreadSkin1.FocusRenderer = defaultFocusIndicatorRenderer1;
            spreadSkin1.Name = "사용1";
            spreadSkin1.RowHeaderDefaultStyle = namedStyle7;
            spreadSkin1.ScrollBarRenderer = defaultScrollBarRenderer2;
            spreadSkin1.SelectionRenderer = new FarPoint.Win.Spread.DefaultSelectionRenderer();
            statusBarSkin1.BackColor = System.Drawing.SystemColors.Control;
            statusBarSkin1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            statusBarSkin1.ForeColor = System.Drawing.SystemColors.ControlText;
            statusBarSkin1.Name = "Classic";
            statusBarSkin1.ZoomButtonHoverColor = System.Drawing.SystemColors.ButtonHighlight;
            statusBarSkin1.ZoomSliderColor = System.Drawing.SystemColors.ControlDarkDark;
            statusBarSkin1.ZoomSliderHoverColor = System.Drawing.SystemColors.ControlDark;
            statusBarSkin1.ZoomSliderTrackColor = System.Drawing.SystemColors.ControlDarkDark;
            spreadSkin1.StatusBarSkin = statusBarSkin1;
            this.spdRawMatList.Skin = spreadSkin1;
            this.spdRawMatList.TabIndex = 251;
            this.spdRawMatList.TabStop = false;
            this.spdRawMatList.VerticalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdRawMatList.VerticalScrollBar.Name = "";
            this.spdRawMatList.VerticalScrollBar.Renderer = defaultScrollBarRenderer3;
            this.spdRawMatList.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdRawMatList.CellClick += new FarPoint.Win.Spread.CellClickEventHandler(this.spdRawMatList_CellClick);
            // 
            // spdRawMatList_Sheet1
            // 
            this.spdRawMatList_Sheet1.Reset();
            this.spdRawMatList_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.spdRawMatList_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.spdRawMatList_Sheet1.ColumnCount = 10;
            this.spdRawMatList_Sheet1.RowCount = 0;
            this.spdRawMatList_Sheet1.ActiveColumnIndex = -1;
            this.spdRawMatList_Sheet1.ActiveRowIndex = -1;
            this.spdRawMatList_Sheet1.ColumnFooter.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdRawMatList_Sheet1.ColumnFooter.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdRawMatList_Sheet1.ColumnFooter.DefaultStyle.Parent = "HeaderDefault";
            this.spdRawMatList_Sheet1.ColumnFooter.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "Inv Lot Id";
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "Mat Id";
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "Mat Ver";
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "Mat Desc";
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "Bom Converted Qty";
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "Unit";
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "Vendor Desc";
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 7).Value = "Recv Date";
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 8).Value = "PO No";
            this.spdRawMatList_Sheet1.ColumnHeader.Cells.Get(0, 9).Value = "PO Seq";
            this.spdRawMatList_Sheet1.ColumnHeader.DefaultStyle.Border = bevelBorder2;
            this.spdRawMatList_Sheet1.ColumnHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdRawMatList_Sheet1.ColumnHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdRawMatList_Sheet1.ColumnHeader.DefaultStyle.Parent = "Style1";
            this.spdRawMatList_Sheet1.ColumnHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.ColumnHeader.Rows.Get(0).Height = 25F;
            this.spdRawMatList_Sheet1.Columns.Get(0).AllowAutoSort = true;
            this.spdRawMatList_Sheet1.Columns.Get(0).Label = "Inv Lot Id";
            this.spdRawMatList_Sheet1.Columns.Get(0).Locked = true;
            this.spdRawMatList_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.Columns.Get(0).Width = 151F;
            this.spdRawMatList_Sheet1.Columns.Get(1).AllowAutoSort = true;
            this.spdRawMatList_Sheet1.Columns.Get(1).Label = "Mat Id";
            this.spdRawMatList_Sheet1.Columns.Get(1).Locked = true;
            this.spdRawMatList_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.Columns.Get(1).Width = 96F;
            this.spdRawMatList_Sheet1.Columns.Get(2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdRawMatList_Sheet1.Columns.Get(2).Label = "Mat Ver";
            this.spdRawMatList_Sheet1.Columns.Get(3).AllowAutoSort = true;
            this.spdRawMatList_Sheet1.Columns.Get(3).Label = "Mat Desc";
            this.spdRawMatList_Sheet1.Columns.Get(3).Locked = true;
            this.spdRawMatList_Sheet1.Columns.Get(3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.Columns.Get(3).Width = 221F;
            this.spdRawMatList_Sheet1.Columns.Get(4).AllowAutoSort = true;
            numberCellType1.DecimalPlaces = 5;
            numberCellType1.ShowSeparator = true;
            this.spdRawMatList_Sheet1.Columns.Get(4).CellType = numberCellType1;
            this.spdRawMatList_Sheet1.Columns.Get(4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdRawMatList_Sheet1.Columns.Get(4).Label = "Bom Converted Qty";
            this.spdRawMatList_Sheet1.Columns.Get(4).Locked = true;
            this.spdRawMatList_Sheet1.Columns.Get(4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.Columns.Get(4).Width = 138F;
            this.spdRawMatList_Sheet1.Columns.Get(5).AllowAutoSort = true;
            this.spdRawMatList_Sheet1.Columns.Get(5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdRawMatList_Sheet1.Columns.Get(5).Label = "Unit";
            this.spdRawMatList_Sheet1.Columns.Get(5).Locked = true;
            this.spdRawMatList_Sheet1.Columns.Get(5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.Columns.Get(6).AllowAutoSort = true;
            this.spdRawMatList_Sheet1.Columns.Get(6).Label = "Vendor Desc";
            this.spdRawMatList_Sheet1.Columns.Get(6).Locked = true;
            this.spdRawMatList_Sheet1.Columns.Get(6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.Columns.Get(6).Width = 174F;
            this.spdRawMatList_Sheet1.Columns.Get(7).AllowAutoSort = true;
            this.spdRawMatList_Sheet1.Columns.Get(7).Label = "Recv Date";
            this.spdRawMatList_Sheet1.Columns.Get(7).Locked = true;
            this.spdRawMatList_Sheet1.Columns.Get(7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.Columns.Get(7).Width = 109F;
            this.spdRawMatList_Sheet1.Columns.Get(8).AllowAutoSort = true;
            this.spdRawMatList_Sheet1.Columns.Get(8).Label = "PO No";
            this.spdRawMatList_Sheet1.Columns.Get(8).Locked = true;
            this.spdRawMatList_Sheet1.Columns.Get(8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.Columns.Get(8).Width = 83F;
            this.spdRawMatList_Sheet1.Columns.Get(9).AllowAutoSort = true;
            numberCellType2.DecimalPlaces = 0;
            this.spdRawMatList_Sheet1.Columns.Get(9).CellType = numberCellType2;
            this.spdRawMatList_Sheet1.Columns.Get(9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdRawMatList_Sheet1.Columns.Get(9).Label = "PO Seq";
            this.spdRawMatList_Sheet1.Columns.Get(9).Locked = true;
            this.spdRawMatList_Sheet1.Columns.Get(9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdRawMatList_Sheet1.Columns.Get(9).Width = 62F;
            this.spdRawMatList_Sheet1.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdRawMatList_Sheet1.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdRawMatList_Sheet1.DefaultStyle.Parent = "Style2";
            this.spdRawMatList_Sheet1.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdRawMatList_Sheet1.EnhancedFilterSortingMode = FarPoint.Win.Spread.EnhancedFilterSortingMode.Text;
            this.spdRawMatList_Sheet1.FilterBar.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdRawMatList_Sheet1.FilterBar.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdRawMatList_Sheet1.FilterBar.DefaultStyle.Parent = "FilterBarDefault";
            this.spdRawMatList_Sheet1.FilterBar.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdRawMatList_Sheet1.FilterBarHeaderStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdRawMatList_Sheet1.FilterBarHeaderStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdRawMatList_Sheet1.FilterBarHeaderStyle.Parent = "RowHeaderDefault";
            this.spdRawMatList_Sheet1.FilterBarHeaderStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdRawMatList_Sheet1.GrayAreaBackColor = System.Drawing.Color.White;
            this.spdRawMatList_Sheet1.NullBackColor = System.Drawing.Color.White;
            this.spdRawMatList_Sheet1.OperationMode = FarPoint.Win.Spread.OperationMode.ReadOnly;
            this.spdRawMatList_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.spdRawMatList_Sheet1.RowHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdRawMatList_Sheet1.RowHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdRawMatList_Sheet1.RowHeader.DefaultStyle.Parent = "Style3";
            this.spdRawMatList_Sheet1.RowHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdRawMatList_Sheet1.RowHeader.Visible = false;
            this.spdRawMatList_Sheet1.Rows.Default.Height = 25F;
            this.spdRawMatList_Sheet1.SheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdRawMatList_Sheet1.SheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdRawMatList_Sheet1.SheetCornerStyle.Parent = "RowHeaderDefault";
            this.spdRawMatList_Sheet1.SheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdRawMatList_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // btnExcel
            // 
            appearance19.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            appearance19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            appearance19.FontData.BoldAsString = "True";
            appearance19.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            this.btnExcel.Appearance = appearance19;
            this.btnExcel.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExcel.Location = new System.Drawing.Point(12, 10);
            this.btnExcel.Name = "btnExcel";
            this.btnExcel.Size = new System.Drawing.Size(100, 30);
            this.btnExcel.TabIndex = 275;
            this.btnExcel.Text = "Excel";
            this.btnExcel.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.btnExcel.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.btnExcel.Click += new System.EventHandler(this.btnExcel_Click);
            // 
            // frmViewShipLotRawMaterialList
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1239, 840);
            this.Name = "frmViewShipLotRawMaterialList";
            this.Text = "View Ship Lot Raw Material List";
            this.Load += new System.EventHandler(this.frmViewShipLotRawMaterialList_Load);
            this.pnlStsCond.ResumeLayout(false);
            this.pnlStsCond.PerformLayout();
            this.pnlMID.ResumeLayout(false);
            this.pnlMID.PerformLayout();
            this.pnlBottom.ResumeLayout(false);
            this.pnlCenter.ResumeLayout(false);
            this.pnlTop.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.grpRawMatList)).EndInit();
            this.grpRawMatList.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.spdRawMatList)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdRawMatList_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        public System.Windows.Forms.TextBox txtLotID;
        public System.Windows.Forms.Label lblLotId;
        private Infragistics.Win.Misc.UltraGroupBox grpRawMatList;
        protected Infragistics.Win.Misc.UltraButton btnExcel;
        private FarPoint.Win.Spread.FpSpread spdRawMatList;
        private FarPoint.Win.Spread.SheetView spdRawMatList_Sheet1;
    }
}