#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Fri Jul 13 13:23:03 KST 2018
apiSecret=96ab35fe2f19f0fb8c6ad10e411df81b65473783d9979d80e714159a3ad5d869
