Insert into MFMBENVDEF
   (FACTORY, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME, FONT_FAMILY, RES_WIDTH, RES_HEIGHT, SRS_WIDTH, SRS_HEIGHT, POT_WIDTH, POT_HEIGHT, TOL_WIDTH, TOL_HEIGHT, RTG_WIDTH, RTG_HEIGHT, ELP_WIDTH, ELP_HEIGHT, TRI_WIDTH, TRI_HEIGHT, VER_WIDTH, VER_HEIGHT, HOR_WIDTH, HOR_HEIGHT, PIE1_WIDTH, PIE1_HEIGHT, PIE2_WIDTH, PIE2_HEIGHT, PIE3_WIDTH, PIE3_HEIGHT, PIE4_WIDTH, PIE4_HEIGHT, LAYOUT_WIDTH, LAYOUT_HEIGHT, UDR_WIDTH, UDR_HEIGHT, EVENT_COLOR_FLAG, SIGNAL_FLAG, TEXT_SIZE, TEXT_COLOR, BACK_COLOR, BACK_OPT)
 Values
   ('SYSTEM', 'ADMIN', '20050324094440', 'ADMIN', '20050328130338', 'Arial', 100, 50, 80, 40, 80, 40, 80, 40, 50, 50, 50, 50, 50, 50, 100, 8, 100, 8, 50, 50, 50, 50, 50, 50, 50, 50, 800, 600, 800, 600, ' ', 'P', 8, 26, 102, ' ');


INSERT INTO MGCMTBLDAT 
(FACTORY, TABLE_NAME, KEY_1, KEY_2, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5,
DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID,
UPDATE_TIME ) 
VALUES 
('SYSTEM', 'UPGRADE_OPTION', 'FMBClient', ' ', '1', 'FMB_V5.0.0.5', ' ', ' ', ' ', ' '
, ' ', ' ', ' ', ' ', 'ADMIN', '20050914170950', 'ADMIN', '20050927132219'); 


Insert into MGCMTBLDEF
   (FACTORY, TABLE_NAME, TABLE_DESC, SYS_TBL_FLAG, CENTRAL_FLAG, TABLE_TYPE, USE_SQL_FLAG, TABLE_GROUP, KEY_1_PRT, KEY_1_FMT, KEY_1_SIZE, KEY_2_PRT, KEY_2_FMT, KEY_2_SIZE, KEY_3_PRT, KEY_3_FMT, KEY_3_SIZE, KEY_4_PRT, KEY_4_FMT, KEY_4_SIZE, KEY_5_PRT, KEY_5_FMT, KEY_5_SIZE, KEY_6_PRT, KEY_6_FMT, KEY_6_SIZE, KEY_7_PRT, KEY_7_FMT, KEY_7_SIZE, KEY_8_PRT, KEY_8_FMT, KEY_8_SIZE, KEY_9_PRT, KEY_9_FMT, KEY_9_SIZE, KEY_10_PRT, KEY_10_FMT, KEY_10_SIZE, DATA_1_PRT, DATA_1_FMT, DATA_1_SIZE, DATA_2_PRT, DATA_2_FMT, DATA_2_SIZE, DATA_3_PRT, DATA_3_FMT, DATA_3_SIZE, DATA_4_PRT, DATA_4_FMT, DATA_4_SIZE, DATA_5_PRT, DATA_5_FMT, DATA_5_SIZE, DATA_6_PRT, DATA_6_FMT, DATA_6_SIZE, DATA_7_PRT, DATA_7_FMT, DATA_7_SIZE, DATA_8_PRT, DATA_8_FMT, DATA_8_SIZE, DATA_9_PRT, DATA_9_FMT, DATA_9_SIZE, DATA_10_PRT, DATA_10_FMT, DATA_10_SIZE, SQL_1, SQL_2, SQL_3, SQL_4, SQL_5, TABLE_PASSWORD, SEC_CHK_FLAG, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'FMB_SUBRES_TYPE', 'FMB Sub Resource Type Table', ' ', 'Y', ' ', ' ', 'SYSTEM', 'TYPE', 'A', 10, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, 'DESCRIPTION', 'A', 50, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20081204174320', ' ', ' ');

Insert into MGCMTBLDAT
   (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'FMB_SUBRES_TYPE', 'RES', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Resource', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20081204174410', ' ', ' ');
Insert into MGCMTBLDAT
   (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'FMB_SUBRES_TYPE', 'SUBRES', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Sub Resource', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20081204174410', ' ', ' ');
Insert into MGCMTBLDAT
   (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'FMB_SUBRES_TYPE', 'PORT', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Port', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20081204174410', ' ', ' ');
Insert into MGCMTBLDAT
   (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'FMB_SUBRES_TYPE', 'TOOL', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Tool', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20081204174410', ' ', ' ');
