--##### INSERT SYSTEM GCM(General Code Table) #####

INSERT INTO MGCMTBLDEF 
(FACTORY, TABLE_NAME, TABLE_DESC, SYS_TBL_FLAG, CENTRAL_FLAG, TABLE_TYPE, TABLE_GROUP,
KEY_1_PRT, KEY_1_FMT, KEY_1_SIZE, KEY_2_PRT, KEY_2_FMT, KEY_2_SIZE, KEY_3_PRT, KEY_3_FMT,
KEY_3_SIZE, KEY_4_PRT, KEY_4_FMT, KEY_4_SIZE, KEY_5_PRT, KEY_5_FMT, KEY_5_SIZE, KEY_6_PRT,
KEY_6_FMT, KEY_6_SIZE, KEY_7_PRT, KEY_7_FMT, KEY_7_SIZE, KEY_8_PRT, KEY_8_FMT, KEY_8_SIZE,
KEY_9_PRT, KEY_9_FMT, KEY_9_SIZE, KEY_10_PRT, KEY_10_FMT, KEY_10_SIZE, DATA_1_PRT, DATA_1_FMT,
DATA_1_SIZE, DATA_2_PRT, DATA_2_FMT, DATA_2_SIZE, DATA_3_PRT, DATA_3_FMT, DATA_3_SIZE, DATA_4_PRT,
DATA_4_FMT, DATA_4_SIZE, DATA_5_PRT, DATA_5_FMT, DATA_5_SIZE, DATA_6_PRT, DATA_6_FMT, DATA_6_SIZE,
DATA_7_PRT, DATA_7_FMT, DATA_7_SIZE, DATA_8_PRT, DATA_8_FMT, DATA_8_SIZE, DATA_9_PRT, DATA_9_FMT,
DATA_9_SIZE, DATA_10_PRT, DATA_10_FMT, DATA_10_SIZE, TABLE_PASSWORD, SEC_CHK_FLAG, CREATE_USER_ID,
CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) 
VALUES
('SYSTEM', 'SERVER_LIST', 'Server Name and Process Count List for Monitoring', 'Y', 'Y', ' ', ' ', 'SERVER_NAME', 'A', 20, 'SERVER_IP', 'A', 20, ' '
, ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' '
, 0, ' ', ' ', 0, 'DESCRIPTION', 'A', 50, 'PROCESS_COUNT', 'N', 2, ' ', ' ', 0, ' '
, ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' '
, 'ADMIN', '20050930151116', 'ADMIN', '20051017104055');

INSERT INTO MGCMTBLDAT 
(FACTORY, TABLE_NAME, KEY_1, KEY_2, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, 
DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, 
UPDATE_TIME) 
VALUES 
('SYSTEM', 'SERVER_LIST', 'ADMServer', 'DEFAULT', ' ', '1', ' ', ' ', ' ', ' ', ' ', ' ', ' '
, ' ', 'ADMIN', '20051017145611', ' ', ' ');

INSERT INTO MGCMTBLDAT 
(FACTORY, TABLE_NAME, KEY_1, KEY_2, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, 
DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, 
UPDATE_TIME) 
VALUES 
('SYSTEM', 'SERVER_LIST', 'RTDServer', 'DEFAULT', ' ', '1', ' ', ' ', ' ', ' ', ' ', ' ', ' '
, ' ', 'ADMIN', '20051017145611', ' ', ' ');

INSERT INTO MGCMTBLDAT 
(FACTORY, TABLE_NAME, KEY_1, KEY_2, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, 
DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, 
UPDATE_TIME) 
VALUES 
('SYSTEM', 'SERVER_LIST', 'MESServer', 'DEFAULT', ' ', '10', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '
, 'ADMIN', '20051017145611', ' ', ' ');


