/*
 MESplusV5 IPFB(Industrial Packaging For Backend) Initial Data Script
 */

INSERT INTO MATRNAMDEF (FACTORY,ATTR_TYPE,ATTR_NAME,ATTR_DESC,ATTR_SEQ,ATTR_FMT,ATTR_SIZE,VALID_TBL_TYPE,VALID_TBL,ALLOW_BLANK,CREATE_USER_ID,CREATE_TIME,UPDATE_USER_ID,UPDATE_TIME,SEC_CHK_FLAG,KEY_HIST_INDEPENDENT_FLAG,NO_HISTORY_FLAG)
VALUES ('SYSTEM','LOT','SHIPPING_ID','Shipping ID',1,'A',30,' ',' ',' ','ADMIN','20120410112643',' ',' ',' ',' ',' ');

