namespace CUS_COM
{
    partial class frmPopMaterialList
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer1 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer1 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer2 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer2 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer3 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer3 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer4 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer4 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer5 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer5 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer6 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer7 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer6 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer8 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer9 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer7 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer10 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer11 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer8 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer12 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer13 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer9 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer14 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer15 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer10 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer16 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer17 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer11 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer18 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer19 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer12 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer20 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer21 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer13 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer22 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer23 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer14 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer24 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer25 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer15 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer26 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer27 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer16 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer28 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer29 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer17 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer30 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer31 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer18 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer32 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer33 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer19 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer34 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer35 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer20 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer36 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer37 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer21 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer38 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer39 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer22 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer40 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer41 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer23 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer42 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer43 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer24 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer44 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer45 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer25 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer46 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer47 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer26 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer48 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer49 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer27 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer50 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer51 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.ColumnHeaderRenderer columnHeaderRenderer28 = new FarPoint.Win.Spread.CellType.ColumnHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer52 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            FarPoint.Win.Spread.CellType.RowHeaderRenderer rowHeaderRenderer53 = new FarPoint.Win.Spread.CellType.RowHeaderRenderer();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            FarPoint.Win.Spread.DefaultFocusIndicatorRenderer defaultFocusIndicatorRenderer2 = new FarPoint.Win.Spread.DefaultFocusIndicatorRenderer();
            FarPoint.Win.Spread.DefaultScrollBarRenderer defaultScrollBarRenderer4 = new FarPoint.Win.Spread.DefaultScrollBarRenderer();
            FarPoint.Win.Spread.NamedStyle namedStyle10 = new FarPoint.Win.Spread.NamedStyle("Style4");
            FarPoint.Win.Spread.CellType.FilterBarCellType filterBarCellType3 = new FarPoint.Win.Spread.CellType.FilterBarCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle11 = new FarPoint.Win.Spread.NamedStyle("Style5");
            FarPoint.Win.Spread.NamedStyle namedStyle12 = new FarPoint.Win.Spread.NamedStyle("DataAreaDefault");
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType5 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle13 = new FarPoint.Win.Spread.NamedStyle("Style1");
            FarPoint.Win.BevelBorder bevelBorder3 = new FarPoint.Win.BevelBorder(FarPoint.Win.BevelBorderType.Lowered);
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType6 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle14 = new FarPoint.Win.Spread.NamedStyle("FilterBarDefault");
            FarPoint.Win.Spread.CellType.FilterBarCellType filterBarCellType4 = new FarPoint.Win.Spread.CellType.FilterBarCellType();
            FarPoint.Win.Spread.NamedStyle namedStyle15 = new FarPoint.Win.Spread.NamedStyle("HeaderDefault");
            FarPoint.Win.Spread.NamedStyle namedStyle16 = new FarPoint.Win.Spread.NamedStyle("Style3");
            FarPoint.Win.Spread.NamedStyle namedStyle17 = new FarPoint.Win.Spread.NamedStyle("RowHeaderDefault");
            FarPoint.Win.Spread.NamedStyle namedStyle18 = new FarPoint.Win.Spread.NamedStyle("Style2");
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType7 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.SpreadSkin spreadSkin2 = new FarPoint.Win.Spread.SpreadSkin();
            FarPoint.Win.Spread.DefaultScrollBarRenderer defaultScrollBarRenderer5 = new FarPoint.Win.Spread.DefaultScrollBarRenderer();
            FarPoint.Win.Spread.StatusBarSkin statusBarSkin2 = new FarPoint.Win.Spread.StatusBarSkin();
            FarPoint.Win.Spread.DefaultScrollBarRenderer defaultScrollBarRenderer6 = new FarPoint.Win.Spread.DefaultScrollBarRenderer();
            FarPoint.Win.BevelBorder bevelBorder4 = new FarPoint.Win.BevelBorder(FarPoint.Win.BevelBorderType.Lowered);
            FarPoint.Win.Spread.CellType.CheckBoxCellType checkBoxCellType2 = new FarPoint.Win.Spread.CellType.CheckBoxCellType();
            FarPoint.Win.Spread.CellType.GeneralCellType generalCellType8 = new FarPoint.Win.Spread.CellType.GeneralCellType();
            FarPoint.Win.Spread.CellType.ButtonCellType buttonCellType4 = new FarPoint.Win.Spread.CellType.ButtonCellType();
            FarPoint.Win.Spread.CellType.ButtonCellType buttonCellType5 = new FarPoint.Win.Spread.CellType.ButtonCellType();
            FarPoint.Win.Spread.CellType.ButtonCellType buttonCellType6 = new FarPoint.Win.Spread.CellType.ButtonCellType();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            this.lblDept = new System.Windows.Forms.Label();
            this.cdvDept = new Miracom.UI.Controls.MCCodeView.MCCodeView();
            this.lblMatType = new System.Windows.Forms.Label();
            this.cdvMatType = new Miracom.UI.Controls.MCCodeView.MCCodeView();
            this.txtMatDesc = new System.Windows.Forms.TextBox();
            this.lblMatDesc = new System.Windows.Forms.Label();
            this.grpMatList = new Infragistics.Win.Misc.UltraGroupBox();
            this.spdmatList = new FarPoint.Win.Spread.FpSpread();
            this.spdmatList_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.btnSelect = new Infragistics.Win.Misc.UltraButton();
            this.btnExcel = new Infragistics.Win.Misc.UltraButton();
            this.label1 = new System.Windows.Forms.Label();
            this.txtExcludeWord = new System.Windows.Forms.TextBox();
            this.pnlStsCond.SuspendLayout();
            this.pnlMID.SuspendLayout();
            this.pnlBottom.SuspendLayout();
            this.pnlCenter.SuspendLayout();
            this.pnlTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.cdvDept)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cdvMatType)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.grpMatList)).BeginInit();
            this.grpMatList.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.spdmatList)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdmatList_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // pnlStsCond
            // 
            this.pnlStsCond.Controls.Add(this.txtExcludeWord);
            this.pnlStsCond.Controls.Add(this.label1);
            this.pnlStsCond.Controls.Add(this.txtMatDesc);
            this.pnlStsCond.Controls.Add(this.lblMatDesc);
            this.pnlStsCond.Controls.Add(this.lblMatType);
            this.pnlStsCond.Controls.Add(this.cdvMatType);
            this.pnlStsCond.Controls.Add(this.lblDept);
            this.pnlStsCond.Controls.Add(this.cdvDept);
            this.pnlStsCond.Size = new System.Drawing.Size(884, 100);
            this.pnlStsCond.Controls.SetChildIndex(this.pnlStsCond3, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.pnlStsCond2, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.cdvDept, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.lblDept, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.cdvMatType, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.lblMatType, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.lblMatDesc, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.txtMatDesc, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.label1, 0);
            this.pnlStsCond.Controls.SetChildIndex(this.txtExcludeWord, 0);
            // 
            // pnlMID
            // 
            this.pnlMID.Controls.Add(this.grpMatList);
            this.pnlMID.Size = new System.Drawing.Size(904, 611);
            this.pnlMID.Controls.SetChildIndex(this.chkFavorite, 0);
            this.pnlMID.Controls.SetChildIndex(this.lblFormName, 0);
            this.pnlMID.Controls.SetChildIndex(this.pnlStsCond, 0);
            this.pnlMID.Controls.SetChildIndex(this.lblDirectQuery, 0);
            this.pnlMID.Controls.SetChildIndex(this.grpMatList, 0);
            // 
            // pnlStsCond3
            // 
            this.pnlStsCond3.Location = new System.Drawing.Point(0, 90);
            this.pnlStsCond3.Size = new System.Drawing.Size(884, 10);
            // 
            // lblFormName
            // 
            this.lblFormName.Size = new System.Drawing.Size(137, 30);
            this.lblFormName.Text = "Material List";
            // 
            // lblDirectQuery
            // 
            this.lblDirectQuery.Location = new System.Drawing.Point(-8120, 30);
            // 
            // btnView
            // 
            this.btnView.Location = new System.Drawing.Point(581, 10);
            this.btnView.TabIndex = 0;
            this.btnView.Click += new System.EventHandler(this.btnView_Click);
            // 
            // btnClose
            // 
            this.btnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.btnClose.Location = new System.Drawing.Point(793, 10);
            this.btnClose.TabIndex = 2;
            // 
            // pnlStsCond2
            // 
            this.pnlStsCond2.Size = new System.Drawing.Size(884, 10);
            // 
            // pnlBottom
            // 
            this.pnlBottom.Controls.Add(this.btnExcel);
            this.pnlBottom.Controls.Add(this.btnSelect);
            this.pnlBottom.Location = new System.Drawing.Point(0, 611);
            this.pnlBottom.Size = new System.Drawing.Size(904, 50);
            this.pnlBottom.Controls.SetChildIndex(this.btnClose, 0);
            this.pnlBottom.Controls.SetChildIndex(this.btnView, 0);
            this.pnlBottom.Controls.SetChildIndex(this.btnSelect, 0);
            this.pnlBottom.Controls.SetChildIndex(this.btnExcel, 0);
            // 
            // pnlCenter
            // 
            this.pnlCenter.Size = new System.Drawing.Size(904, 611);
            // 
            // pnlTop
            // 
            this.pnlTop.Size = new System.Drawing.Size(1239, 0);
            // 
            // lblFormTitle
            // 
            this.lblFormTitle.Size = new System.Drawing.Size(1235, 0);
            this.lblFormTitle.Text = "TranForm01";
            columnHeaderRenderer1.Name = "columnHeaderRenderer1";
            columnHeaderRenderer1.PictureZoomEffect = false;
            columnHeaderRenderer1.TextRotationAngle = 0D;
            columnHeaderRenderer1.ZoomFactor = 1F;
            rowHeaderRenderer1.Name = "rowHeaderRenderer1";
            rowHeaderRenderer1.PictureZoomEffect = false;
            rowHeaderRenderer1.TextRotationAngle = 0D;
            rowHeaderRenderer1.ZoomFactor = 1F;
            columnHeaderRenderer2.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer2.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer2.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer2.Name = "columnHeaderRenderer2";
            columnHeaderRenderer2.PictureZoomEffect = false;
            columnHeaderRenderer2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer2.TextRotationAngle = 0D;
            columnHeaderRenderer2.ZoomFactor = 1F;
            rowHeaderRenderer2.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer2.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer2.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer2.Name = "rowHeaderRenderer2";
            rowHeaderRenderer2.PictureZoomEffect = false;
            rowHeaderRenderer2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer2.TextRotationAngle = 0D;
            rowHeaderRenderer2.ZoomFactor = 1F;
            columnHeaderRenderer3.Name = "columnHeaderRenderer3";
            columnHeaderRenderer3.PictureZoomEffect = false;
            columnHeaderRenderer3.TextRotationAngle = 0D;
            columnHeaderRenderer3.ZoomFactor = 1F;
            rowHeaderRenderer3.Name = "rowHeaderRenderer3";
            rowHeaderRenderer3.PictureZoomEffect = false;
            rowHeaderRenderer3.TextRotationAngle = 0D;
            rowHeaderRenderer3.ZoomFactor = 1F;
            rowHeaderRenderer4.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer4.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer4.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer4.Name = "rowHeaderRenderer4";
            rowHeaderRenderer4.PictureZoomEffect = false;
            rowHeaderRenderer4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer4.TextRotationAngle = 0D;
            rowHeaderRenderer4.ZoomFactor = 1F;
            columnHeaderRenderer4.Name = "columnHeaderRenderer4";
            columnHeaderRenderer4.PictureZoomEffect = false;
            columnHeaderRenderer4.TextRotationAngle = 0D;
            columnHeaderRenderer4.ZoomFactor = 1F;
            rowHeaderRenderer5.Name = "rowHeaderRenderer5";
            rowHeaderRenderer5.PictureZoomEffect = false;
            rowHeaderRenderer5.TextRotationAngle = 0D;
            rowHeaderRenderer5.ZoomFactor = 1F;
            columnHeaderRenderer5.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer5.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer5.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer5.Name = "columnHeaderRenderer5";
            columnHeaderRenderer5.PictureZoomEffect = false;
            columnHeaderRenderer5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer5.TextRotationAngle = 0D;
            columnHeaderRenderer5.ZoomFactor = 1F;
            rowHeaderRenderer6.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer6.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer6.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer6.Name = "rowHeaderRenderer6";
            rowHeaderRenderer6.PictureZoomEffect = false;
            rowHeaderRenderer6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer6.TextRotationAngle = 0D;
            rowHeaderRenderer6.ZoomFactor = 1F;
            rowHeaderRenderer7.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer7.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer7.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer7.Name = "rowHeaderRenderer7";
            rowHeaderRenderer7.PictureZoomEffect = false;
            rowHeaderRenderer7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer7.TextRotationAngle = 0D;
            rowHeaderRenderer7.ZoomFactor = 1F;
            columnHeaderRenderer6.Name = "columnHeaderRenderer6";
            columnHeaderRenderer6.PictureZoomEffect = false;
            columnHeaderRenderer6.TextRotationAngle = 0D;
            columnHeaderRenderer6.ZoomFactor = 1F;
            rowHeaderRenderer8.Name = "rowHeaderRenderer8";
            rowHeaderRenderer8.PictureZoomEffect = false;
            rowHeaderRenderer8.TextRotationAngle = 0D;
            rowHeaderRenderer8.ZoomFactor = 1F;
            rowHeaderRenderer9.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer9.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer9.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer9.Name = "rowHeaderRenderer9";
            rowHeaderRenderer9.PictureZoomEffect = false;
            rowHeaderRenderer9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer9.TextRotationAngle = 0D;
            rowHeaderRenderer9.ZoomFactor = 1F;
            columnHeaderRenderer7.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer7.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer7.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer7.Name = "columnHeaderRenderer7";
            columnHeaderRenderer7.PictureZoomEffect = false;
            columnHeaderRenderer7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer7.TextRotationAngle = 0D;
            columnHeaderRenderer7.ZoomFactor = 1F;
            rowHeaderRenderer10.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer10.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer10.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer10.Name = "rowHeaderRenderer10";
            rowHeaderRenderer10.PictureZoomEffect = false;
            rowHeaderRenderer10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer10.TextRotationAngle = 0D;
            rowHeaderRenderer10.ZoomFactor = 1F;
            rowHeaderRenderer11.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer11.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer11.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer11.Name = "rowHeaderRenderer11";
            rowHeaderRenderer11.PictureZoomEffect = false;
            rowHeaderRenderer11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer11.TextRotationAngle = 0D;
            rowHeaderRenderer11.ZoomFactor = 1F;
            columnHeaderRenderer8.Name = "columnHeaderRenderer8";
            columnHeaderRenderer8.PictureZoomEffect = false;
            columnHeaderRenderer8.TextRotationAngle = 0D;
            columnHeaderRenderer8.ZoomFactor = 1F;
            rowHeaderRenderer12.Name = "rowHeaderRenderer12";
            rowHeaderRenderer12.PictureZoomEffect = false;
            rowHeaderRenderer12.TextRotationAngle = 0D;
            rowHeaderRenderer12.ZoomFactor = 1F;
            rowHeaderRenderer13.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer13.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer13.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer13.Name = "rowHeaderRenderer13";
            rowHeaderRenderer13.PictureZoomEffect = false;
            rowHeaderRenderer13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer13.TextRotationAngle = 0D;
            rowHeaderRenderer13.ZoomFactor = 1F;
            columnHeaderRenderer9.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer9.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer9.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer9.Name = "columnHeaderRenderer9";
            columnHeaderRenderer9.PictureZoomEffect = false;
            columnHeaderRenderer9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer9.TextRotationAngle = 0D;
            columnHeaderRenderer9.ZoomFactor = 1F;
            rowHeaderRenderer14.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer14.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer14.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer14.Name = "rowHeaderRenderer14";
            rowHeaderRenderer14.PictureZoomEffect = false;
            rowHeaderRenderer14.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer14.TextRotationAngle = 0D;
            rowHeaderRenderer14.ZoomFactor = 1F;
            rowHeaderRenderer15.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer15.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer15.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer15.Name = "rowHeaderRenderer15";
            rowHeaderRenderer15.PictureZoomEffect = false;
            rowHeaderRenderer15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer15.TextRotationAngle = 0D;
            rowHeaderRenderer15.ZoomFactor = 1F;
            columnHeaderRenderer10.Name = "columnHeaderRenderer10";
            columnHeaderRenderer10.PictureZoomEffect = false;
            columnHeaderRenderer10.TextRotationAngle = 0D;
            columnHeaderRenderer10.ZoomFactor = 1F;
            rowHeaderRenderer16.Name = "rowHeaderRenderer16";
            rowHeaderRenderer16.PictureZoomEffect = false;
            rowHeaderRenderer16.TextRotationAngle = 0D;
            rowHeaderRenderer16.ZoomFactor = 1F;
            rowHeaderRenderer17.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer17.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer17.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer17.Name = "rowHeaderRenderer17";
            rowHeaderRenderer17.PictureZoomEffect = false;
            rowHeaderRenderer17.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer17.TextRotationAngle = 0D;
            rowHeaderRenderer17.ZoomFactor = 1F;
            columnHeaderRenderer11.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer11.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer11.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer11.Name = "columnHeaderRenderer11";
            columnHeaderRenderer11.PictureZoomEffect = false;
            columnHeaderRenderer11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer11.TextRotationAngle = 0D;
            columnHeaderRenderer11.ZoomFactor = 1F;
            rowHeaderRenderer18.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer18.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer18.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer18.Name = "rowHeaderRenderer18";
            rowHeaderRenderer18.PictureZoomEffect = false;
            rowHeaderRenderer18.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer18.TextRotationAngle = 0D;
            rowHeaderRenderer18.ZoomFactor = 1F;
            rowHeaderRenderer19.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer19.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer19.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer19.Name = "rowHeaderRenderer19";
            rowHeaderRenderer19.PictureZoomEffect = false;
            rowHeaderRenderer19.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer19.TextRotationAngle = 0D;
            rowHeaderRenderer19.ZoomFactor = 1F;
            columnHeaderRenderer12.Name = "columnHeaderRenderer12";
            columnHeaderRenderer12.PictureZoomEffect = false;
            columnHeaderRenderer12.TextRotationAngle = 0D;
            columnHeaderRenderer12.ZoomFactor = 1F;
            rowHeaderRenderer20.Name = "rowHeaderRenderer20";
            rowHeaderRenderer20.PictureZoomEffect = false;
            rowHeaderRenderer20.TextRotationAngle = 0D;
            rowHeaderRenderer20.ZoomFactor = 1F;
            rowHeaderRenderer21.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer21.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer21.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer21.Name = "rowHeaderRenderer21";
            rowHeaderRenderer21.PictureZoomEffect = false;
            rowHeaderRenderer21.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer21.TextRotationAngle = 0D;
            rowHeaderRenderer21.ZoomFactor = 1F;
            columnHeaderRenderer13.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer13.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer13.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer13.Name = "columnHeaderRenderer13";
            columnHeaderRenderer13.PictureZoomEffect = false;
            columnHeaderRenderer13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer13.TextRotationAngle = 0D;
            columnHeaderRenderer13.ZoomFactor = 1F;
            rowHeaderRenderer22.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer22.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer22.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer22.Name = "rowHeaderRenderer22";
            rowHeaderRenderer22.PictureZoomEffect = false;
            rowHeaderRenderer22.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer22.TextRotationAngle = 0D;
            rowHeaderRenderer22.ZoomFactor = 1F;
            rowHeaderRenderer23.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer23.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer23.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer23.Name = "rowHeaderRenderer23";
            rowHeaderRenderer23.PictureZoomEffect = false;
            rowHeaderRenderer23.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer23.TextRotationAngle = 0D;
            rowHeaderRenderer23.ZoomFactor = 1F;
            columnHeaderRenderer14.Name = "columnHeaderRenderer14";
            columnHeaderRenderer14.PictureZoomEffect = false;
            columnHeaderRenderer14.TextRotationAngle = 0D;
            columnHeaderRenderer14.ZoomFactor = 1F;
            rowHeaderRenderer24.Name = "rowHeaderRenderer24";
            rowHeaderRenderer24.PictureZoomEffect = false;
            rowHeaderRenderer24.TextRotationAngle = 0D;
            rowHeaderRenderer24.ZoomFactor = 1F;
            rowHeaderRenderer25.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer25.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer25.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer25.Name = "rowHeaderRenderer25";
            rowHeaderRenderer25.PictureZoomEffect = false;
            rowHeaderRenderer25.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer25.TextRotationAngle = 0D;
            rowHeaderRenderer25.ZoomFactor = 1F;
            columnHeaderRenderer15.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer15.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer15.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer15.Name = "columnHeaderRenderer15";
            columnHeaderRenderer15.PictureZoomEffect = false;
            columnHeaderRenderer15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer15.TextRotationAngle = 0D;
            columnHeaderRenderer15.ZoomFactor = 1F;
            rowHeaderRenderer26.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer26.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer26.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer26.Name = "rowHeaderRenderer26";
            rowHeaderRenderer26.PictureZoomEffect = false;
            rowHeaderRenderer26.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer26.TextRotationAngle = 0D;
            rowHeaderRenderer26.ZoomFactor = 1F;
            rowHeaderRenderer27.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer27.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer27.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer27.Name = "rowHeaderRenderer27";
            rowHeaderRenderer27.PictureZoomEffect = false;
            rowHeaderRenderer27.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer27.TextRotationAngle = 0D;
            rowHeaderRenderer27.ZoomFactor = 1F;
            columnHeaderRenderer16.Name = "columnHeaderRenderer16";
            columnHeaderRenderer16.PictureZoomEffect = false;
            columnHeaderRenderer16.TextRotationAngle = 0D;
            columnHeaderRenderer16.ZoomFactor = 1F;
            rowHeaderRenderer28.Name = "rowHeaderRenderer28";
            rowHeaderRenderer28.PictureZoomEffect = false;
            rowHeaderRenderer28.TextRotationAngle = 0D;
            rowHeaderRenderer28.ZoomFactor = 1F;
            rowHeaderRenderer29.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer29.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer29.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer29.Name = "rowHeaderRenderer29";
            rowHeaderRenderer29.PictureZoomEffect = false;
            rowHeaderRenderer29.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer29.TextRotationAngle = 0D;
            rowHeaderRenderer29.ZoomFactor = 1F;
            columnHeaderRenderer17.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer17.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer17.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer17.Name = "columnHeaderRenderer17";
            columnHeaderRenderer17.PictureZoomEffect = false;
            columnHeaderRenderer17.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer17.TextRotationAngle = 0D;
            columnHeaderRenderer17.ZoomFactor = 1F;
            rowHeaderRenderer30.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer30.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer30.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer30.Name = "rowHeaderRenderer30";
            rowHeaderRenderer30.PictureZoomEffect = false;
            rowHeaderRenderer30.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer30.TextRotationAngle = 0D;
            rowHeaderRenderer30.ZoomFactor = 1F;
            rowHeaderRenderer31.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer31.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer31.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer31.Name = "rowHeaderRenderer31";
            rowHeaderRenderer31.PictureZoomEffect = false;
            rowHeaderRenderer31.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer31.TextRotationAngle = 0D;
            rowHeaderRenderer31.ZoomFactor = 1F;
            columnHeaderRenderer18.Name = "columnHeaderRenderer18";
            columnHeaderRenderer18.PictureZoomEffect = false;
            columnHeaderRenderer18.TextRotationAngle = 0D;
            columnHeaderRenderer18.ZoomFactor = 1F;
            rowHeaderRenderer32.Name = "rowHeaderRenderer32";
            rowHeaderRenderer32.PictureZoomEffect = false;
            rowHeaderRenderer32.TextRotationAngle = 0D;
            rowHeaderRenderer32.ZoomFactor = 1F;
            rowHeaderRenderer33.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer33.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer33.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer33.Name = "rowHeaderRenderer33";
            rowHeaderRenderer33.PictureZoomEffect = false;
            rowHeaderRenderer33.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer33.TextRotationAngle = 0D;
            rowHeaderRenderer33.ZoomFactor = 1F;
            columnHeaderRenderer19.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer19.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer19.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer19.Name = "columnHeaderRenderer19";
            columnHeaderRenderer19.PictureZoomEffect = false;
            columnHeaderRenderer19.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer19.TextRotationAngle = 0D;
            columnHeaderRenderer19.ZoomFactor = 1F;
            rowHeaderRenderer34.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer34.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer34.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer34.Name = "rowHeaderRenderer34";
            rowHeaderRenderer34.PictureZoomEffect = false;
            rowHeaderRenderer34.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer34.TextRotationAngle = 0D;
            rowHeaderRenderer34.ZoomFactor = 1F;
            rowHeaderRenderer35.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer35.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer35.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer35.Name = "rowHeaderRenderer35";
            rowHeaderRenderer35.PictureZoomEffect = false;
            rowHeaderRenderer35.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer35.TextRotationAngle = 0D;
            rowHeaderRenderer35.ZoomFactor = 1F;
            columnHeaderRenderer20.Name = "columnHeaderRenderer20";
            columnHeaderRenderer20.PictureZoomEffect = false;
            columnHeaderRenderer20.TextRotationAngle = 0D;
            columnHeaderRenderer20.ZoomFactor = 1F;
            rowHeaderRenderer36.Name = "rowHeaderRenderer36";
            rowHeaderRenderer36.PictureZoomEffect = false;
            rowHeaderRenderer36.TextRotationAngle = 0D;
            rowHeaderRenderer36.ZoomFactor = 1F;
            rowHeaderRenderer37.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer37.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer37.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer37.Name = "rowHeaderRenderer37";
            rowHeaderRenderer37.PictureZoomEffect = false;
            rowHeaderRenderer37.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer37.TextRotationAngle = 0D;
            rowHeaderRenderer37.ZoomFactor = 1F;
            columnHeaderRenderer21.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer21.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer21.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer21.Name = "columnHeaderRenderer21";
            columnHeaderRenderer21.PictureZoomEffect = false;
            columnHeaderRenderer21.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer21.TextRotationAngle = 0D;
            columnHeaderRenderer21.ZoomFactor = 1F;
            rowHeaderRenderer38.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer38.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer38.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer38.Name = "rowHeaderRenderer38";
            rowHeaderRenderer38.PictureZoomEffect = false;
            rowHeaderRenderer38.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer38.TextRotationAngle = 0D;
            rowHeaderRenderer38.ZoomFactor = 1F;
            rowHeaderRenderer39.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer39.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer39.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer39.Name = "rowHeaderRenderer39";
            rowHeaderRenderer39.PictureZoomEffect = false;
            rowHeaderRenderer39.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer39.TextRotationAngle = 0D;
            rowHeaderRenderer39.ZoomFactor = 1F;
            columnHeaderRenderer22.Name = "columnHeaderRenderer22";
            columnHeaderRenderer22.PictureZoomEffect = false;
            columnHeaderRenderer22.TextRotationAngle = 0D;
            columnHeaderRenderer22.ZoomFactor = 1F;
            rowHeaderRenderer40.Name = "rowHeaderRenderer40";
            rowHeaderRenderer40.PictureZoomEffect = false;
            rowHeaderRenderer40.TextRotationAngle = 0D;
            rowHeaderRenderer40.ZoomFactor = 1F;
            rowHeaderRenderer41.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer41.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer41.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer41.Name = "rowHeaderRenderer41";
            rowHeaderRenderer41.PictureZoomEffect = false;
            rowHeaderRenderer41.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer41.TextRotationAngle = 0D;
            rowHeaderRenderer41.ZoomFactor = 1F;
            columnHeaderRenderer23.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer23.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer23.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer23.Name = "columnHeaderRenderer23";
            columnHeaderRenderer23.PictureZoomEffect = false;
            columnHeaderRenderer23.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer23.TextRotationAngle = 0D;
            columnHeaderRenderer23.ZoomFactor = 1F;
            rowHeaderRenderer42.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer42.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer42.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer42.Name = "rowHeaderRenderer42";
            rowHeaderRenderer42.PictureZoomEffect = false;
            rowHeaderRenderer42.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer42.TextRotationAngle = 0D;
            rowHeaderRenderer42.ZoomFactor = 1F;
            rowHeaderRenderer43.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer43.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer43.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer43.Name = "rowHeaderRenderer43";
            rowHeaderRenderer43.PictureZoomEffect = false;
            rowHeaderRenderer43.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer43.TextRotationAngle = 0D;
            rowHeaderRenderer43.ZoomFactor = 1F;
            columnHeaderRenderer24.Name = "columnHeaderRenderer24";
            columnHeaderRenderer24.PictureZoomEffect = false;
            columnHeaderRenderer24.TextRotationAngle = 0D;
            columnHeaderRenderer24.ZoomFactor = 1F;
            rowHeaderRenderer44.Name = "rowHeaderRenderer44";
            rowHeaderRenderer44.PictureZoomEffect = false;
            rowHeaderRenderer44.TextRotationAngle = 0D;
            rowHeaderRenderer44.ZoomFactor = 1F;
            rowHeaderRenderer45.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer45.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer45.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer45.Name = "rowHeaderRenderer45";
            rowHeaderRenderer45.PictureZoomEffect = false;
            rowHeaderRenderer45.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer45.TextRotationAngle = 0D;
            rowHeaderRenderer45.ZoomFactor = 1F;
            columnHeaderRenderer25.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer25.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer25.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer25.Name = "columnHeaderRenderer25";
            columnHeaderRenderer25.PictureZoomEffect = false;
            columnHeaderRenderer25.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer25.TextRotationAngle = 0D;
            columnHeaderRenderer25.ZoomFactor = 1F;
            rowHeaderRenderer46.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer46.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer46.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer46.Name = "rowHeaderRenderer46";
            rowHeaderRenderer46.PictureZoomEffect = false;
            rowHeaderRenderer46.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer46.TextRotationAngle = 0D;
            rowHeaderRenderer46.ZoomFactor = 1F;
            rowHeaderRenderer47.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer47.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer47.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer47.Name = "rowHeaderRenderer47";
            rowHeaderRenderer47.PictureZoomEffect = false;
            rowHeaderRenderer47.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer47.TextRotationAngle = 0D;
            rowHeaderRenderer47.ZoomFactor = 1F;
            columnHeaderRenderer26.Name = "columnHeaderRenderer26";
            columnHeaderRenderer26.PictureZoomEffect = false;
            columnHeaderRenderer26.TextRotationAngle = 0D;
            columnHeaderRenderer26.ZoomFactor = 1F;
            rowHeaderRenderer48.Name = "rowHeaderRenderer48";
            rowHeaderRenderer48.PictureZoomEffect = false;
            rowHeaderRenderer48.TextRotationAngle = 0D;
            rowHeaderRenderer48.ZoomFactor = 1F;
            rowHeaderRenderer49.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer49.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer49.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer49.Name = "rowHeaderRenderer49";
            rowHeaderRenderer49.PictureZoomEffect = false;
            rowHeaderRenderer49.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer49.TextRotationAngle = 0D;
            rowHeaderRenderer49.ZoomFactor = 1F;
            columnHeaderRenderer27.BackColor = System.Drawing.SystemColors.Control;
            columnHeaderRenderer27.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            columnHeaderRenderer27.ForeColor = System.Drawing.SystemColors.ControlText;
            columnHeaderRenderer27.Name = "columnHeaderRenderer27";
            columnHeaderRenderer27.PictureZoomEffect = false;
            columnHeaderRenderer27.RightToLeft = System.Windows.Forms.RightToLeft.No;
            columnHeaderRenderer27.TextRotationAngle = 0D;
            columnHeaderRenderer27.ZoomFactor = 1F;
            rowHeaderRenderer50.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer50.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer50.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer50.Name = "rowHeaderRenderer50";
            rowHeaderRenderer50.PictureZoomEffect = false;
            rowHeaderRenderer50.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer50.TextRotationAngle = 0D;
            rowHeaderRenderer50.ZoomFactor = 1F;
            rowHeaderRenderer51.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer51.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer51.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer51.Name = "rowHeaderRenderer51";
            rowHeaderRenderer51.PictureZoomEffect = false;
            rowHeaderRenderer51.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer51.TextRotationAngle = 0D;
            rowHeaderRenderer51.ZoomFactor = 1F;
            columnHeaderRenderer28.Name = "columnHeaderRenderer28";
            columnHeaderRenderer28.PictureZoomEffect = false;
            columnHeaderRenderer28.TextRotationAngle = 0D;
            columnHeaderRenderer28.ZoomFactor = 1F;
            rowHeaderRenderer52.Name = "rowHeaderRenderer52";
            rowHeaderRenderer52.PictureZoomEffect = false;
            rowHeaderRenderer52.TextRotationAngle = 0D;
            rowHeaderRenderer52.ZoomFactor = 1F;
            rowHeaderRenderer53.BackColor = System.Drawing.SystemColors.Control;
            rowHeaderRenderer53.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            rowHeaderRenderer53.ForeColor = System.Drawing.SystemColors.ControlText;
            rowHeaderRenderer53.Name = "rowHeaderRenderer53";
            rowHeaderRenderer53.PictureZoomEffect = false;
            rowHeaderRenderer53.RightToLeft = System.Windows.Forms.RightToLeft.No;
            rowHeaderRenderer53.TextRotationAngle = 0D;
            rowHeaderRenderer53.ZoomFactor = 1F;
            // 
            // lblDept
            // 
            this.lblDept.AutoSize = true;
            this.lblDept.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.lblDept.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDept.ForeColor = System.Drawing.Color.Black;
            this.lblDept.Location = new System.Drawing.Point(11, 25);
            this.lblDept.Name = "lblDept";
            this.lblDept.Size = new System.Drawing.Size(87, 16);
            this.lblDept.TabIndex = 163;
            this.lblDept.Text = "Department";
            this.lblDept.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // cdvDept
            // 
            this.cdvDept.BorderColor = System.Drawing.Color.DarkGray;
            this.cdvDept.BorderHotColor = System.Drawing.Color.Black;
            this.cdvDept.BtnFlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.cdvDept.BtnToolTipText = "";
            this.cdvDept.ButtonWidth = 30;
            this.cdvDept.DescText = "";
            this.cdvDept.DisplaySubItemIndex = 1;
            this.cdvDept.DisplayText = "";
            this.cdvDept.Focusing = null;
            this.cdvDept.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cdvDept.Index = 0;
            this.cdvDept.IsViewBtnImage = false;
            this.cdvDept.Location = new System.Drawing.Point(120, 20);
            this.cdvDept.MaxLength = 100;
            this.cdvDept.MCViewStyle.BorderColor = System.Drawing.SystemColors.Control;
            this.cdvDept.MCViewStyle.BorderHotColor = System.Drawing.SystemColors.Control;
            this.cdvDept.MultiSelect = false;
            this.cdvDept.Name = "cdvDept";
            this.cdvDept.ReadOnly = true;
            this.cdvDept.SameWidthHeightOfButton = false;
            this.cdvDept.SearchSubItemIndex = 0;
            this.cdvDept.SelectedDescIndex = 0;
            this.cdvDept.SelectedDescToQueryText = "";
            this.cdvDept.SelectedSubItemIndex = 0;
            this.cdvDept.SelectedValueToQueryText = "";
            this.cdvDept.SelectionStart = 0;
            this.cdvDept.Size = new System.Drawing.Size(200, 26);
            this.cdvDept.SmallImageList = null;
            this.cdvDept.StyleBorder = System.Windows.Forms.BorderStyle.Fixed3D;
            this.cdvDept.TabIndex = 0;
            this.cdvDept.TextBoxToolTipText = "";
            this.cdvDept.TextBoxWidth = 200;
            this.cdvDept.VisibleButton = true;
            this.cdvDept.VisibleColumnHeader = false;
            this.cdvDept.VisibleDescription = false;
            this.cdvDept.ButtonPress += new System.EventHandler(this.cdvDept_ButtonPress);
            // 
            // lblMatType
            // 
            this.lblMatType.AutoSize = true;
            this.lblMatType.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.lblMatType.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblMatType.ForeColor = System.Drawing.Color.Black;
            this.lblMatType.Location = new System.Drawing.Point(350, 25);
            this.lblMatType.Name = "lblMatType";
            this.lblMatType.Size = new System.Drawing.Size(103, 16);
            this.lblMatType.TabIndex = 165;
            this.lblMatType.Text = "Material Type";
            this.lblMatType.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // cdvMatType
            // 
            this.cdvMatType.BorderColor = System.Drawing.Color.DarkGray;
            this.cdvMatType.BorderHotColor = System.Drawing.Color.Black;
            this.cdvMatType.BtnFlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.cdvMatType.BtnToolTipText = "";
            this.cdvMatType.ButtonWidth = 30;
            this.cdvMatType.DescText = "";
            this.cdvMatType.DisplaySubItemIndex = 1;
            this.cdvMatType.DisplayText = "";
            this.cdvMatType.Focusing = null;
            this.cdvMatType.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cdvMatType.Index = 0;
            this.cdvMatType.IsViewBtnImage = false;
            this.cdvMatType.Location = new System.Drawing.Point(471, 20);
            this.cdvMatType.MaxLength = 100;
            this.cdvMatType.MCViewStyle.BorderColor = System.Drawing.SystemColors.Control;
            this.cdvMatType.MCViewStyle.BorderHotColor = System.Drawing.SystemColors.Control;
            this.cdvMatType.MultiSelect = false;
            this.cdvMatType.Name = "cdvMatType";
            this.cdvMatType.ReadOnly = true;
            this.cdvMatType.SameWidthHeightOfButton = false;
            this.cdvMatType.SearchSubItemIndex = 0;
            this.cdvMatType.SelectedDescIndex = 0;
            this.cdvMatType.SelectedDescToQueryText = "";
            this.cdvMatType.SelectedSubItemIndex = 0;
            this.cdvMatType.SelectedValueToQueryText = "";
            this.cdvMatType.SelectionStart = 0;
            this.cdvMatType.Size = new System.Drawing.Size(200, 26);
            this.cdvMatType.SmallImageList = null;
            this.cdvMatType.StyleBorder = System.Windows.Forms.BorderStyle.Fixed3D;
            this.cdvMatType.TabIndex = 1;
            this.cdvMatType.TextBoxToolTipText = "";
            this.cdvMatType.TextBoxWidth = 200;
            this.cdvMatType.VisibleButton = true;
            this.cdvMatType.VisibleColumnHeader = false;
            this.cdvMatType.VisibleDescription = false;
            this.cdvMatType.ButtonPress += new System.EventHandler(this.cdvMatType_ButtonPress);
            // 
            // txtMatDesc
            // 
            this.txtMatDesc.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.txtMatDesc.Location = new System.Drawing.Point(120, 52);
            this.txtMatDesc.Name = "txtMatDesc";
            this.txtMatDesc.Size = new System.Drawing.Size(200, 26);
            this.txtMatDesc.TabIndex = 2;
            this.txtMatDesc.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtMatDesc_KeyPress);
            // 
            // lblMatDesc
            // 
            this.lblMatDesc.AutoSize = true;
            this.lblMatDesc.BackColor = System.Drawing.Color.White;
            this.lblMatDesc.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.lblMatDesc.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblMatDesc.ForeColor = System.Drawing.Color.Black;
            this.lblMatDesc.Location = new System.Drawing.Point(11, 58);
            this.lblMatDesc.Name = "lblMatDesc";
            this.lblMatDesc.Size = new System.Drawing.Size(103, 16);
            this.lblMatDesc.TabIndex = 252;
            this.lblMatDesc.Text = "Material Desc";
            this.lblMatDesc.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // grpMatList
            // 
            this.grpMatList.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.None;
            appearance1.BackColor = System.Drawing.Color.White;
            appearance1.BackColor2 = System.Drawing.Color.White;
            this.grpMatList.ContentAreaAppearance = appearance1;
            this.grpMatList.Controls.Add(this.spdmatList);
            this.grpMatList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpMatList.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            appearance2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(59)))), ((int)(((byte)(98)))));
            appearance2.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(59)))), ((int)(((byte)(98)))));
            appearance2.ForeColor = System.Drawing.Color.White;
            this.grpMatList.HeaderAppearance = appearance2;
            this.grpMatList.Location = new System.Drawing.Point(10, 150);
            this.grpMatList.Margin = new System.Windows.Forms.Padding(5);
            this.grpMatList.Name = "grpMatList";
            this.grpMatList.Size = new System.Drawing.Size(884, 461);
            this.grpMatList.TabIndex = 244;
            this.grpMatList.Text = "Materials Information";
            // 
            // spdmatList
            // 
            this.spdmatList.AccessibleDescription = "spdmatList, Sheet1, Row 0, Column 0, ";
            this.spdmatList.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.spdmatList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.spdmatList.EditModeReplace = true;
            this.spdmatList.FocusRenderer = defaultFocusIndicatorRenderer2;
            this.spdmatList.HorizontalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdmatList.HorizontalScrollBar.Name = "";
            this.spdmatList.HorizontalScrollBar.Renderer = defaultScrollBarRenderer4;
            this.spdmatList.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdmatList.Location = new System.Drawing.Point(1, 19);
            this.spdmatList.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.spdmatList.Name = "spdmatList";
            namedStyle10.BackColor = System.Drawing.SystemColors.Control;
            filterBarCellType3.FormatString = "";
            namedStyle10.CellType = filterBarCellType3;
            namedStyle10.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle10.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle10.Locked = false;
            namedStyle10.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle10.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle10.Renderer = filterBarCellType3;
            namedStyle10.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle10.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle11.BackColor = System.Drawing.Color.Aqua;
            namedStyle11.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle11.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle11.Locked = false;
            namedStyle11.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle11.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle11.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle11.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle12.BackColor = System.Drawing.SystemColors.Window;
            namedStyle12.CellType = generalCellType5;
            namedStyle12.ForeColor = System.Drawing.SystemColors.WindowText;
            namedStyle12.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle12.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle12.Renderer = generalCellType5;
            namedStyle12.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle12.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle13.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            namedStyle13.Border = bevelBorder3;
            namedStyle13.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            namedStyle13.ForeColor = System.Drawing.Color.White;
            namedStyle13.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle13.Locked = false;
            namedStyle13.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle13.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle13.Renderer = generalCellType6;
            namedStyle13.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle13.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle14.BackColor = System.Drawing.SystemColors.Control;
            filterBarCellType4.FormatString = "";
            namedStyle14.CellType = filterBarCellType4;
            namedStyle14.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle14.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle14.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle14.Renderer = filterBarCellType4;
            namedStyle14.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle14.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle15.BackColor = System.Drawing.SystemColors.Control;
            namedStyle15.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle15.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle15.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle15.Renderer = columnHeaderRenderer28;
            namedStyle15.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle15.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle16.BackColor = System.Drawing.SystemColors.Control;
            namedStyle16.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            namedStyle16.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle16.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle16.Locked = false;
            namedStyle16.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle16.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle16.Renderer = rowHeaderRenderer53;
            namedStyle16.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle16.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle17.BackColor = System.Drawing.SystemColors.Control;
            namedStyle17.ForeColor = System.Drawing.SystemColors.ControlText;
            namedStyle17.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            namedStyle17.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle17.Renderer = rowHeaderRenderer52;
            namedStyle17.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            namedStyle17.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            namedStyle18.BackColor = System.Drawing.Color.White;
            namedStyle18.CellType = generalCellType7;
            namedStyle18.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            namedStyle18.ForeColor = System.Drawing.Color.Black;
            namedStyle18.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            namedStyle18.Locked = false;
            namedStyle18.NoteIndicatorColor = System.Drawing.Color.Red;
            namedStyle18.NoteStyle = FarPoint.Win.Spread.NoteStyle.PopupNote;
            namedStyle18.Renderer = generalCellType7;
            namedStyle18.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            namedStyle18.VisualStyles = FarPoint.Win.VisualStyles.Auto;
            this.spdmatList.NamedStyles.AddRange(new FarPoint.Win.Spread.NamedStyle[] {
            namedStyle10,
            namedStyle11,
            namedStyle12,
            namedStyle13,
            namedStyle14,
            namedStyle15,
            namedStyle16,
            namedStyle17,
            namedStyle18});
            this.spdmatList.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.spdmatList_Sheet1});
            this.spdmatList.Size = new System.Drawing.Size(882, 441);
            spreadSkin2.ColumnFooterDefaultStyle = namedStyle15;
            spreadSkin2.ColumnHeaderDefaultStyle = namedStyle13;
            spreadSkin2.CornerDefaultStyle = namedStyle17;
            spreadSkin2.DefaultStyle = namedStyle18;
            spreadSkin2.FilterBarDefaultStyle = namedStyle14;
            spreadSkin2.FilterBarHeaderDefaultStyle = namedStyle17;
            spreadSkin2.FocusRenderer = defaultFocusIndicatorRenderer2;
            spreadSkin2.Name = "사용1";
            spreadSkin2.RowHeaderDefaultStyle = namedStyle16;
            spreadSkin2.ScrollBarRenderer = defaultScrollBarRenderer5;
            spreadSkin2.SelectionRenderer = new FarPoint.Win.Spread.DefaultSelectionRenderer();
            statusBarSkin2.BackColor = System.Drawing.SystemColors.Control;
            statusBarSkin2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            statusBarSkin2.ForeColor = System.Drawing.SystemColors.ControlText;
            statusBarSkin2.Name = "Classic";
            statusBarSkin2.ZoomButtonHoverColor = System.Drawing.SystemColors.ButtonHighlight;
            statusBarSkin2.ZoomSliderColor = System.Drawing.SystemColors.ControlDarkDark;
            statusBarSkin2.ZoomSliderHoverColor = System.Drawing.SystemColors.ControlDark;
            statusBarSkin2.ZoomSliderTrackColor = System.Drawing.SystemColors.ControlDarkDark;
            spreadSkin2.StatusBarSkin = statusBarSkin2;
            this.spdmatList.Skin = spreadSkin2;
            this.spdmatList.TabIndex = 255;
            this.spdmatList.TabStop = false;
            this.spdmatList.VerticalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdmatList.VerticalScrollBar.Name = "";
            this.spdmatList.VerticalScrollBar.Renderer = defaultScrollBarRenderer6;
            this.spdmatList.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdmatList.CellClick += new FarPoint.Win.Spread.CellClickEventHandler(this.spdmatList_CellClick);
            this.spdmatList.CellDoubleClick += new FarPoint.Win.Spread.CellClickEventHandler(this.spdmatList_CellDoubleClick);
            this.spdmatList.ButtonClicked += new FarPoint.Win.Spread.EditorNotifyEventHandler(this.spdmatList_ButtonClicked);
            // 
            // spdmatList_Sheet1
            // 
            this.spdmatList_Sheet1.Reset();
            this.spdmatList_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.spdmatList_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            this.spdmatList_Sheet1.ColumnCount = 13;
            this.spdmatList_Sheet1.RowCount = 0;
            this.spdmatList_Sheet1.ActiveColumnIndex = -1;
            this.spdmatList_Sheet1.ActiveRowIndex = -1;
            this.spdmatList_Sheet1.ColumnFooter.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdmatList_Sheet1.ColumnFooter.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdmatList_Sheet1.ColumnFooter.DefaultStyle.Parent = "HeaderDefault";
            this.spdmatList_Sheet1.ColumnFooter.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = " ";
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "Material ID";
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "Material Desc";
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "Material Type";
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "Unit";
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "Department";
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "Mat Ver";
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 7).ColumnSpan = 2;
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 7).Value = "Convert Unit";
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 9).ColumnSpan = 2;
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 9).Value = "Grade";
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 11).ColumnSpan = 2;
            this.spdmatList_Sheet1.ColumnHeader.Cells.Get(0, 11).Value = "Size";
            this.spdmatList_Sheet1.ColumnHeader.DefaultStyle.Border = bevelBorder4;
            this.spdmatList_Sheet1.ColumnHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdmatList_Sheet1.ColumnHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdmatList_Sheet1.ColumnHeader.DefaultStyle.Parent = "Style1";
            this.spdmatList_Sheet1.ColumnHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdmatList_Sheet1.ColumnHeader.Rows.Get(0).Height = 25F;
            this.spdmatList_Sheet1.Columns.Get(0).CellType = checkBoxCellType2;
            this.spdmatList_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdmatList_Sheet1.Columns.Get(0).Label = " ";
            this.spdmatList_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdmatList_Sheet1.Columns.Get(0).Width = 32F;
            this.spdmatList_Sheet1.Columns.Get(1).AllowAutoSort = true;
            generalCellType8.ReadOnly = true;
            this.spdmatList_Sheet1.Columns.Get(1).CellType = generalCellType8;
            this.spdmatList_Sheet1.Columns.Get(1).Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.spdmatList_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdmatList_Sheet1.Columns.Get(1).Label = "Material ID";
            this.spdmatList_Sheet1.Columns.Get(1).Locked = true;
            this.spdmatList_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdmatList_Sheet1.Columns.Get(1).Width = 108F;
            this.spdmatList_Sheet1.Columns.Get(2).AllowAutoSort = true;
            this.spdmatList_Sheet1.Columns.Get(2).Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.spdmatList_Sheet1.Columns.Get(2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdmatList_Sheet1.Columns.Get(2).Label = "Material Desc";
            this.spdmatList_Sheet1.Columns.Get(2).Locked = true;
            this.spdmatList_Sheet1.Columns.Get(2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdmatList_Sheet1.Columns.Get(2).Width = 131F;
            this.spdmatList_Sheet1.Columns.Get(3).AllowAutoSort = true;
            this.spdmatList_Sheet1.Columns.Get(3).Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.spdmatList_Sheet1.Columns.Get(3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdmatList_Sheet1.Columns.Get(3).Label = "Material Type";
            this.spdmatList_Sheet1.Columns.Get(3).Locked = true;
            this.spdmatList_Sheet1.Columns.Get(3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdmatList_Sheet1.Columns.Get(3).Width = 96F;
            this.spdmatList_Sheet1.Columns.Get(4).AllowAutoSort = true;
            this.spdmatList_Sheet1.Columns.Get(4).Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.spdmatList_Sheet1.Columns.Get(4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdmatList_Sheet1.Columns.Get(4).Label = "Unit";
            this.spdmatList_Sheet1.Columns.Get(4).Locked = true;
            this.spdmatList_Sheet1.Columns.Get(4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdmatList_Sheet1.Columns.Get(5).AllowAutoSort = true;
            this.spdmatList_Sheet1.Columns.Get(5).Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F);
            this.spdmatList_Sheet1.Columns.Get(5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdmatList_Sheet1.Columns.Get(5).Label = "Department";
            this.spdmatList_Sheet1.Columns.Get(5).Locked = true;
            this.spdmatList_Sheet1.Columns.Get(5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdmatList_Sheet1.Columns.Get(5).Width = 84F;
            this.spdmatList_Sheet1.Columns.Get(6).Label = "Mat Ver";
            this.spdmatList_Sheet1.Columns.Get(6).Visible = false;
            this.spdmatList_Sheet1.Columns.Get(7).Label = "Convert Unit";
            this.spdmatList_Sheet1.Columns.Get(7).Locked = false;
            this.spdmatList_Sheet1.Columns.Get(7).Width = 97F;
            buttonCellType4.ButtonColor2 = System.Drawing.SystemColors.ButtonFace;
            buttonCellType4.Text = "Save";
            this.spdmatList_Sheet1.Columns.Get(8).CellType = buttonCellType4;
            this.spdmatList_Sheet1.Columns.Get(8).Locked = false;
            this.spdmatList_Sheet1.Columns.Get(8).Width = 37F;
            this.spdmatList_Sheet1.Columns.Get(9).Label = "Grade";
            this.spdmatList_Sheet1.Columns.Get(9).Locked = false;
            this.spdmatList_Sheet1.Columns.Get(9).Width = 125F;
            buttonCellType5.ButtonColor2 = System.Drawing.SystemColors.ButtonFace;
            buttonCellType5.Text = "Save";
            this.spdmatList_Sheet1.Columns.Get(10).CellType = buttonCellType5;
            this.spdmatList_Sheet1.Columns.Get(10).Locked = false;
            this.spdmatList_Sheet1.Columns.Get(10).Width = 40F;
            this.spdmatList_Sheet1.Columns.Get(11).Label = "Size";
            this.spdmatList_Sheet1.Columns.Get(11).Locked = false;
            this.spdmatList_Sheet1.Columns.Get(11).Width = 93F;
            buttonCellType6.ButtonColor2 = System.Drawing.SystemColors.ButtonFace;
            buttonCellType6.Text = "Save";
            this.spdmatList_Sheet1.Columns.Get(12).CellType = buttonCellType6;
            this.spdmatList_Sheet1.Columns.Get(12).Locked = false;
            this.spdmatList_Sheet1.Columns.Get(12).Width = 39F;
            this.spdmatList_Sheet1.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdmatList_Sheet1.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdmatList_Sheet1.DefaultStyle.Parent = "Style2";
            this.spdmatList_Sheet1.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdmatList_Sheet1.EnhancedFilterSortingMode = FarPoint.Win.Spread.EnhancedFilterSortingMode.Text;
            this.spdmatList_Sheet1.FilterBar.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdmatList_Sheet1.FilterBar.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdmatList_Sheet1.FilterBar.DefaultStyle.Parent = "FilterBarDefault";
            this.spdmatList_Sheet1.FilterBar.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdmatList_Sheet1.FilterBarHeaderStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdmatList_Sheet1.FilterBarHeaderStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdmatList_Sheet1.FilterBarHeaderStyle.Parent = "RowHeaderDefault";
            this.spdmatList_Sheet1.FilterBarHeaderStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdmatList_Sheet1.GrayAreaBackColor = System.Drawing.Color.White;
            this.spdmatList_Sheet1.NullBackColor = System.Drawing.Color.White;
            this.spdmatList_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.spdmatList_Sheet1.RowHeader.DefaultStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdmatList_Sheet1.RowHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdmatList_Sheet1.RowHeader.DefaultStyle.Parent = "Style3";
            this.spdmatList_Sheet1.RowHeader.DefaultStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdmatList_Sheet1.RowHeader.Visible = false;
            this.spdmatList_Sheet1.Rows.Default.Height = 25F;
            this.spdmatList_Sheet1.SheetCornerStyle.HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.General;
            this.spdmatList_Sheet1.SheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdmatList_Sheet1.SheetCornerStyle.Parent = "RowHeaderDefault";
            this.spdmatList_Sheet1.SheetCornerStyle.VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.General;
            this.spdmatList_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // btnSelect
            // 
            appearance4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            appearance4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            appearance4.FontData.BoldAsString = "True";
            appearance4.ForeColor = System.Drawing.Color.White;
            this.btnSelect.Appearance = appearance4;
            this.btnSelect.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSelect.Location = new System.Drawing.Point(687, 10);
            this.btnSelect.Name = "btnSelect";
            this.btnSelect.Size = new System.Drawing.Size(100, 30);
            this.btnSelect.TabIndex = 1;
            this.btnSelect.Text = "Select";
            this.btnSelect.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.btnSelect.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.btnSelect.Click += new System.EventHandler(this.btnSelect_Click);
            // 
            // btnExcel
            // 
            appearance7.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(240)))), ((int)(((byte)(248)))));
            appearance7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            appearance7.FontData.BoldAsString = "True";
            appearance7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(86)))), ((int)(((byte)(155)))));
            this.btnExcel.Appearance = appearance7;
            this.btnExcel.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExcel.Location = new System.Drawing.Point(17, 10);
            this.btnExcel.Name = "btnExcel";
            this.btnExcel.Size = new System.Drawing.Size(100, 30);
            this.btnExcel.TabIndex = 289;
            this.btnExcel.Text = "Excel";
            this.btnExcel.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.btnExcel.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.btnExcel.Click += new System.EventHandler(this.btnExcel_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.White;
            this.label1.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Black;
            this.label1.Location = new System.Drawing.Point(350, 57);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(99, 16);
            this.label1.TabIndex = 252;
            this.label1.Text = "Exclude word";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // txtExcludeWord
            // 
            this.txtExcludeWord.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.txtExcludeWord.Location = new System.Drawing.Point(471, 52);
            this.txtExcludeWord.Name = "txtExcludeWord";
            this.txtExcludeWord.Size = new System.Drawing.Size(300, 26);
            this.txtExcludeWord.TabIndex = 2;
            this.txtExcludeWord.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtMatDesc_KeyPress);
            // 
            // frmPopMaterialList
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(904, 661);
            this.Name = "frmPopMaterialList";
            this.ShowInTaskbar = false;
            this.Text = "Material List";
            this.Load += new System.EventHandler(this.frmPopMaterialList_Load);
            this.pnlStsCond.ResumeLayout(false);
            this.pnlStsCond.PerformLayout();
            this.pnlMID.ResumeLayout(false);
            this.pnlMID.PerformLayout();
            this.pnlBottom.ResumeLayout(false);
            this.pnlCenter.ResumeLayout(false);
            this.pnlTop.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.cdvDept)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cdvMatType)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.grpMatList)).EndInit();
            this.grpMatList.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.spdmatList)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdmatList_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        public System.Windows.Forms.Label lblDept;
        public Miracom.UI.Controls.MCCodeView.MCCodeView cdvDept;
        public System.Windows.Forms.Label lblMatType;
        public Miracom.UI.Controls.MCCodeView.MCCodeView cdvMatType;
        private System.Windows.Forms.TextBox txtMatDesc;
        public System.Windows.Forms.Label lblMatDesc;
        private Infragistics.Win.Misc.UltraGroupBox grpMatList;
        private FarPoint.Win.Spread.FpSpread spdmatList;
        private FarPoint.Win.Spread.SheetView spdmatList_Sheet1;
        protected Infragistics.Win.Misc.UltraButton btnSelect;
        protected Infragistics.Win.Misc.UltraButton btnExcel;
        private System.Windows.Forms.TextBox txtExcludeWord;
        public System.Windows.Forms.Label label1;
    }
}