/*******************************************************************************
' MessageCaster.h
'
' Copyright (c) 2008 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2008/06/09 10:59:31
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
'******************************************************************************/

#ifndef _XGEN_MESSAGE_SENDER_H
#define _XGEN_MESSAGE_SENDER_H

#include <TRSCore_common.h>
#include "MessageDefines.h"

extern int CallService(char *s_module_name, char *s_service_name, TRSNode *in_node, TRSNode *out_node, char *channel, int ttl, int mode);

#endif /* _XGEN_MESSAGE_SENDER_H */

