/*******************************************************************************
' MessageTuner.h
'
' Copyright (c) 2007 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2008/06/09 10:59:31
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
'******************************************************************************/

#ifndef _XGEN_MESSAGE_RECEIVER_H
#define _XGEN_MESSAGE_RECEIVER_H

#if defined(_H101)

extern void registMESPLUS();
extern IOIStatus recv_CallService(IOISession session, IOIMessage msg);

#elif defined(_TIBRV)

extern int recv_CallService(tibrvEvent event, tibrvMsg message, void* closure);

#endif

#endif /* _XGEN_MESSAGE_RECEIVER_H */

