/*********************************************************************
**
**    File Name   : DBC_cwiplotrmk.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2022-12-15 14:56:20
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2022 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBC_CWIPLOTRMK_LOADED
#define __DBC_CWIPLOTRMK_LOADED


struct CWIPLOTRMK_TAG
{
    char          FACTORY[10];
    char          LOT_ID[25];
    char          COMMENT_1[400];
    char          COMMENT_2[400];
    char          COMMENT_3[400];
    char          COMMENT_4[400];
    char          COMMENT_5[400];
    char          COMMENT_6[400];
    char          COMMENT_7[400];
    char          COMMENT_8[400];
    char          COMMENT_9[400];
    char          COMMENT_10[400];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBC_init_cwiplotrmk(struct CWIPLOTRMK_TAG *CWIPLOTRMK);
extern void   DBC_select_cwiplotrmk(int sel_type, struct CWIPLOTRMK_TAG *CWIPLOTRMK);
extern void   DBC_select_cwiplotrmk_for_update(int sel_type, struct CWIPLOTRMK_TAG *CWIPLOTRMK);
extern double DBC_select_cwiplotrmk_scalar(int sel_type, struct CWIPLOTRMK_TAG *CWIPLOTRMK);
extern void   DBC_delete_cwiplotrmk(int sel_type, struct CWIPLOTRMK_TAG *CWIPLOTRMK);
extern void   DBC_insert_cwiplotrmk(struct CWIPLOTRMK_TAG *CWIPLOTRMK);
extern void   DBC_update_cwiplotrmk(int sel_type, struct CWIPLOTRMK_TAG *CWIPLOTRMK);
extern void   DBC_open_cwiplotrmk(int sel_type, struct CWIPLOTRMK_TAG *CWIPLOTRMK);
extern void   DBC_fetch_cwiplotrmk(int sel_type, struct CWIPLOTRMK_TAG *CWIPLOTRMK);
extern void   DBC_close_cwiplotrmk(int sel_type);


#endif               /* __DBC_CWIPLOTRMK_LOADED */

