/*********************************************************************
**
**    File Name   : DBU_cerpaststs_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-09-16 08:37:47
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CERPASTSTS_N_LOADED
#define __DBU_CERPASTSTS_N_LOADED


struct CERPASTSTS_N_TAG
{
    char          FACTORY[11];
    char          BOOK_TYPE_CODE[201];
    char          ASSET_NUMBER[201];
    char          ASSET_NAME[201];
    char          ATTRIBUTE_CATEGORY_CODE[201];
    char          CATEGORY_CODE[201];
    char          CURRENT_UNITS[201];
    char          ORIGINAL_COST[201];
    char          DATE_PLACED_IN_SERVICE[201];
    char          OPERATING_UNIT_SEG[201];
    char          OPERATING_UNIT[201];
    char          DEPARTMENT_SEG[201];
    char          DEPARTMENTS[201];
    char          PRODUCT_FAMILY_SEG[201];
    char          PRODUCT_FAMILY[201];
    char          BUSINESS_UNIT[201];
    char          TAG_NUMBER[201];
    char          SERIAL_NUMBER[201];
    char          MANUFACTURER_NAME[201];
    char          MODEL_NUMBER[201];
    char          EMPLOYEE_NUMBER[201];
    char          EMPLOYEE_NAME[201];
    char          IN_USE_FLAG[201];
    char          PRORATE_DATE[201];
    char          LOCATION_ID[201];
    char          LOCATION_DESCRIPTION[201];
    char          DEPRN_METHOD_CODE[201];
    char          PLC[201];
    char          PURCHASING_DATE[201];
    char          CONFIRMATION_DATE[201];
    char          CONFIRMED_PLC[201];
    char          RES_ID[201];
    char          CMF_1[501];
    char          CMF_2[501];
    char          CMF_3[501];
    char          CMF_4[501];
    char          CMF_5[501];
    char          CMF_6[501];
    char          CMF_7[501];
    char          CMF_8[501];
    char          CMF_9[501];
    char          CMF_10[501];
    char          CMF_11[501];
    char          CMF_12[501];
    char          CMF_13[501];
    char          CMF_14[501];
    char          CMF_15[501];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CERPASTSTS_N_LOADED */

