/*********************************************************************
**
**    File Name   : DBC_mdnmdvwcnd.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2014/06/25 16:31:02
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2014 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBC_MDNMDVWCND_LOADED
#define __DBC_MDNMDVWCND_LOADED


struct MDNMDVWCND_TAG
{
    char          VIEW_ID[30];
    int           COND_SEQ;
    char          COND_NAME[30];
    char          COND_DESC[200];
    char          REQ_FLAG;
    char          DATA_TYPE[30];
    char          INPUT_TYPE[30];
    char          DATA_TBL[30];
    char          CREATE_TIME[14];
    char          CREATE_USER_ID[20];
    char          UPDATE_TIME[14];
    char          UPDATE_USER_ID[20];
};


/* Function Declaration */
extern void   DBC_init_mdnmdvwcnd(struct MDNMDVWCND_TAG *MDNMDVWCND);
extern void   DBC_select_mdnmdvwcnd(int sel_type, struct MDNMDVWCND_TAG *MDNMDVWCND);
extern void   DBC_select_mdnmdvwcnd_for_update(int sel_type, struct MDNMDVWCND_TAG *MDNMDVWCND);
extern double DBC_select_mdnmdvwcnd_scalar(int sel_type, struct MDNMDVWCND_TAG *MDNMDVWCND);
extern void   DBC_delete_mdnmdvwcnd(int sel_type, struct MDNMDVWCND_TAG *MDNMDVWCND);
extern void   DBC_insert_mdnmdvwcnd(struct MDNMDVWCND_TAG *MDNMDVWCND);
extern void   DBC_update_mdnmdvwcnd(int sel_type, struct MDNMDVWCND_TAG *MDNMDVWCND);
extern void   DBC_open_mdnmdvwcnd(int sel_type, struct MDNMDVWCND_TAG *MDNMDVWCND);
extern void   DBC_fetch_mdnmdvwcnd(int sel_type, struct MDNMDVWCND_TAG *MDNMDVWCND);
extern void   DBC_close_mdnmdvwcnd(int sel_type);
extern void   DBC_insert_select_mdnmdvwcnd(struct MDNMDVWCND_TAG *MDNMDVWCND);

#endif               /* __DBC_MDNMDVWCND_LOADED */

