/*********************************************************************
**
**    File Name   : DBU_cerpaststs.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-09-16 08:37:47
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CERPASTSTS_LOADED
#define __DBU_CERPASTSTS_LOADED


struct CERPASTSTS_TAG
{
    char          FACTORY[10];
    char          BOOK_TYPE_CODE[200];
    char          ASSET_NUMBER[200];
    char          ASSET_NAME[200];
    char          ATTRIBUTE_CATEGORY_CODE[200];
    char          CATEGORY_CODE[200];
    char          CURRENT_UNITS[200];
    char          ORIGINAL_COST[200];
    char          DATE_PLACED_IN_SERVICE[200];
    char          OPERATING_UNIT_SEG[200];
    char          OPERATING_UNIT[200];
    char          DEPARTMENT_SEG[200];
    char          DEPARTMENTS[200];
    char          PRODUCT_FAMILY_SEG[200];
    char          PRODUCT_FAMILY[200];
    char          BUSINESS_UNIT[200];
    char          TAG_NUMBER[200];
    char          SERIAL_NUMBER[200];
    char          MANUFACTURER_NAME[200];
    char          MODEL_NUMBER[200];
    char          EMPLOYEE_NUMBER[200];
    char          EMPLOYEE_NAME[200];
    char          IN_USE_FLAG[200];
    char          PRORATE_DATE[200];
    char          LOCATION_ID[200];
    char          LOCATION_DESCRIPTION[200];
    char          DEPRN_METHOD_CODE[200];
    char          PLC[200];
    char          PURCHASING_DATE[200];
    char          CONFIRMATION_DATE[200];
    char          CONFIRMED_PLC[200];
    char          RES_ID[200];
    char          CMF_1[500];
    char          CMF_2[500];
    char          CMF_3[500];
    char          CMF_4[500];
    char          CMF_5[500];
    char          CMF_6[500];
    char          CMF_7[500];
    char          CMF_8[500];
    char          CMF_9[500];
    char          CMF_10[500];
    char          CMF_11[500];
    char          CMF_12[500];
    char          CMF_13[500];
    char          CMF_14[500];
    char          CMF_15[500];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cerpaststs(struct CERPASTSTS_TAG *CERPASTSTS);
extern void   DBU_select_cerpaststs(int sel_type, struct CERPASTSTS_TAG *CERPASTSTS);
extern void   DBU_select_cerpaststs_for_update(int sel_type, struct CERPASTSTS_TAG *CERPASTSTS);
extern double DBU_select_cerpaststs_scalar(int sel_type, struct CERPASTSTS_TAG *CERPASTSTS);
extern void   DBU_delete_cerpaststs(int sel_type, struct CERPASTSTS_TAG *CERPASTSTS);
extern void   DBU_insert_cerpaststs(struct CERPASTSTS_TAG *CERPASTSTS);
extern void   DBU_update_cerpaststs(int sel_type, struct CERPASTSTS_TAG *CERPASTSTS);
extern void   DBU_open_cerpaststs(int sel_type, struct CERPASTSTS_TAG *CERPASTSTS);
extern void   DBU_fetch_cerpaststs(int sel_type, struct CERPASTSTS_TAG *CERPASTSTS);
extern void   DBU_close_cerpaststs(int sel_type);


#endif               /* __DBU_CERPASTSTS_LOADED */

