/*********************************************************************
**
**    File Name   : DBC_msecfugsum_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2015/08/18 13:55:56
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2015 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBC_MSECFUGSUM_N_LOADED
#define __DBC_MSECFUGSUM_N_LOADED


struct MSECFUGSUM_N_TAG
{
    char          TRAN_DATE[9];
    char          FUNC_NAME[13];
    char          FACTORY[11];
    char          PROGRAM_ID[21];
    int           USAGE_COUNT;
};


#endif               /* __DBC_MSECFUGSUM_N_LOADED */

