/*********************************************************************
**
**    File Name   : DBC_mdndvwcnd_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2014/06/25 16:31:02
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2014 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBC_MDNMDVWCND_N_LOADED
#define __DBC_MDNMDVWCND_N_LOADED


struct MDNMDVWCND_N_TAG
{
    char          VIEW_ID[31];
    int           COND_SEQ;
    char          COND_NAME[31];
    char          COND_DESC[201];
    char          REQ_FLAG[2];
    char          DATA_TYPE[31];
    char          INPUT_TYPE[31];
    char          DATA_TBL[31];
    char          CREATE_TIME[15];
    char          CREATE_USER_ID[21];
    char          UPDATE_TIME[15];
    char          UPDATE_USER_ID[21];
};


#endif               /* __DBC_MDNMDVWCND_N_LOADED */

