/*********************************************************************
**
**    File Name   : DBC_mrcppraver.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2005/06/15 11:05:46
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2005 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBC_MRCPPRAVER_N_LOADED
#define __DBC_MRCPPRAVER_N_LOADED


struct MRCPPRAVER_N_TAG
{
    char   FACTORY[11];
    char   RES_ID[21];
    char   SUBRES_ID[21];
    char   RECIPE[26];
    int    RECIPE_VERSION;
    int    PARA_SEQ;
    char   PARA_ID[21];
    char   PARA_VALUE[21];
    char   PARA_DESC[201];
    char   MODIFY_FLAG[2];
    char   CREATE_USER_ID[21];
    char   CREATE_TIME[15];
    char   UPDATE_USER_ID[21];
    char   UPDATE_TIME[15];
};

#endif               /* __DBC_MRCPPRAVER_LOADED */

