/*********************************************************************
**
**    File Name   : DBC_msecfugsum.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2015/08/18 13:55:56
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2015 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBC_MSECFUGSUM_LOADED
#define __DBC_MSECFUGSUM_LOADED


struct MSECFUGSUM_TAG
{
    char          TRAN_DATE[8];
    char          FUNC_NAME[12];
    char          FACTORY[10];
    char          PROGRAM_ID[20];
    int           USAGE_COUNT;
};


/* Function Declaration */
extern void   DBC_init_msecfugsum(struct MSECFUGSUM_TAG *MSECFUGSUM);
extern void   DBC_select_msecfugsum(int sel_type, struct MSECFUGSUM_TAG *MSECFUGSUM);
extern void   DBC_select_msecfugsum_for_update(int sel_type, struct MSECFUGSUM_TAG *MSECFUGSUM);
extern double DBC_select_msecfugsum_scalar(int sel_type, struct MSECFUGSUM_TAG *MSECFUGSUM);
extern void   DBC_delete_msecfugsum(int sel_type, struct MSECFUGSUM_TAG *MSECFUGSUM);
extern void   DBC_insert_msecfugsum(struct MSECFUGSUM_TAG *MSECFUGSUM);
extern void   DBC_update_msecfugsum(int sel_type, struct MSECFUGSUM_TAG *MSECFUGSUM);
extern void   DBC_open_msecfugsum(int sel_type, struct MSECFUGSUM_TAG *MSECFUGSUM);
extern void   DBC_fetch_msecfugsum(int sel_type, struct MSECFUGSUM_TAG *MSECFUGSUM);
extern void   DBC_close_msecfugsum(int sel_type);


#endif               /* __DBC_MSECFUGSUM_LOADED */

