/*********************************************************************
**
**    File Name   : DBU_cqcmispsts.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-11 17:32:39
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMISPSTS_LOADED
#define __DBU_CQCMISPSTS_LOADED


struct CQCMISPSTS_TAG
{
	char          FACTORY[10];
	char          INSP_ID[30];
	char          INSP_TYPE[30];
	char          INSP_REQ_TIME[14];
	char          INSP_STATUS;
	char          INSP_JUDGE_FLAG;
	char          INSP_JUDGE_TYPE[30];
	char          INSP_JUDGE_TIME[14];
	char          INSP_OPER[10];
	char          COL_SET_ID[25];
	int           COL_SET_VERSION;
	char          LOT_ID[25];
	char          MAT_ID[30];
	int           MAT_VER;
	double        QTY;
	char          RWK_FLOW[20];
	char          RWK_OPER[10];
	char          INSP_COMMENT[400];
	char          AREA_ID[20];
	char          SUB_AREA_ID[20];
	char          CMF_1[30];
	char          CMF_2[30];
	char          CMF_3[30];
	char          CMF_4[30];
	char          CMF_5[30];
	char          CMF_6[30];
	char          CMF_7[30];
	char          CMF_8[30];
	char          CMF_9[30];
	char          CMF_10[30];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cqcmispsts(struct CQCMISPSTS_TAG *CQCMISPSTS);
extern void   DBU_select_cqcmispsts(int sel_type, struct CQCMISPSTS_TAG *CQCMISPSTS);
extern void   DBU_select_cqcmispsts_for_update(int sel_type, struct CQCMISPSTS_TAG *CQCMISPSTS);
extern double DBU_select_cqcmispsts_scalar(int sel_type, struct CQCMISPSTS_TAG *CQCMISPSTS);
extern void   DBU_delete_cqcmispsts(int sel_type, struct CQCMISPSTS_TAG *CQCMISPSTS);
extern void   DBU_insert_cqcmispsts(struct CQCMISPSTS_TAG *CQCMISPSTS);
extern void   DBU_update_cqcmispsts(int sel_type, struct CQCMISPSTS_TAG *CQCMISPSTS);
extern void   DBU_open_cqcmispsts(int sel_type, struct CQCMISPSTS_TAG *CQCMISPSTS);
extern void   DBU_fetch_cqcmispsts(int sel_type, struct CQCMISPSTS_TAG *CQCMISPSTS);
extern void   DBU_close_cqcmispsts(int sel_type);


#endif               /* __DBU_CQCMISPSTS_LOADED */

