/*********************************************************************
**
**    File Name   : DBU_cbascptdef.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-06-18 17:02:37
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CBASCPTDEF_LOADED
#define __DBU_CBASCPTDEF_LOADED


struct CBASCPTDEF_TAG
{
    char          CAPTION_TYPE[10];
    char          CAPTION_KEY[1000];
    char          CAPTION_MSG_1[1000];
    char          CAPTION_MSG_2[1000];
    char          CAPTION_MSG_3[1000];
    char          CAPTION_MSG_4[1000];
    char          CAPTION_MSG_5[1000];
    char          CAPTION_CMF_1[30];
    char          CAPTION_CMF_2[30];
    char          CAPTION_CMF_3[30];
    char          CAPTION_CMF_4[30];
    char          CAPTION_CMF_5[30];
    char          CAPTION_CMF_6[30];
    char          CAPTION_CMF_7[30];
    char          CAPTION_CMF_8[30];
    char          CAPTION_CMF_9[30];
    char          CAPTION_CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cbascptdef(struct CBASCPTDEF_TAG *CBASCPTDEF);
extern void   DBU_select_cbascptdef(int sel_type, struct CBASCPTDEF_TAG *CBASCPTDEF);
extern void   DBU_select_cbascptdef_for_update(int sel_type, struct CBASCPTDEF_TAG *CBASCPTDEF);
extern double DBU_select_cbascptdef_scalar(int sel_type, struct CBASCPTDEF_TAG *CBASCPTDEF);
extern void   DBU_delete_cbascptdef(int sel_type, struct CBASCPTDEF_TAG *CBASCPTDEF);
extern void   DBU_insert_cbascptdef(struct CBASCPTDEF_TAG *CBASCPTDEF);
extern void   DBU_update_cbascptdef(int sel_type, struct CBASCPTDEF_TAG *CBASCPTDEF);
extern void   DBU_open_cbascptdef(int sel_type, struct CBASCPTDEF_TAG *CBASCPTDEF);
extern void   DBU_fetch_cbascptdef(int sel_type, struct CBASCPTDEF_TAG *CBASCPTDEF);
extern void   DBU_close_cbascptdef(int sel_type);


#endif               /* __DBU_CBASCPTDEF_LOADED */

