/*********************************************************************
**
**    File Name   : DBU_cqcmrptgnp.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-05 20:39:24
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTGNP_LOADED
#define __DBU_CQCMRPTGNP_LOADED


struct CQCMRPTGNP_TAG
{
	char          FACTORY[10];
    char          REPORT_NO[20];
    int           SORT_NO;
    char          QC_NAME[30];
    char          SPEC_VAL[30];
    char          LOT_01[30];
    char          LOT_02[30];
    char          LOT_03[30];
    char          LOT_04[30];
    char          LOT_05[30];
    char          LOT_06[30];
    char          LOT_07[30];
    char          REMARKS[100];
    char          USE_YN;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
    char          CUST_NO[50];
    char          IMAGE_NUM[20];
    char          IMAGE_NUM2[20];
    char          IMAGE_NUM3[20];
    char          RPT_CMF_1[50];
    char          RPT_CMF_2[50];
    char          RPT_CMF_3[50];
    char          RPT_CMF_4[50];
    char          RPT_CMF_5[50];
    char          RPT_CMF_6[50];
    char          RPT_CMF_7[50];
    char          RPT_CMF_8[50];
    char          RPT_CMF_9[50];
    char          RPT_CMF_10[50];
    char          RPT_CMF_11[50];
    char          RPT_CMF_12[50];
    char          RPT_CMF_13[50];
    char          RPT_CMF_14[50];
    char          RPT_CMF_15[50];
};


/* Function Declaration */
extern void   DBU_init_cqcmrptgnp(struct CQCMRPTGNP_TAG *CQCMRPTGNP);
extern void   DBU_select_cqcmrptgnp(int sel_type, struct CQCMRPTGNP_TAG *CQCMRPTGNP);
extern void   DBU_select_cqcmrptgnp_for_update(int sel_type, struct CQCMRPTGNP_TAG *CQCMRPTGNP);
extern double DBU_select_cqcmrptgnp_scalar(int sel_type, struct CQCMRPTGNP_TAG *CQCMRPTGNP);
extern void   DBU_delete_cqcmrptgnp(int sel_type, struct CQCMRPTGNP_TAG *CQCMRPTGNP);
extern void   DBU_insert_cqcmrptgnp(struct CQCMRPTGNP_TAG *CQCMRPTGNP);
extern void   DBU_update_cqcmrptgnp(int sel_type, struct CQCMRPTGNP_TAG *CQCMRPTGNP);
extern void   DBU_open_cqcmrptgnp(int sel_type, struct CQCMRPTGNP_TAG *CQCMRPTGNP);
extern void   DBU_fetch_cqcmrptgnp(int sel_type, struct CQCMRPTGNP_TAG *CQCMRPTGNP);
extern void   DBU_close_cqcmrptgnp(int sel_type);


#endif               /* __DBU_CQCMRPTGNP_LOADED */

