/*********************************************************************
**
**    File Name   : DBU_cwipprsrun_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-02-09 15:34:32
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPPRSRUN_N_LOADED
#define __DBU_CWIPPRSRUN_N_LOADED


struct CWIPPRSRUN_N_TAG
{
    char          FACTORY[11];
    char          WORK_DATE[9];
    char          RES_ID[21];
    int           RUN_COUNT;
    char          CELL_ID[26];
    char          LOT_ID[26];
    int           MAPPING_SEQ;
    char          LOSS_YN[2];
    char          CAR[11];
    char          DAY_NIGHT[2];
    char          MAT_ID[31];
    char          AREA_ID[21];
    char          SUB_AREA_ID[21];
    char          OPER[11];
    char          TRAN_TIME[15];
    char          ORG_LOT_ID[26];
    int           ORG_LOT_HIST_SEQ;
    double        CELL_WEIGHT;
    double        CELL_HEIGHT;
    char          PROFILE_ID[21];
    double        SET_VOLTAGE;
    double        SET_POWER_1;
    double        SET_POWER_2;
    double        SET_POWER_3;
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPPRSRUN_N_LOADED */

