/*********************************************************************
**
**    File Name   : DBU_cqcmrptctm_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-30 15:23:11
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTCTM_N_LOADED
#define __DBU_CQCMRPTCTM_N_LOADED


struct CQCMRPTCTM_N_TAG
{
    char          FACTORY[11];
    char          REPORT_NO[21];
    char          PACK_LOT_ID[26];
    char          ORG_LOT_ID[26];
    char          GRADE[31];
    char          TYPES[51];
    char          PACK_ORDER_ID[26];
    char          CUSTOMER_ID[41];
    char          OD_STANDARD[31];
    char          OD_SPEC[31];
    char          OD_MIN_VAL[31];
    char          OD_MAX_VAL[31];
    char          AT_STANDARD[31];
    char          AT_SPEC[31];
    char          AT_MIN_VAL[31];
    char          AT_MAX_VAL[31];
    char          GT_STANDARD[31];
    char          GT_SPEC[31];
    char          GT_MIN_VAL[31];
    char          GT_MAX_VAL[31];
    char          LEN01_STANDARD[31];
    char          LEN01_SPEC[31];
    char          LEN_MIN_VAL01[31];
    char          LEN_MAX_VAL01[31];
    char          LEN02_STANDARD[31];
    char          LEN02_SPEC[31];
    char          LEN_MIN_VAL02[31];
    char          LEN_MAX_VAL02[31];
    char          DMG_STANDARD[31];
    char          DMG_SPEC[31];
    char          DMG_MIN_VAL[31];
    char          DMG_MAX_VAL[31];
    char          RPT_CMF_1[51];
    char          RPT_CMF_2[51];
    char          RPT_CMF_3[51];
    char          RPT_CMF_4[51];
    char          RPT_CMF_5[51];
    char          COMMENTS[101];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
    char          RPT_CMF_6[51];
    char          RPT_CMF_7[51];
    char          RPT_CMF_8[51];
    char          RPT_CMF_9[51];
    char          RPT_CMF_10[51];
    char          RPT_CMF_11[51];
    char          RPT_CMF_12[51];
    char          RPT_CMF_13[51];
    char          RPT_CMF_14[51];
    char          RPT_CMF_15[51];
    char          FIT_STANDARD[31];
    char          FIT_SPEC[31];
    char          FIT_MIN_VAL[31];
    char          FIT_MAX_VAL[31];
};


#endif               /* __DBU_CQCMRPTCTM_N_LOADED */

