/*********************************************************************
**
**    File Name   : DBU_cqcmrptctm.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-30 15:23:11
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTCTM_LOADED
#define __DBU_CQCMRPTCTM_LOADED


struct CQCMRPTCTM_TAG
{
    char          FACTORY[10];
    char          REPORT_NO[20];
    char          PACK_LOT_ID[25];
    char          ORG_LOT_ID[25];
    char          GRADE[30];
    char          TYPES[50];
    char          PACK_ORDER_ID[25];
    char          CUSTOMER_ID[40];
    char          OD_STANDARD[30];
    char          OD_SPEC[30];
    char          OD_MIN_VAL[30];
    char          OD_MAX_VAL[30];
    char          AT_STANDARD[30];
    char          AT_SPEC[30];
    char          AT_MIN_VAL[30];
    char          AT_MAX_VAL[30];
    char          GT_STANDARD[30];
    char          GT_SPEC[30];
    char          GT_MIN_VAL[30];
    char          GT_MAX_VAL[30];
    char          LEN01_STANDARD[30];
    char          LEN01_SPEC[30];
    char          LEN_MIN_VAL01[30];
    char          LEN_MAX_VAL01[30];
    char          LEN02_STANDARD[30];
    char          LEN02_SPEC[30];
    char          LEN_MIN_VAL02[30];
    char          LEN_MAX_VAL02[30];
    char          DMG_STANDARD[30];
    char          DMG_SPEC[30];
    char          DMG_MIN_VAL[30];
    char          DMG_MAX_VAL[30];
    char          RPT_CMF_1[50];
    char          RPT_CMF_2[50];
    char          RPT_CMF_3[50];
    char          RPT_CMF_4[50];
    char          RPT_CMF_5[50];
    char          COMMENTS[100];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
    char          RPT_CMF_6[50];
    char          RPT_CMF_7[50];
    char          RPT_CMF_8[50];
    char          RPT_CMF_9[50];
    char          RPT_CMF_10[50];
    char          RPT_CMF_11[50];
    char          RPT_CMF_12[50];
    char          RPT_CMF_13[50];
    char          RPT_CMF_14[50];
    char          RPT_CMF_15[50];
    char          FIT_STANDARD[30];
    char          FIT_SPEC[30];
    char          FIT_MIN_VAL[30];
    char          FIT_MAX_VAL[30];
};


/* Function Declaration */
extern void   DBU_init_cqcmrptctm(struct CQCMRPTCTM_TAG *CQCMRPTCTM);
extern void   DBU_select_cqcmrptctm(int sel_type, struct CQCMRPTCTM_TAG *CQCMRPTCTM);
extern void   DBU_select_cqcmrptctm_for_update(int sel_type, struct CQCMRPTCTM_TAG *CQCMRPTCTM);
extern double DBU_select_cqcmrptctm_scalar(int sel_type, struct CQCMRPTCTM_TAG *CQCMRPTCTM);
extern void   DBU_delete_cqcmrptctm(int sel_type, struct CQCMRPTCTM_TAG *CQCMRPTCTM);
extern void   DBU_insert_cqcmrptctm(struct CQCMRPTCTM_TAG *CQCMRPTCTM);
extern void   DBU_update_cqcmrptctm(int sel_type, struct CQCMRPTCTM_TAG *CQCMRPTCTM);
extern void   DBU_open_cqcmrptctm(int sel_type, struct CQCMRPTCTM_TAG *CQCMRPTCTM);
extern void   DBU_fetch_cqcmrptctm(int sel_type, struct CQCMRPTCTM_TAG *CQCMRPTCTM);
extern void   DBU_close_cqcmrptctm(int sel_type);


#endif               /* __DBU_CQCMRPTCTM_LOADED */

