/*********************************************************************
**
**    File Name   : DBU_cwiplotrnd.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-29 19:39:13
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTRND_LOADED
#define __DBU_CWIPLOTRND_LOADED


struct CWIPLOTRND_TAG
{
    char          LOT_ID[25];
    int           HIST_SEQ;
    char          OPER[10];
    char          MAT_ID[30];
    char          FLOW[20];
    int           FLOW_SEQ_NUM;
    char          GRADE[50];
    char          RES_ID[20];
    char          FACTORY[10];
    char          WORK_DATE[8];
    char          WORK_TIME[14];
    char          DAY_NIGHT[10];
    int           EDC_HIST_SEQ;
    char          RECIPE_ID[50];
    char          START_TIME[14];
    char          END_TIME[14];
    char          JUDGMENT[10];
    double        S_DEFECT_NUMBER;
    double        S_OUTER_DIAMETER_MIN;
    double        S_ALL_THICKNESS_MIN;
    double        S_ALL_THICKNESS_MAX;
    double        S_ALL_THICKNESS_TARGET;
    double        S_FLATNESS_MAX;
    double        S_FLATNESS_MIN;
    double        SIZE_UM;
    double        SIZE_UM2;
    char          CLASSFICATION[30];
    double        OUTER_DIAMETER_1;
    double        OUTER_DIAMETER_2;
    double        OUTER_DIAMETER_MIN;
    double        ALL_THICKNESS_1;
    double        ALL_THICKNESS_2;
    double        ALL_THICKNESS_3;
    double        ALL_THICKNESS_4;
    double        ALL_THICKNESS_5;
    double        ALL_THICKNESS_6;
    double        ALL_THICKNESS_7;
    double        ALL_THICKNESS_8;
    double        ALL_THICKNESS_9;
    double        ALL_THICKNESS_10;
    double        ALL_THICKNESS_11;
    double        ALL_THICKNESS_12;
    double        ALL_THICKNESS_13;
    double        ALL_THICKNESS_14;
    double        ALL_THICKNESS_15;
    double        ALL_THICKNESS_MAX;
    double        ALL_THICKNESS_MIN;
    double        FLATNESS_1;
    double        FLATNESS_2;
    double        FLATNESS_3;
    double        FLATNESS_4;
    double        FLATNESS_5;
    double        FLATNESS_6;
    double        FLATNESS_7;
    double        FLATNESS_8;
    double        FLATNESS_9;
    double        FLATNESS_10;
    double        FLATNESS_11;
    double        FLATNESS_12;
    double        FLATNESS_13;
    double        FLATNESS_14;
    double        FLATNESS_15;
    double        FLATNESS_MAX;
    char          DEFECT_IMAGE_1[100];
    char          DEFECT_IMAGE_2[100];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiplotrnd(struct CWIPLOTRND_TAG *CWIPLOTRND);
extern void   DBU_select_cwiplotrnd(int sel_type, struct CWIPLOTRND_TAG *CWIPLOTRND);
extern void   DBU_select_cwiplotrnd_for_update(int sel_type, struct CWIPLOTRND_TAG *CWIPLOTRND);
extern double DBU_select_cwiplotrnd_scalar(int sel_type, struct CWIPLOTRND_TAG *CWIPLOTRND);
extern void   DBU_delete_cwiplotrnd(int sel_type, struct CWIPLOTRND_TAG *CWIPLOTRND);
extern void   DBU_insert_cwiplotrnd(struct CWIPLOTRND_TAG *CWIPLOTRND);
extern void   DBU_update_cwiplotrnd(int sel_type, struct CWIPLOTRND_TAG *CWIPLOTRND);
extern void   DBU_open_cwiplotrnd(int sel_type, struct CWIPLOTRND_TAG *CWIPLOTRND);
extern void   DBU_fetch_cwiplotrnd(int sel_type, struct CWIPLOTRND_TAG *CWIPLOTRND);
extern void   DBU_close_cwiplotrnd(int sel_type);


#endif               /* __DBU_CWIPLOTRND_LOADED */

