/*********************************************************************
**
**    File Name   : DBU_cqcmrptgmp_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-10 18:15:40
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTGMP_N_LOADED
#define __DBU_CQCMRPTGMP_N_LOADED


struct CQCMRPTGMP_N_TAG
{
    char          FACTORY[11];
    char          REPORT_NO[31];
    char          LOT_ID[21];
    int           LOT_SEQ;
    char          SUB_CODE[21];
    char          CODE_NAME[101];
    char          CODE_VALUE[31];
    char          RPT_CMF_1[51];
    char          RPT_CMF_2[51];
    char          RPT_CMF_3[51];
    char          RPT_CMF_4[51];
    char          RPT_CMF_5[51];
    char          RPT_CMF_6[51];
    char          RPT_CMF_7[51];
    char          RPT_CMF_8[51];
    char          RPT_CMF_9[51];
    char          RPT_CMF_10[51];
    char          RPT_CMF_11[51];
    char          RPT_CMF_12[51];
    char          RPT_CMF_13[51];
    char          RPT_CMF_14[51];
    char          RPT_CMF_15[51];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CQCMRPTGMP_N_LOADED */

