/*********************************************************************
**
**    File Name   : DBU_cras5thprs.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2022-03-23 15:45:32
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2022 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRAS5THPRS_LOADED
#define __DBU_CRAS5THPRS_LOADED


struct CRAS5THPRS_TAG
{
    char          RES_ID[20];
    int           HIST_SEQ;
    char          WORK_TIME[17];
    char          FACTORY[10];
    char          WORK_DATE[8];
    char          DAY_NIGHT[10];
    double        SV_PRESSURE;
    double        PV_PRESSURE;
    double        SV_POWER;
    double        PV_POWER;
    double        PV_VOLT;
    double        PV_ELECTRIC;
    double        PV_RESISTANCE;
    double        PV_STROKE;
    double        PV_CLW_IN_TEMP;
    double        PV_CLW_OUT_TEMP;
    double        PV_HDL_TEMP;
    char          RES_STATUS;
    char          START_TIME[14];
    char          END_TIME[14];
    char          EVENT_ID[12];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cras5thprs(struct CRAS5THPRS_TAG *CRAS5THPRS);
extern void   DBU_select_cras5thprs(int sel_type, struct CRAS5THPRS_TAG *CRAS5THPRS);
extern void   DBU_select_cras5thprs_for_update(int sel_type, struct CRAS5THPRS_TAG *CRAS5THPRS);
extern double DBU_select_cras5thprs_scalar(int sel_type, struct CRAS5THPRS_TAG *CRAS5THPRS);
extern void   DBU_delete_cras5thprs(int sel_type, struct CRAS5THPRS_TAG *CRAS5THPRS);
extern void   DBU_insert_cras5thprs(struct CRAS5THPRS_TAG *CRAS5THPRS);
extern void   DBU_update_cras5thprs(int sel_type, struct CRAS5THPRS_TAG *CRAS5THPRS);
extern void   DBU_open_cras5thprs(int sel_type, struct CRAS5THPRS_TAG *CRAS5THPRS);
extern void   DBU_fetch_cras5thprs(int sel_type, struct CRAS5THPRS_TAG *CRAS5THPRS);
extern void   DBU_close_cras5thprs(int sel_type);


#endif               /* __DBU_CRAS5THPRS_LOADED */

