/*********************************************************************
**
**    File Name   : DBU_mwipcoldef_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-28 09:30:06
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MWIPCOLDEF_N_LOADED
#define __DBU_MWIPCOLDEF_N_LOADED

/*
struct MWIPCOLDEF_N_TAG
{
    char          FACTORY[11];
    char          MAT_ID[31];
    int           MAT_VER;
    char          FLOW[21];
    char          OPER[11];
    char          OPT_LEVEL[2];
    char          COL_SET_ID[26];
    char          COLLECTION_MODE[2];
    char          DEFAULT_FLAG[2];
    char          DISABLE_FLAG[2];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};
*/

#endif               /* __DBU_MWIPCOLDEF_N_LOADED */

