/*********************************************************************
**
**    File Name   : DBU_cqcmispsts_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-11 17:32:39
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMISPSTS_N_LOADED
#define __DBU_CQCMISPSTS_N_LOADED


struct CQCMISPSTS_N_TAG
{
	char          FACTORY[11];
	char          INSP_ID[31];
	char          INSP_TYPE[31];
	char          INSP_REQ_TIME[15];
	char          INSP_STATUS[2];
	char          INSP_JUDGE_FLAG[2];
	char          INSP_JUDGE_TYPE[31];
	char          INSP_JUDGE_TIME[15];
	char          INSP_OPER[11];
	char          COL_SET_ID[26];
	int           COL_SET_VERSION;
	char          LOT_ID[26];
	char          MAT_ID[31];
	int           MAT_VER;
	double        QTY;
	char          RWK_FLOW[21];
	char          RWK_OPER[11];
	char          INSP_COMMENT[401];
	char          AREA_ID[21];
	char          SUB_AREA_ID[21];
	char          CMF_1[31];
	char          CMF_2[31];
	char          CMF_3[31];
	char          CMF_4[31];
	char          CMF_5[31];
	char          CMF_6[31];
	char          CMF_7[31];
	char          CMF_8[31];
	char          CMF_9[31];
	char          CMF_10[31];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_CQCMISPSTS_N_LOADED */

