/*********************************************************************
**
**    File Name   : DBU_cpaklothis.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-30 18:22:45
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CPAKLOTHIS_LOADED
#define __DBU_CPAKLOTHIS_LOADED


struct CPAKLOTHIS_TAG
{
    char          FACTORY[10];
    char          ORG_LOT_ID[25];
    char          PACK_LOT_ID[25];
    char          MAT_ID[30];
    int           MAT_VER;
    double        QTY;
    char          UNIT[10];
    char          PACK_FLAG;
    char          PACK_DATE[14];
    char          PACK_ORDER_ID[25];
    int           PACK_LINE_NO;
    char          SHIP_FLAG;
    char          SHIP_DATE[14];
    char          SHIP_ORDER_ID[25];
    int           SHIP_ORDER_SEQ;
    char          RET_FLAG;
    double        RETURNED_QTY;
    char          BOX_ID_1[25];
    char          BOX_ID_2[25];
    char          BOX_ID_3[25];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cpaklothis(struct CPAKLOTHIS_TAG *CPAKLOTHIS);
extern void   DBU_select_cpaklothis(int sel_type, struct CPAKLOTHIS_TAG *CPAKLOTHIS);
extern void   DBU_select_cpaklothis_for_update(int sel_type, struct CPAKLOTHIS_TAG *CPAKLOTHIS);
extern double DBU_select_cpaklothis_scalar(int sel_type, struct CPAKLOTHIS_TAG *CPAKLOTHIS);
extern void   DBU_delete_cpaklothis(int sel_type, struct CPAKLOTHIS_TAG *CPAKLOTHIS);
extern void   DBU_insert_cpaklothis(struct CPAKLOTHIS_TAG *CPAKLOTHIS);
extern void   DBU_update_cpaklothis(int sel_type, struct CPAKLOTHIS_TAG *CPAKLOTHIS);
extern void   DBU_open_cpaklothis(int sel_type, struct CPAKLOTHIS_TAG *CPAKLOTHIS);
extern void   DBU_fetch_cpaklothis(int sel_type, struct CPAKLOTHIS_TAG *CPAKLOTHIS);
extern void   DBU_close_cpaklothis(int sel_type);


#endif               /* __DBU_CPAKLOTHIS_LOADED */

