/*********************************************************************
**
**    File Name   : DBU_mrasresmfo_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-21 13:03:20
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MRASRESMFO_N_LOADED
#define __DBU_MRASRESMFO_N_LOADED

/*
struct MRASRESMFO_N_TAG
{
    char          FACTORY[11];
    char          MAT_ID[31];
    int           MAT_VER;
    char          FLOW[21];
    char          OPER[11];
    char          RES_ID[21];
    char          RESG_ID[21];
    char          REL_LEVEL[2];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};
*/

#endif               /* __DBU_MRASRESMFO_N_LOADED */

