/*********************************************************************
**
**    File Name   : DBU_ishpisprcv_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-05-20 09:53:24
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_ISHPISPRCV_N_LOADED
#define __DBU_ISHPISPRCV_N_LOADED


struct ISHPISPRCV_N_TAG
{
    char          FACTORY[11];
    char          PACK_LOT_ID[26];
    char          ORG_LOT_ID[26];
    char          FROM_FACTORY[11];
    char          INSP_ID[31];
    char          COL_SET_ID[26];
    int           COL_SET_VER;
    char          CHAR_ID[26];
    int           CHAR_SEQ;
    int           UNIT_SEQ;
    int           VALUE_SEQ;
    char          UNIT_ID[51];
    char          VALUE_TYPE[2];
    int           VALUE_COUNT;
    char          VALUE_1[26];
    char          VALUE_2[26];
    char          VALUE_3[26];
    char          VALUE_4[26];
    char          VALUE_5[26];
    char          VALUE_6[26];
    char          VALUE_7[26];
    char          VALUE_8[26];
    char          VALUE_9[26];
    char          VALUE_10[26];
    char          VALUE_11[26];
    char          VALUE_12[26];
    char          VALUE_13[26];
    char          VALUE_14[26];
    char          VALUE_15[26];
    char          VALUE_16[26];
    char          VALUE_17[26];
    char          VALUE_18[26];
    char          VALUE_19[26];
    char          VALUE_20[26];
    char          VALUE_21[26];
    char          VALUE_22[26];
    char          VALUE_23[26];
    char          VALUE_24[26];
    char          VALUE_25[26];
    int           SAMPLE_COUNT;
    char          SPEC_OUT_MASK[26];
    char          INSP_JUDGE_FLAG[2];
    char          INSP_JUDGE_TYPE[31];
    char          INSP_JUDGE_TIME[31];
    char          RECEIVE_FLAG[2];
    char          DELETE_FLAG[2];
    char          CMF_1[51];
    char          CMF_2[51];
    char          CMF_3[51];
    char          CMF_4[51];
    char          CMF_5[51];
    char          CMF_6[51];
    char          CMF_7[51];
    char          CMF_8[51];
    char          CMF_9[51];
    char          CMF_10[51];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_ISHPISPRCV_N_LOADED */

