/*********************************************************************
**
**    File Name   : DBU_cretlotsts_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-10 12:00:44
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRETLOTSTS_N_LOADED
#define __DBU_CRETLOTSTS_N_LOADED


struct CRETLOTSTS_N_TAG
{
    char          FACTORY[11];
    char          RET_ORDER_ID[26];
    char          LOT_ID[26];
    char          RET_LOT_ID[26];
    char          MAT_ID[31];
    int           MAT_VER;
    double        QTY;
    char          UNIT[11];
    char          RET_DATE[15];
    int           RET_LINE_NO;
    char          PACK_DATE[15];
    char          PACK_ORDER_ID[26];
    int           PACK_LINE_NO;
    char          SHIP_DATE[15];
    char          SHIP_ORDER_ID[26];
    double        SHIP_ORDER_SEQ;
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CRETLOTSTS_N_LOADED */

