/*********************************************************************
**
**    File Name   : DBU_cwipgrplot.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-25 13:48:39
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPGRPLOT_LOADED
#define __DBU_CWIPGRPLOT_LOADED


struct CWIPGRPLOT_TAG
{
    char          FACTORY[10];
    char          GROUP_ID[25];
    char          LOT_ID[25];
    int           MAPPING_SEQ;
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          OPER[10];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwipgrplot(struct CWIPGRPLOT_TAG *CWIPGRPLOT);
extern void   DBU_select_cwipgrplot(int sel_type, struct CWIPGRPLOT_TAG *CWIPGRPLOT);
extern void   DBU_select_cwipgrplot_for_update(int sel_type, struct CWIPGRPLOT_TAG *CWIPGRPLOT);
extern double DBU_select_cwipgrplot_scalar(int sel_type, struct CWIPGRPLOT_TAG *CWIPGRPLOT);
extern void   DBU_delete_cwipgrplot(int sel_type, struct CWIPGRPLOT_TAG *CWIPGRPLOT);
extern void   DBU_insert_cwipgrplot(struct CWIPGRPLOT_TAG *CWIPGRPLOT);
extern void   DBU_update_cwipgrplot(int sel_type, struct CWIPGRPLOT_TAG *CWIPGRPLOT);
extern void   DBU_open_cwipgrplot(int sel_type, struct CWIPGRPLOT_TAG *CWIPGRPLOT);
extern void   DBU_fetch_cwipgrplot(int sel_type, struct CWIPGRPLOT_TAG *CWIPGRPLOT);
extern void   DBU_close_cwipgrplot(int sel_type);


#endif               /* __DBU_CWIPGRPLOT_LOADED */

