/*********************************************************************
**
**    File Name   : DBU_cqcmrpthmm_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-02 15:46:49
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTHMM_N_LOADED
#define __DBU_CQCMRPTHMM_N_LOADED


struct CQCMRPTHMM_N_TAG
{
	char          FACTORY[11];
	char          REPORT_NO[21];
	char          PACK_LOT_ID[21];
	char          ORG_LOT_ID[26];
	char          GRADE[31];
	char          TYPES[51];
	char          PACK_ORDER_ID[21];
	char          CUSTOMER_ID[101];
	double        LOT_QTY;
	char          OD_METER[31];
	char          ID_METER[31];
	char          HEIGHT[31];
	char          DIA_METER[31];
	char          LENGTH[31];
	char          DENSITY[31];
	char          MAG_SAT[31];
	char          COER_FORCE[31];
	char          HARDNESS_HV20[31];
	char          HARDNESS_HRA[31];
	char          TRS[31];
	char          ATTRIBUTE01[101];
	char          ATTRIBUTE02[101];
	char          ATTRIBUTE03[101];
	char          ATTRIBUTE04[101];
	char          ATTRIBUTE05[101];
	char          COMMENTS[101];
	char          IMAGE_NUM1[21];
	char          IMAGE_NUM2[21];
	char          PITCH_AVG[21];
	char          ROUGHNESS_AVG[21];
	char          ROUGHNESS_STD[21];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
	char          GRAIN_SIZE[31];
	char          DENSITY_SPEC[51];
	char          MAG_SAT_SPEC[51];
	char          COER_FORCE_SPEC[51];
	char          HARDNESS_HV20_SPEC[51];
	char          TRS_SPEC[51];
	char          GRAIN_SIZE_SPEC[51];
	char          RPT_CMF_1[51];
    char          RPT_CMF_2[51];
    char          RPT_CMF_3[51];
    char          RPT_CMF_4[51];
    char          RPT_CMF_5[51];
    char          RPT_CMF_6[51];
    char          RPT_CMF_7[51];
    char          RPT_CMF_8[51];
    char          RPT_CMF_9[51];
    char          RPT_CMF_10[51];
    char          RPT_CMF_11[51];
    char          RPT_CMF_12[51];
    char          RPT_CMF_13[51];
    char          RPT_CMF_14[51];
    char          RPT_CMF_15[51];
};


#endif               /* __DBU_CQCMRPTHMM_N_LOADED */

