/*********************************************************************
**
**    File Name   : DBU_cwipordopr_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-30 13:36:04
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPORDOPR_N_LOADED
#define __DBU_CWIPORDOPR_N_LOADED


struct CWIPORDOPR_N_TAG
{
    char          FACTORY[11];
    char          ORDER_ID[26];
    char          OPER[11];
    char          FLOW[21];
    char          OPER_START_TIME[15];
    char          OPER_START_DATE[9];
    char          OPER_END_TIME[15];
    char          OPER_END_DATE[9];
    char          OPER_STATUS_FLAG[2];
    double        OPER_IN_QTY;
    double        OPER_OUT_QTY;
    double        OPER_LOSS_QTY;
    double        OPER_RWK_IN_QTY;
    double        OPER_RWK_OUT_QTY;
    double        OPER_CV_QTY;
    char          AREA_ID[21];
    char          SUB_AREA_ID[21];
    char          ERP_OPER[31];
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPORDOPR_N_LOADED */

