/*********************************************************************
**
**    File Name   : DBU_crasmdextd.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2022-03-23 14:43:26
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2022 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRASMDEXTD_LOADED
#define __DBU_CRASMDEXTD_LOADED


struct CRASMDEXTD_TAG
{
    char          RES_ID[20];
    int           HIST_SEQ;
    char          WORK_TIME[14];
    char          FACTORY[10];
    char          WORK_DATE[8];
    char          DAY_NIGHT[10];
    double        SV_PRESSURE;
    double        PV_PRESSURE;
    char          RES_STATUS;
    char          START_TIME[14];
    char          END_TIME[14];
    char          EVENT_ID[12];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
	double        SV_TEMP;
	double        PV_TEMP;
};


/* Function Declaration */
extern void   DBU_init_crasmdextd(struct CRASMDEXTD_TAG *CRASMDEXTD);
extern void   DBU_select_crasmdextd(int sel_type, struct CRASMDEXTD_TAG *CRASMDEXTD);
extern void   DBU_select_crasmdextd_for_update(int sel_type, struct CRASMDEXTD_TAG *CRASMDEXTD);
extern double DBU_select_crasmdextd_scalar(int sel_type, struct CRASMDEXTD_TAG *CRASMDEXTD);
extern void   DBU_delete_crasmdextd(int sel_type, struct CRASMDEXTD_TAG *CRASMDEXTD);
extern void   DBU_insert_crasmdextd(struct CRASMDEXTD_TAG *CRASMDEXTD);
extern void   DBU_update_crasmdextd(int sel_type, struct CRASMDEXTD_TAG *CRASMDEXTD);
extern void   DBU_open_crasmdextd(int sel_type, struct CRASMDEXTD_TAG *CRASMDEXTD);
extern void   DBU_fetch_crasmdextd(int sel_type, struct CRASMDEXTD_TAG *CRASMDEXTD);
extern void   DBU_close_crasmdextd(int sel_type);


#endif               /* __DBU_CRASMDEXTD_LOADED */

