/*********************************************************************
**
**    File Name   : DBU_if_vendor_def_his.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-28 11:17:28
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_VENDOR_DEF_HIS_LOADED
#define __DBU_IF_VENDOR_DEF_HIS_LOADED


struct IF_VENDOR_DEF_HIS_TAG
{
	int           IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	int           VENDOR_ID;
	char          VENDOE_CODE[30];
	char          VENDOR_NAME[240];
	char          VENDOR_TYPE[30];
	int           VENDOR_SITE_ID;
	char          VENDOR_SITE_CODE[15];
	char          VAT_REGISTRATION_NUM[20];
	char          PURCHASING_SITE_FLAG;
	char          ENABLED_FLAG;
	char          START_DATE_ACTIVE[14];
	char          END_DATE_ACTIVE[14];
	char          TRAN_FLAG;
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_vendor_def_his(struct IF_VENDOR_DEF_HIS_TAG *IF_VENDOR_DEF_HIS);
extern void   DBU_select_if_vendor_def_his(int sel_type, struct IF_VENDOR_DEF_HIS_TAG *IF_VENDOR_DEF_HIS);
extern void   DBU_select_if_vendor_def_his_for_update(int sel_type, struct IF_VENDOR_DEF_HIS_TAG *IF_VENDOR_DEF_HIS);
extern double DBU_select_if_vendor_def_his_scalar(int sel_type, struct IF_VENDOR_DEF_HIS_TAG *IF_VENDOR_DEF_HIS);
extern void   DBU_delete_if_vendor_def_his(int sel_type, struct IF_VENDOR_DEF_HIS_TAG *IF_VENDOR_DEF_HIS);
extern void   DBU_insert_if_vendor_def_his(struct IF_VENDOR_DEF_HIS_TAG *IF_VENDOR_DEF_HIS);
extern void   DBU_update_if_vendor_def_his(int sel_type, struct IF_VENDOR_DEF_HIS_TAG *IF_VENDOR_DEF_HIS);
extern void   DBU_open_if_vendor_def_his(int sel_type, struct IF_VENDOR_DEF_HIS_TAG *IF_VENDOR_DEF_HIS);
extern void   DBU_fetch_if_vendor_def_his(int sel_type, struct IF_VENDOR_DEF_HIS_TAG *IF_VENDOR_DEF_HIS);
extern void   DBU_close_if_vendor_def_his(int sel_type);


#endif               /* __DBU_IF_VENDOR_DEF_HIS_LOADED */

