/*********************************************************************
**
**    File Name   : DBU_cbasshpbom.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-02-09 15:47:09
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CBASSHPBOM_LOADED
#define __DBU_CBASSHPBOM_LOADED


struct CBASSHPBOM_TAG
{
    char          FACTORY[10];
    char          MAT_ID[30];
    char          BOM_MAT_ID[30];
    double        QTY;
    char          REMARKS[400];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cbasshpbom(struct CBASSHPBOM_TAG *CBASSHPBOM);
extern void   DBU_select_cbasshpbom(int sel_type, struct CBASSHPBOM_TAG *CBASSHPBOM);
extern void   DBU_select_cbasshpbom_for_update(int sel_type, struct CBASSHPBOM_TAG *CBASSHPBOM);
extern double DBU_select_cbasshpbom_scalar(int sel_type, struct CBASSHPBOM_TAG *CBASSHPBOM);
extern void   DBU_delete_cbasshpbom(int sel_type, struct CBASSHPBOM_TAG *CBASSHPBOM);
extern void   DBU_insert_cbasshpbom(struct CBASSHPBOM_TAG *CBASSHPBOM);
extern void   DBU_update_cbasshpbom(int sel_type, struct CBASSHPBOM_TAG *CBASSHPBOM);
extern void   DBU_open_cbasshpbom(int sel_type, struct CBASSHPBOM_TAG *CBASSHPBOM);
extern void   DBU_fetch_cbasshpbom(int sel_type, struct CBASSHPBOM_TAG *CBASSHPBOM);
extern void   DBU_close_cbasshpbom(int sel_type);


#endif               /* __DBU_CBASSHPBOM_LOADED */

