/*********************************************************************
**
**    File Name   : DBU_cqcmgrtcot_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-03 12:25:59
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMGRTCOT_N_LOADED
#define __DBU_CQCMGRTCOT_N_LOADED


struct CQCMGRTCOT_N_TAG
{
    char          FACTORY[11];
    char          INSP_ID[31];
    char          INSP_DTL_TYPE[31];
    int           INSP_COUNT;
    char          SIZES[31];
    double        MA_VALUE_1;
    double        MA_RESULT;
    double        WT_VALUE_1;
    double        WT_VALUE_2;
    double        WT_VALUE_3;
    double        WT_RESULT;
    double        BD_VALUE_1;
    double        BD_RESULT;
    double        TD_VALUE_1;
    double        TD_RESULT;
    double        PCS_VALUE_1;
    double        PCS_RESULT;
    double        PS_VALUE_1;
    double        PS_VALUE_2;
    double        PS_RESULT;
    double        CM_L;
    double        CM_A;
    double        CM_B;
    double        CM_YI;
    char          REMARKS[301];
    double        COMPAC_VALUE;
    double        ELIP_VALUE;
    double        ROUG_VALUE;
    double        SURFACE_NI;
    double        SURFACE_FE;
    double        SURFACE_CU;
    double        SURFACE_CR;
    double        SURFACE_TI;
    double        SURFACE_MN;
    double        SURFACE_CO;
    double        SURFACE_CA;
    double        SURFACE_MG;
    double        SURFACE_ZN;
    double        SURFACE_MO;
    double        SURFACE_PB;
    double        SURFACE_AL;
    double        SURFACE_SI;
    double        SURFACE_B;
    double        SURFACE_NA;
    double        CON_O_VALUE;
    double        ELIP_VALUE2;
    double        SHAPE_FACTOR;
    double        GRAIN_SIZE;
    double        CIRCULRARITY;
    double        CONVEXITY;
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CQCMGRTCOT_N_LOADED */

