/*********************************************************************
**
**    File Name   : DBU_cwiplotmvr.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-27 22:15:22
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTMVR_LOADED
#define __DBU_CWIPLOTMVR_LOADED


struct CWIPLOTMVR_TAG
{
    char          FACTORY[10];
    char          MOVE_ID[20];
    char          LOT_ID[25];
    int           HIST_SEQ;
    char          MERGE_LOT_FLAG;
    char          MERGE_FLAG;
    double        QTY;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiplotmvr(struct CWIPLOTMVR_TAG *CWIPLOTMVR);
extern void   DBU_select_cwiplotmvr(int sel_type, struct CWIPLOTMVR_TAG *CWIPLOTMVR);
extern void   DBU_select_cwiplotmvr_for_update(int sel_type, struct CWIPLOTMVR_TAG *CWIPLOTMVR);
extern double DBU_select_cwiplotmvr_scalar(int sel_type, struct CWIPLOTMVR_TAG *CWIPLOTMVR);
extern void   DBU_delete_cwiplotmvr(int sel_type, struct CWIPLOTMVR_TAG *CWIPLOTMVR);
extern void   DBU_insert_cwiplotmvr(struct CWIPLOTMVR_TAG *CWIPLOTMVR);
extern void   DBU_update_cwiplotmvr(int sel_type, struct CWIPLOTMVR_TAG *CWIPLOTMVR);
extern void   DBU_open_cwiplotmvr(int sel_type, struct CWIPLOTMVR_TAG *CWIPLOTMVR);
extern void   DBU_fetch_cwiplotmvr(int sel_type, struct CWIPLOTMVR_TAG *CWIPLOTMVR);
extern void   DBU_close_cwiplotmvr(int sel_type);


#endif               /* __DBU_CWIPLOTMVR_LOADED */

