/*********************************************************************
**
**    File Name   : DBU_cwipordopr.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-30 13:36:04
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPORDOPR_LOADED
#define __DBU_CWIPORDOPR_LOADED


struct CWIPORDOPR_TAG
{
    char          FACTORY[10];
    char          ORDER_ID[25];
    char          OPER[10];
    char          FLOW[20];
    char          OPER_START_TIME[14];
    char          OPER_START_DATE[8];
    char          OPER_END_TIME[14];
    char          OPER_END_DATE[8];
    char          OPER_STATUS_FLAG;
    double        OPER_IN_QTY;
    double        OPER_OUT_QTY;
    double        OPER_LOSS_QTY;
    double        OPER_RWK_IN_QTY;
    double        OPER_RWK_OUT_QTY;
    double        OPER_CV_QTY;
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          ERP_OPER[30];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwipordopr(struct CWIPORDOPR_TAG *CWIPORDOPR);
extern void   DBU_select_cwipordopr(int sel_type, struct CWIPORDOPR_TAG *CWIPORDOPR);
extern void   DBU_select_cwipordopr_for_update(int sel_type, struct CWIPORDOPR_TAG *CWIPORDOPR);
extern double DBU_select_cwipordopr_scalar(int sel_type, struct CWIPORDOPR_TAG *CWIPORDOPR);
extern void   DBU_delete_cwipordopr(int sel_type, struct CWIPORDOPR_TAG *CWIPORDOPR);
extern void   DBU_insert_cwipordopr(struct CWIPORDOPR_TAG *CWIPORDOPR);
extern void   DBU_update_cwipordopr(int sel_type, struct CWIPORDOPR_TAG *CWIPORDOPR);
extern void   DBU_open_cwipordopr(int sel_type, struct CWIPORDOPR_TAG *CWIPORDOPR);
extern void   DBU_fetch_cwipordopr(int sel_type, struct CWIPORDOPR_TAG *CWIPORDOPR);
extern void   DBU_close_cwipordopr(int sel_type);


#endif               /* __DBU_CWIPORDOPR_LOADED */

