/*********************************************************************
**
**    File Name   : DBU_if_po_rcv_txns_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-13 16:18:34
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_PO_RCV_TXNS_N_LOADED
#define __DBU_IF_PO_RCV_TXNS_N_LOADED


struct IF_PO_RCV_TXNS_N_TAG
{
	double        IF_SEQ;
    char          IF_TIME[15];
    char          IF_CODE[2];
    char          IF_MSG[201];
    char          FACTORY[11];
    int           TRAN_TYPE_ID;
    char          TRAN_TYPE[11];
    char          TRAN_TIME[15];
    char          TRAN_FLAG[2];
	double        RCV_HEADER_ID;
    int           PO_HEADER_ID;
    int           PO_LINE_ID;
    int           PO_RELEASE_ID;
    int           PO_LINE_LOCATION_ID;
    int           PO_DISTRIBUTION_ID;
    char          PO_TYPE[151];
    int           ERP_MAT_ID;
    char          MAT_ID[31];
    char          OPER_CODE[11];
    double        QTY;
    char          UNIT[4];
    char          LOT_ID[31];
    char          MES_ID[31];
    char          INV_OPER[11];
    int           ERP_AREA_ID;
    char          AREA_ID[4];
	double        SRC_IF_SEQ;
    char          CMF_1[51];
    char          CMF_2[51];
    char          CMF_3[51];
    char          CMF_4[51];
    char          CMF_5[51];
    char          CMF_6[51];
    char          CMF_7[51];
    char          CMF_8[51];
    char          CMF_9[51];
    char          CMF_10[51];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_PO_RCV_TXNS_N_LOADED */

