/*********************************************************************
**
**    File Name   : DBU_cwiplotimp_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-15 08:25:21
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTIMP_N_LOADED
#define __DBU_CWIPLOTIMP_N_LOADED


struct CWIPLOTIMP_N_TAG
{
    char          LOT_ID[26];
    int           HIST_SEQ;
    char          OPER[11];
    char          MAT_ID[31];
    char          FLOW[21];
    int           FLOW_SEQ_NUM;
    char          GRADE[51];
    char          RES_ID[21];
    char          FACTORY[11];
    char          WORK_DATE[9];
    char          WORK_TIME[15];
    char          DAY_NIGHT[11];
    int           EDC_HIST_SEQ;
    char          RECIPE_ID[51];
    char          START_TIME[15];
    char          END_TIME[15];
    char          JUDGMENT[11];
    double        FLATNESS_1;
    double        FLATNESS_2;
    double        FLATNESS_3;
    double        FLATNESS_4;
    double        FLATNESS_5;
    double        WEIGHT;
    double        AIR_POCKET;
    char          IMPACT_NO[31];
    int           IMPACT_TIME;
    char          AUTO_FLAG[2];
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPLOTIMP_N_LOADED */

