/*********************************************************************
**
**    File Name   : DBU_if_wo_info_his.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-25 18:07:15
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_WO_INFO_HIS_LOADED
#define __DBU_IF_WO_INFO_HIS_LOADED


struct IF_WO_INFO_HIS_TAG
{
	int           IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	int           ORG_ID;
	char          ORG_CODE[3];
	int           WIP_ENTITY_ID;
	char          WIP_ENTITY_NAME[240];
	int           ITEM_ID;
	char          ITEM_CODE[40];
	char          ITEM_DESC[240];
	char          ITEM_UNIT[3];
	char          ITEM_TYPE[30];
	char          ALTERNATE_BOM_DESIGNATOR[10];
	char          ALTER_RTG_NAME[10];
	char          COMPLETION_INV_OPER[10];
	int           OPER_SEQ_NUM;
	int           STANDARD_OPER_ID;
	char          OPER[10];
	char          OPER_DESC[240];
	int           DEPT_ID;
	char          DEPT_CODE[10];
	char          DEPT_DESC[240];
	int           STATUS_TYPE;
	char          STATUS_TYPE_NAME[19];
	int           JOB_TYPE;
	char          JOB_TYPE_NAME[12];
	char          PLAN_START_DATE[14];
	char          PLAN_END_DATE[14];
	char          RELEASED_DATE[14];
	char          COMP_DATE[14];
	char          CLOSED_DATE[14];
	double        PLAN_QTY;
	double        QTY_IN_QUEUE;
	double        QTY_WAITING_TO_MOVE;
	double        QTY_SCRAPPED;
	double        QTY_COMPLETED;
	char          CUT_MULTI[150];
	int           PRE_OPER_SEQ;
	char          PRE_OPER[10];
	int           NEXT_OPER_SEQ;
	char          NEXT_OPER[10];
	char          FIRST_OPER_YN;
	char          LAST_OPER_YN;
	char          SRS_YN[3];
	char          PUP_GBN[240];
	char          CUTTING[50];
	char          CUST_NAME[240];
	char          VENDORS[240];
	char          REMARKS[150];
	char          SO_NUM[150];
	char          LAST_COMP_DATE[14];
	char          TRAN_FLAG;
	int           IF_GROUP_ID;
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_wo_info_his(struct IF_WO_INFO_HIS_TAG *IF_WO_INFO_HIS);
extern void   DBU_select_if_wo_info_his(int sel_type, struct IF_WO_INFO_HIS_TAG *IF_WO_INFO_HIS);
extern void   DBU_select_if_wo_info_his_for_update(int sel_type, struct IF_WO_INFO_HIS_TAG *IF_WO_INFO_HIS);
extern double DBU_select_if_wo_info_his_scalar(int sel_type, struct IF_WO_INFO_HIS_TAG *IF_WO_INFO_HIS);
extern void   DBU_delete_if_wo_info_his(int sel_type, struct IF_WO_INFO_HIS_TAG *IF_WO_INFO_HIS);
extern void   DBU_insert_if_wo_info_his(struct IF_WO_INFO_HIS_TAG *IF_WO_INFO_HIS);
extern void   DBU_update_if_wo_info_his(int sel_type, struct IF_WO_INFO_HIS_TAG *IF_WO_INFO_HIS);
extern void   DBU_open_if_wo_info_his(int sel_type, struct IF_WO_INFO_HIS_TAG *IF_WO_INFO_HIS);
extern void   DBU_fetch_if_wo_info_his(int sel_type, struct IF_WO_INFO_HIS_TAG *IF_WO_INFO_HIS);
extern void   DBU_close_if_wo_info_his(int sel_type);


#endif               /* __DBU_IF_WO_INFO_HIS_LOADED */

