/*********************************************************************
**
**    File Name   : DBU_if_move_trx_save.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-09 02:01:19
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_MOVE_TRX_SAVE_LOADED
#define __DBU_IF_MOVE_TRX_SAVE_LOADED


struct IF_MOVE_TRX_SAVE_TAG
{
	double        IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	int           TRAN_TYPE_ID;
	char          TRAN_TYPE[10];
	char          TRAN_TIME[14];
	char          TRAN_FLAG;
	int           ERP_ORDER_NUM;
	int           ERP_AREA_ID;
	char          AREA_ID[3];
	int           ERP_WO_ID;
	char          WO_ID[240];
	int           FROM_OPER_SEQ;
	char          FROM_OPER[10];
	int           FROM_STEP_TYPE;
	char          FROM_STEP[20];
	int           TO_OPER_SEQ;
	char          TO_OPER[10];
	int           TO_STEP_TYPE;
	char          TO_STEP[20];
	char          UNIT[3];
	double        QTY;
	double        TRAN_HEADER_ID;
	double        SRC_TRAN_ID;
	char          OVER_FLAG;
	char          MES_OPER[10];
	char          LOT_ID[25];
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_move_trx_save(struct IF_MOVE_TRX_SAVE_TAG *IF_MOVE_TRX_SAVE);
extern void   DBU_select_if_move_trx_save(int sel_type, struct IF_MOVE_TRX_SAVE_TAG *IF_MOVE_TRX_SAVE);
extern void   DBU_select_if_move_trx_save_for_update(int sel_type, struct IF_MOVE_TRX_SAVE_TAG *IF_MOVE_TRX_SAVE);
extern double DBU_select_if_move_trx_save_scalar(int sel_type, struct IF_MOVE_TRX_SAVE_TAG *IF_MOVE_TRX_SAVE);
extern void   DBU_delete_if_move_trx_save(int sel_type, struct IF_MOVE_TRX_SAVE_TAG *IF_MOVE_TRX_SAVE);
extern void   DBU_insert_if_move_trx_save(struct IF_MOVE_TRX_SAVE_TAG *IF_MOVE_TRX_SAVE);
extern void   DBU_update_if_move_trx_save(int sel_type, struct IF_MOVE_TRX_SAVE_TAG *IF_MOVE_TRX_SAVE);
extern void   DBU_open_if_move_trx_save(int sel_type, struct IF_MOVE_TRX_SAVE_TAG *IF_MOVE_TRX_SAVE);
extern void   DBU_fetch_if_move_trx_save(int sel_type, struct IF_MOVE_TRX_SAVE_TAG *IF_MOVE_TRX_SAVE);
extern void   DBU_close_if_move_trx_save(int sel_type);


#endif               /* __DBU_IF_MOVE_TRX_SAVE_LOADED */

