/*********************************************************************
**
**    File Name   : DBU_mwiplotlos.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-27 17:14:26
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MWIPLOTLOS_LOADED
#define __DBU_MWIPLOTLOS_LOADED




/* Function Declaration */
extern void   DBU_init_mwiplotlos(struct MWIPLOTLOS_TAG *MWIPLOTLOS);
extern void   DBU_select_mwiplotlos(int sel_type, struct MWIPLOTLOS_TAG *MWIPLOTLOS);
extern void   DBU_select_mwiplotlos_for_update(int sel_type, struct MWIPLOTLOS_TAG *MWIPLOTLOS);
extern double DBU_select_mwiplotlos_scalar(int sel_type, struct MWIPLOTLOS_TAG *MWIPLOTLOS);
extern void   DBU_delete_mwiplotlos(int sel_type, struct MWIPLOTLOS_TAG *MWIPLOTLOS);
extern void   DBU_insert_mwiplotlos(struct MWIPLOTLOS_TAG *MWIPLOTLOS);
extern void   DBU_update_mwiplotlos(int sel_type, struct MWIPLOTLOS_TAG *MWIPLOTLOS);
extern void   DBU_open_mwiplotlos(int sel_type, struct MWIPLOTLOS_TAG *MWIPLOTLOS);
extern void   DBU_fetch_mwiplotlos(int sel_type, struct MWIPLOTLOS_TAG *MWIPLOTLOS);
extern void   DBU_close_mwiplotlos(int sel_type);


#endif               /* __DBU_MWIPLOTLOS_LOADED */

