/*********************************************************************
**
**    File Name   : DBU_crasbalmil_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2022-03-23 15:50:55
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2022 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRASBALMIL_N_LOADED
#define __DBU_CRASBALMIL_N_LOADED


struct CRASBALMIL_N_TAG
{
    char          RES_ID[21];
    int           HIST_SEQ;
    char          WORK_TIME[15];
    char          FACTORY[11];
    char          WORK_DATE[9];
    char          DAY_NIGHT[11];
    char          SV_TIME[15];
    char          PV_TIME[15];
	double		  SV_RPM;
    double        PV_RPM;
    char          RES_STATUS[2];
    char          START_TIME[15];
    char          END_TIME[15];
    char          EVENT_ID[13];
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CRASBALMIL_N_LOADED */

