/*********************************************************************
**
**    File Name   : DBU_cwipgrplot_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-25 13:48:39
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPGRPLOT_N_LOADED
#define __DBU_CWIPGRPLOT_N_LOADED


struct CWIPGRPLOT_N_TAG
{
    char          FACTORY[11];
    char          GROUP_ID[26];
    char          LOT_ID[26];
    int           MAPPING_SEQ;
    char          AREA_ID[21];
    char          SUB_AREA_ID[21];
    char          OPER[11];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPGRPLOT_N_LOADED */

