/*********************************************************************
**
**    File Name   : DBU_if_mat_def_his.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-14 16:33:40
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_MAT_DEF_HIS_LOADED
#define __DBU_IF_MAT_DEF_HIS_LOADED


struct IF_MAT_DEF_HIS_TAG
{
	double        IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	int           ORG_ID;
	char          ORG_CODE[3];
	int           ITEM_ID;
	char          ITEM_CODE[40];
	char          ITEM_DESC[240];
	double        UNIT_WEIGHT;
	char          UNIT[3];
	char          ITEM_TYPE[30];
	char          ITEM_TYPE_NAME[80];
	char          ITEM_TYPE_DESC[240];
	char          ENABLED_FLAG;
	char          INVENTORY_ASSET_FLAG;
	char          CATALOG_NAME10[30];
	char          CATALOG_VALUE10[30];
	char          CATALOG_NAME20[30];
	char          CATALOG_VALUE20[30];
	char          CATALOG_NAME30[30];
	char          CATALOG_VALUE30[30];
	char          CATALOG_NAME40[30];
	char          CATALOG_VALUE40[30];
	char          CATALOG_NAME50[30];
	char          CATALOG_VALUE50[30];
	char          CATALOG_NAME60[30];
	char          CATALOG_VALUE60[30];
	char          CATALOG_NAME70[30];
	char          CATALOG_VALUE70[30];
	char          ITEM_SIZE[30];
	char          ITEM_LENG[30];
	char          ITEM_NTRL[30];
	char          ITEM_MTHD[30];
	char          STATUS_CODE[10];
	char          TRAN_FLAG;
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_mat_def_his(struct IF_MAT_DEF_HIS_TAG *IF_MAT_DEF_HIS);
extern void   DBU_select_if_mat_def_his(int sel_type, struct IF_MAT_DEF_HIS_TAG *IF_MAT_DEF_HIS);
extern void   DBU_select_if_mat_def_his_for_update(int sel_type, struct IF_MAT_DEF_HIS_TAG *IF_MAT_DEF_HIS);
extern double DBU_select_if_mat_def_his_scalar(int sel_type, struct IF_MAT_DEF_HIS_TAG *IF_MAT_DEF_HIS);
extern void   DBU_delete_if_mat_def_his(int sel_type, struct IF_MAT_DEF_HIS_TAG *IF_MAT_DEF_HIS);
extern void   DBU_insert_if_mat_def_his(struct IF_MAT_DEF_HIS_TAG *IF_MAT_DEF_HIS);
extern void   DBU_update_if_mat_def_his(int sel_type, struct IF_MAT_DEF_HIS_TAG *IF_MAT_DEF_HIS);
extern void   DBU_open_if_mat_def_his(int sel_type, struct IF_MAT_DEF_HIS_TAG *IF_MAT_DEF_HIS);
extern void   DBU_fetch_if_mat_def_his(int sel_type, struct IF_MAT_DEF_HIS_TAG *IF_MAT_DEF_HIS);
extern void   DBU_close_if_mat_def_his(int sel_type);


#endif               /* __DBU_IF_MAT_DEF_HIS_LOADED */

