/*********************************************************************
**
**    File Name   : DBU_cbasshpbom_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-02-09 15:47:09
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CBASSHPBOM_N_LOADED
#define __DBU_CBASSHPBOM_N_LOADED


struct CBASSHPBOM_N_TAG
{
    char          FACTORY[11];
    char          MAT_ID[31];
    char          BOM_MAT_ID[31];
    double        QTY;
    char          REMARKS[401];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CBASSHPBOM_N_LOADED */

