/*********************************************************************
**
**    File Name   : DBU_if_txn_type_def.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-28 11:16:07
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_TXN_TYPE_DEF_LOADED
#define __DBU_IF_TXN_TYPE_DEF_LOADED


struct IF_TXN_TYPE_DEF_TAG
{
	int           IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	int           ORG_ID;
	char          ORG_CODE[3];
	int           TRANSACTION_TYPE_ID;
	char          TRANSACTION_TYPE_NAME[80];
	int           TRANSACTION_SOURCE_ID;
	char          TRANSACTION_SOURCE_DESC[50];
	char          USER_DEFINED_FLAG;
	char          ISSUE_RECEIPT_FLAG[7];
	int           TRANSACTION_ACTION_ID;
	int           TRANSACTION_SOURCE_TYPE_ID;
	char          TRANSACTION_SOURCE_TYPE_NAME[240];
	char          MRO_FLAG[150];
	char          ENABLED_FLAG;
	char          DISABLE_DATE[14];
	char          TRAN_FLAG;
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_txn_type_def(struct IF_TXN_TYPE_DEF_TAG *IF_TXN_TYPE_DEF);
extern void   DBU_select_if_txn_type_def(int sel_type, struct IF_TXN_TYPE_DEF_TAG *IF_TXN_TYPE_DEF);
extern void   DBU_select_if_txn_type_def_for_update(int sel_type, struct IF_TXN_TYPE_DEF_TAG *IF_TXN_TYPE_DEF);
extern double DBU_select_if_txn_type_def_scalar(int sel_type, struct IF_TXN_TYPE_DEF_TAG *IF_TXN_TYPE_DEF);
extern void   DBU_delete_if_txn_type_def(int sel_type, struct IF_TXN_TYPE_DEF_TAG *IF_TXN_TYPE_DEF);
extern void   DBU_insert_if_txn_type_def(struct IF_TXN_TYPE_DEF_TAG *IF_TXN_TYPE_DEF);
extern void   DBU_update_if_txn_type_def(int sel_type, struct IF_TXN_TYPE_DEF_TAG *IF_TXN_TYPE_DEF);
extern void   DBU_open_if_txn_type_def(int sel_type, struct IF_TXN_TYPE_DEF_TAG *IF_TXN_TYPE_DEF);
extern void   DBU_fetch_if_txn_type_def(int sel_type, struct IF_TXN_TYPE_DEF_TAG *IF_TXN_TYPE_DEF);
extern void   DBU_close_if_txn_type_def(int sel_type);


#endif               /* __DBU_IF_TXN_TYPE_DEF_LOADED */

