/*********************************************************************
**
**    File Name   : DBU_ishprptrcv.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-05-14 11:16:14
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_ISHPRPTRCV_LOADED
#define __DBU_ISHPRPTRCV_LOADED


struct ISHPRPTRCV_TAG
{
    char          FACTORY[10];
    char          PACK_LOT_ID[25];
    char          ORG_LOT_ID[25];
    char          TO_FACTORY[10];
    char          PACK_ORDER_ID[25];
    int           PACK_LINE_NO;
    char          CUSTOMER_ID[200];
    char          SHIP_DATE[14];
    char          SHIP_ORDER_ID[25];
    int           SHIP_ORDER_SEQ;
    int           SHIPPING_LINE_ID;
    char          GRADE[30];
    char          TYPES[50];
    char          OD_STANDARD[30];
    char          OD_SPEC[30];
    char          OD_MIN_VAL[30];
    char          OD_MAX_VAL[30];
    char          AT_STANDARD[30];
    char          AT_SPEC[30];
    char          AT_MIN_VAL[30];
    char          AT_MAX_VAL[30];
    char          GT_STANDARD[30];
    char          GT_SPEC[30];
    char          GT_MIN_VAL[30];
    char          GT_MAX_VAL[30];
    char          LEN01_STANDARD[30];
    char          LEN01_SPEC[30];
    char          LEN_MIN_VAL01[30];
    char          LEN_MAX_VAL01[30];
    char          LEN02_STANDARD[30];
    char          LEN02_SPEC[30];
    char          LEN_MIN_VAL02[30];
    char          LEN_MAX_VAL02[30];
    char          DMG_STANDARD[30];
    char          DMG_SPEC[30];
    char          DMG_MIN_VAL[30];
    char          DMG_MAX_VAL[30];
    char          RECEIVE_FLAG;
    char          DELETE_FLAG;
    char          CMF_1[50];
    char          CMF_2[50];
    char          CMF_3[50];
    char          CMF_4[50];
    char          CMF_5[50];
    char          CMF_6[50];
    char          CMF_7[50];
    char          CMF_8[50];
    char          CMF_9[50];
    char          CMF_10[50];
    char          CMF_11[50];
    char          CMF_12[50];
    char          CMF_13[50];
    char          CMF_14[50];
    char          CMF_15[50];
    char          COMMENTS[100];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_ishprptrcv(struct ISHPRPTRCV_TAG *ISHPRPTRCV);
extern void   DBU_select_ishprptrcv(int sel_type, struct ISHPRPTRCV_TAG *ISHPRPTRCV);
extern void   DBU_select_ishprptrcv_for_update(int sel_type, struct ISHPRPTRCV_TAG *ISHPRPTRCV);
extern double DBU_select_ishprptrcv_scalar(int sel_type, struct ISHPRPTRCV_TAG *ISHPRPTRCV);
extern void   DBU_delete_ishprptrcv(int sel_type, struct ISHPRPTRCV_TAG *ISHPRPTRCV);
extern void   DBU_insert_ishprptrcv(struct ISHPRPTRCV_TAG *ISHPRPTRCV);
extern void   DBU_update_ishprptrcv(int sel_type, struct ISHPRPTRCV_TAG *ISHPRPTRCV);
extern void   DBU_open_ishprptrcv(int sel_type, struct ISHPRPTRCV_TAG *ISHPRPTRCV);
extern void   DBU_fetch_ishprptrcv(int sel_type, struct ISHPRPTRCV_TAG *ISHPRPTRCV);
extern void   DBU_close_ishprptrcv(int sel_type);


#endif               /* __DBU_ISHPRPTRCV_LOADED */

