/*********************************************************************
**
**    File Name   : DBU_csecusedat_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-01 15:01:37
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CSECUSEDAT_N_LOADED
#define __DBU_CSECUSEDAT_N_LOADED


struct CSECUSEDAT_N_TAG
{
    char          FACTORY[11];
    char          USE_DATE[9];
    char          PROGRAM_ID[51];
    char          USER_ID[21];
    char          PROGRAM_DESC[101];
    char          FUNC_NAME[13];
    char          PG_KIND[11];
    int           USE_COUNT;
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CSECUSEDAT_N_LOADED */

