/*********************************************************************
**
**    File Name   : DBU_cqcmispwrk_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-22 17:30:02
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMISPWRK_N_LOADED
#define __DBU_CQCMISPWRK_N_LOADED


struct CQCMISPWRK_N_TAG
{
    char          FACTORY[11];
    char          INSP_ID[31];
    char          WORKER_ID[21];
    char          WORKER_DESC[31];
    char          WORK_TYPE[31];
};


#endif               /* __DBU_CQCMISPWRK_N_LOADED */

