/*********************************************************************
**
**    File Name   : DBU_csumlotdat.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-01-05 11:17:19
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CSUMLOTDAT_LOADED
#define __DBU_CSUMLOTDAT_LOADED


struct CSUMLOTDAT_TAG
{
    char          LOT_ID[25];
    char          OPER[10];
    int           START_HIST_SEQ;
    char          RWK_FLAG;
    char          RES_ID[20];
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          FACTORY[10];
    char          MAT_ID[30];
    char          FLOW[20];
    int           FLOW_SEQ_NUM;
    double        IN_QTY;
    double        OUT_QTY;
    double        LOSS_QTY;
    char          UNIT[10];
    char          ORDER_ID[25];
    char          START_DATE[8];
    char          START_TIME[14];
    char          START_DAY_NIGHT[10];
    int           END_HIST_SEQ;
    char          END_DATE[8];
    char          END_TIME[14];
    char          END_DAY_NIGHT[10];
    char          ONLY_END_FLAG;
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_csumlotdat(struct CSUMLOTDAT_TAG *CSUMLOTDAT);
extern void   DBU_select_csumlotdat(int sel_type, struct CSUMLOTDAT_TAG *CSUMLOTDAT);
extern void   DBU_select_csumlotdat_for_update(int sel_type, struct CSUMLOTDAT_TAG *CSUMLOTDAT);
extern double DBU_select_csumlotdat_scalar(int sel_type, struct CSUMLOTDAT_TAG *CSUMLOTDAT);
extern void   DBU_delete_csumlotdat(int sel_type, struct CSUMLOTDAT_TAG *CSUMLOTDAT);
extern void   DBU_insert_csumlotdat(struct CSUMLOTDAT_TAG *CSUMLOTDAT);
extern void   DBU_update_csumlotdat(int sel_type, struct CSUMLOTDAT_TAG *CSUMLOTDAT);
extern void   DBU_open_csumlotdat(int sel_type, struct CSUMLOTDAT_TAG *CSUMLOTDAT);
extern void   DBU_fetch_csumlotdat(int sel_type, struct CSUMLOTDAT_TAG *CSUMLOTDAT);
extern void   DBU_close_csumlotdat(int sel_type);


#endif               /* __DBU_CSUMLOTDAT_LOADED */

