/*********************************************************************
**
**    File Name   : DBU_minvlotmvh.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-31 16:59:19
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MINVLOTMVH_LOADED
#define __DBU_MINVLOTMVH_LOADED


struct MINVLOTMVH_TAG
{
    char          FACTORY[10];
    char          INV_LOT_ID[25];
    int           HIST_SEQ;
    char          TRAN_CODE[12];
    char          TRAN_USER_ID[20];
    char          TRAN_TIME[14];
    char          MAT_ID[30];
    int           MAT_VER;
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          OPER[10];
    char          TO_AREA_ID[20];
    char          TO_SUB_AREA_ID[20];
    char          TO_OPER[10];
    double        TRAN_QTY;
    double        TRAN_QTY_2;
    double        TRAN_QTY_3;
    char          HIST_DEL_FLAG;
};


/* Function Declaration */
extern void   DBU_init_minvlotmvh(struct MINVLOTMVH_TAG *MINVLOTMVH);
extern void   DBU_select_minvlotmvh(int sel_type, struct MINVLOTMVH_TAG *MINVLOTMVH);
extern void   DBU_select_minvlotmvh_for_update(int sel_type, struct MINVLOTMVH_TAG *MINVLOTMVH);
extern double DBU_select_minvlotmvh_scalar(int sel_type, struct MINVLOTMVH_TAG *MINVLOTMVH);
extern void   DBU_delete_minvlotmvh(int sel_type, struct MINVLOTMVH_TAG *MINVLOTMVH);
extern void   DBU_insert_minvlotmvh(struct MINVLOTMVH_TAG *MINVLOTMVH);
extern void   DBU_update_minvlotmvh(int sel_type, struct MINVLOTMVH_TAG *MINVLOTMVH);
extern void   DBU_open_minvlotmvh(int sel_type, struct MINVLOTMVH_TAG *MINVLOTMVH);
extern void   DBU_fetch_minvlotmvh(int sel_type, struct MINVLOTMVH_TAG *MINVLOTMVH);
extern void   DBU_close_minvlotmvh(int sel_type);


#endif               /* __DBU_MINVLOTMVH_LOADED */

