/*********************************************************************
**
**    File Name   : DBU_if_vendor_def_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-28 11:17:15
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_VENDOR_DEF_N_LOADED
#define __DBU_IF_VENDOR_DEF_N_LOADED


struct IF_VENDOR_DEF_N_TAG
{
	int           IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	int           VENDOR_ID;
	char          VENDOE_CODE[31];
	char          VENDOR_NAME[241];
	char          VENDOR_TYPE[31];
	int           VENDOR_SITE_ID;
	char          VENDOR_SITE_CODE[16];
	char          VAT_REGISTRATION_NUM[21];
	char          PURCHASING_SITE_FLAG[2];
	char          ENABLED_FLAG[2];
	char          START_DATE_ACTIVE[15];
	char          END_DATE_ACTIVE[15];
	char          TRAN_FLAG[2];
	char          CMF_1[51];
	char          CMF_2[51];
	char          CMF_3[51];
	char          CMF_4[51];
	char          CMF_5[51];
	char          CMF_6[51];
	char          CMF_7[51];
	char          CMF_8[51];
	char          CMF_9[51];
	char          CMF_10[51];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_VENDOR_DEF_N_LOADED */

