/*********************************************************************
**
**    File Name   : DBU_ct_mold_v.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-04 15:39:46
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CT_MOLD_V_LOADED
#define __DBU_CT_MOLD_V_LOADED


struct CT_MOLD_V_TAG
{
    char          ORG_CODE[3];
    char          LOT_ID[30];
    char          ITEM_CODE[30];
    int           REMAIN_QTY;
    char          WH_CODE[20];
    char          SUUPLIER_LOT_ID[30];
    char          REMARKS[1000];
    char          USE_YN;
    char          STATUS[2];
    char          TRANS_MASTER_SEQ[30];
    char          DA_MODELS[10];
    char          DA_TYPE[5];
};


/* Function Declaration */
extern void   DBU_init_ct_mold_v(struct CT_MOLD_V_TAG *CT_MOLD_V);
extern void   DBU_select_ct_mold_v(int sel_type, struct CT_MOLD_V_TAG *CT_MOLD_V);
extern void   DBU_select_ct_mold_v_for_update(int sel_type, struct CT_MOLD_V_TAG *CT_MOLD_V);
extern double DBU_select_ct_mold_v_scalar(int sel_type, struct CT_MOLD_V_TAG *CT_MOLD_V);
extern void   DBU_delete_ct_mold_v(int sel_type, struct CT_MOLD_V_TAG *CT_MOLD_V);
extern void   DBU_insert_ct_mold_v(struct CT_MOLD_V_TAG *CT_MOLD_V);
extern void   DBU_update_ct_mold_v(int sel_type, struct CT_MOLD_V_TAG *CT_MOLD_V);
extern void   DBU_open_ct_mold_v(int sel_type, struct CT_MOLD_V_TAG *CT_MOLD_V);
extern void   DBU_fetch_ct_mold_v(int sel_type, struct CT_MOLD_V_TAG *CT_MOLD_V);
extern void   DBU_close_ct_mold_v(int sel_type);


#endif               /* __DBU_CT_MOLD_V_LOADED */

