/*********************************************************************
**
**    File Name   : DBU_mwipcaldef_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-06 13:28:37
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MWIPCALDEF_N_LOADED
#define __DBU_MWIPCALDEF_N_LOADED




#endif               /* __DBU_MWIPCALDEF_N_LOADED */

