/*********************************************************************
**
**    File Name   : DBU_cqcmcusspe_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2025-01-02 14:15:29
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2025 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMCUSSPE_N_LOADED
#define __DBU_CQCMCUSSPE_N_LOADED


struct CQCMCUSSPE_N_TAG
{
    char          FACTORY[11];
    char          REPORT_NO[21];
    char          REPORT_TYPE[11];
    char          CUST_NO[101];
    char          CUST_NAME[101];
    char          SAL_GROUP[21];
    char          CREATE_DATE[9];
    char          GRADE[21];
    char          DATA_01[101];
    char          DATA_02[101];
    char          DATA_03[101];
    char          DATA_04[101];
    char          DATA_05[101];
    char          DATA_06[101];
    char          DATA_07[101];
    char          DATA_08[101];
    char          DATA_09[101];
    char          DATA_10[101];
    char          DATA_11[101];
    char          DATA_12[101];
    char          DATA_13[101];
    char          DATA_14[101];
    char          DATA_15[101];
    char          DATA_16[101];
    char          DATA_17[101];
    char          DATA_18[101];
    char          DATA_19[101];
    char          DATA_20[101];
    char          DATA_21[101];
    char          DATA_22[101];
    char          DATA_23[101];
    char          DATA_24[101];
    char          DATA_25[101];
    char          DATA_26[101];
    char          DATA_27[101];
    char          DATA_28[101];
    char          DATA_29[101];
    char          DATA_30[101];
    char          FILE_NO_01[21];
    char          FILE_PATH_01[301];
    char          FILE_NO_02[21];
    char          FILE_PATH_02[301];
    char          FILE_NO_03[21];
    char          FILE_PATH_03[301];
    char          FILE_NO_04[21];
    char          FILE_PATH_04[301];
    char          FILE_NO_05[21];
    char          FILE_PATH_05[301];
    char          COMMENT_01[1001];
    char          COMMENT_02[1001];
    char          COMMENT_03[1001];
    char          COMMENT_04[1001];
    char          COMMENT_05[1001];
    char          COMMENT_06[1001];
    char          COMMENT_07[1001];
    char          COMMENT_08[1001];
    char          COMMENT_09[1001];
    char          COMMENT_10[1001];
    char          CMF_01[51];
    char          CMF_02[51];
    char          CMF_03[51];
    char          CMF_04[51];
    char          CMF_05[51];
    char          CMF_06[51];
    char          CMF_07[51];
    char          CMF_08[51];
    char          CMF_09[51];
    char          CMF_10[51];
    char          USE_YN[2];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CQCMCUSSPE_N_LOADED */

