/*********************************************************************
**
**    File Name   : DBU_medccolver_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-08 16:49:15
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MEDCCOLVER_N_LOADED
#define __DBU_MEDCCOLVER_N_LOADED

/*
struct MEDCCOLVER_N_TAG
{
    char          FACTORY[11];
    char          COL_SET_ID[26];
    int           COL_SET_VERSION;
    char          APPLY_START_TIME[15];
    char          APPLY_END_TIME[15];
    char          APPROVAL_FLAG[2];
    char          APPROVAL_USER_ID[21];
    char          APPROVAL_TIME[15];
    char          RELEASE_FLAG[2];
    char          RELEASE_USER_ID[21];
    char          RELEASE_TIME[15];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};
*/

#endif               /* __DBU_MEDCCOLVER_N_LOADED */

