/*********************************************************************
**
**    File Name   : DBU_ishplotrcv.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-01-04 13:34:06
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_ISHPLOTRCV_LOADED
#define __DBU_ISHPLOTRCV_LOADED


struct ISHPLOTRCV_TAG
{
    char          FACTORY[10];
    char          ORG_LOT_ID[25];
    char          PACK_LOT_ID[25];
    char          FROM_FACTORY[10];
    char          MAT_ID[30];
    int           MAT_VER;
    double        QTY;
    char          UNIT[10];
    char          PACK_ORDER_ID[25];
    int           PACK_LINE_NO;
    char          SHIP_DATE[14];
    char          SHIP_ORDER_ID[25];
    int           SHIP_ORDER_SEQ;
    char          CUSTOMER_ID[20];
    int           CUSTOMER_SITE_ID;
    char          CUSTOMER_NUMBER[30];
    char          CUSTOMER_NAME[50];
    char          DELIVERY[40];
    int           DELIVERY_ID;
    char          DELIVERY_NAME[40];
    char          DELIVERY_LOCATION[240];
    char          DELIVERY_PHONE_NO[150];
    char          DELIVERY_USER_ID[150];
    int           SHIPPING_LINE_ID;
    char          PRS_WORK_DATE[8];
    char          RES_ID[20];
    char          RES_DESC[200];
    int           RUN_COUNT;
    char          CELL_ID[25];
    int           MAPPING_SEQ;
    char          CAR[10];
    char          DAY_NIGHT;
    char          PRS_TRAN_TIME[14];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
	char		  RECEIVE_FLAG;
	char		  DELETE_FLAG;
};


/* Function Declaration */
extern void   DBU_init_ishplotrcv(struct ISHPLOTRCV_TAG *ISHPLOTRCV);
extern void   DBU_select_ishplotrcv(int sel_type, struct ISHPLOTRCV_TAG *ISHPLOTRCV);
extern void   DBU_select_ishplotrcv_for_update(int sel_type, struct ISHPLOTRCV_TAG *ISHPLOTRCV);
extern double DBU_select_ishplotrcv_scalar(int sel_type, struct ISHPLOTRCV_TAG *ISHPLOTRCV);
extern void   DBU_delete_ishplotrcv(int sel_type, struct ISHPLOTRCV_TAG *ISHPLOTRCV);
extern void   DBU_insert_ishplotrcv(struct ISHPLOTRCV_TAG *ISHPLOTRCV);
extern void   DBU_update_ishplotrcv(int sel_type, struct ISHPLOTRCV_TAG *ISHPLOTRCV);
extern void   DBU_open_ishplotrcv(int sel_type, struct ISHPLOTRCV_TAG *ISHPLOTRCV);
extern void   DBU_fetch_ishplotrcv(int sel_type, struct ISHPLOTRCV_TAG *ISHPLOTRCV);
extern void   DBU_close_ishplotrcv(int sel_type);


#endif               /* __DBU_ISHPLOTRCV_LOADED */

