/*********************************************************************
**
**    File Name   : DBU_cwipdwnsts.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-27 14:03:29
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPDWNSTS_LOADED
#define __DBU_CWIPDWNSTS_LOADED


struct CWIPDWNSTS_TAG
{
    char          FACTORY[10];
    char          FLOW[20];
    char          OPER[10];
    char          RES_ID[20];
    int           HIST_SEQ;
    int           SEQ;
    char          AREA_ID[30];
    char          SUB_AREA_ID[30];
    char          ORDER_ID[25];
    char          DOWN_CODE[30];
    char          DOWN_TYPE_1[30];
    char          DOWN_TYPE_2[30];
    char          DOWN_TYPE_3[30];
    char          DOWN_START_DATE[8];
    char          DOWN_START_DAY_NIGHT[10];
    char          DOWN_START_TIME[14];
    char          DOWN_END_DATE[8];
    char          DOWN_END_DAY_NIGHT[10];
    char          DOWN_END_TIME[14];
    char          DOWN_STATUS;
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwipdwnsts(struct CWIPDWNSTS_TAG *CWIPDWNSTS);
extern void   DBU_select_cwipdwnsts(int sel_type, struct CWIPDWNSTS_TAG *CWIPDWNSTS);
extern void   DBU_select_cwipdwnsts_for_update(int sel_type, struct CWIPDWNSTS_TAG *CWIPDWNSTS);
extern double DBU_select_cwipdwnsts_scalar(int sel_type, struct CWIPDWNSTS_TAG *CWIPDWNSTS);
extern void   DBU_delete_cwipdwnsts(int sel_type, struct CWIPDWNSTS_TAG *CWIPDWNSTS);
extern void   DBU_insert_cwipdwnsts(struct CWIPDWNSTS_TAG *CWIPDWNSTS);
extern void   DBU_update_cwipdwnsts(int sel_type, struct CWIPDWNSTS_TAG *CWIPDWNSTS);
extern void   DBU_open_cwipdwnsts(int sel_type, struct CWIPDWNSTS_TAG *CWIPDWNSTS);
extern void   DBU_fetch_cwipdwnsts(int sel_type, struct CWIPDWNSTS_TAG *CWIPDWNSTS);
extern void   DBU_close_cwipdwnsts(int sel_type);


#endif               /* __DBU_CWIPDWNSTS_LOADED */

