/*********************************************************************
**
**    File Name   : DBU_cbascptdef_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-06-18 17:02:37
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CBASCPTDEF_N_LOADED
#define __DBU_CBASCPTDEF_N_LOADED


struct CBASCPTDEF_N_TAG
{
    char          CAPTION_TYPE[11];
    char          CAPTION_KEY[1001];
    char          CAPTION_MSG_1[1001];
    char          CAPTION_MSG_2[1001];
    char          CAPTION_MSG_3[1001];
    char          CAPTION_MSG_4[1001];
    char          CAPTION_MSG_5[1001];
    char          CAPTION_CMF_1[31];
    char          CAPTION_CMF_2[31];
    char          CAPTION_CMF_3[31];
    char          CAPTION_CMF_4[31];
    char          CAPTION_CMF_5[31];
    char          CAPTION_CMF_6[31];
    char          CAPTION_CMF_7[31];
    char          CAPTION_CMF_8[31];
    char          CAPTION_CMF_9[31];
    char          CAPTION_CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CBASCPTDEF_N_LOADED */

