/*********************************************************************
**
**    File Name   : DBU_if_pack_info_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-23 15:41:48
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_PACK_INFO_N_LOADED
#define __DBU_IF_PACK_INFO_N_LOADED


struct IF_PACK_INFO_N_TAG
{
	int           IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	int           OU_ID;
	int           ORG_ID;
	char          ORG_CODE[4];
	int           ORDER_HEADER_ID;
	int           ORDER_NUMBER;
	int           LINE_NUMBER;
	int           ORDER_TYPE_ID;
	char          ORDERED_DATE[15];
	char          BOOKED_DATE[4];
	int           ITEM_ID;
	char          ITEM_CODE[41];
	char          ITEM_DESC[241];
	char          LABEL_NAME[1001];
	int           CUSTOMER_ID;
	char          CUSTOMER_NUMBER[31];
	char          CUSTOMER_NAME[51];
	int           SHIP_TO_SITE_USE_ID;
	char          SHIP_TO_NAME[41];
	int           END_SHIP_TO_ID;
	char          END_SHIP_TO_NAME[241];
	char          DRAWING_FLAG[2001];
	char          PACKING_INSTRUCTIONS[2001];
	char          ORDER_TYPE[31];
	char          REQUEST_DATE[15];
	char          SCHEDULE_SHIP_DATE[15];
	char          SCHEDULE_ARRIVAL_DATE[15];
	char          PROMISE_DATE[15];
	char          INCLUDE_INSPECTION[241];
	char          LABEL_TYPE[241];
	char          LABEL_MESH[241];
	char          LINE_DESC[241];
	char          ORDER_UNIT[4];
	char          CURRENCY_CODE[16];
	double        ORDERED_QTY;
	double        SHIPED_QTY;
	double        CANCELED_QTY;
	double        UNIT_SELLING_PRICE;
	double        UNIT_SELLING_PRICE_KR;
	char          ALLOCATE_FLAG[241];
	char          CUSTOMER_PO_NO[241];
	char          CUST_ITME_NAME[241];
	char          CUST_ITEM_TYPE[241];
	char          REST[241];
	char          CUSTOMER_PO_LINE[241];
	char          FORMAT_ID[241];
	char          CUSTOMER_PO[241];
	char          PO_GUBUN[241];
	char          TRAN_FLAG[2];
	int           IF_GROUP_ID;
	char          CMF_2[51];
	char          CMF_3[51];
	char          CMF_4[51];
	char          CMF_5[51];
	char          CMF_6[51];
	char          CMF_7[51];
	char          CMF_8[51];
	char          CMF_9[51];
	char          CMF_10[51];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_PACK_INFO_N_LOADED */

