/*********************************************************************
**
**    File Name   : DBU_mwipordsts.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-29 18:12:58
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MWIPORDSTS_LOADED
#define __DBU_MWIPORDSTS_LOADED

/*
struct MWIPORDSTS_TAG
{
    char          FACTORY[10];
    char          ORDER_ID[25];
    char          MAT_ID[30];
    int           MAT_VER;
    char          FLOW[20];
    int           FLOW_SEQ_NUM;
    double        ORD_QTY;
    char          RES_ID[20];
    char          BOM_SET_ID[25];
    int           BOM_SET_VERSION;
    char          CUSTOMER_ID[20];
    char          CUSTOMER_MAT_ID[30];
    char          WORK_DATE[8];
    char          PLAN_DUE_TIME[14];
    char          PLAN_START_TIME[14];
    char          PLAN_END_TIME[14];
    char          ORD_CMF_1[30];
    char          ORD_CMF_2[30];
    char          ORD_CMF_3[30];
    char          ORD_CMF_4[30];
    char          ORD_CMF_5[30];
    char          ORD_CMF_6[30];
    char          ORD_CMF_7[30];
    char          ORD_CMF_8[30];
    char          ORD_CMF_9[30];
    char          ORD_CMF_10[30];
    double        QTY;
    char          LOT_TYPE;
    char          OWNER_CODE[10];
    char          CREATE_CODE[10];
    char          LOT_PRIORITY;
    char          ORG_DUE_TIME[14];
    char          ORD_STATUS_FLAG;
    char          ORD_SHIP_FLAG;
    char          ORD_START_TIME[14];
    char          ORD_END_TIME[14];
    double        ORD_IN_QTY;
    double        ORD_OUT_QTY;
    double        ORD_LOSS_QTY;
    double        ORD_RWK_QTY;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
    char          ORDER_DESC[200];
};
*/

/* Function Declaration */
extern void   DBU_init_mwipordsts(struct MWIPORDSTS_TAG *MWIPORDSTS);
extern void   DBU_select_mwipordsts(int sel_type, struct MWIPORDSTS_TAG *MWIPORDSTS);
extern void   DBU_select_mwipordsts_for_update(int sel_type, struct MWIPORDSTS_TAG *MWIPORDSTS);
extern double DBU_select_mwipordsts_scalar(int sel_type, struct MWIPORDSTS_TAG *MWIPORDSTS);
extern void   DBU_delete_mwipordsts(int sel_type, struct MWIPORDSTS_TAG *MWIPORDSTS);
extern void   DBU_insert_mwipordsts(struct MWIPORDSTS_TAG *MWIPORDSTS);
extern void   DBU_update_mwipordsts(int sel_type, struct MWIPORDSTS_TAG *MWIPORDSTS);
extern void   DBU_open_mwipordsts(int sel_type, struct MWIPORDSTS_TAG *MWIPORDSTS);
extern void   DBU_fetch_mwipordsts(int sel_type, struct MWIPORDSTS_TAG *MWIPORDSTS);
extern void   DBU_close_mwipordsts(int sel_type);


#endif               /* __DBU_MWIPORDSTS_LOADED */

