/*********************************************************************
**
**    File Name   : DBU_minvdlvlbl.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-10 09:00:33
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MINVDLVLBL_LOADED
#define __DBU_MINVDLVLBL_LOADED


struct MINVDLVLBL_TAG
{
    char          FACTORY[10];
    char          DLV_LOT_ID[25];
    char          LABEL_ID[25];
    double        QTY;
    double        QTY_2;
	double        QTY_3;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_minvdlvlbl(struct MINVDLVLBL_TAG *MINVDLVLBL);
extern void   DBU_select_minvdlvlbl(int sel_type, struct MINVDLVLBL_TAG *MINVDLVLBL);
extern void   DBU_select_minvdlvlbl_for_update(int sel_type, struct MINVDLVLBL_TAG *MINVDLVLBL);
extern double DBU_select_minvdlvlbl_scalar(int sel_type, struct MINVDLVLBL_TAG *MINVDLVLBL);
extern void   DBU_delete_minvdlvlbl(int sel_type, struct MINVDLVLBL_TAG *MINVDLVLBL);
extern void   DBU_insert_minvdlvlbl(struct MINVDLVLBL_TAG *MINVDLVLBL);
extern void   DBU_update_minvdlvlbl(int sel_type, struct MINVDLVLBL_TAG *MINVDLVLBL);
extern void   DBU_open_minvdlvlbl(int sel_type, struct MINVDLVLBL_TAG *MINVDLVLBL);
extern void   DBU_fetch_minvdlvlbl(int sel_type, struct MINVDLVLBL_TAG *MINVDLVLBL);
extern void   DBU_close_minvdlvlbl(int sel_type);


#endif               /* __DBU_MINVDLVLBL_LOADED */

