/*********************************************************************
**
**    File Name   : DBU_cqcmcstspg_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-16 18:15:41
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMCSTSPG_N_LOADED
#define __DBU_CQCMCSTSPG_N_LOADED


struct CQCMCSTSPG_N_TAG
{
    char          FACTORY[11];
    char          INSP_TYPE[31];
    char          GRADE[31];
    char          DELIVERY_ID[21];
    char          DELIVERY_NAME[241];
    char          CHAR_ID[26];
    char          SPEC_TYPE[2];
    char          TARGET_VALUE[21];
    char          LOW_SPEC_LIMIT[21];
    char          UPPER_SPEC_LIMIT[21];
    char          CMF_1[51];
    char          CMF_2[51];
    char          CMF_3[51];
    char          CMF_4[51];
    char          CMF_5[51];
    char          CMF_6[51];
    char          CMF_7[51];
    char          CMF_8[51];
    char          CMF_9[51];
    char          CMF_10[51];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CQCMCSTSPG_N_LOADED */

