/*********************************************************************
**
**    File Name   : DBU_ct_mold_v_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-04 15:39:46
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CT_MOLD_V_N_LOADED
#define __DBU_CT_MOLD_V_N_LOADED


struct CT_MOLD_V_N_TAG
{
    char          ORG_CODE[4];
    char          LOT_ID[31];
    char          ITEM_CODE[31];
    int           REMAIN_QTY;
    char          WH_CODE[21];
    char          SUUPLIER_LOT_ID[31];
    char          REMARKS[1001];
    char          USE_YN[2];
    char          STATUS[3];
    char          TRANS_MASTER_SEQ[31];
    char          DA_MODELS[11];
    char          DA_TYPE[6];
};


#endif               /* __DBU_CT_MOLD_V_N_LOADED */

