/*********************************************************************
**
**    File Name   : DBU_minvlothis.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-31 16:58:56
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MINVLOTHIS_LOADED
#define __DBU_MINVLOTHIS_LOADED


struct MINVLOTHIS_TAG
{
    char          FACTORY[10];
    char          INV_LOT_ID[25];
    int           HIST_SEQ;
    char          INV_LOT_DESC[200];
    char          INV_LOT_TYPE[20];
    char          TRAN_CODE[12];
    char          TRAN_USER_ID[20];
    char          TRAN_TIME[14];
    char          SYS_TRAN_TIME[14];
    char          TRAN_COMMENT[400];
    char          INV_LOT_STATUS[10];
    char          INV_LOT_PRIORITY;
    char          MAT_ID[30];
    int           MAT_VER;
    double        QTY;
    double        QTY_2;
    double        QTY_3;
    char          UNIT[10];
    char          UNIT_2[10];
    char          UNIT_3[10];
    char          ORDER_ID[25];
    char          ADD_ORDER_ID_1[25];
    char          ADD_ORDER_ID_2[25];
    char          ADD_ORDER_ID_3[25];
    char          VENDOR_ID[20];
	int			  VENDOR_SITE_ID;
    char          VENDOR_LOT_ID[50];
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          LOCATION_1[20];
    char          LOCATION_2[20];
    char          LOCATION_3[20];
    char          OPER[10];
    char          LOC_NO[30];
    char          RES_ID[20];
    char          PORT_ID[10];
    char          SLOT_NO[10];
    char          CRR_ID[20];
    char          LOT_ID[25];
    char          RECV_DATE[8];
    double        RECV_QTY;
    char          REASON_CODE[30];
    char          LOAD_FLAG;
    char          TRANSIT_FLAG;
    char          DELETE_FLAG;
    char          DELETE_CODE[30];
    char          DELETE_TIME[14];
    char          HOLD_FLAG;
    char          HOLD_CODE[30];
    char          INSP_FLAG;
    char          INSP_ID[30];
    char          INSP_RESULT_FLAG;
    char          INV_LOT_GRADE[10];
    char          DLV_NO[30];
	int           DLV_SEQ;
    char          PO_NO[30];
    int           PO_SEQ;
    char          BL_NO[30];
    int           BL_SEQ;
	int			  PO_DISTRIBUTION_ID;
    char          INV_CMF_1[30];
    char          INV_CMF_2[30];
    char          INV_CMF_3[30];
    char          INV_CMF_4[30];
    char          INV_CMF_5[30];
    char          INV_CMF_6[30];
    char          INV_CMF_7[30];
    char          INV_CMF_8[30];
    char          INV_CMF_9[30];
    char          INV_CMF_10[30];
    char          INV_CMF_11[30];
    char          INV_CMF_12[30];
    char          INV_CMF_13[30];
    char          INV_CMF_14[30];
    char          INV_CMF_15[30];
    char          INV_CMF_16[30];
    char          INV_CMF_17[30];
    char          INV_CMF_18[30];
    char          INV_CMF_19[30];
    char          INV_CMF_20[30];
    char          TRAN_CMF_1[30];
    char          TRAN_CMF_2[30];
    char          TRAN_CMF_3[30];
    char          TRAN_CMF_4[30];
    char          TRAN_CMF_5[30];
    char          TRAN_CMF_6[30];
    char          TRAN_CMF_7[30];
    char          TRAN_CMF_8[30];
    char          TRAN_CMF_9[30];
    char          TRAN_CMF_10[30];
    char          ORG_INV_LOT_ID[25];
    char          FROM_TO_DIV;
    char          FROM_TO_INV_LOT_ID[25];
    int           FROM_TO_HIST_SEQ;
    int           OLD_ACTIVE_HIST_SEQ;
    char          OLD_FACTORY[10];
    char          OLD_MAT_ID[30];
	char          OLD_AREA_ID[20];
	char          OLD_SUB_AREA_ID[20];
    char          OLD_OPER[10];
    double        OLD_QTY;
    double        OLD_QTY_2;
    double        OLD_QTY_3;
    char          OLD_UNIT[10];
    char          OLD_UNIT_2[10];
    char          OLD_UNIT_3[10];
    double        CHANGE_QTY;
    double        CHANGE_QTY_2;
    double        CHANGE_QTY_3;
    double        CREATE_QTY;
    double        CREATE_QTY_2;
    double        CREATE_QTY_3;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
    char          HIST_DEL_FLAG;
    char          HIST_DEL_USER_ID[20];
    char          HIST_DEL_TIME[14];
    char          HIST_DEL_COMMENT[400];
};


/* Function Declaration */
extern void   DBU_init_minvlothis(struct MINVLOTHIS_TAG *MINVLOTHIS);
extern void   DBU_select_minvlothis(int sel_type, struct MINVLOTHIS_TAG *MINVLOTHIS);
extern void   DBU_select_minvlothis_for_update(int sel_type, struct MINVLOTHIS_TAG *MINVLOTHIS);
extern double DBU_select_minvlothis_scalar(int sel_type, struct MINVLOTHIS_TAG *MINVLOTHIS);
extern void   DBU_delete_minvlothis(int sel_type, struct MINVLOTHIS_TAG *MINVLOTHIS);
extern void   DBU_insert_minvlothis(struct MINVLOTHIS_TAG *MINVLOTHIS);
extern void   DBU_update_minvlothis(int sel_type, struct MINVLOTHIS_TAG *MINVLOTHIS);
extern void   DBU_open_minvlothis(int sel_type, struct MINVLOTHIS_TAG *MINVLOTHIS);
extern void   DBU_fetch_minvlothis(int sel_type, struct MINVLOTHIS_TAG *MINVLOTHIS);
extern void   DBU_close_minvlothis(int sel_type);


#endif               /* __DBU_MINVLOTHIS_LOADED */

