/*********************************************************************
**
**    File Name   : DBU_cbasfildef_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-28 13:44:38
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CBASFILDEF_N_LOADED
#define __DBU_CBASFILDEF_N_LOADED


struct CBASFILDEF_N_TAG
{
    char          FACTORY[11];
    char          FILE_NO[21];
    char          FILE_TYPE[11];
    char          FILE_NAME[101];
    char          FILE_PATH[201];
	char		  TO_FILE_PATH[201];
    char          AREA_ID[21];
    char          SUB_AREA_ID[21];
    char          OPER[11];
    char          RES_ID[21];
    char          TOOL_ID[31];
    char          MAT_ID[31];
    char          INSP_ID[21];
    char          LOT_ID[26];
    int           LOT_HIST_SEQ;
    int           ROUND_FILE_SEQ;
    char          ROUND_IMG_TYPE[21];
    char          REAL_COORDINATE_X[21];
    char          REAL_COORDINATE_Y[21];
    char          IMG_COORDINATE_X[21];
    char          IMG_COORDINATE_Y[21];
    char          SCULPTURE_IMG_PATH[201];
    char          CAMERA_TYPE[21];
    double        SIZE_1;
    double        SIZE_2;
    unsigned char IMAGE_DATA[2048001];
    int           IMAGE_SIZE;
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CBASFILDEF_N_LOADED */

