/*********************************************************************
**
**    File Name   : DBU_cqcmrptgrm_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-10 18:12:51
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTGRM_N_LOADED
#define __DBU_CQCMRPTGRM_N_LOADED


struct CQCMRPTGRM_N_TAG
{
    char          FACTORY[11];
    char          REPORT_NO[21];
    char          LOT_ID[21];
    char          ITEM_CODE[21];
    char          GRADE[21];
    char          SIZES[21];
    char          HEADER_ID[21];
    int           LINE_NUMBER;
    char          CUST_NO[31];
    char          CUST_NAME[101];
    char          REPORT_DATE[9];
    char          INSP_VALUE[21];
    char          SHIP_NAME[101];
    char          WT[21];
    char          MEAN[21];
    char          SD[21];
    char          LP[21];
    char          ELEC_CONDUCTIVITY[21];
    char          VOL_STATIC01[21];
    char          VOL_STATIC02[21];
    char          VOL_STATIC03[21];
    char          VOL_STATIC04[21];
    char          VOL_STATIC05[21];
    char          VOL_STATIC06[21];
    char          VOL_STATIC07[21];
    char          VOL_STATIC08[21];
    char          VOL_STATIC09[21];
    char          IMAGE01[21];
    char          IMAGE02[21];
    char          IMAGE03[21];
    char          IMAGE04[21];
    char          IMAGE05[21];
    char          ANALYZER[21];
    char          WT_CHK[21];
    char          MEAN_CHK[21];
    char          SD_CHK[21];
    char          LP_CHK[21];
    char          ELEC_CONDUCTIVITY_CHK[6];
    char          VOL_STATIC01_CHK[6];
    char          VOL_STATIC02_CHK[6];
    char          VOL_STATIC03_CHK[6];
    char          VOL_STATIC04_CHK[6];
    char          VOL_STATIC05_CHK[6];
    char          VOL_STATIC06_CHK[6];
    char          VOL_STATIC07_CHK[6];
    char          VOL_STATIC08_CHK[6];
    char          VOL_STATIC09_CHK[6];
    char          IMAGE01_CHK[6];
    char          IMAGE02_CHK[6];
    char          IMAGE03_CHK[6];
    char          IMAGE04_CHK[6];
    char          IMAGE05_CHK[6];
    char          ATTRIBUTE01[51];
    char          ATTRIBUTE02[51];
    char          ATTRIBUTE03[51];
    char          ATTRIBUTE04[51];
    char          ATTRIBUTE05[51];
    char          ATTRIBUTE06[51];
    char          ATTRIBUTE07[51];
    char          ATTRIBUTE08[51];
    char          ATTRIBUTE09[51];
    char          ATTRIBUTE10[51];
    char          REMARKS[101];
    char          USE_YN[2];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
    char          SUB_IMAGE01[21];
    char          SUB_IMAGE02[21];
    char          SUB_IMAGE03[21];
    char          SUB_IMAGE04[21];
    char          SUB_IMAGE05[21];
    char          SUB_IMAGE06[21];
    char          RPT_CMF_1[51];
    char          RPT_CMF_2[51];
    char          RPT_CMF_3[51];
    char          RPT_CMF_4[51];
    char          RPT_CMF_5[51];
    char          RPT_CMF_6[51];
    char          RPT_CMF_7[51];
    char          RPT_CMF_8[51];
    char          RPT_CMF_9[51];
    char          RPT_CMF_10[51];
    char          RPT_CMF_11[51];
    char          RPT_CMF_12[51];
    char          RPT_CMF_13[51];
    char          RPT_CMF_14[51];
    char          RPT_CMF_15[51];
};


#endif               /* __DBU_CQCMRPTGRM_N_LOADED */

