/*********************************************************************
**
**    File Name   : DBU_if_po_info_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-14 16:34:22
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_PO_INFO_N_LOADED
#define __DBU_IF_PO_INFO_N_LOADED


struct IF_PO_INFO_N_TAG
{
	int           IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	char          SHIPMENT_TYPE[26];
	int           ORG_ID;
	char          ORG_CODE[4];
	int           SHIP_TO_LOCATION_ID;
	char          SHIP_TO_LOCATION_CODE[61];
	int           VENDOR_ID;
	int           VENDOR_SITE_ID;
	char          VENDOR_CODE[31];
	char          VENDOR_NAME[241];
	int           PO_HEADER_ID;
	int           PO_LINE_ID;
	int           PO_RELEASE_ID;
	int           LINE_LOCATION_ID;
	int           PO_DISTRIBUTION_ID;
	char          PO_NUM[21];
	int           REVISION_NUM;
	int           LINE_NUM;
	int           RELEASE_NUM;
	int           SHIPMENT_NUM;
	int           INVENTORY_ITEM_ID;
	char          ITEM_CODE[41];
	char          ITEM_DESC[241];
	char          ITEM_UNIT[4];
	char          PO_UNIT[4];
	char          PO_DATE[15];
	char          NEED_BY_DATE[15];
	double        ORDER_QTY;
	double        DELIVERY_QTY;
	double        REMAIN_QTY;
	double        QTY_RCV_TOLERANCE;
	char          INSPECT_FLAG[2];
	char          PLLA_CANCEL_FLAG[2];
	char          PLA_CANCEL_FLAG[2];
	char          PHA_CANCEL_FLAG[2];
	char          PO_TYPE[26];
	int           WIP_ENTITY_ID;
	char          WIP_ENTITY_NAME[241];
	int           OPER_SEQ;
	int           STD_OPER_ID;
	char          OPER[11];
	char          OPER_DESC[241];
	char          CONSIGNMENT_FLAG[151];
	char          APPROVED_FLAG_HEADER[2];
	char          APPROVED_FLAG_LOCATION[2];
	char          APPROVED_DATE_HEADER[15];
	char          APPROVED_DATE_LOCATION[15];
	char          CLOSED_CODE_HEADER[31];
	char          CLOSED_CODE_LOCATION[31];
	char          USER_HOLD_FLAG[2];
	char          FROZEN_FLAG[2];
	char          TRAN_FLAG[2];
	char          CMF_1[51];
	char          CMF_2[51];
	char          CMF_3[51];
	char          CMF_4[51];
	char          CMF_5[51];
	char          CMF_6[51];
	char          CMF_7[51];
	char          CMF_8[51];
	char          CMF_9[51];
	char          CMF_10[51];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_PO_INFO_N_LOADED */

