/*********************************************************************
**
**    File Name   : DBU_if_p_wo_info.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-25 19:15:45
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_P_WO_INFO_LOADED
#define __DBU_IF_P_WO_INFO_LOADED


struct IF_P_WO_INFO_TAG
{
	int           IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	int           ORG_ID;
	char          ORG_CODE[3];
	int           WIP_ENTITY_ID;
	char          WIP_ENTITY_NAME[240];
	int           ITEM_ID;
	char          ITEM_CODE[40];
	char          ITEM_DESC[240];
	char          ITEM_UNIT[3];
	char          ITEM_TYPE[30];
	double        REMAIN_QTY;
	char          ENABLED_FLAG;
	char          TRAN_FLAG;
	int           IF_GROUP_ID;
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_p_wo_info(struct IF_P_WO_INFO_TAG *IF_P_WO_INFO);
extern void   DBU_select_if_p_wo_info(int sel_type, struct IF_P_WO_INFO_TAG *IF_P_WO_INFO);
extern void   DBU_select_if_p_wo_info_for_update(int sel_type, struct IF_P_WO_INFO_TAG *IF_P_WO_INFO);
extern double DBU_select_if_p_wo_info_scalar(int sel_type, struct IF_P_WO_INFO_TAG *IF_P_WO_INFO);
extern void   DBU_delete_if_p_wo_info(int sel_type, struct IF_P_WO_INFO_TAG *IF_P_WO_INFO);
extern void   DBU_insert_if_p_wo_info(struct IF_P_WO_INFO_TAG *IF_P_WO_INFO);
extern void   DBU_update_if_p_wo_info(int sel_type, struct IF_P_WO_INFO_TAG *IF_P_WO_INFO);
extern void   DBU_open_if_p_wo_info(int sel_type, struct IF_P_WO_INFO_TAG *IF_P_WO_INFO);
extern void   DBU_fetch_if_p_wo_info(int sel_type, struct IF_P_WO_INFO_TAG *IF_P_WO_INFO);
extern void   DBU_close_if_p_wo_info(int sel_type);


#endif               /* __DBU_IF_P_WO_INFO_LOADED */

