/*********************************************************************
**
**    File Name   : DBU_minvreqdtl_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-18 09:20:15
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MINVREQDTL_N_LOADED
#define __DBU_MINVREQDTL_N_LOADED


struct MINVREQDTL_N_TAG
{
    char          FACTORY[11];
    char          REQ_NO[31];
    char          REQ_MAT_ID[31];
    int           REQ_MAT_VER;
    double        REQ_QTY;
    char          UNIT[11];
    char          REQ_STATUS[11];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_MINVREQDTL_N_LOADED */

