/*********************************************************************
**
**    File Name   : DBU_cwiperpopr_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-16 21:39:39
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPERPOPR_N_LOADED
#define __DBU_CWIPERPOPR_N_LOADED


struct CWIPERPOPR_N_TAG
{
	char          FACTORY[11];
	char          AREA_ID[21];
	char          SUB_AREA_ID[21];
	char          ORDER_ID[26];
	int           OPER_SEQ;
	char          OPER[31];
	char          OPER_DESC[241];
	char          INV_OPER[11];
	int           PREV_OPER_SEQ;
	char          PREV_OPER[11];
	int           NEXT_OPER_SEQ;
	char          NEXT_OPER[11];
	char          FIRST_FLAG[2];
	char          LAST_FLAG[2];
	char          CMF_1[31];
	char          CMF_2[31];
	char          CMF_3[31];
	char          CMF_4[31];
	char          CMF_5[31];
	char          CMF_6[31];
	char          CMF_7[31];
	char          CMF_8[31];
	char          CMF_9[31];
	char          CMF_10[31];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPERPOPR_N_LOADED */

