/*********************************************************************
**
**    File Name   : DBU_cshpordmst.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-25 14:47:30
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CSHPORDMST_LOADED
#define __DBU_CSHPORDMST_LOADED


struct CSHPORDMST_TAG
{
    char          FACTORY[10];
    char          SHIP_ORDER_ID[25];
    char          SHIP_ORD_DATE[14];
    char          CUSTOMER_ID[20];
	char		  CUSTOMER_NUMBER[30];
	char		  CUSTOMER_NAME[50];
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          OPER[10];
	char		  DELIVERY[40];
    int	          DELIVERY_ID;
	char		  DELIVERY_NAME[40];
    char          DELIVERY_LOCATION[240];
    char          DELIVERY_PHONE_NO[150];
    char          DELIVERY_USER_ID[150];
    char          SHIP_ORD_STATUS[10];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
	char		  DELETE_FLAG;
};


/* Function Declaration */
extern void   DBU_init_cshpordmst(struct CSHPORDMST_TAG *CSHPORDMST);
extern void   DBU_select_cshpordmst(int sel_type, struct CSHPORDMST_TAG *CSHPORDMST);
extern void   DBU_select_cshpordmst_for_update(int sel_type, struct CSHPORDMST_TAG *CSHPORDMST);
extern double DBU_select_cshpordmst_scalar(int sel_type, struct CSHPORDMST_TAG *CSHPORDMST);
extern void   DBU_delete_cshpordmst(int sel_type, struct CSHPORDMST_TAG *CSHPORDMST);
extern void   DBU_insert_cshpordmst(struct CSHPORDMST_TAG *CSHPORDMST);
extern void   DBU_update_cshpordmst(int sel_type, struct CSHPORDMST_TAG *CSHPORDMST);
extern void   DBU_open_cshpordmst(int sel_type, struct CSHPORDMST_TAG *CSHPORDMST);
extern void   DBU_fetch_cshpordmst(int sel_type, struct CSHPORDMST_TAG *CSHPORDMST);
extern void   DBU_close_cshpordmst(int sel_type);


#endif               /* __DBU_CSHPORDMST_LOADED */

