/*********************************************************************
**
**    File Name   : DBU_cwipinvlod.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-10 15:06:29
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPINVLOD_LOADED
#define __DBU_CWIPINVLOD_LOADED


struct CWIPINVLOD_TAG
{
    char          FACTORY[10];
    char          INV_LOT_ID[25];
    char          AREA_ID[30];
    char          SUB_AREA_ID[30];
    char          FLOW[20];
    char          OPER[10];
    char          ORDER_ID[25];
    char          RES_ID[20];
    char          TRAN_TIME[14];
    char          MAT_ID[30];
    int           MAT_VER;
    char          OUT_OPER[20];
    char          LOT_TYPE[10];
    char          INPUT_TYPE[10];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwipinvlod(struct CWIPINVLOD_TAG *CWIPINVLOD);
extern void   DBU_select_cwipinvlod(int sel_type, struct CWIPINVLOD_TAG *CWIPINVLOD);
extern void   DBU_select_cwipinvlod_for_update(int sel_type, struct CWIPINVLOD_TAG *CWIPINVLOD);
extern double DBU_select_cwipinvlod_scalar(int sel_type, struct CWIPINVLOD_TAG *CWIPINVLOD);
extern void   DBU_delete_cwipinvlod(int sel_type, struct CWIPINVLOD_TAG *CWIPINVLOD);
extern void   DBU_insert_cwipinvlod(struct CWIPINVLOD_TAG *CWIPINVLOD);
extern void   DBU_update_cwipinvlod(int sel_type, struct CWIPINVLOD_TAG *CWIPINVLOD);
extern void   DBU_open_cwipinvlod(int sel_type, struct CWIPINVLOD_TAG *CWIPINVLOD);
extern void   DBU_fetch_cwipinvlod(int sel_type, struct CWIPINVLOD_TAG *CWIPINVLOD);
extern void   DBU_close_cwipinvlod(int sel_type);


#endif               /* __DBU_CWIPINVLOD_LOADED */

