/*********************************************************************
**
**    File Name   : DBU_mwipflwopr.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-21 13:09:25
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MWIPFLWOPR_LOADED
#define __DBU_MWIPFLWOPR_LOADED

/*
struct MWIPFLWOPR_TAG
{
    char          FACTORY[10];
    char          FLOW[20];
    char          OPER[10];
    char          OPT_OPER_GROUP[20];
    char          OPT_OPER_OPTION_FLAG;
    int           SEQ_NUM;
    char          PREV_OPER[10];
    char          NEXT_OPER[10];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};
*/

/* Function Declaration */
extern void   DBU_init_mwipflwopr(struct MWIPFLWOPR_TAG *MWIPFLWOPR);
extern void   DBU_select_mwipflwopr(int sel_type, struct MWIPFLWOPR_TAG *MWIPFLWOPR);
extern void   DBU_select_mwipflwopr_for_update(int sel_type, struct MWIPFLWOPR_TAG *MWIPFLWOPR);
extern double DBU_select_mwipflwopr_scalar(int sel_type, struct MWIPFLWOPR_TAG *MWIPFLWOPR);
extern void   DBU_delete_mwipflwopr(int sel_type, struct MWIPFLWOPR_TAG *MWIPFLWOPR);
extern void   DBU_insert_mwipflwopr(struct MWIPFLWOPR_TAG *MWIPFLWOPR);
extern void   DBU_update_mwipflwopr(int sel_type, struct MWIPFLWOPR_TAG *MWIPFLWOPR);
extern void   DBU_open_mwipflwopr(int sel_type, struct MWIPFLWOPR_TAG *MWIPFLWOPR);
extern void   DBU_fetch_mwipflwopr(int sel_type, struct MWIPFLWOPR_TAG *MWIPFLWOPR);
extern void   DBU_close_mwipflwopr(int sel_type);


#endif               /* __DBU_MWIPFLWOPR_LOADED */

