/*********************************************************************
**
**    File Name   : DBU_csecusedat.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-01 15:01:37
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CSECUSEDAT_LOADED
#define __DBU_CSECUSEDAT_LOADED


struct CSECUSEDAT_TAG
{
    char          FACTORY[10];
    char          USE_DATE[8];
    char          PROGRAM_ID[50];
    char          USER_ID[20];
    char          PROGRAM_DESC[100];
    char          FUNC_NAME[12];
    char          PG_KIND[10];
    int           USE_COUNT;
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_csecusedat(struct CSECUSEDAT_TAG *CSECUSEDAT);
extern void   DBU_select_csecusedat(int sel_type, struct CSECUSEDAT_TAG *CSECUSEDAT);
extern void   DBU_select_csecusedat_for_update(int sel_type, struct CSECUSEDAT_TAG *CSECUSEDAT);
extern double DBU_select_csecusedat_scalar(int sel_type, struct CSECUSEDAT_TAG *CSECUSEDAT);
extern void   DBU_delete_csecusedat(int sel_type, struct CSECUSEDAT_TAG *CSECUSEDAT);
extern void   DBU_insert_csecusedat(struct CSECUSEDAT_TAG *CSECUSEDAT);
extern void   DBU_update_csecusedat(int sel_type, struct CSECUSEDAT_TAG *CSECUSEDAT);
extern void   DBU_open_csecusedat(int sel_type, struct CSECUSEDAT_TAG *CSECUSEDAT);
extern void   DBU_fetch_csecusedat(int sel_type, struct CSECUSEDAT_TAG *CSECUSEDAT);
extern void   DBU_close_csecusedat(int sel_type);


#endif               /* __DBU_CSECUSEDAT_LOADED */

