/*********************************************************************
**
**    File Name   : DBU_if_om_promise_date_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-01-05 12:38:27
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_OM_PROMISE_DATE_N_LOADED
#define __DBU_IF_OM_PROMISE_DATE_N_LOADED


struct IF_OM_PROMISE_DATE_N_TAG
{
	double        IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	int           TRAN_TYPE_ID;
	char          TRAN_TYPE[11];
	char          TRAN_TIME[15];
	char          TRAN_FLAG[2];
	int           HEADER_ID;
	int           LINE_NUMBER;
	char          PROMISE_DATE[15];
	char          CMF_1[151];
	char          CMF_2[151];
	char          CMF_3[151];
	char          CMF_4[151];
	char          CMF_5[151];
	char          CMF_6[151];
	char          CMF_7[151];
	char          CMF_8[151];
	char          CMF_9[151];
	char          CMF_10[151];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_OM_PROMISE_DATE_N_LOADED */

