/*********************************************************************
**
**    File Name   : DBU_cwiplotmov.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-13 10:04:33
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTMOV_LOADED
#define __DBU_CWIPLOTMOV_LOADED


struct CWIPLOTMOV_TAG
{
    char          FACTORY[10];
    char          MOVE_ID[20];
    char          LOT_ID[25];
    char          FROM_AREA_ID[20];
    char          FROM_SUB_AREA_ID[20];
    char          FROM_OPER[10];
    char          TO_AREA_ID[20];
    char          TO_SUB_AREA_ID[20];
    char          TO_OPER[10];
    char          MOVE_STATUS[10];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiplotmov(struct CWIPLOTMOV_TAG *CWIPLOTMOV);
extern void   DBU_select_cwiplotmov(int sel_type, struct CWIPLOTMOV_TAG *CWIPLOTMOV);
extern void   DBU_select_cwiplotmov_for_update(int sel_type, struct CWIPLOTMOV_TAG *CWIPLOTMOV);
extern double DBU_select_cwiplotmov_scalar(int sel_type, struct CWIPLOTMOV_TAG *CWIPLOTMOV);
extern void   DBU_delete_cwiplotmov(int sel_type, struct CWIPLOTMOV_TAG *CWIPLOTMOV);
extern void   DBU_insert_cwiplotmov(struct CWIPLOTMOV_TAG *CWIPLOTMOV);
extern void   DBU_update_cwiplotmov(int sel_type, struct CWIPLOTMOV_TAG *CWIPLOTMOV);
extern void   DBU_open_cwiplotmov(int sel_type, struct CWIPLOTMOV_TAG *CWIPLOTMOV);
extern void   DBU_fetch_cwiplotmov(int sel_type, struct CWIPLOTMOV_TAG *CWIPLOTMOV);
extern void   DBU_close_cwiplotmov(int sel_type);


#endif               /* __DBU_CWIPLOTMOV_LOADED */

