/*********************************************************************
**
**    File Name   : DBU_cwiplotbas.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-15 15:38:02
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTBAS_LOADED
#define __DBU_CWIPLOTBAS_LOADED


struct CWIPLOTBAS_TAG
{
    char          MASTER_LOT_ID[25];
    char          RES_ID[20];
    char          ORDER_ID[25];
    char          MAT_ID[30];
    char          FACTORY[10];
    int           LOT_QTY;
    char          RECIPE_ID[50];
    char          AUTO_FLAG;
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiplotbas(struct CWIPLOTBAS_TAG *CWIPLOTBAS);
extern void   DBU_select_cwiplotbas(int sel_type, struct CWIPLOTBAS_TAG *CWIPLOTBAS);
extern void   DBU_select_cwiplotbas_for_update(int sel_type, struct CWIPLOTBAS_TAG *CWIPLOTBAS);
extern double DBU_select_cwiplotbas_scalar(int sel_type, struct CWIPLOTBAS_TAG *CWIPLOTBAS);
extern void   DBU_delete_cwiplotbas(int sel_type, struct CWIPLOTBAS_TAG *CWIPLOTBAS);
extern void   DBU_insert_cwiplotbas(struct CWIPLOTBAS_TAG *CWIPLOTBAS);
extern void   DBU_update_cwiplotbas(int sel_type, struct CWIPLOTBAS_TAG *CWIPLOTBAS);
extern void   DBU_open_cwiplotbas(int sel_type, struct CWIPLOTBAS_TAG *CWIPLOTBAS);
extern void   DBU_fetch_cwiplotbas(int sel_type, struct CWIPLOTBAS_TAG *CWIPLOTBAS);
extern void   DBU_close_cwiplotbas(int sel_type);


#endif               /* __DBU_CWIPLOTBAS_LOADED */

