/*********************************************************************
**
**    File Name   : DBU_medccolver.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-08 16:49:15
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MEDCCOLVER_LOADED
#define __DBU_MEDCCOLVER_LOADED

/*
struct MEDCCOLVER_TAG
{
    char          FACTORY[10];
    char          COL_SET_ID[25];
    int           COL_SET_VERSION;
    char          APPLY_START_TIME[14];
    char          APPLY_END_TIME[14];
    char          APPROVAL_FLAG;
    char          APPROVAL_USER_ID[20];
    char          APPROVAL_TIME[14];
    char          RELEASE_FLAG;
    char          RELEASE_USER_ID[20];
    char          RELEASE_TIME[14];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};
*/

/* Function Declaration */
extern void   DBU_init_medccolver(struct MEDCCOLVER_TAG *MEDCCOLVER);
extern void   DBU_select_medccolver(int sel_type, struct MEDCCOLVER_TAG *MEDCCOLVER);
extern void   DBU_select_medccolver_for_update(int sel_type, struct MEDCCOLVER_TAG *MEDCCOLVER);
extern double DBU_select_medccolver_scalar(int sel_type, struct MEDCCOLVER_TAG *MEDCCOLVER);
extern void   DBU_delete_medccolver(int sel_type, struct MEDCCOLVER_TAG *MEDCCOLVER);
extern void   DBU_insert_medccolver(struct MEDCCOLVER_TAG *MEDCCOLVER);
extern void   DBU_update_medccolver(int sel_type, struct MEDCCOLVER_TAG *MEDCCOLVER);
extern void   DBU_open_medccolver(int sel_type, struct MEDCCOLVER_TAG *MEDCCOLVER);
extern void   DBU_fetch_medccolver(int sel_type, struct MEDCCOLVER_TAG *MEDCCOLVER);
extern void   DBU_close_medccolver(int sel_type);


#endif               /* __DBU_MEDCCOLVER_LOADED */

