/*********************************************************************
**
**    File Name   : DBU_if_so_mst.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-28 10:50:06
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_SO_MST_LOADED
#define __DBU_IF_SO_MST_LOADED


struct IF_SO_MST_TAG
{
	int           IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	int           SHIPPING_HEADER_ID;
	char          SHIPPING_HEADER_NUM[30];
	int           SHIP_TRX_ID;
	int           CUSTOMER_ID;
	char          CUSTOMER_NUMBER[30];
	char          CUSTOMER_NAME[50];
	char          SHIPPING_DATE[14];
	char          SHIPPING_STATUS;
	int           SHIP_FROM_ORG_ID;
	char          SHIP_FROM_ORG_NAME[3];
	int           SHIP_TO_ORG_ID;
	char          SHIP_TO_ORG_NAME[40];
	char          SHIP_TO_ADDRESS[240];
	int           INVOICE_TO_ORG_ID;
	char          INVOICE_TO_ORG_NAME[40];
	char          ATTRIBUTE1[150];
	char          ATTRIBUTE2[150];
	char          ATTRIBUTE3[150];
	char          ATTRIBUTE4[150];
	char          ATTRIBUTE5[150];
	char          MES_SHIPPING_YN;
	char          MES_SHIPPING_DATE[14];
	int           ORDER_NUMBER;
	int           PARTY_SITE_ID;
	int           CUST_ACCT_SITE_ID;
	char          CUST_PHONE_NUMBER[150];
	char          CUST_CONTACT_NAME[150];
	int           CREATED_BY;
	int           LAST_UPDATED_BY;
	int           LAST_UPDATE_LOGIN;
	char          TRAN_FLAG;
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_so_mst(struct IF_SO_MST_TAG *IF_SO_MST);
extern void   DBU_select_if_so_mst(int sel_type, struct IF_SO_MST_TAG *IF_SO_MST);
extern void   DBU_select_if_so_mst_for_update(int sel_type, struct IF_SO_MST_TAG *IF_SO_MST);
extern double DBU_select_if_so_mst_scalar(int sel_type, struct IF_SO_MST_TAG *IF_SO_MST);
extern void   DBU_delete_if_so_mst(int sel_type, struct IF_SO_MST_TAG *IF_SO_MST);
extern void   DBU_insert_if_so_mst(struct IF_SO_MST_TAG *IF_SO_MST);
extern void   DBU_update_if_so_mst(int sel_type, struct IF_SO_MST_TAG *IF_SO_MST);
extern void   DBU_open_if_so_mst(int sel_type, struct IF_SO_MST_TAG *IF_SO_MST);
extern void   DBU_fetch_if_so_mst(int sel_type, struct IF_SO_MST_TAG *IF_SO_MST);
extern void   DBU_close_if_so_mst(int sel_type);


#endif               /* __DBU_IF_SO_MST_LOADED */

