/*********************************************************************
**
**    File Name   : DBU_cwipgrtbld_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-01-18 11:55:48
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPGRTBLD_N_LOADED
#define __DBU_CWIPGRTBLD_N_LOADED


struct CWIPGRTBLD_N_TAG
{
    char          FACTORY[11];
    char          ORDER_ID[26];
    char          LOT_ID[26];
    char          OPER[11];
    double        QTY_1;
    char          MAT_ID[31];
    int           SHEET_NO;
    double        PSD_UP;
    double        SS;
    double        OS;
    double        PSD_LO;
    double        TI;
    double        BI;
    double        TTI;
    double        MA;
    double        HLT;
    double        EILLPT;
    double        BTI;
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPGRTBLD_N_LOADED */

