/*********************************************************************
**
**    File Name   : DBU_ct_sal110t_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-21 11:37:59
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CT_SAL110T_N_LOADED
#define __DBU_CT_SAL110T_N_LOADED


struct CT_SAL110T_N_TAG
{
    char          LOT_ID[31];
    int           LOT_SEQ;
    double        LOT_QTY;
    char          STATUS[3];
    char          USE_YN[2];
    int           ORDER_NUM;
    int           HEADER_ID;
    int           LINE_NUMBER;
    char          ITEM_NAME[101];
    char          LABEL_TYPE[51];
    char          LABEL_MESH[51];
    char          TRANS_SEQ[21];
    double        COATING_RATE;
    char          INSERT_DATE[15];
    char          INSERT_USER[21];
    char          UPDATE_DATE[15];
    char          UPDATE_USER[21];
    char          INCLUDE_INSPECTION[2];
    char          DRAWING_FLAG[2001];
    char          CUST_CODE[21];
    int           CUST_SITE_ID;
    int           END_CUST_ID;
};


#endif               /* __DBU_CT_SAL110T_N_LOADED */

