/*********************************************************************
**
**    File Name   : DBU_if_comp_issue_trx_save_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-09 01:57:58
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_COMP_ISSUE_TRX_SAVE_N_LOADED
#define __DBU_IF_COMP_ISSUE_TRX_SAVE_N_LOADED


struct IF_COMP_ISSUE_TRX_SAVE_N_TAG
{
	double        IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	int           TRAN_TYPE_ID;
	char          TRAN_TYPE[11];
	char          TRAN_TIME[15];
	char          TRAN_FLAG[2];
	int           ERP_ORDER_NUM;
	int           ERP_AREA_ID;
	char          AREA_ID[4];
	int           ERP_SUB_AREA_ID;
	char          SUB_AREA_ID[4];
	int           ERP_WO_ID;
	char          WO_ID[241];
	int           OPER_SEQ;
	char          OPER[11];
	char          INV_OPER[11];
	int           ERP_MAT_ID;
	char          MAT_ID[31];
	char          UNIT[4];
	double        QTY;
	double        TRAN_HEADER_ID;
	double        SRC_TRAN_ID;
	double        MMT_TRAN_ID;
	double        MMT_TRAN_HEADER_ID;
	char          CMF_1[51];
	char          CMF_2[51];
	char          CMF_3[51];
	char          CMF_4[51];
	char          CMF_5[51];
	char          CMF_6[51];
	char          CMF_7[51];
	char          CMF_8[51];
	char          CMF_9[51];
	char          CMF_10[51];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_COMP_ISSUE_TRX_SAVE_N_LOADED */

