/*********************************************************************
**
**    File Name   : DBU_cwipinvldm.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-17 14:28:40
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPINVLDM_LOADED
#define __DBU_CWIPINVLDM_LOADED


struct CWIPINVLDM_TAG
{
    char          FACTORY[10];
    char          REL_LEVEL;
    char          INV_LOT_ID[25];
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          FLOW[20];
    char          OPER[10];
    char          ORDER_ID[25];
    char          RES_ID[20];
    char          LOT_ID[25];
    double        BOM_QTY;
    double        QTY;
    char          TRAN_TIME[14];
    char          MAT_ID[30];
    int           MAT_VER;
    char          OUT_OPER[20];
    char          LOT_TYPE[10];
    char          INPUT_TYPE[10];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwipinvldm(struct CWIPINVLDM_TAG *CWIPINVLDM);
extern void   DBU_select_cwipinvldm(int sel_type, struct CWIPINVLDM_TAG *CWIPINVLDM);
extern void   DBU_select_cwipinvldm_for_update(int sel_type, struct CWIPINVLDM_TAG *CWIPINVLDM);
extern double DBU_select_cwipinvldm_scalar(int sel_type, struct CWIPINVLDM_TAG *CWIPINVLDM);
extern void   DBU_delete_cwipinvldm(int sel_type, struct CWIPINVLDM_TAG *CWIPINVLDM);
extern void   DBU_insert_cwipinvldm(struct CWIPINVLDM_TAG *CWIPINVLDM);
extern void   DBU_update_cwipinvldm(int sel_type, struct CWIPINVLDM_TAG *CWIPINVLDM);
extern void   DBU_open_cwipinvldm(int sel_type, struct CWIPINVLDM_TAG *CWIPINVLDM);
extern void   DBU_fetch_cwipinvldm(int sel_type, struct CWIPINVLDM_TAG *CWIPINVLDM);
extern void   DBU_close_cwipinvldm(int sel_type);


#endif               /* __DBU_CWIPINVLDM_LOADED */

