/*********************************************************************
**
**    File Name   : DBU_mwipcaldef.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-06 13:28:37
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MWIPCALDEF_LOADED
#define __DBU_MWIPCALDEF_LOADED



/* Function Declaration */
extern void   DBU_init_mwipcaldef(struct MWIPCALDEF_TAG *MWIPCALDEF);
extern void   DBU_select_mwipcaldef(int sel_type, struct MWIPCALDEF_TAG *MWIPCALDEF);
extern void   DBU_select_mwipcaldef_for_update(int sel_type, struct MWIPCALDEF_TAG *MWIPCALDEF);
extern double DBU_select_mwipcaldef_scalar(int sel_type, struct MWIPCALDEF_TAG *MWIPCALDEF);
extern void   DBU_delete_mwipcaldef(int sel_type, struct MWIPCALDEF_TAG *MWIPCALDEF);
extern void   DBU_insert_mwipcaldef(struct MWIPCALDEF_TAG *MWIPCALDEF);
extern void   DBU_update_mwipcaldef(int sel_type, struct MWIPCALDEF_TAG *MWIPCALDEF);
extern void   DBU_open_mwipcaldef(int sel_type, struct MWIPCALDEF_TAG *MWIPCALDEF);
extern void   DBU_fetch_mwipcaldef(int sel_type, struct MWIPCALDEF_TAG *MWIPCALDEF);
extern void   DBU_close_mwipcaldef(int sel_type);


#endif               /* __DBU_MWIPCALDEF_LOADED */

