/*********************************************************************
**
**    File Name   : DBU_ishprptrcv_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-05-14 11:16:14
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_ISHPRPTRCV_N_LOADED
#define __DBU_ISHPRPTRCV_N_LOADED


struct ISHPRPTRCV_N_TAG
{
    char          FACTORY[11];
    char          PACK_LOT_ID[26];
    char          ORG_LOT_ID[26];
    char          TO_FACTORY[11];
    char          PACK_ORDER_ID[26];
    int           PACK_LINE_NO;
    char          CUSTOMER_ID[201];
    char          SHIP_DATE[15];
    char          SHIP_ORDER_ID[26];
    int           SHIP_ORDER_SEQ;
    int           SHIPPING_LINE_ID;
    char          GRADE[31];
    char          TYPES[51];
    char          OD_STANDARD[31];
    char          OD_SPEC[31];
    char          OD_MIN_VAL[31];
    char          OD_MAX_VAL[31];
    char          AT_STANDARD[31];
    char          AT_SPEC[31];
    char          AT_MIN_VAL[31];
    char          AT_MAX_VAL[31];
    char          GT_STANDARD[31];
    char          GT_SPEC[31];
    char          GT_MIN_VAL[31];
    char          GT_MAX_VAL[31];
    char          LEN01_STANDARD[31];
    char          LEN01_SPEC[31];
    char          LEN_MIN_VAL01[31];
    char          LEN_MAX_VAL01[31];
    char          LEN02_STANDARD[31];
    char          LEN02_SPEC[31];
    char          LEN_MIN_VAL02[31];
    char          LEN_MAX_VAL02[31];
    char          DMG_STANDARD[31];
    char          DMG_SPEC[31];
    char          DMG_MIN_VAL[31];
    char          DMG_MAX_VAL[31];
    char          RECEIVE_FLAG[2];
    char          DELETE_FLAG[2];
    char          CMF_1[51];
    char          CMF_2[51];
    char          CMF_3[51];
    char          CMF_4[51];
    char          CMF_5[51];
    char          CMF_6[51];
    char          CMF_7[51];
    char          CMF_8[51];
    char          CMF_9[51];
    char          CMF_10[51];
    char          CMF_11[51];
    char          CMF_12[51];
    char          CMF_13[51];
    char          CMF_14[51];
    char          CMF_15[51];
    char          COMMENTS[101];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_ISHPRPTRCV_N_LOADED */

