/*********************************************************************
**
**    File Name   : DBU_cbaschkdef.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-08 09:58:43
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CBASCHKDEF_LOADED
#define __DBU_CBASCHKDEF_LOADED


struct CBASCHKDEF_TAG
{
    char          FACTORY[10];
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          OPER[10];
    char          MAT_ID[30];
    int           SEQ;
    char          CHK_COMMENT[2000];
    char          CHK_UNIT[30];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cbaschkdef(struct CBASCHKDEF_TAG *CBASCHKDEF);
extern void   DBU_select_cbaschkdef(int sel_type, struct CBASCHKDEF_TAG *CBASCHKDEF);
extern void   DBU_select_cbaschkdef_for_update(int sel_type, struct CBASCHKDEF_TAG *CBASCHKDEF);
extern double DBU_select_cbaschkdef_scalar(int sel_type, struct CBASCHKDEF_TAG *CBASCHKDEF);
extern void   DBU_delete_cbaschkdef(int sel_type, struct CBASCHKDEF_TAG *CBASCHKDEF);
extern void   DBU_insert_cbaschkdef(struct CBASCHKDEF_TAG *CBASCHKDEF);
extern void   DBU_update_cbaschkdef(int sel_type, struct CBASCHKDEF_TAG *CBASCHKDEF);
extern void   DBU_open_cbaschkdef(int sel_type, struct CBASCHKDEF_TAG *CBASCHKDEF);
extern void   DBU_fetch_cbaschkdef(int sel_type, struct CBASCHKDEF_TAG *CBASCHKDEF);
extern void   DBU_close_cbaschkdef(int sel_type);


#endif               /* __DBU_CBASCHKDEF_LOADED */

