/*********************************************************************
**
**    File Name   : DBU_if_so_mst_his_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-28 10:50:21
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_SO_MST_HIS_N_LOADED
#define __DBU_IF_SO_MST_HIS_N_LOADED


struct IF_SO_MST_HIS_N_TAG
{
	int           IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	int           SHIPPING_HEADER_ID;
	char          SHIPPING_HEADER_NUM[31];
	int           SHIP_TRX_ID;
	int           CUSTOMER_ID;
	char          CUSTOMER_NUMBER[31];
	char          CUSTOMER_NAME[51];
	char          SHIPPING_DATE[15];
	char          SHIPPING_STATUS[2];
	int           SHIP_FROM_ORG_ID;
	char          SHIP_FROM_ORG_NAME[4];
	int           SHIP_TO_ORG_ID;
	char          SHIP_TO_ORG_NAME[41];
	char          SHIP_TO_ADDRESS[241];
	int           INVOICE_TO_ORG_ID;
	char          INVOICE_TO_ORG_NAME[41];
	char          ATTRIBUTE1[151];
	char          ATTRIBUTE2[151];
	char          ATTRIBUTE3[151];
	char          ATTRIBUTE4[151];
	char          ATTRIBUTE5[151];
	char          MES_SHIPPING_YN[2];
	char          MES_SHIPPING_DATE[15];
	int           ORDER_NUMBER;
	int           PARTY_SITE_ID;
	int           CUST_ACCT_SITE_ID;
	char          CUST_PHONE_NUMBER[151];
	char          CUST_CONTACT_NAME[151];
	int           CREATED_BY;
	int           LAST_UPDATED_BY;
	int           LAST_UPDATE_LOGIN;
	char          TRAN_FLAG[2];
	char          CMF_1[51];
	char          CMF_2[51];
	char          CMF_3[51];
	char          CMF_4[51];
	char          CMF_5[51];
	char          CMF_6[51];
	char          CMF_7[51];
	char          CMF_8[51];
	char          CMF_9[51];
	char          CMF_10[51];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_SO_MST_HIS_N_LOADED */

