/*********************************************************************
**
**    File Name   : DBU_cwiplotcup.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-15 15:56:47
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTCUP_LOADED
#define __DBU_CWIPLOTCUP_LOADED


struct CWIPLOTCUP_TAG
{
    char          LOT_ID[25];
    int           HIST_SEQ;
    char          OPER[10];
    char          MAT_ID[30];
    char          FLOW[20];
    int           FLOW_SEQ_NUM;
    char          GRADE[50];
    char          RES_ID[20];
    char          FACTORY[10];
    char          WORK_DATE[8];
    char          WORK_TIME[14];
    char          DAY_NIGHT[10];
    int           EDC_HIST_SEQ;
    char          MASTER_LOT_ID[25];
    char          RECIPE_ID[50];
    char          START_TIME[14];
    char          END_TIME[14];
    char          JUDGMENT[10];
    char          INPUT_TIME[14];
    int           CUP_INPUT_COUNTER;
    char          CUP_TYPE[10];
    double        CUP_WEIGHT_STANDARD;
    double        CUP_WEIGHT_VALUE;
    char          POWDER_INJECTION_LOCATION[30];
    double        ROBOT_MEASURABLE_STANDARD;
    double        ROBOT_MEASURABLE_VALUE;
    double        PRECISION_WEIGH_STANDARD;
    double        PRECISION_WEIGH_VALUE;
    char          PRESS_TIME[30];
    int           NUMBER_OF_PRESSES;
    char          KNIFE_FLATTENING_USE[10];
    char          CARBIDE_TYPE[10];
    int           CARBIDE_SAMPLE_PASSED_NO;
    char          CARBIDE_SAMPLE_RESULT;
    double        CARBIDE_WEIGHT_STANDARD;
    double        CARBIDE_WEIGHT_VALUE;
    double        CARBIDE_HEIGHT_STANDARD;
    double        CARBIDE_HEIGHT_P1;
    double        CARBIDE_HEIGHT_P2;
    double        CARBIDE_HEIGHT_P3;
    double        CARBIDE_HEIGHT_P4;
    double        CARBIDE_HEIGHT_P5;
    double        CARBIDE_OUTER_DIAMETER_STANDARD;
    double        CARBIDE_OUTER_DIAMETER_VALUE;
    double        COMPLETE_FLATNESS_STANDARD;
    double        COMPLETE_FLATNESS_VALUE;
    double        COMPLETE_WEIGHT_STANDARD;
    double        COMPLETE_WEIGHT_VALUE;
    int           CARBIDE_INPUT_COUNT;
    int           IMPACT_PROCESS_INPUT_COUNT;
    int           NG_COUND;
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiplotcup(struct CWIPLOTCUP_TAG *CWIPLOTCUP);
extern void   DBU_select_cwiplotcup(int sel_type, struct CWIPLOTCUP_TAG *CWIPLOTCUP);
extern void   DBU_select_cwiplotcup_for_update(int sel_type, struct CWIPLOTCUP_TAG *CWIPLOTCUP);
extern double DBU_select_cwiplotcup_scalar(int sel_type, struct CWIPLOTCUP_TAG *CWIPLOTCUP);
extern void   DBU_delete_cwiplotcup(int sel_type, struct CWIPLOTCUP_TAG *CWIPLOTCUP);
extern void   DBU_insert_cwiplotcup(struct CWIPLOTCUP_TAG *CWIPLOTCUP);
extern void   DBU_update_cwiplotcup(int sel_type, struct CWIPLOTCUP_TAG *CWIPLOTCUP);
extern void   DBU_open_cwiplotcup(int sel_type, struct CWIPLOTCUP_TAG *CWIPLOTCUP);
extern void   DBU_fetch_cwiplotcup(int sel_type, struct CWIPLOTCUP_TAG *CWIPLOTCUP);
extern void   DBU_close_cwiplotcup(int sel_type);


#endif               /* __DBU_CWIPLOTCUP_LOADED */

