/*********************************************************************
**
**    File Name   : DBU_ishplotiss_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-01-04 13:33:50
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_ISHPLOTISS_N_LOADED
#define __DBU_ISHPLOTISS_N_LOADED


struct ISHPLOTISS_N_TAG
{
    char          FACTORY[11];
    char          ORG_LOT_ID[26];
    char          PACK_LOT_ID[26];
    char          IF_TIME[15];
    char          IF_CODE[2];
    char          IF_MSG[201];
    char          TO_FACTORY[11];
    char          MAT_ID[31];
    int           MAT_VER;
    double        QTY;
    char          UNIT[11];
    char          PACK_ORDER_ID[26];
    int           PACK_LINE_NO;
    char          SHIP_DATE[15];
    char          SHIP_ORDER_ID[26];
    int           SHIP_ORDER_SEQ;
    char          CUSTOMER_ID[21];
    int           CUSTOMER_SITE_ID;
    char          CUSTOMER_NUMBER[31];
    char          CUSTOMER_NAME[51];
    char          DELIVERY[41];
    int           DELIVERY_ID;
    char          DELIVERY_NAME[41];
    char          DELIVERY_LOCATION[241];
    char          DELIVERY_PHONE_NO[151];
    char          DELIVERY_USER_ID[151];
    int           SHIPPING_LINE_ID;
    char          PRS_WORK_DATE[9];
    char          RES_ID[21];
    char          RES_DESC[201];
    int           RUN_COUNT;
    char          CELL_ID[26];
    int           MAPPING_SEQ;
    char          CAR[11];
    char          DAY_NIGHT[2];
    char          PRS_TRAN_TIME[15];
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_ISHPLOTISS_N_LOADED */

