/*********************************************************************
**
**    File Name   : DBU_cwiplotrec_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-03 14:49:57
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTREC_N_LOADED
#define __DBU_CWIPLOTREC_N_LOADED


struct CWIPLOTREC_N_TAG
{
    char          FACTORY[11];
    char          LOT_ID[26];
    int           HIST_SEQ;
    char          AREA_ID[21];
    char          ORDER_ID[26];
    char          INV_OPER[11];
    char          TRAN_OPER[11];
    char          TRAN_FLOW[21];
    char          TRAN_TIME[15];
    char          WORK_DATE[9];
    char          MAT_ID[31];
    int           MAT_VER;
    char          UNIT[11];
    double        QTY;
    char          DELETE_FLAG[2];
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPLOTREC_N_LOADED */

