/*********************************************************************
**
**    File Name   : DBU_minvlotswh_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-31 16:59:36
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MINVLOTSWH_N_LOADED
#define __DBU_MINVLOTSWH_N_LOADED


struct MINVLOTSWH_N_TAG
{
    char          FACTORY[11];
    char          INV_LOT_ID[26];
    int           HIST_SEQ;
    char          TRAN_CODE[13];
    char          TRAN_USER_ID[21];
    char          TRAN_TIME[15];
    char          TRAN_COMMENT[401];
    char          MAT_ID[31];
    int           MAT_VER;
    double        QTY;
    double        QTY_2;
    double        QTY_3;
    char          UNIT[11];
    char          UNIT_2[11];
    char          UNIT_3[11];
    double        OLD_QTY;
    double        OLD_QTY_2;
    double        OLD_QTY_3;
    double        CHANGE_QTY;
    double        CHANGE_QTY_2;
    double        CHANGE_QTY_3;
    char          OPER[11];
    char          RES_ID[21];
    char          FROM_TO_DIV[2];
    char          FROM_TO_INV_LOT_ID[26];
    double        FROM_TO_QTY;
    double        FROM_TO_QTY_2;
    double        FROM_TO_QTY_3;
    char          HIST_DEL_FLAG[2];
};


#endif               /* __DBU_MINVLOTSWH_N_LOADED */

