/*********************************************************************
**
**    File Name   : DBU_cwipuoplot.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-06 17:47:05
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPUOPLOT_LOADED
#define __DBU_CWIPUOPLOT_LOADED


struct CWIPUOPLOT_TAG
{
    char          LOT_ID[25];
    int           LOT_SEQ;
    char          WH_CODE[20];
    char          MAT_ID[30];
    char          ORG_CODE[20];
    char          WC_CODE[20];
    char          FACTORY[10];
    double        REMAIN_QTY;
    char          USE_YN;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwipuoplot(struct CWIPUOPLOT_TAG *CWIPUOPLOT);
extern void   DBU_select_cwipuoplot(int sel_type, struct CWIPUOPLOT_TAG *CWIPUOPLOT);
extern void   DBU_select_cwipuoplot_for_update(int sel_type, struct CWIPUOPLOT_TAG *CWIPUOPLOT);
extern double DBU_select_cwipuoplot_scalar(int sel_type, struct CWIPUOPLOT_TAG *CWIPUOPLOT);
extern void   DBU_delete_cwipuoplot(int sel_type, struct CWIPUOPLOT_TAG *CWIPUOPLOT);
extern void   DBU_insert_cwipuoplot(struct CWIPUOPLOT_TAG *CWIPUOPLOT);
extern void   DBU_update_cwipuoplot(int sel_type, struct CWIPUOPLOT_TAG *CWIPUOPLOT);
extern void   DBU_open_cwipuoplot(int sel_type, struct CWIPUOPLOT_TAG *CWIPUOPLOT);
extern void   DBU_fetch_cwipuoplot(int sel_type, struct CWIPUOPLOT_TAG *CWIPUOPLOT);
extern void   DBU_close_cwipuoplot(int sel_type);


#endif               /* __DBU_CWIPUOPLOT_LOADED */

