/*********************************************************************
**
**    File Name   : DBU_cqcmgrtsiv.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-03 12:22:27
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMGRTSIV_LOADED
#define __DBU_CQCMGRTSIV_LOADED


struct CQCMGRTSIV_TAG
{
    char          FACTORY[10];
    char          INSP_ID[30];
    char          INSP_DTL_TYPE[30];
    int           INSP_COUNT;
    int           INSP_SEQ;
    char          SIEVE_CODE[30];
    char          SIZES[30];
    double        SIEVE_VALUE;
    double        COUNT_1;
    double        NOT_SIEVE_1;
    double        EXIST_SIEVE_1;
    double        DIFF_SIEVE_1;
    double        TI_VALUE_1;
    double        COUNT_2;
    double        NOT_SIEVE_2;
    double        EXIST_SIEVE_2;
    double        DIFF_SIEVE_2;
    double        TI_VALUE_2;
    double        SUM_DIFF_SIEVE;
    double        RATIO_SIEVE;
    double        AVG_SIEVE;
    double        TI_CHANGE;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cqcmgrtsiv(struct CQCMGRTSIV_TAG *CQCMGRTSIV);
extern void   DBU_select_cqcmgrtsiv(int sel_type, struct CQCMGRTSIV_TAG *CQCMGRTSIV);
extern void   DBU_select_cqcmgrtsiv_for_update(int sel_type, struct CQCMGRTSIV_TAG *CQCMGRTSIV);
extern double DBU_select_cqcmgrtsiv_scalar(int sel_type, struct CQCMGRTSIV_TAG *CQCMGRTSIV);
extern void   DBU_delete_cqcmgrtsiv(int sel_type, struct CQCMGRTSIV_TAG *CQCMGRTSIV);
extern void   DBU_insert_cqcmgrtsiv(struct CQCMGRTSIV_TAG *CQCMGRTSIV);
extern void   DBU_update_cqcmgrtsiv(int sel_type, struct CQCMGRTSIV_TAG *CQCMGRTSIV);
extern void   DBU_open_cqcmgrtsiv(int sel_type, struct CQCMGRTSIV_TAG *CQCMGRTSIV);
extern void   DBU_fetch_cqcmgrtsiv(int sel_type, struct CQCMGRTSIV_TAG *CQCMGRTSIV);
extern void   DBU_close_cqcmgrtsiv(int sel_type);


#endif               /* __DBU_CQCMGRTSIV_LOADED */

