/*********************************************************************
**
**    File Name   : DBU_if_ro_info_his_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-14 16:35:03
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_RO_INFO_HIS_N_LOADED
#define __DBU_IF_RO_INFO_HIS_N_LOADED


struct IF_RO_INFO_HIS_N_TAG
{
	double        IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	int           ORG_ID;
	char          ORG_CODE[4];
	int           ORDER_NUMBER;
	int           LINE_NUMBER;
	char          LOT_ID[31];
	char          ITEM_CODE[41];
	char          ITEM_DESC[1001];
	char          UNIT[4];
	double        ORDERED_QTY;
	double        SHIPPED_QTY;
	char          SHIPPED_DATE[15];
	char          CUSTOMER_NUMBER[31];
	char          CUSTOMER_NAME[51];
	char          ORDERED_DATE[15];
	int           CUSTOMER_ID;
	int           CUSTOMER_SITE_ID;
	double        OE_ORDER_HEADER_ID;
	double        OE_ORDER_LINE_ID;
	double        REFERENCE_LINE_ID;
	double        SHIPPING_HEADER_ID;
	double        SHIPPING_LINE_ID;
	double        SHIP_LINE_IF_ID;
	double        SHIP_LINE_LOT_IF_ID;
	char          TRAN_FLAG[2];
	char          CMF_1[51];
	char          CMF_2[51];
	char          CMF_3[51];
	char          CMF_4[51];
	char          CMF_5[51];
	char          CMF_6[51];
	char          CMF_7[51];
	char          CMF_8[51];
	char          CMF_9[51];
	char          CMF_10[51];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_RO_INFO_HIS_N_LOADED */

