/*********************************************************************
**
**    File Name   : DBU_cqcmrptgny.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-05 20:37:43
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTGNY_LOADED
#define __DBU_CQCMRPTGNY_LOADED


struct CQCMRPTGNY_TAG
{
	char          FACTORY[10];
    char          REPORT_NO[20];
    int           SORT_NO;
    char          QC_NAME[30];
    char          SPEC_VAL[30];
    char          VAL_01[30];
    char          VAL_02[30];
    char          VAL_03[30];
    char          VAL_04[30];
    char          VAL_05[30];
    char          VAL_06[30];
    char          VAL_07[30];
    char          REMARKS[100];
    char          USE_YN;
    char          RPT_CMF_1[50];
    char          RPT_CMF_2[50];
    char          RPT_CMF_3[50];
    char          RPT_CMF_4[50];
    char          RPT_CMF_5[50];
    char          RPT_CMF_6[50];
    char          RPT_CMF_7[50];
    char          RPT_CMF_8[50];
    char          RPT_CMF_9[50];
    char          RPT_CMF_10[50];
    char          RPT_CMF_11[50];
    char          RPT_CMF_12[50];
    char          RPT_CMF_13[50];
    char          RPT_CMF_14[50];
    char          RPT_CMF_15[50];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cqcmrptgny(struct CQCMRPTGNY_TAG *CQCMRPTGNY);
extern void   DBU_select_cqcmrptgny(int sel_type, struct CQCMRPTGNY_TAG *CQCMRPTGNY);
extern void   DBU_select_cqcmrptgny_for_update(int sel_type, struct CQCMRPTGNY_TAG *CQCMRPTGNY);
extern double DBU_select_cqcmrptgny_scalar(int sel_type, struct CQCMRPTGNY_TAG *CQCMRPTGNY);
extern void   DBU_delete_cqcmrptgny(int sel_type, struct CQCMRPTGNY_TAG *CQCMRPTGNY);
extern void   DBU_insert_cqcmrptgny(struct CQCMRPTGNY_TAG *CQCMRPTGNY);
extern void   DBU_update_cqcmrptgny(int sel_type, struct CQCMRPTGNY_TAG *CQCMRPTGNY);
extern void   DBU_open_cqcmrptgny(int sel_type, struct CQCMRPTGNY_TAG *CQCMRPTGNY);
extern void   DBU_fetch_cqcmrptgny(int sel_type, struct CQCMRPTGNY_TAG *CQCMRPTGNY);
extern void   DBU_close_cqcmrptgny(int sel_type);


#endif               /* __DBU_CQCMRPTGNY_LOADED */

