/*********************************************************************
**
**    File Name   : DBU_if_sub_area_def_his.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-28 10:51:15
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_SUB_AREA_DEF_HIS_LOADED
#define __DBU_IF_SUB_AREA_DEF_HIS_LOADED


struct IF_SUB_AREA_DEF_HIS_TAG
{
	int           IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	int           ORG_ID;
	char          ORG_CODE[3];
	int           DEPT_ID;
	char          DEPT_CODE[10];
	char          DEPT_DESC[240];
	char          DISABLE_DATE[14];
	char          TRAN_FLAG;
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_sub_area_def_his(struct IF_SUB_AREA_DEF_HIS_TAG *IF_SUB_AREA_DEF_HIS);
extern void   DBU_select_if_sub_area_def_his(int sel_type, struct IF_SUB_AREA_DEF_HIS_TAG *IF_SUB_AREA_DEF_HIS);
extern void   DBU_select_if_sub_area_def_his_for_update(int sel_type, struct IF_SUB_AREA_DEF_HIS_TAG *IF_SUB_AREA_DEF_HIS);
extern double DBU_select_if_sub_area_def_his_scalar(int sel_type, struct IF_SUB_AREA_DEF_HIS_TAG *IF_SUB_AREA_DEF_HIS);
extern void   DBU_delete_if_sub_area_def_his(int sel_type, struct IF_SUB_AREA_DEF_HIS_TAG *IF_SUB_AREA_DEF_HIS);
extern void   DBU_insert_if_sub_area_def_his(struct IF_SUB_AREA_DEF_HIS_TAG *IF_SUB_AREA_DEF_HIS);
extern void   DBU_update_if_sub_area_def_his(int sel_type, struct IF_SUB_AREA_DEF_HIS_TAG *IF_SUB_AREA_DEF_HIS);
extern void   DBU_open_if_sub_area_def_his(int sel_type, struct IF_SUB_AREA_DEF_HIS_TAG *IF_SUB_AREA_DEF_HIS);
extern void   DBU_fetch_if_sub_area_def_his(int sel_type, struct IF_SUB_AREA_DEF_HIS_TAG *IF_SUB_AREA_DEF_HIS);
extern void   DBU_close_if_sub_area_def_his(int sel_type);


#endif               /* __DBU_IF_SUB_AREA_DEF_HIS_LOADED */

