/*********************************************************************
**
**    File Name   : DBU_crasbasdat.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-01-29 13:25:03
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRASBASDAT_LOADED
#define __DBU_CRASBASDAT_LOADED


struct CRASBASDAT_TAG
{
    char          FACTORY[10];
    char          RES_ID[20];
    char          PROC_YN;
    char          NOWORK_TYPE;
    char          RUN_TYPE;
    char          CMF_1[20];
    char          CMF_2[20];
    char          CMF_3[20];
    char          CMF_4[20];
    char          CMF_5[20];
};


/* Function Declaration */
extern void   DBU_init_crasbasdat(struct CRASBASDAT_TAG *CRASBASDAT);
extern void   DBU_select_crasbasdat(int sel_type, struct CRASBASDAT_TAG *CRASBASDAT);
extern void   DBU_select_crasbasdat_for_update(int sel_type, struct CRASBASDAT_TAG *CRASBASDAT);
extern double DBU_select_crasbasdat_scalar(int sel_type, struct CRASBASDAT_TAG *CRASBASDAT);
extern void   DBU_delete_crasbasdat(int sel_type, struct CRASBASDAT_TAG *CRASBASDAT);
extern void   DBU_insert_crasbasdat(struct CRASBASDAT_TAG *CRASBASDAT);
extern void   DBU_update_crasbasdat(int sel_type, struct CRASBASDAT_TAG *CRASBASDAT);
extern void   DBU_open_crasbasdat(int sel_type, struct CRASBASDAT_TAG *CRASBASDAT);
extern void   DBU_fetch_crasbasdat(int sel_type, struct CRASBASDAT_TAG *CRASBASDAT);
extern void   DBU_close_crasbasdat(int sel_type);


#endif               /* __DBU_CRASBASDAT_LOADED */

