/*********************************************************************
**
**    File Name   : DBU_if_po_info_his.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-14 16:34:32
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_PO_INFO_HIS_LOADED
#define __DBU_IF_PO_INFO_HIS_LOADED


struct IF_PO_INFO_HIS_TAG
{
	int           IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	char          SHIPMENT_TYPE[25];
	int           ORG_ID;
	char          ORG_CODE[3];
	int           SHIP_TO_LOCATION_ID;
	char          SHIP_TO_LOCATION_CODE[60];
	int           VENDOR_ID;
	int           VENDOR_SITE_ID;
	char          VENDOR_CODE[30];
	char          VENDOR_NAME[240];
	int           PO_HEADER_ID;
	int           PO_LINE_ID;
	int           PO_RELEASE_ID;
	int           LINE_LOCATION_ID;
	int           PO_DISTRIBUTION_ID;
	char          PO_NUM[20];
	int           REVISION_NUM;
	int           LINE_NUM;
	int           RELEASE_NUM;
	int           SHIPMENT_NUM;
	int           INVENTORY_ITEM_ID;
	char          ITEM_CODE[40];
	char          ITEM_DESC[240];
	char          ITEM_UNIT[3];
	char          PO_UNIT[3];
	char          PO_DATE[14];
	char          NEED_BY_DATE[14];
	double        ORDER_QTY;
	double        DELIVERY_QTY;
	double        REMAIN_QTY;
	double        QTY_RCV_TOLERANCE;
	char          INSPECT_FLAG;
	char          PLLA_CANCEL_FLAG;
	char          PLA_CANCEL_FLAG;
	char          PHA_CANCEL_FLAG;
	char          PO_TYPE[25];
	int           WIP_ENTITY_ID;
	char          WIP_ENTITY_NAME[240];
	int           OPER_SEQ;
	int           STD_OPER_ID;
	char          OPER[10];
	char          OPER_DESC[240];
	char          CONSIGNMENT_FLAG[150];
	char          APPROVED_FLAG_HEADER;
	char          APPROVED_FLAG_LOCATION;
	char          APPROVED_DATE_HEADER[14];
	char          APPROVED_DATE_LOCATION[14];
	char          CLOSED_CODE_HEADER[30];
	char          CLOSED_CODE_LOCATION[30];
	char          USER_HOLD_FLAG;
	char          FROZEN_FLAG;
	char          TRAN_FLAG;
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_po_info_his(struct IF_PO_INFO_HIS_TAG *IF_PO_INFO_HIS);
extern void   DBU_select_if_po_info_his(int sel_type, struct IF_PO_INFO_HIS_TAG *IF_PO_INFO_HIS);
extern void   DBU_select_if_po_info_his_for_update(int sel_type, struct IF_PO_INFO_HIS_TAG *IF_PO_INFO_HIS);
extern double DBU_select_if_po_info_his_scalar(int sel_type, struct IF_PO_INFO_HIS_TAG *IF_PO_INFO_HIS);
extern void   DBU_delete_if_po_info_his(int sel_type, struct IF_PO_INFO_HIS_TAG *IF_PO_INFO_HIS);
extern void   DBU_insert_if_po_info_his(struct IF_PO_INFO_HIS_TAG *IF_PO_INFO_HIS);
extern void   DBU_update_if_po_info_his(int sel_type, struct IF_PO_INFO_HIS_TAG *IF_PO_INFO_HIS);
extern void   DBU_open_if_po_info_his(int sel_type, struct IF_PO_INFO_HIS_TAG *IF_PO_INFO_HIS);
extern void   DBU_fetch_if_po_info_his(int sel_type, struct IF_PO_INFO_HIS_TAG *IF_PO_INFO_HIS);
extern void   DBU_close_if_po_info_his(int sel_type);


#endif               /* __DBU_IF_PO_INFO_HIS_LOADED */

