/*********************************************************************
**
**    File Name   : DBU_crastolbrk.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2022-08-12 16:16:35
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2022 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRASTOLBRK_LOADED
#define __DBU_CRASTOLBRK_LOADED


struct CRASTOLBRK_TAG
{
	char          FACTORY[10];
	char          TOOL_ID[30];
	int           HIST_SEQ;
	char          AREA_ID[20];
	char          MAT_ID[30];
	char          OPER[10];
	char          RES_ID[20];
	char          BREAK_DATE[8];
	char          OCCUR_TIME[14];
	char          TOOL_KIND[10];
	char          CAR[10];
	char          TOP_BASE[10];
	char          WORKER_ID[20];
	int           LIMIT_COUNT;
	int           USE_COUNT;
	int           ALAM_COUNT;
	char          ISSUE_TYPE[10];
	char          ISSUE_COMMENT[300];
	char          BREAK_CAUSE[300];
	char          ACTION_COMMENT[300];
	char          BO_TIME[14];
	char          BREAK_PATTERN[10];
	char          CROWN_NO[25];
	char          CARBIDE_LOT[25];
	double        SIZE_1;
	double        SIZE_2;
	double        SIZE_3;
	char          C_SCAN[10];
	char          BREAK_TYPE[10];
	char          VENDOR_LOT_ID[50];
	char          MAT_TYPE[30];
	char          GRADE[30];
	char          BO_DIE_NO[25];
	char          D10_TYPE[10];
	char          D10_CREATE_TIME[14];
	double        D10_WEIGHT;
	double        D10_HEIGHT;
	char          M15_LOT_ID[25];
	char          M13_LOT_ID[25];
	char          CONFIRM_FLAG;
	char          CONFIRM_TIME[14];
	char          REQ_NO[20];
	char          BO_PRESSURE[50];
	char          BO_ELECTRICITY[50];
	char          BO_RESISTANCE[50];
	char          BO_CURRENT[50];
	char          HOLD_LOT_ID[50];
	char          ASSY_MOLD[50];
	char          ASSY_MOLD_PRESSURE[50];
	char          PROFILE_NO[50];
	char          PROFILE_PRESSURE[50];
	char          PROFILE_ELECTRICITY[50];
	char          MOLD_LOCATION[50];
	char          MOD_IN_FORN_LOT[50];
	char          MOD_IN_REAR_LOT[50];
	char          MOD_IN_LEFT_LOT[50];
	char          MOD_IN_RIGHT_LOT[50];
	char          MOD_IN_TOP_LOT[50];
	char          MOD_IN_BOTTON_LOT[50];
	char          CMF_1[30];
	char          CMF_2[30];
	char          CMF_3[30];
	char          CMF_4[30];
	char          CMF_5[30];
	char          CMF_6[30];
	char          CMF_7[30];
	char          CMF_8[30];
	char          CMF_9[30];
	char          CMF_10[30];
	char          CMF_11[30];
	char          CMF_12[30];
	char          CMF_13[30];
	char          CMF_14[30];
	char          CMF_15[30];
	char          CMF_16[30];
	char          CMF_17[30];
	char          CMF_18[30];
	char          CMF_19[30];
	char          CMF_20[30];
	char          REMARK[300];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_crastolbrk(struct CRASTOLBRK_TAG *CRASTOLBRK);
extern void   DBU_select_crastolbrk(int sel_type, struct CRASTOLBRK_TAG *CRASTOLBRK);
extern void   DBU_select_crastolbrk_for_update(int sel_type, struct CRASTOLBRK_TAG *CRASTOLBRK);
extern double DBU_select_crastolbrk_scalar(int sel_type, struct CRASTOLBRK_TAG *CRASTOLBRK);
extern void   DBU_delete_crastolbrk(int sel_type, struct CRASTOLBRK_TAG *CRASTOLBRK);
extern void   DBU_insert_crastolbrk(struct CRASTOLBRK_TAG *CRASTOLBRK);
extern void   DBU_update_crastolbrk(int sel_type, struct CRASTOLBRK_TAG *CRASTOLBRK);
extern void   DBU_open_crastolbrk(int sel_type, struct CRASTOLBRK_TAG *CRASTOLBRK);
extern void   DBU_fetch_crastolbrk(int sel_type, struct CRASTOLBRK_TAG *CRASTOLBRK);
extern void   DBU_close_crastolbrk(int sel_type);


#endif               /* __DBU_CRASTOLBRK_LOADED */

