/*********************************************************************
**
**    File Name   : DBU_if_po_requests_receipts_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2023-06-21 08:22:55
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2023 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_PO_REQUESTS_RECEIPTS_N_LOADED
#define __DBU_IF_PO_REQUESTS_RECEIPTS_N_LOADED


struct IF_PO_REQUESTS_RECEIPTS_N_TAG
{
    int           IF_SEQ;
    char          IF_TIME[15];
    char          IF_CODE_REQ[2];
    char          IF_CODE_REC[2];
    char          TRAN_TIME[15];
    char          FROM_ORG_CODE[4];
    char          TO_ORG_CODE[4];
    char          FROM_ITEM_CODE[31];
    char          TO_ITEM_CODE[31];
    char          UOM[4];
    double        QUANTITY;
    double        UNIT_PRICE;
    char          FROM_SUBINVENTORY[11];
    char          TO_SUBINVENTORY[11];
    char          NEED_BY_DATE[9];
    char          CMF_1[51];
    char          CMF_2[51];
    char          CMF_3[51];
    char          CMF_4[51];
    char          CMF_5[51];
    char          CMF_6[51];
    char          CMF_7[51];
    char          CMF_8[51];
    char          CMF_9[51];
    char          CMF_10[51];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_PO_REQUESTS_RECEIPTS_N_LOADED */

