/*********************************************************************
**
**    File Name   : DBU_cwiplotrec.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-03 14:49:57
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTREC_LOADED
#define __DBU_CWIPLOTREC_LOADED


struct CWIPLOTREC_TAG
{
    char          FACTORY[10];
    char          LOT_ID[25];
    int           HIST_SEQ;
    char          AREA_ID[20];
    char          ORDER_ID[25];
    char          INV_OPER[10];
    char          TRAN_OPER[10];
    char          TRAN_FLOW[20];
    char          TRAN_TIME[14];
    char          WORK_DATE[8];
    char          MAT_ID[30];
    int           MAT_VER;
    char          UNIT[10];
    double        QTY;
    char          DELETE_FLAG;
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiplotrec(struct CWIPLOTREC_TAG *CWIPLOTREC);
extern void   DBU_select_cwiplotrec(int sel_type, struct CWIPLOTREC_TAG *CWIPLOTREC);
extern void   DBU_select_cwiplotrec_for_update(int sel_type, struct CWIPLOTREC_TAG *CWIPLOTREC);
extern double DBU_select_cwiplotrec_scalar(int sel_type, struct CWIPLOTREC_TAG *CWIPLOTREC);
extern void   DBU_delete_cwiplotrec(int sel_type, struct CWIPLOTREC_TAG *CWIPLOTREC);
extern void   DBU_insert_cwiplotrec(struct CWIPLOTREC_TAG *CWIPLOTREC);
extern void   DBU_update_cwiplotrec(int sel_type, struct CWIPLOTREC_TAG *CWIPLOTREC);
extern void   DBU_open_cwiplotrec(int sel_type, struct CWIPLOTREC_TAG *CWIPLOTREC);
extern void   DBU_fetch_cwiplotrec(int sel_type, struct CWIPLOTREC_TAG *CWIPLOTREC);
extern void   DBU_close_cwiplotrec(int sel_type);


#endif               /* __DBU_CWIPLOTREC_LOADED */

