/*********************************************************************
**
**    File Name   : DBU_cwiplotdry.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-30 06:50:24
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTDRY_LOADED
#define __DBU_CWIPLOTDRY_LOADED


struct CWIPLOTDRY_TAG
{
    char          LOT_ID[25];
    int           HIST_SEQ;
    char          WORK_TIME[14];
    char          OPER[10];
    char          MAT_ID[30];
    char          FLOW[20];
    int           FLOW_SEQ_NUM;
    char          RES_ID[20];
    char          FACTORY[10];
    char          WORK_DATE[8];
    char          DAY_NIGHT[10];
    int           OPERATION_PRESS;
    int           PRESS_HOLD_TIME_1;
    int           PRESS_HOLD_TIME_2;
    char          PRESS_OPERATION_FLAG;
    char          DISCHARGE_OPERATION_FLAG;
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiplotdry(struct CWIPLOTDRY_TAG *CWIPLOTDRY);
extern void   DBU_select_cwiplotdry(int sel_type, struct CWIPLOTDRY_TAG *CWIPLOTDRY);
extern void   DBU_select_cwiplotdry_for_update(int sel_type, struct CWIPLOTDRY_TAG *CWIPLOTDRY);
extern double DBU_select_cwiplotdry_scalar(int sel_type, struct CWIPLOTDRY_TAG *CWIPLOTDRY);
extern void   DBU_delete_cwiplotdry(int sel_type, struct CWIPLOTDRY_TAG *CWIPLOTDRY);
extern void   DBU_insert_cwiplotdry(struct CWIPLOTDRY_TAG *CWIPLOTDRY);
extern void   DBU_update_cwiplotdry(int sel_type, struct CWIPLOTDRY_TAG *CWIPLOTDRY);
extern void   DBU_open_cwiplotdry(int sel_type, struct CWIPLOTDRY_TAG *CWIPLOTDRY);
extern void   DBU_fetch_cwiplotdry(int sel_type, struct CWIPLOTDRY_TAG *CWIPLOTDRY);
extern void   DBU_close_cwiplotdry(int sel_type);


#endif               /* __DBU_CWIPLOTDRY_LOADED */

