/*********************************************************************
**
**    File Name   : DBU_cretordsts.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-25 14:48:17
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRETORDSTS_LOADED
#define __DBU_CRETORDSTS_LOADED


struct CRETORDSTS_TAG
{
    char          FACTORY[10];
    char          RET_ORDER_ID[25];
    char          RET_LOT_ID[25];
    int           LINE_NO;
    char          RET_ORD_DATE[14];
    char          MAT_ID[30];
    int           MAT_VER;
    char          CUSTOMER_ID[20];
	char		  CUSTOMER_NUMBER[30];
	char		  CUSTOMER_NAME[50];
	int			  CUSTOMER_SITE_ID;
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          OPER[10];
    double        QTY;
	double        RETURNED_QTY;
    char          UNIT[10];
    char          RET_ORD_STATUS[10];
    char          RET_DATE[14];
    char          SHIP_ORDER_ID[25];
	double        SHIP_ORDER_SEQ;
	double	      SHIP_LINE_IF_ID;
	double   	  SHIP_LINE_LOT_IF_ID;
	double		  REFERENCE_LINE_ID;
	double		  OE_ORDER_HEADER_ID;
	double		  OE_ORDER_LINE_ID;
	char		  LABEL_NAME[1000];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cretordsts(struct CRETORDSTS_TAG *CRETORDSTS);
extern void   DBU_select_cretordsts(int sel_type, struct CRETORDSTS_TAG *CRETORDSTS);
extern void   DBU_select_cretordsts_for_update(int sel_type, struct CRETORDSTS_TAG *CRETORDSTS);
extern double DBU_select_cretordsts_scalar(int sel_type, struct CRETORDSTS_TAG *CRETORDSTS);
extern void   DBU_delete_cretordsts(int sel_type, struct CRETORDSTS_TAG *CRETORDSTS);
extern void   DBU_insert_cretordsts(struct CRETORDSTS_TAG *CRETORDSTS);
extern void   DBU_update_cretordsts(int sel_type, struct CRETORDSTS_TAG *CRETORDSTS);
extern void   DBU_open_cretordsts(int sel_type, struct CRETORDSTS_TAG *CRETORDSTS);
extern void   DBU_fetch_cretordsts(int sel_type, struct CRETORDSTS_TAG *CRETORDSTS);
extern void   DBU_close_cretordsts(int sel_type);


#endif               /* __DBU_CRETORDSTS_LOADED */

