/*********************************************************************
**
**    File Name   : DBU_cwiplotrnd_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-29 19:39:13
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTRND_N_LOADED
#define __DBU_CWIPLOTRND_N_LOADED


struct CWIPLOTRND_N_TAG
{
    char          LOT_ID[26];
    int           HIST_SEQ;
    char          OPER[11];
    char          MAT_ID[31];
    char          FLOW[21];
    int           FLOW_SEQ_NUM;
    char          GRADE[51];
    char          RES_ID[21];
    char          FACTORY[11];
    char          WORK_DATE[9];
    char          WORK_TIME[15];
    char          DAY_NIGHT[11];
    int           EDC_HIST_SEQ;
    char          RECIPE_ID[51];
    char          START_TIME[15];
    char          END_TIME[15];
    char          JUDGMENT[11];
    double        S_DEFECT_NUMBER;
    double        S_OUTER_DIAMETER_MIN;
    double        S_ALL_THICKNESS_MIN;
    double        S_ALL_THICKNESS_MAX;
    double        S_ALL_THICKNESS_TARGET;
    double        S_FLATNESS_MAX;
    double        S_FLATNESS_MIN;
    double        SIZE_UM;
    double        SIZE_UM2;
    char          CLASSFICATION[31];
    double        OUTER_DIAMETER_1;
    double        OUTER_DIAMETER_2;
    double        OUTER_DIAMETER_MIN;
    double        ALL_THICKNESS_1;
    double        ALL_THICKNESS_2;
    double        ALL_THICKNESS_3;
    double        ALL_THICKNESS_4;
    double        ALL_THICKNESS_5;
    double        ALL_THICKNESS_6;
    double        ALL_THICKNESS_7;
    double        ALL_THICKNESS_8;
    double        ALL_THICKNESS_9;
    double        ALL_THICKNESS_10;
    double        ALL_THICKNESS_11;
    double        ALL_THICKNESS_12;
    double        ALL_THICKNESS_13;
    double        ALL_THICKNESS_14;
    double        ALL_THICKNESS_15;
    double        ALL_THICKNESS_MAX;
    double        ALL_THICKNESS_MIN;
    double        FLATNESS_1;
    double        FLATNESS_2;
    double        FLATNESS_3;
    double        FLATNESS_4;
    double        FLATNESS_5;
    double        FLATNESS_6;
    double        FLATNESS_7;
    double        FLATNESS_8;
    double        FLATNESS_9;
    double        FLATNESS_10;
    double        FLATNESS_11;
    double        FLATNESS_12;
    double        FLATNESS_13;
    double        FLATNESS_14;
    double        FLATNESS_15;
    double        FLATNESS_MAX;
    char          DEFECT_IMAGE_1[101];
    char          DEFECT_IMAGE_2[101];
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPLOTRND_N_LOADED */

