/*********************************************************************
**
**    File Name   : DBU_cwiplotmvc.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-27 22:20:18
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTMVC_LOADED
#define __DBU_CWIPLOTMVC_LOADED


struct CWIPLOTMVC_TAG
{
    char          FACTORY[10];
    char          MOVE_ID[20];
    char          LOT_ID[25];
    int           HIST_SEQ;
    double        QTY;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiplotmvc(struct CWIPLOTMVC_TAG *CWIPLOTMVC);
extern void   DBU_select_cwiplotmvc(int sel_type, struct CWIPLOTMVC_TAG *CWIPLOTMVC);
extern void   DBU_select_cwiplotmvc_for_update(int sel_type, struct CWIPLOTMVC_TAG *CWIPLOTMVC);
extern double DBU_select_cwiplotmvc_scalar(int sel_type, struct CWIPLOTMVC_TAG *CWIPLOTMVC);
extern void   DBU_delete_cwiplotmvc(int sel_type, struct CWIPLOTMVC_TAG *CWIPLOTMVC);
extern void   DBU_insert_cwiplotmvc(struct CWIPLOTMVC_TAG *CWIPLOTMVC);
extern void   DBU_update_cwiplotmvc(int sel_type, struct CWIPLOTMVC_TAG *CWIPLOTMVC);
extern void   DBU_open_cwiplotmvc(int sel_type, struct CWIPLOTMVC_TAG *CWIPLOTMVC);
extern void   DBU_fetch_cwiplotmvc(int sel_type, struct CWIPLOTMVC_TAG *CWIPLOTMVC);
extern void   DBU_close_cwiplotmvc(int sel_type);


#endif               /* __DBU_CWIPLOTMVC_LOADED */

