/*********************************************************************
**
**    File Name   : DBU_cbaslbldat.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-30 13:45:10
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CBASLBLDAT_LOADED
#define __DBU_CBASLBLDAT_LOADED


struct CBASLBLDAT_TAG
{
    char          FACTORY[10];
    char          AREA_ID[30];
    char          FILE_NAME[30];
    int           SEQ;
    char          LABEL_SIZE[20];
    char          PRINT_DATE[8];
    char          LOT_ID[25];
    char          ITEM_CODE[30];
    char          ITEM_NAME[200];
    char          INPUT_DATE[8];
    double        LOT_QTY;
    char          UOM[10];
    char          VENDOR_NAME[50];
    char          SUPPLIER_LOT_ID[25];
    char          CELL_NO[30];
    char          WO_NO[25];
    char          PC0201[30];
    char          PC0202[30];
    char          PC0203[20];
    char          PC0204[10];
    char          MAIN_LOT_ID[25];
    char          GRADE[200];
    char          ITEM_UOM[10];
    char          REMARKS[400];
    char          GROUP_ID[30];
    char          ITEM_NAME2[200];
    char          TYPE[30];
    char          SPEC[200];
    char          BOX_COUNT[20];
    char          ITEM_NAME1[200];
    char          ITEM[200];
    char          PO_NUMBER[25];
    char          MN_NO[20];
    char          DRAWING_FLAG[2000];
    char          COAT[30];
    double        GROSS;
    char          QR_DATA[200];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cbaslbldat(struct CBASLBLDAT_TAG *CBASLBLDAT);
extern void   DBU_select_cbaslbldat(int sel_type, struct CBASLBLDAT_TAG *CBASLBLDAT);
extern void   DBU_select_cbaslbldat_for_update(int sel_type, struct CBASLBLDAT_TAG *CBASLBLDAT);
extern double DBU_select_cbaslbldat_scalar(int sel_type, struct CBASLBLDAT_TAG *CBASLBLDAT);
extern void   DBU_delete_cbaslbldat(int sel_type, struct CBASLBLDAT_TAG *CBASLBLDAT);
extern void   DBU_insert_cbaslbldat(struct CBASLBLDAT_TAG *CBASLBLDAT);
extern void   DBU_update_cbaslbldat(int sel_type, struct CBASLBLDAT_TAG *CBASLBLDAT);
extern void   DBU_open_cbaslbldat(int sel_type, struct CBASLBLDAT_TAG *CBASLBLDAT);
extern void   DBU_fetch_cbaslbldat(int sel_type, struct CBASLBLDAT_TAG *CBASLBLDAT);
extern void   DBU_close_cbaslbldat(int sel_type);


#endif               /* __DBU_CBASLBLDAT_LOADED */

