/*********************************************************************
**
**    File Name   : DBU_minvlothld.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-31 16:59:02
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MINVLOTHLD_LOADED
#define __DBU_MINVLOTHLD_LOADED


struct MINVLOTHLD_TAG
{
    char          FACTORY[10];
    char          INV_LOT_ID[25];
    int           HIST_SEQ;
	int           RELEASE_HIST_SEQ;
    char          MAT_ID[30];
    int           MAT_VER;
    double        QTY;
    double        QTY_2;
    double        QTY_3;
    char          UNIT[10];
    char          UNIT_2[10];
    char          UNIT_3[10];
    char          OPER[10];
    char          HOLD_CODE[30];
    char          HOLD_FLAG;
    char          HOLD_USER_ID[20];
    char          HOLD_TIME[14];
    char          HOLD_COMMENT[400];
    char          RELEASE_CODE[30];
    char          RELEASE_USER_ID[20];
    char          RELEASE_TIME[14];
    char          RELEASE_COMMENT[400];
    char          HIST_DEL_FLAG;
};


/* Function Declaration */
extern void   DBU_init_minvlothld(struct MINVLOTHLD_TAG *MINVLOTHLD);
extern void   DBU_select_minvlothld(int sel_type, struct MINVLOTHLD_TAG *MINVLOTHLD);
extern void   DBU_select_minvlothld_for_update(int sel_type, struct MINVLOTHLD_TAG *MINVLOTHLD);
extern double DBU_select_minvlothld_scalar(int sel_type, struct MINVLOTHLD_TAG *MINVLOTHLD);
extern void   DBU_delete_minvlothld(int sel_type, struct MINVLOTHLD_TAG *MINVLOTHLD);
extern void   DBU_insert_minvlothld(struct MINVLOTHLD_TAG *MINVLOTHLD);
extern void   DBU_update_minvlothld(int sel_type, struct MINVLOTHLD_TAG *MINVLOTHLD);
extern void   DBU_open_minvlothld(int sel_type, struct MINVLOTHLD_TAG *MINVLOTHLD);
extern void   DBU_fetch_minvlothld(int sel_type, struct MINVLOTHLD_TAG *MINVLOTHLD);
extern void   DBU_close_minvlothld(int sel_type);


#endif               /* __DBU_MINVLOTHLD_LOADED */

