/*********************************************************************
**
**    File Name   : DBU_cordprdpln_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-08 13:58:04
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CORDPRDPLN_N_LOADED
#define __DBU_CORDPRDPLN_N_LOADED


struct CORDPRDPLN_N_TAG
{
    char          FACTORY[11];
    char          AREA_ID[21];
    char          OPER[11];
    char          PLAN_DATE[9];
    char          MAT_ID[31];
    int           MAT_VER;
    double        QTY;
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CORDPRDPLN_N_LOADED */

