/*********************************************************************
**
**    File Name   : DBU_minvmatiss.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-18 09:19:44
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MINVMATISS_LOADED
#define __DBU_MINVMATISS_LOADED


struct MINVMATISS_TAG
{
    char          FACTORY[10];
    char          INV_LOT_ID[25];
    int           HIST_SEQ;
    char          REQ_NO[30];
    char          REQ_MAT_ID[30];
    int           REQ_MAT_VER;
    char          ISSUE_TIME[14];
    double        ISSUE_QTY;
	char          UNIT[10];
    char          AREA_ID[20];
    char          SUB_AREA_ID[20];
    char          OPER[10];
    char          TO_AREA_ID[20];
    char          TO_SUB_AREA_ID[20];
    char          TO_OPER[10];
    char          TRAN_COMMENT[400];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_minvmatiss(struct MINVMATISS_TAG *MINVMATISS);
extern void   DBU_select_minvmatiss(int sel_type, struct MINVMATISS_TAG *MINVMATISS);
extern void   DBU_select_minvmatiss_for_update(int sel_type, struct MINVMATISS_TAG *MINVMATISS);
extern double DBU_select_minvmatiss_scalar(int sel_type, struct MINVMATISS_TAG *MINVMATISS);
extern void   DBU_delete_minvmatiss(int sel_type, struct MINVMATISS_TAG *MINVMATISS);
extern void   DBU_insert_minvmatiss(struct MINVMATISS_TAG *MINVMATISS);
extern void   DBU_update_minvmatiss(int sel_type, struct MINVMATISS_TAG *MINVMATISS);
extern void   DBU_open_minvmatiss(int sel_type, struct MINVMATISS_TAG *MINVMATISS);
extern void   DBU_fetch_minvmatiss(int sel_type, struct MINVMATISS_TAG *MINVMATISS);
extern void   DBU_close_minvmatiss(int sel_type);


#endif               /* __DBU_MINVMATISS_LOADED */

