/*********************************************************************
**
**    File Name   : DBU_cqcmispwrk.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-22 17:30:02
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMISPWRK_LOADED
#define __DBU_CQCMISPWRK_LOADED


struct CQCMISPWRK_TAG
{
    char          FACTORY[10];
    char          INSP_ID[30];
    char          WORKER_ID[20];
    char          WORKER_DESC[30];
    char          WORK_TYPE[30];
};


/* Function Declaration */
extern void   DBU_init_cqcmispwrk(struct CQCMISPWRK_TAG *CQCMISPWRK);
extern void   DBU_select_cqcmispwrk(int sel_type, struct CQCMISPWRK_TAG *CQCMISPWRK);
extern void   DBU_select_cqcmispwrk_for_update(int sel_type, struct CQCMISPWRK_TAG *CQCMISPWRK);
extern double DBU_select_cqcmispwrk_scalar(int sel_type, struct CQCMISPWRK_TAG *CQCMISPWRK);
extern void   DBU_delete_cqcmispwrk(int sel_type, struct CQCMISPWRK_TAG *CQCMISPWRK);
extern void   DBU_insert_cqcmispwrk(struct CQCMISPWRK_TAG *CQCMISPWRK);
extern void   DBU_update_cqcmispwrk(int sel_type, struct CQCMISPWRK_TAG *CQCMISPWRK);
extern void   DBU_open_cqcmispwrk(int sel_type, struct CQCMISPWRK_TAG *CQCMISPWRK);
extern void   DBU_fetch_cqcmispwrk(int sel_type, struct CQCMISPWRK_TAG *CQCMISPWRK);
extern void   DBU_close_cqcmispwrk(int sel_type);


#endif               /* __DBU_CQCMISPWRK_LOADED */

