/*********************************************************************
**
**    File Name   : DBU_ct_prd210t_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-03 19:04:07
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CT_PRD210T_N_LOADED
#define __DBU_CT_PRD210T_N_LOADED


struct CT_PRD210T_N_TAG
{
    char          LOT_ID[21];
    char          ORG_CODE[21];
    char          WC_CODE[21];
    int           OP_SEQ;
    char          OP_CODE[21];
    int           LOT_SEQ;
    int           WORK_QTY;
    int           BAD_QTY;
    int           LOT_QTY;
    char          ACTUAL_DATE[9];
    char          WG_CODE[21];
    char          MACHINE[21];
    int           READ_TIME;
    char          START_DATE[9];
    char          START_TIME[7];
    char          END_DATE[9];
    char          END_TIME[7];
    char          STATUS[3];
    char          USE_YN[2];
    char          IF_YN[2];
    char          REMARKS[201];
    char          CREATE_DATE[15];
    char          CREATE_USER[21];
    char          UPDATE_DATE[15];
    char          UPDATE_USER[21];
    char          ATTRIBUTE01[31];
    char          ATTRIBUTE02[31];
    char          ATTRIBUTE03[31];
    char          ATTRIBUTE04[31];
    char          ATTRIBUTE05[31];
    char          ATTRIBUTE06[31];
    char          ATTRIBUTE07[31];
    char          ATTRIBUTE08[31];
    char          ATTRIBUTE09[31];
    char          ATTRIBUTE10[31];
    char          ATTRIBUTE11[31];
    char          ATTRIBUTE12[31];
    char          ATTRIBUTE13[31];
    char          ATTRIBUTE14[31];
    char          ATTRIBUTE15[31];
    char          TO_WC_CODE[31];
    int           TO_OP_SEQ;
    char          TO_OP_CODE[31];
    int           INPUT_QTY;
    char          OVER_YN[2];
    char          DECISION[21];
    int           STATION_NO;
    char          CELL_NO[21];
};


#endif               /* __DBU_CT_PRD210T_N_LOADED */

