/*********************************************************************
**
**    File Name   : DBU_crashitfnc.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-07-23 09:33:32
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRASHITFNC_LOADED
#define __DBU_CRASHITFNC_LOADED


struct CRASHITFNC_TAG
{
    char          RES_ID[20];
    int           HIST_SEQ;
    char          WORK_TIME[14];
    char          FACTORY[10];
    char          WORK_DATE[8];
    char          DAY_NIGHT[10];
    double        SV_TEMP;
    double        PV_TEMP;
    char          TIME_RM[20];
    double        VACCUM_PV1;
    double        VACCUM_PV2;
    double        THROTTLE_SV;
    double        THROTTLE_PV;
    double        THROTTLE_OUT;
    char          RES_STATUS;
    char          START_TIME[14];
    char          END_TIME[14];
    char          EVENT_ID[12];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_crashitfnc(struct CRASHITFNC_TAG *CRASHITFNC);
extern void   DBU_select_crashitfnc(int sel_type, struct CRASHITFNC_TAG *CRASHITFNC);
extern void   DBU_select_crashitfnc_for_update(int sel_type, struct CRASHITFNC_TAG *CRASHITFNC);
extern double DBU_select_crashitfnc_scalar(int sel_type, struct CRASHITFNC_TAG *CRASHITFNC);
extern void   DBU_delete_crashitfnc(int sel_type, struct CRASHITFNC_TAG *CRASHITFNC);
extern void   DBU_insert_crashitfnc(struct CRASHITFNC_TAG *CRASHITFNC);
extern void   DBU_update_crashitfnc(int sel_type, struct CRASHITFNC_TAG *CRASHITFNC);
extern void   DBU_open_crashitfnc(int sel_type, struct CRASHITFNC_TAG *CRASHITFNC);
extern void   DBU_fetch_crashitfnc(int sel_type, struct CRASHITFNC_TAG *CRASHITFNC);
extern void   DBU_close_crashitfnc(int sel_type);


#endif               /* __DBU_CRASHITFNC_LOADED */

