/*********************************************************************
**
**    File Name   : DBU_if_wo_info_his_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-25 18:07:15
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_WO_INFO_HIS_N_LOADED
#define __DBU_IF_WO_INFO_HIS_N_LOADED


struct IF_WO_INFO_HIS_N_TAG
{
	int           IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	int           ORG_ID;
	char          ORG_CODE[4];
	int           WIP_ENTITY_ID;
	char          WIP_ENTITY_NAME[241];
	int           ITEM_ID;
	char          ITEM_CODE[41];
	char          ITEM_DESC[241];
	char          ITEM_UNIT[4];
	char          ITEM_TYPE[31];
	char          ALTERNATE_BOM_DESIGNATOR[11];
	char          ALTER_RTG_NAME[11];
	char          COMPLETION_INV_OPER[11];
	int           OPER_SEQ_NUM;
	int           STANDARD_OPER_ID;
	char          OPER[11];
	char          OPER_DESC[241];
	int           DEPT_ID;
	char          DEPT_CODE[11];
	char          DEPT_DESC[241];
	int           STATUS_TYPE;
	char          STATUS_TYPE_NAME[20];
	int           JOB_TYPE;
	char          JOB_TYPE_NAME[13];
	char          PLAN_START_DATE[15];
	char          PLAN_END_DATE[15];
	char          RELEASED_DATE[15];
	char          COMP_DATE[15];
	char          CLOSED_DATE[15];
	double        PLAN_QTY;
	double        QTY_IN_QUEUE;
	double        QTY_WAITING_TO_MOVE;
	double        QTY_SCRAPPED;
	double        QTY_COMPLETED;
	char          CUT_MULTI[151];
	int           PRE_OPER_SEQ;
	char          PRE_OPER[11];
	int           NEXT_OPER_SEQ;
	char          NEXT_OPER[11];
	char          FIRST_OPER_YN[2];
	char          LAST_OPER_YN[2];
	char          SRS_YN[4];
	char          PUP_GBN[241];
	char          CUTTING[51];
	char          CUST_NAME[241];
	char          VENDORS[241];
	char          REMARKS[151];
	char          SO_NUM[151];
	char          LAST_COMP_DATE[15];
	char          TRAN_FLAG[2];
	int           IF_GROUP_ID;
	char          CMF_1[51];
	char          CMF_2[51];
	char          CMF_3[51];
	char          CMF_4[51];
	char          CMF_5[51];
	char          CMF_6[51];
	char          CMF_7[51];
	char          CMF_8[51];
	char          CMF_9[51];
	char          CMF_10[51];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_WO_INFO_HIS_N_LOADED */

