/*********************************************************************
**
**    File Name   : DBU_cqcmispcol.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-07 08:58:32
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMISPCOL_LOADED
#define __DBU_CQCMISPCOL_LOADED


struct CQCMISPCOL_TAG
{
	char          FACTORY[10];
	char          INSP_ID[30];
	char          COL_SET_ID;
	char          COL_SET_VER;
	int           INSP_SEQ;
	char          RES_ID[20];
	char          INSP_USER_ID[30];
	char          INSP_USER_NAME[250];
	char          INSP_JUDGE_FLAG;
	char          INSP_JUDGE_TYPE[30];
	char          INSP_JUDGE_TIME[30];
	char          RWK_FLOW[20];
	char          RWK_OPER[10];
	char          CMF_1[50];
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cqcmispcol(struct CQCMISPCOL_TAG *CQCMISPCOL);
extern void   DBU_select_cqcmispcol(int sel_type, struct CQCMISPCOL_TAG *CQCMISPCOL);
extern void   DBU_select_cqcmispcol_for_update(int sel_type, struct CQCMISPCOL_TAG *CQCMISPCOL);
extern double DBU_select_cqcmispcol_scalar(int sel_type, struct CQCMISPCOL_TAG *CQCMISPCOL);
extern void   DBU_delete_cqcmispcol(int sel_type, struct CQCMISPCOL_TAG *CQCMISPCOL);
extern void   DBU_insert_cqcmispcol(struct CQCMISPCOL_TAG *CQCMISPCOL);
extern void   DBU_update_cqcmispcol(int sel_type, struct CQCMISPCOL_TAG *CQCMISPCOL);
extern void   DBU_open_cqcmispcol(int sel_type, struct CQCMISPCOL_TAG *CQCMISPCOL);
extern void   DBU_fetch_cqcmispcol(int sel_type, struct CQCMISPCOL_TAG *CQCMISPCOL);
extern void   DBU_close_cqcmispcol(int sel_type);


#endif               /* __DBU_CQCMISPCOL_LOADED */

