/*********************************************************************
**
**    File Name   : DBU_cwiprcpdef.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-23 14:41:58
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPRCPDEF_LOADED
#define __DBU_CWIPRCPDEF_LOADED


struct CWIPRCPDEF_TAG
{
	char          FACTORY[10];
	char          AREA_ID[20];
	char          MAT_ID[30];
	char          OPER[10];
	char          RECIPE_NO[30];
	char          CMF_1[30];
	char          CMF_2[30];
	char          CMF_3[30];
	char          CMF_4[30];
	char          CMF_5[30];
	char          CMF_6[30];
	char          CMF_7[30];
	char          CMF_8[30];
	char          CMF_9[30];
	char          CMF_10[30];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiprcpdef(struct CWIPRCPDEF_TAG *CWIPRCPDEF);
extern void   DBU_select_cwiprcpdef(int sel_type, struct CWIPRCPDEF_TAG *CWIPRCPDEF);
extern void   DBU_select_cwiprcpdef_for_update(int sel_type, struct CWIPRCPDEF_TAG *CWIPRCPDEF);
extern double DBU_select_cwiprcpdef_scalar(int sel_type, struct CWIPRCPDEF_TAG *CWIPRCPDEF);
extern void   DBU_delete_cwiprcpdef(int sel_type, struct CWIPRCPDEF_TAG *CWIPRCPDEF);
extern void   DBU_insert_cwiprcpdef(struct CWIPRCPDEF_TAG *CWIPRCPDEF);
extern void   DBU_update_cwiprcpdef(int sel_type, struct CWIPRCPDEF_TAG *CWIPRCPDEF);
extern void   DBU_open_cwiprcpdef(int sel_type, struct CWIPRCPDEF_TAG *CWIPRCPDEF);
extern void   DBU_fetch_cwiprcpdef(int sel_type, struct CWIPRCPDEF_TAG *CWIPRCPDEF);
extern void   DBU_close_cwiprcpdef(int sel_type);


#endif               /* __DBU_CWIPRCPDEF_LOADED */

