/*********************************************************************
**
**    File Name   : DBU_minvdlvlot_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-10 09:00:49
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MINVDLVLOT_N_LOADED
#define __DBU_MINVDLVLOT_N_LOADED


struct MINVDLVLOT_N_TAG
{
    char          FACTORY[11];
    char          DLV_LOT_ID[26];
    char          MAT_ID[31];
	int			  MAT_VER;
    double        QTY;
    double        QTY_2;
    double        QTY_3;
    char          UNIT[11];
    char          UNIT_2[11];
    char          UNIT_3[11];
	char          AREA_ID[21];
	char          SUB_AREA_ID[21];
	char          OPER[11];
    char          VENDOR_LOT_ID[26];
	char          DLV_LOT_STATUS[11];
    char          DLV_TIME[15];
    char          DLV_NO[31];
    int           DLV_SEQ;
    char          PO_NO[31];
    int           PO_SEQ;
    char          BL_NO[31];
    int           BL_SEQ;
	int			  PO_DISTRIBUTION_ID;
    char          INSP_ID[31];
    char          INSP_REQ_TIME[15];
    char          INSP_USER_ID[21];
    char          INSP_STATUS[15];
	char          INSP_RESULT_FLAG[2];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_MINVDLVLOT_N_LOADED */

