/*********************************************************************
**
**    File Name    CST_batch_job_n.h
**    DB Type      Unix Oracle
**    Description  Table Structure Definition Header File
**    Create date  2020-11-19 092900
**
**    Generated by DB HN.LEE
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_BATCH_JOB_N_LOADED
#define __DBU_BATCH_JOB_N_LOADED




#endif               /* __DBU_BATCH_JOB_N_LOADED */

