/*********************************************************************
**
**    File Name   : DBU_cinvuoplot.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-04 20:07:01
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CINVUOPLOT_LOADED
#define __DBU_CINVUOPLOT_LOADED


struct CINVUOPLOT_TAG
{
    char          LOT_ID[25];
    int           SEQ;
    char          OPER[10];
    char          MAT_ID[30];
    double        QTY;
    char          VENDOR_ID[20];
    int           VENDOR_SITE_ID;
    char          VENDOR_LOT_ID[50];
    char          MOLD_TYPE[30];
    char          MOLD_MODEL[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cinvuoplot(struct CINVUOPLOT_TAG *CINVUOPLOT);
extern void   DBU_select_cinvuoplot(int sel_type, struct CINVUOPLOT_TAG *CINVUOPLOT);
extern void   DBU_select_cinvuoplot_for_update(int sel_type, struct CINVUOPLOT_TAG *CINVUOPLOT);
extern double DBU_select_cinvuoplot_scalar(int sel_type, struct CINVUOPLOT_TAG *CINVUOPLOT);
extern void   DBU_delete_cinvuoplot(int sel_type, struct CINVUOPLOT_TAG *CINVUOPLOT);
extern void   DBU_insert_cinvuoplot(struct CINVUOPLOT_TAG *CINVUOPLOT);
extern void   DBU_update_cinvuoplot(int sel_type, struct CINVUOPLOT_TAG *CINVUOPLOT);
extern void   DBU_open_cinvuoplot(int sel_type, struct CINVUOPLOT_TAG *CINVUOPLOT);
extern void   DBU_fetch_cinvuoplot(int sel_type, struct CINVUOPLOT_TAG *CINVUOPLOT);
extern void   DBU_close_cinvuoplot(int sel_type);


#endif               /* __DBU_CINVUOPLOT_LOADED */

