/*********************************************************************
**
**    File Name   : DBU_esecusrdef.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-25 23:39:43
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_ESECUSRDEF_LOADED
#define __DBU_ESECUSRDEF_LOADED


struct ESECUSRDEF_TAG
{
    char          FACTORY[10];
    char          USER_ID[20];
    char          USER_DESC[200];
    char          PASSWORD[20];
    char          CHG_PASS_FLAG;
    char          USER_GRP_1[30];
    char          USER_GRP_2[30];
    char          USER_GRP_3[30];
    char          USER_GRP_4[30];
    char          USER_GRP_5[30];
    char          USER_GRP_6[30];
    char          USER_GRP_7[30];
    char          USER_GRP_8[30];
    char          USER_GRP_9[30];
    char          USER_GRP_10[30];
    char          USER_CMF_1[30];
    char          USER_CMF_2[30];
    char          USER_CMF_3[30];
    char          USER_CMF_4[30];
    char          USER_CMF_5[30];
    char          USER_CMF_6[30];
    char          USER_CMF_7[30];
    char          USER_CMF_8[30];
    char          USER_CMF_9[30];
    char          USER_CMF_10[30];
    char          SEC_GRP_ID[20];
    char          PHONE_OFFICE[20];
    char          PHONE_MOBILE[20];
    char          PHONE_HOME[20];
    char          PHONE_OTHER[20];
    char          EXPIRE_DATE[8];
    char          PASS_EXPIRE_DATE[8];
    char          ENTER_DATE[8];
    char          RETIRE_DATE[8];
    char          EMAIL_ID[50];
    char          BIRTHDAY[8];
    char          SEX_FLAG;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_esecusrdef(struct ESECUSRDEF_TAG *ESECUSRDEF);
extern void   DBU_select_esecusrdef(int sel_type, struct ESECUSRDEF_TAG *ESECUSRDEF);
extern void   DBU_select_esecusrdef_for_update(int sel_type, struct ESECUSRDEF_TAG *ESECUSRDEF);
extern double DBU_select_esecusrdef_scalar(int sel_type, struct ESECUSRDEF_TAG *ESECUSRDEF);
extern void   DBU_delete_esecusrdef(int sel_type, struct ESECUSRDEF_TAG *ESECUSRDEF);
extern void   DBU_insert_esecusrdef(int sel_type, struct ESECUSRDEF_TAG *ESECUSRDEF);
extern void   DBU_update_esecusrdef(int sel_type, struct ESECUSRDEF_TAG *ESECUSRDEF);
extern void   DBU_open_esecusrdef(int sel_type, struct ESECUSRDEF_TAG *ESECUSRDEF);
extern void   DBU_fetch_esecusrdef(int sel_type, struct ESECUSRDEF_TAG *ESECUSRDEF);
extern void   DBU_close_esecusrdef(int sel_type);


#endif               /* __DBU_ESECUSRDEF_LOADED */

