/*********************************************************************
**
**    File Name   : DBU_cwiplotimp.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-15 08:25:21
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTIMP_LOADED
#define __DBU_CWIPLOTIMP_LOADED


struct CWIPLOTIMP_TAG
{
    char          LOT_ID[25];
    int           HIST_SEQ;
    char          OPER[10];
    char          MAT_ID[30];
    char          FLOW[20];
    int           FLOW_SEQ_NUM;
    char          GRADE[50];
    char          RES_ID[20];
    char          FACTORY[10];
    char          WORK_DATE[8];
    char          WORK_TIME[14];
    char          DAY_NIGHT[10];
    int           EDC_HIST_SEQ;
    char          RECIPE_ID[50];
    char          START_TIME[14];
    char          END_TIME[14];
    char          JUDGMENT[10];
    double        FLATNESS_1;
    double        FLATNESS_2;
    double        FLATNESS_3;
    double        FLATNESS_4;
    double        FLATNESS_5;
    double        WEIGHT;
    double        AIR_POCKET;
    char          IMPACT_NO[30];
    int           IMPACT_TIME;
    char          AUTO_FLAG;
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwiplotimp(struct CWIPLOTIMP_TAG *CWIPLOTIMP);
extern void   DBU_select_cwiplotimp(int sel_type, struct CWIPLOTIMP_TAG *CWIPLOTIMP);
extern void   DBU_select_cwiplotimp_for_update(int sel_type, struct CWIPLOTIMP_TAG *CWIPLOTIMP);
extern double DBU_select_cwiplotimp_scalar(int sel_type, struct CWIPLOTIMP_TAG *CWIPLOTIMP);
extern void   DBU_delete_cwiplotimp(int sel_type, struct CWIPLOTIMP_TAG *CWIPLOTIMP);
extern void   DBU_insert_cwiplotimp(struct CWIPLOTIMP_TAG *CWIPLOTIMP);
extern void   DBU_update_cwiplotimp(int sel_type, struct CWIPLOTIMP_TAG *CWIPLOTIMP);
extern void   DBU_open_cwiplotimp(int sel_type, struct CWIPLOTIMP_TAG *CWIPLOTIMP);
extern void   DBU_fetch_cwiplotimp(int sel_type, struct CWIPLOTIMP_TAG *CWIPLOTIMP);
extern void   DBU_close_cwiplotimp(int sel_type);


#endif               /* __DBU_CWIPLOTIMP_LOADED */

