/*********************************************************************
**
**    File Name   : DBU_cqcmrptgrn.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-05 20:35:39
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTGRN_LOADED
#define __DBU_CQCMRPTGRN_LOADED


struct CQCMRPTGRN_TAG
{
	char          FACTORY[10];
    char          REPORT_NO[20];
    char          LOT_ID[20];
    char          GRADE[20];
    char          SIZES[20];
    char          ORDER_NO[20];
    char          CUST_NO[100];
    char          GRADE_SPEC[30];
    char          SIZES_SPEC[30];
    char          TI_SPEC[30];
    char          TTI_SPEC[30];
    char          MA_SPEC[30];
    char          WT_SPEC[30];
    char          BD_SPEC[30];
    char          TD_SPEC[30];
    char          PCS_SPEC[30];
    char          PSD_TS_SPEC[30];
    char          PSD_US_SPEC[30];
    char          PSD_SS_SPEC[30];
    char          PSD_OS_SPEC[30];
    char          PSD_LS_SPEC[30];
    char          PSD_FS_SPEC[30];
    char          HLT_TI_SPEC[30];
    char          TI_VAL[30];
    char          TTI_VAL[30];
    char          MA_VAL[30];
    char          WT_VAL[30];
    char          BD_VAL[30];
    char          TD_VAL[30];
    char          PCS_VAL[30];
    char          PSD_TS_VAL[30];
    char          PSD_US_VAL[30];
    char          PSD_SS_VAL[30];
    char          PSD_OS_VAL[30];
    char          PSD_LS_VAL[30];
    char          PSD_FS_VAL[30];
    char          HLT_TI_VAL[30];
    char          ATTRIBUTE01[50];
    char          ATTRIBUTE02[50];
    char          ATTRIBUTE03[50];
    char          ATTRIBUTE04[50];
    char          ATTRIBUTE05[50];
    char          ATTRIBUTE06[50];
    char          ATTRIBUTE07[50];
    char          ATTRIBUTE08[50];
    char          ATTRIBUTE09[50];
    char          ATTRIBUTE10[50];
    char          REMARKS[100];
    char          USE_YN;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
    char          IMAGE_NUM[20];
    char          BD_TI_SPEC[30];
    char          BD_TTI_SPEC[30];
    char          BD_TTI_VAL[30];
    char          BD_TI_VAL[30];
    char          SURFACE_B_VAL[30];
    char          HEADER_ID[20];
    char          LINE_NUMBER[30];
    char          IMAGE_NUM2[20];
    char          IMAGE_NUM3[20];
    char          CM_L_VAL[30];
    char          CM_A_VAL[30];
    char          CM_B_VAL[30];
    char          RPT_CMF_1[50];
    char          RPT_CMF_2[50];
    char          RPT_CMF_3[50];
    char          RPT_CMF_4[50];
    char          RPT_CMF_5[50];
    char          RPT_CMF_6[50];
    char          RPT_CMF_7[50];
    char          RPT_CMF_8[50];
    char          RPT_CMF_9[50];
    char          RPT_CMF_10[50];
    char          RPT_CMF_11[50];
    char          RPT_CMF_12[50];
    char          RPT_CMF_13[50];
    char          RPT_CMF_14[50];
    char          RPT_CMF_15[50];
};


/* Function Declaration */
extern void   DBU_init_cqcmrptgrn(struct CQCMRPTGRN_TAG *CQCMRPTGRN);
extern void   DBU_select_cqcmrptgrn(int sel_type, struct CQCMRPTGRN_TAG *CQCMRPTGRN);
extern void   DBU_select_cqcmrptgrn_for_update(int sel_type, struct CQCMRPTGRN_TAG *CQCMRPTGRN);
extern double DBU_select_cqcmrptgrn_scalar(int sel_type, struct CQCMRPTGRN_TAG *CQCMRPTGRN);
extern void   DBU_delete_cqcmrptgrn(int sel_type, struct CQCMRPTGRN_TAG *CQCMRPTGRN);
extern void   DBU_insert_cqcmrptgrn(struct CQCMRPTGRN_TAG *CQCMRPTGRN);
extern void   DBU_update_cqcmrptgrn(int sel_type, struct CQCMRPTGRN_TAG *CQCMRPTGRN);
extern void   DBU_open_cqcmrptgrn(int sel_type, struct CQCMRPTGRN_TAG *CQCMRPTGRN);
extern void   DBU_fetch_cqcmrptgrn(int sel_type, struct CQCMRPTGRN_TAG *CQCMRPTGRN);
extern void   DBU_close_cqcmrptgrn(int sel_type);


#endif               /* __DBU_CQCMRPTGRN_LOADED */

