/*********************************************************************
**
**    File Name   : DBU_cqcmrptgmp.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-10 18:15:40
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTGMP_LOADED
#define __DBU_CQCMRPTGMP_LOADED


struct CQCMRPTGMP_TAG
{
    char          FACTORY[10];
    char          REPORT_NO[30];
    char          LOT_ID[20];
    int           LOT_SEQ;
    char          SUB_CODE[20];
    char          CODE_NAME[100];
    char          CODE_VALUE[30];
    char          RPT_CMF_1[50];
    char          RPT_CMF_2[50];
    char          RPT_CMF_3[50];
    char          RPT_CMF_4[50];
    char          RPT_CMF_5[50];
    char          RPT_CMF_6[50];
    char          RPT_CMF_7[50];
    char          RPT_CMF_8[50];
    char          RPT_CMF_9[50];
    char          RPT_CMF_10[50];
    char          RPT_CMF_11[50];
    char          RPT_CMF_12[50];
    char          RPT_CMF_13[50];
    char          RPT_CMF_14[50];
    char          RPT_CMF_15[50];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cqcmrptgmp(struct CQCMRPTGMP_TAG *CQCMRPTGMP);
extern void   DBU_select_cqcmrptgmp(int sel_type, struct CQCMRPTGMP_TAG *CQCMRPTGMP);
extern void   DBU_select_cqcmrptgmp_for_update(int sel_type, struct CQCMRPTGMP_TAG *CQCMRPTGMP);
extern double DBU_select_cqcmrptgmp_scalar(int sel_type, struct CQCMRPTGMP_TAG *CQCMRPTGMP);
extern void   DBU_delete_cqcmrptgmp(int sel_type, struct CQCMRPTGMP_TAG *CQCMRPTGMP);
extern void   DBU_insert_cqcmrptgmp(struct CQCMRPTGMP_TAG *CQCMRPTGMP);
extern void   DBU_update_cqcmrptgmp(int sel_type, struct CQCMRPTGMP_TAG *CQCMRPTGMP);
extern void   DBU_open_cqcmrptgmp(int sel_type, struct CQCMRPTGMP_TAG *CQCMRPTGMP);
extern void   DBU_fetch_cqcmrptgmp(int sel_type, struct CQCMRPTGMP_TAG *CQCMRPTGMP);
extern void   DBU_close_cqcmrptgmp(int sel_type);


#endif               /* __DBU_CQCMRPTGMP_LOADED */

