/*********************************************************************
**
**    File Name   : DBU_cwipgrtbld.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-01-18 11:55:48
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPGRTBLD_LOADED
#define __DBU_CWIPGRTBLD_LOADED


struct CWIPGRTBLD_TAG
{
    char          FACTORY[10];
    char          ORDER_ID[25];
    char          LOT_ID[25];
    char          OPER[10];
    double        QTY_1;
    char          MAT_ID[30];
    int           SHEET_NO;
    double        PSD_UP;
    double        SS;
    double        OS;
    double        PSD_LO;
    double        TI;
    double        BI;
    double        TTI;
    double        MA;
    double        HLT;
    double        EILLPT;
    double        BTI;
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwipgrtbld(struct CWIPGRTBLD_TAG *CWIPGRTBLD);
extern void   DBU_select_cwipgrtbld(int sel_type, struct CWIPGRTBLD_TAG *CWIPGRTBLD);
extern void   DBU_select_cwipgrtbld_for_update(int sel_type, struct CWIPGRTBLD_TAG *CWIPGRTBLD);
extern double DBU_select_cwipgrtbld_scalar(int sel_type, struct CWIPGRTBLD_TAG *CWIPGRTBLD);
extern void   DBU_delete_cwipgrtbld(int sel_type, struct CWIPGRTBLD_TAG *CWIPGRTBLD);
extern void   DBU_insert_cwipgrtbld(struct CWIPGRTBLD_TAG *CWIPGRTBLD);
extern void   DBU_update_cwipgrtbld(int sel_type, struct CWIPGRTBLD_TAG *CWIPGRTBLD);
extern void   DBU_open_cwipgrtbld(int sel_type, struct CWIPGRTBLD_TAG *CWIPGRTBLD);
extern void   DBU_fetch_cwipgrtbld(int sel_type, struct CWIPGRTBLD_TAG *CWIPGRTBLD);
extern void   DBU_close_cwipgrtbld(int sel_type);


#endif               /* __DBU_CWIPGRTBLD_LOADED */

