/*********************************************************************
**
**    File Name   : DBU_cshporddtl.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-08-25 14:47:39
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CSHPORDDTL_LOADED
#define __DBU_CSHPORDDTL_LOADED


struct CSHPORDDTL_TAG
{
    char          FACTORY[10];
    char          SHIP_ORDER_ID[25];
    int           SEQ;
    char          MAT_ID[30];
    int           MAT_VER;
    double        QTY;
	double        SHIPPED_QTY;
    char          UNIT[10];
    char          SHIP_ORD_STATUS[10];
    char          SHIP_DATE[14];
    char          PACK_ORDER_ID[25];
    int           PACK_LINE_NO;
	int			  SHIPPING_LINE_ID;
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
	char		  DELETE_FLAG;
};


/* Function Declaration */
extern void   DBU_init_cshporddtl(struct CSHPORDDTL_TAG *CSHPORDDTL);
extern void   DBU_select_cshporddtl(int sel_type, struct CSHPORDDTL_TAG *CSHPORDDTL);
extern void   DBU_select_cshporddtl_for_update(int sel_type, struct CSHPORDDTL_TAG *CSHPORDDTL);
extern double DBU_select_cshporddtl_scalar(int sel_type, struct CSHPORDDTL_TAG *CSHPORDDTL);
extern void   DBU_delete_cshporddtl(int sel_type, struct CSHPORDDTL_TAG *CSHPORDDTL);
extern void   DBU_insert_cshporddtl(struct CSHPORDDTL_TAG *CSHPORDDTL);
extern void   DBU_update_cshporddtl(int sel_type, struct CSHPORDDTL_TAG *CSHPORDDTL);
extern void   DBU_open_cshporddtl(int sel_type, struct CSHPORDDTL_TAG *CSHPORDDTL);
extern void   DBU_fetch_cshporddtl(int sel_type, struct CSHPORDDTL_TAG *CSHPORDDTL);
extern void   DBU_close_cshporddtl(int sel_type);


#endif               /* __DBU_CSHPORDDTL_LOADED */

