/*********************************************************************
**
**    File Name   : DBU_cqcmrptgrm.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-10 18:12:51
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTGRM_LOADED
#define __DBU_CQCMRPTGRM_LOADED


struct CQCMRPTGRM_TAG
{
    char          FACTORY[10];
    char          REPORT_NO[20];
    char          LOT_ID[20];
    char          ITEM_CODE[20];
    char          GRADE[20];
    char          SIZES[20];
    char          HEADER_ID[20];
    int           LINE_NUMBER;
    char          CUST_NO[30];
    char          CUST_NAME[100];
    char          REPORT_DATE[8];
    char          INSP_VALUE[20];
    char          SHIP_NAME[100];
    char          WT[20];
    char          MEAN[20];
    char          SD[20];
    char          LP[20];
    char          ELEC_CONDUCTIVITY[20];
    char          VOL_STATIC01[20];
    char          VOL_STATIC02[20];
    char          VOL_STATIC03[20];
    char          VOL_STATIC04[20];
    char          VOL_STATIC05[20];
    char          VOL_STATIC06[20];
    char          VOL_STATIC07[20];
    char          VOL_STATIC08[20];
    char          VOL_STATIC09[20];
    char          IMAGE01[20];
    char          IMAGE02[20];
    char          IMAGE03[20];
    char          IMAGE04[20];
    char          IMAGE05[20];
    char          ANALYZER[20];
    char          WT_CHK[20];
    char          MEAN_CHK[20];
    char          SD_CHK[20];
    char          LP_CHK[20];
    char          ELEC_CONDUCTIVITY_CHK[5];
    char          VOL_STATIC01_CHK[5];
    char          VOL_STATIC02_CHK[5];
    char          VOL_STATIC03_CHK[5];
    char          VOL_STATIC04_CHK[5];
    char          VOL_STATIC05_CHK[5];
    char          VOL_STATIC06_CHK[5];
    char          VOL_STATIC07_CHK[5];
    char          VOL_STATIC08_CHK[5];
    char          VOL_STATIC09_CHK[5];
    char          IMAGE01_CHK[5];
    char          IMAGE02_CHK[5];
    char          IMAGE03_CHK[5];
    char          IMAGE04_CHK[5];
    char          IMAGE05_CHK[5];
    char          ATTRIBUTE01[50];
    char          ATTRIBUTE02[50];
    char          ATTRIBUTE03[50];
    char          ATTRIBUTE04[50];
    char          ATTRIBUTE05[50];
    char          ATTRIBUTE06[50];
    char          ATTRIBUTE07[50];
    char          ATTRIBUTE08[50];
    char          ATTRIBUTE09[50];
    char          ATTRIBUTE10[50];
    char          REMARKS[100];
    char          USE_YN;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
    char          SUB_IMAGE01[20];
    char          SUB_IMAGE02[20];
    char          SUB_IMAGE03[20];
    char          SUB_IMAGE04[20];
    char          SUB_IMAGE05[20];
    char          SUB_IMAGE06[20];
    char          RPT_CMF_1[50];
    char          RPT_CMF_2[50];
    char          RPT_CMF_3[50];
    char          RPT_CMF_4[50];
    char          RPT_CMF_5[50];
    char          RPT_CMF_6[50];
    char          RPT_CMF_7[50];
    char          RPT_CMF_8[50];
    char          RPT_CMF_9[50];
    char          RPT_CMF_10[50];
    char          RPT_CMF_11[50];
    char          RPT_CMF_12[50];
    char          RPT_CMF_13[50];
    char          RPT_CMF_14[50];
    char          RPT_CMF_15[50];
};


/* Function Declaration */
extern void   DBU_init_cqcmrptgrm(struct CQCMRPTGRM_TAG *CQCMRPTGRM);
extern void   DBU_select_cqcmrptgrm(int sel_type, struct CQCMRPTGRM_TAG *CQCMRPTGRM);
extern void   DBU_select_cqcmrptgrm_for_update(int sel_type, struct CQCMRPTGRM_TAG *CQCMRPTGRM);
extern double DBU_select_cqcmrptgrm_scalar(int sel_type, struct CQCMRPTGRM_TAG *CQCMRPTGRM);
extern void   DBU_delete_cqcmrptgrm(int sel_type, struct CQCMRPTGRM_TAG *CQCMRPTGRM);
extern void   DBU_insert_cqcmrptgrm(struct CQCMRPTGRM_TAG *CQCMRPTGRM);
extern void   DBU_update_cqcmrptgrm(int sel_type, struct CQCMRPTGRM_TAG *CQCMRPTGRM);
extern void   DBU_open_cqcmrptgrm(int sel_type, struct CQCMRPTGRM_TAG *CQCMRPTGRM);
extern void   DBU_fetch_cqcmrptgrm(int sel_type, struct CQCMRPTGRM_TAG *CQCMRPTGRM);
extern void   DBU_close_cqcmrptgrm(int sel_type);


#endif               /* __DBU_CQCMRPTGRM_LOADED */

