/*********************************************************************
**
**    File Name   : DBU_cwipwrkinp_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-12-05 16:39:47
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPWRKINP_N_LOADED
#define __DBU_CWIPWRKINP_N_LOADED


struct CWIPWRKINP_N_TAG
{
    int           WORK_SEQ;
    char          FACTORY[11];
    char          WORK_DATE[9];
    char          USER_ID[21];
    char          USER_DESC[201];
    char          AREA_ID[31];
    char          OPER[11];
    char          OPER_DESC[201];
    char          START_DT[9];
    char          START_TIME[7];
    char          END_DT[9];
    char          END_TIME[7];
    double        TOTAL_WORK_TIME;
    double        TOTAL_CONV_TIME;
    double        BREAK_TIME;
    double        WEK_01_ST_TIME;
    double        WEK_01_OV_TIME;
    double        WEK_02_ST_TIME;
    double        WEK_02_OV_TIME;
    double        HOL_01_ST_TIME;
    double        HOL_01_OV_TIME;
    double        HOL_02_ST_TIME;
    double        HOL_02_OV_TIME;
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          REMARKS[301];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPWRKINP_N_LOADED */

