/*********************************************************************
**
**    File Name   : DBU_cqcmsplmst.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2024-12-19 11:02:34
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2024 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMSPLMST_LOADED
#define __DBU_CQCMSPLMST_LOADED


struct CQCMSPLMST_TAG
{
    char          FACTORY[10];
    char          REPORT_NO[20];
    char          CUST_NO[100];
    char          CUST_NAME[100];
    char          EVENT_DATE[8];
    char          RECEIVED_DATE_1[8];
    char          RECEIVED_DATE_2[8];
    char          RECEIVED_DATE_3[8];
    char          GRADE[20];
    char          MAT_ID[30];
    char          MAT_DESC[200];
    char          CLOSURE_DATE[8];
    char          SHARE_DATE[8];
    char          SAL_GROUP[20];
    char          SAL_USER[200];
    char          ANALYZE_STATUS;
    int           COST_QTY_01;
    int           COST_QTY_02;
    int           COST_QTY_03;
    int           COST_MONTH;
    char          FILE_NO_01[20];
    char          FILE_PATH_01[300];
    char          FILE_NO_02[20];
    char          FILE_PATH_02[300];
    char          FILE_NO_03[20];
    char          FILE_PATH_03[300];
    char          FILE_NO_04[20];
    char          FILE_PATH_04[300];
    char          FILE_NO_05[20];
    char          FILE_PATH_05[300];
    char          COMMENT_01[1000];
    char          COMMENT_02[1000];
    char          COMMENT_03[1000];
    char          COMMENT_04[1000];
    char          COMMENT_05[1000];
    char          COMMENT_06[1000];
    char          COMMENT_07[1000];
    char          COMMENT_08[1000];
    char          COMMENT_09[1000];
    char          COMMENT_10[1000];
    char          CMF_01[50];
    char          CMF_02[50];
    char          CMF_03[50];
    char          CMF_04[50];
    char          CMF_05[50];
    char          CMF_06[50];
    char          CMF_07[50];
    char          CMF_08[50];
    char          CMF_09[50];
    char          CMF_10[50];
    char          USE_YN;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cqcmsplmst(struct CQCMSPLMST_TAG *CQCMSPLMST);
extern void   DBU_select_cqcmsplmst(int sel_type, struct CQCMSPLMST_TAG *CQCMSPLMST);
extern void   DBU_select_cqcmsplmst_for_update(int sel_type, struct CQCMSPLMST_TAG *CQCMSPLMST);
extern double DBU_select_cqcmsplmst_scalar(int sel_type, struct CQCMSPLMST_TAG *CQCMSPLMST);
extern void   DBU_delete_cqcmsplmst(int sel_type, struct CQCMSPLMST_TAG *CQCMSPLMST);
extern void   DBU_insert_cqcmsplmst(struct CQCMSPLMST_TAG *CQCMSPLMST);
extern void   DBU_update_cqcmsplmst(int sel_type, struct CQCMSPLMST_TAG *CQCMSPLMST);
extern void   DBU_open_cqcmsplmst(int sel_type, struct CQCMSPLMST_TAG *CQCMSPLMST);
extern void   DBU_fetch_cqcmsplmst(int sel_type, struct CQCMSPLMST_TAG *CQCMSPLMST);
extern void   DBU_close_cqcmsplmst(int sel_type);


#endif               /* __DBU_CQCMSPLMST_LOADED */

