/*********************************************************************
**
**    File Name   : DBU_crasbalmil.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2022-03-23 15:50:55
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2022 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRASBALMIL_LOADED
#define __DBU_CRASBALMIL_LOADED


struct CRASBALMIL_TAG
{
    char          RES_ID[20];
    int           HIST_SEQ;
    char          WORK_TIME[14];
    char          FACTORY[10];
    char          WORK_DATE[8];
    char          DAY_NIGHT[10];
    char          SV_TIME[14];
    char          PV_TIME[14];
	double		  SV_RPM;
    double        PV_RPM;
    char          RES_STATUS;
    char          START_TIME[14];
    char          END_TIME[14];
    char          EVENT_ID[12];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_crasbalmil(struct CRASBALMIL_TAG *CRASBALMIL);
extern void   DBU_select_crasbalmil(int sel_type, struct CRASBALMIL_TAG *CRASBALMIL);
extern void   DBU_select_crasbalmil_for_update(int sel_type, struct CRASBALMIL_TAG *CRASBALMIL);
extern double DBU_select_crasbalmil_scalar(int sel_type, struct CRASBALMIL_TAG *CRASBALMIL);
extern void   DBU_delete_crasbalmil(int sel_type, struct CRASBALMIL_TAG *CRASBALMIL);
extern void   DBU_insert_crasbalmil(struct CRASBALMIL_TAG *CRASBALMIL);
extern void   DBU_update_crasbalmil(int sel_type, struct CRASBALMIL_TAG *CRASBALMIL);
extern void   DBU_open_crasbalmil(int sel_type, struct CRASBALMIL_TAG *CRASBALMIL);
extern void   DBU_fetch_crasbalmil(int sel_type, struct CRASBALMIL_TAG *CRASBALMIL);
extern void   DBU_close_crasbalmil(int sel_type);


#endif               /* __DBU_CRASBALMIL_LOADED */

