/*********************************************************************
**
**    File Name   : DBU_cwippryer_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2021-05-14 11:14:10
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2021 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPPRYER_N_LOADED
#define __DBU_CWIPPRYER_N_LOADED


struct CWIPPRYER_N_TAG
{
    char          FACTORY[11];
    char          STD_YEAR[26];
    int           STD_TYPE;
    char          STD_TYPE_DESC[26];
    char          AREA_ID[21];
    double        QTR_01;
    double        QTR_02;
    double        QTR_03;
    double        QTR_04;
    double        MTH_01;
    double        MTH_02;
    double        MTH_03;
    double        MTH_04;
    double        MTH_05;
    double        MTH_06;
    double        MTH_07;
    double        MTH_08;
    double        MTH_09;
    double        MTH_10;
    double        MTH_11;
    double        MTH_12;
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CMF_11[31];
    char          CMF_12[31];
    char          REMARK[301];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CWIPPRYER_N_LOADED */

