/*********************************************************************
**
**    File Name   : DBU_crasrprwrk_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-23 17:40:01
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRASRPRWRK_N_LOADED
#define __DBU_CRASRPRWRK_N_LOADED


struct CRASRPRWRK_N_TAG
{
    char          FACTORY[11];
    char          REPAIR_ID[21];
    char          WORKER_ID[21];
    char          WORKER_DESC[31];
    char          CMF_1[31];
    char          CMF_2[31];
    char          CMF_3[31];
    char          CMF_4[31];
    char          CMF_5[31];
    char          CMF_6[31];
    char          CMF_7[31];
    char          CMF_8[31];
    char          CMF_9[31];
    char          CMF_10[31];
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CRASRPRWRK_N_LOADED */

