/*********************************************************************
**
**    File Name   : DBU_cbastxndef_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-05 13:29:18
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CBASTXNDEF_N_LOADED
#define __DBU_CBASTXNDEF_N_LOADED


struct CBASTXNDEF_N_TAG
{
	char          FACTORY[11];
	int           ERP_AREA_ID;
	char          AREA_ID[21];
	int           TRAN_TYPE_ID;
	char          TRAN_TYPE_NAME[81];
	int           TRAN_SRC_ID;
	char          TRAN_SRC_DESC[51];
	char          USER_DEFINED_FLAG[2];
	char          ISSUE_RECEIPT_FLAG[8];
	int           TRAN_ACTION_ID;
	int           TRAN_SRC_TYPE_ID;
	char          TRAN_SRC_TYPE_NAME[241];
	char          MRO_FLAG[2];
	char          ENABLED_FLAG[2];
	char          DISABLE_DATE[15];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_CBASTXNDEF_N_LOADED */

