/*********************************************************************
**
**    File Name   : DBU_minvlotsts_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-31 16:59:27
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MINVLOTSTS_N_LOADED
#define __DBU_MINVLOTSTS_N_LOADED


struct MINVLOTSTS_N_TAG
{
    char          FACTORY[11];
    char          INV_LOT_ID[26];
    char          INV_LOT_DESC[201];
    char          INV_LOT_TYPE[21];
    char          INV_LOT_STATUS[11];
    char          INV_LOT_PRIORITY[2];
    char          MAT_ID[31];
    int           MAT_VER;
    double        QTY;
    double        QTY_2;
    double        QTY_3;
    char          UNIT[11];
    char          UNIT_2[11];
    char          UNIT_3[11];
    char          ORDER_ID[26];
    char          ADD_ORDER_ID_1[26];
    char          ADD_ORDER_ID_2[26];
    char          ADD_ORDER_ID_3[26];
    char          VENDOR_ID[21];
	int			  VENDOR_SITE_ID;
    char          VENDOR_LOT_ID[51];
    char          AREA_ID[21];
    char          SUB_AREA_ID[21];
    char          LOCATION_1[21];
    char          LOCATION_2[21];
    char          LOCATION_3[21];
    char          OPER[11];
    char          LOC_NO[31];
    char          RES_ID[21];
    char          PORT_ID[11];
    char          SLOT_NO[11];
    char          CRR_ID[21];
    char          LOT_ID[26];
    char          RECV_DATE[9];
    double        RECV_QTY;
    char          REASON_CODE[31];
    char          LOAD_FLAG[2];
    char          TRANSIT_FLAG[2];
    char          DELETE_FLAG[2];
    char          DELETE_CODE[31];
    char          DELETE_USER_ID[21];
    char          DELETE_TIME[15];
    char          HOLD_FLAG[2];
    char          HOLD_CODE[31];
    char          INSP_FLAG[2];
    char          INSP_ID[31];
    char          INSP_RESULT_FLAG[2];
    char          INV_LOT_GRADE[11];
    char          DLV_NO[31];
	int           DLV_SEQ;
    char          PO_NO[31];
    int           PO_SEQ;
    char          BL_NO[31];
    int           BL_SEQ;
	int			  PO_DISTRIBUTION_ID;
    char          INV_CMF_1[31];
    char          INV_CMF_2[31];
    char          INV_CMF_3[31];
    char          INV_CMF_4[31];
    char          INV_CMF_5[31];
    char          INV_CMF_6[31];
    char          INV_CMF_7[31];
    char          INV_CMF_8[31];
    char          INV_CMF_9[31];
    char          INV_CMF_10[31];
    char          INV_CMF_11[31];
    char          INV_CMF_12[31];
    char          INV_CMF_13[31];
    char          INV_CMF_14[31];
    char          INV_CMF_15[31];
    char          INV_CMF_16[31];
    char          INV_CMF_17[31];
    char          INV_CMF_18[31];
    char          INV_CMF_19[31];
    char          INV_CMF_20[31];
    char          LAST_TRAN_CODE[31];
    char          LAST_TRAN_TIME[15];
    char          LAST_TRAN_COMMENT[401];
    int           LAST_ACTIVE_HIST_SEQ;
    int           LAST_HIST_SEQ;
    char          ORG_INV_LOT_ID[26];
    char          FROM_TO_DIV[2];
    char          FROM_TO_INV_LOT_ID[26];
    int           FROM_TO_HIST_SEQ;
    double        CREATE_QTY;
    double        CREATE_QTY_2;
    double        CREATE_QTY_3;
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_MINVLOTSTS_N_LOADED */

