/*********************************************************************
**
**    File Name   : DBU_crasrprwrk.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-07-23 17:40:01
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CRASRPRWRK_LOADED
#define __DBU_CRASRPRWRK_LOADED


struct CRASRPRWRK_TAG
{
    char          FACTORY[10];
    char          REPAIR_ID[20];
    char          WORKER_ID[20];
    char          WORKER_DESC[30];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_crasrprwrk(struct CRASRPRWRK_TAG *CRASRPRWRK);
extern void   DBU_select_crasrprwrk(int sel_type, struct CRASRPRWRK_TAG *CRASRPRWRK);
extern void   DBU_select_crasrprwrk_for_update(int sel_type, struct CRASRPRWRK_TAG *CRASRPRWRK);
extern double DBU_select_crasrprwrk_scalar(int sel_type, struct CRASRPRWRK_TAG *CRASRPRWRK);
extern void   DBU_delete_crasrprwrk(int sel_type, struct CRASRPRWRK_TAG *CRASRPRWRK);
extern void   DBU_insert_crasrprwrk(struct CRASRPRWRK_TAG *CRASRPRWRK);
extern void   DBU_update_crasrprwrk(int sel_type, struct CRASRPRWRK_TAG *CRASRPRWRK);
extern void   DBU_open_crasrprwrk(int sel_type, struct CRASRPRWRK_TAG *CRASRPRWRK);
extern void   DBU_fetch_crasrprwrk(int sel_type, struct CRASRPRWRK_TAG *CRASRPRWRK);
extern void   DBU_close_crasrprwrk(int sel_type);


#endif               /* __DBU_CRASRPRWRK_LOADED */

