/*********************************************************************
**
**    File Name   : DBU_if_wo_bom_info_his_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-14 16:37:15
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_WO_BOM_INFO_HIS_N_LOADED
#define __DBU_IF_WO_BOM_INFO_HIS_N_LOADED


struct IF_WO_BOM_INFO_HIS_N_TAG
{
	int           IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	int           ORG_ID;
	char          ORG_CODE[4];
	int           WIP_ENTITY_ID;
	char          WIP_ENTITY_NAME[241];
	int           ITEM_ID;
	char          ITEM_CODE[41];
	int           COMP_ITEM_ID;
	char          COMP_ITEM_CODE[41];
	char          COMP_ITEM_DESC[241];
	char          COMP_ITEM_TYPE[31];
	char          COMP_ITEM_UNIT[4];
	char          ALTERNATE_BOM_DESIGNATOR[11];
	char          ALTER_RTG_NAME[11];
	int           OPER_SEQ;
	int           OPER_ID;
	char          OPER[11];
	char          OPER_DESC[241];
	int           DEPT_ID;
	char          DEPT_CODE[11];
	char          DEPT_DESC[241];
	double        TOTAL_QTY;
	double        ISSUED_QTY;
	double        UNIT_QTY;
	int           SUPPLY_TYPE;
	char          SUPPLY_TYPE_NAME[241];
	char          SUPPLY_INV_OPER[11];
	char          TRAN_FLAG[2];
	char          CMF_1[51];
	char          CMF_2[51];
	char          CMF_3[51];
	char          CMF_4[51];
	char          CMF_5[51];
	char          CMF_6[51];
	char          CMF_7[51];
	char          CMF_8[51];
	char          CMF_9[51];
	char          CMF_10[51];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_WO_BOM_INFO_HIS_N_LOADED */

