/*********************************************************************
**
**    File Name   : DBU_cqcmisplos.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-07 08:57:33
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMISPLOS_LOADED
#define __DBU_CQCMISPLOS_LOADED


struct CQCMISPLOS_TAG
{
	char          FACTORY[10];
	char          INSP_ID[30];
	int           SEQ;
	char          QTY_FLAG;
	char          LOSS_CODE[10];
	double        LOSS_QTY;
	char          LOT_ID[25];
	int           HIST_SEQ;
	char          TRAN_TIME[14];
	char          MAT_ID[30];
	int           MAT_VER;
	char          FLOW[20];
	int           FLOW_SEQ;
	char          OPER[30];
	char          RES_ID[20];
	char          MAIN_FLAG;
};


/* Function Declaration */
extern void   DBU_init_cqcmisplos(struct CQCMISPLOS_TAG *CQCMISPLOS);
extern void   DBU_select_cqcmisplos(int sel_type, struct CQCMISPLOS_TAG *CQCMISPLOS);
extern void   DBU_select_cqcmisplos_for_update(int sel_type, struct CQCMISPLOS_TAG *CQCMISPLOS);
extern double DBU_select_cqcmisplos_scalar(int sel_type, struct CQCMISPLOS_TAG *CQCMISPLOS);
extern void   DBU_delete_cqcmisplos(int sel_type, struct CQCMISPLOS_TAG *CQCMISPLOS);
extern void   DBU_insert_cqcmisplos(struct CQCMISPLOS_TAG *CQCMISPLOS);
extern void   DBU_update_cqcmisplos(int sel_type, struct CQCMISPLOS_TAG *CQCMISPLOS);
extern void   DBU_open_cqcmisplos(int sel_type, struct CQCMISPLOS_TAG *CQCMISPLOS);
extern void   DBU_fetch_cqcmisplos(int sel_type, struct CQCMISPLOS_TAG *CQCMISPLOS);
extern void   DBU_close_cqcmisplos(int sel_type);


#endif               /* __DBU_CQCMISPLOS_LOADED */

