/*********************************************************************
**
**    File Name   : DBU_cwipgrtcls.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-05 09:40:07
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPGRTCLS_LOADED
#define __DBU_CWIPGRTCLS_LOADED


struct CWIPGRTCLS_TAG
{
    char          FACTORY[10];
    char          MAT_GROUP[20];
    char          INPUT_MAT_ID[30];
    char          CLASS_TYPE[10];
    char          CLASS_VALUE[30];
    char          OUT_MAT_ID[30];
    char          CMF_1[30];
    char          CMF_2[30];
    char          CMF_3[30];
    char          CMF_4[30];
    char          CMF_5[30];
    char          CMF_6[30];
    char          CMF_7[30];
    char          CMF_8[30];
    char          CMF_9[30];
    char          CMF_10[30];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_cwipgrtcls(struct CWIPGRTCLS_TAG *CWIPGRTCLS);
extern void   DBU_select_cwipgrtcls(int sel_type, struct CWIPGRTCLS_TAG *CWIPGRTCLS);
extern void   DBU_select_cwipgrtcls_for_update(int sel_type, struct CWIPGRTCLS_TAG *CWIPGRTCLS);
extern double DBU_select_cwipgrtcls_scalar(int sel_type, struct CWIPGRTCLS_TAG *CWIPGRTCLS);
extern void   DBU_delete_cwipgrtcls(int sel_type, struct CWIPGRTCLS_TAG *CWIPGRTCLS);
extern void   DBU_insert_cwipgrtcls(struct CWIPGRTCLS_TAG *CWIPGRTCLS);
extern void   DBU_update_cwipgrtcls(int sel_type, struct CWIPGRTCLS_TAG *CWIPGRTCLS);
extern void   DBU_open_cwipgrtcls(int sel_type, struct CWIPGRTCLS_TAG *CWIPGRTCLS);
extern void   DBU_fetch_cwipgrtcls(int sel_type, struct CWIPGRTCLS_TAG *CWIPGRTCLS);
extern void   DBU_close_cwipgrtcls(int sel_type);


#endif               /* __DBU_CWIPGRTCLS_LOADED */

