/*********************************************************************
**
**    File Name   : DBU_cwiplottrc_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-15 13:42:50
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CWIPLOTTRC_N_LOADED
#define __DBU_CWIPLOTTRC_N_LOADED


struct CWIPLOTTRC_N_TAG
{
    char          FACTORY[11];
    char          AREA_ID[21];
    char          SUB_AREA_ID[21];
    char          OPER[11];
    char          LOT_ID[26];
    int           LOT_HIST_SEQ;
    char          FROM_LOT_ID[26];
    int           FROM_LOT_HIST_SEQ;
	char          TRACE_FLAG[2];
	char          TRAN_CODE[13];
};


#endif               /* __DBU_CWIPLOTTRC_N_LOADED */

