/*********************************************************************
**
**    File Name   : DBU_if_so_dtl_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-14 16:35:14
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_SO_DTL_N_LOADED
#define __DBU_IF_SO_DTL_N_LOADED


struct IF_SO_DTL_N_TAG
{
	int           IF_SEQ;
	char          IF_TIME[15];
	char          IF_CODE[2];
	char          IF_MSG[201];
	char          FACTORY[11];
	int           SHIPPING_LINE_ID;
	int           SHIPPING_LINE_NUM;
	int           SHIPPING_HEADER_ID;
	int           D4_SUM_ID;
	int           OE_HEADER_ID;
	int           OE_LINE_ID;
	char          ORDER_TYPE[31];
	char          PRICE_TYPE[31];
	int           ITEM_ID;
	char          ITEM_CODE[41];
	char          ITEM_DESC[241];
	double        SHIPPING_QTY;
	char          SHIPPING_UOM[4];
	double        SALES_PRICE;
	char          CURRENCY_CODE[16];
	char          DATE_REQUESTED[15];
	char          DATE_SCHEDULED[15];
	char          RELEASED_STATUS[2];
	int           SHIP_TO_ORG_ID;
	int           INVOICE_TO_ORG_ID;
	char          SHIP_FROM_INV_OPER[11];
	char          TRX_INV_OPER[11];
	char          SHIP_TO_INV_OPER[11];
	char          ACTUAL_DEPARTURE_DATE[15];
	char          PICK_STATUS[2];
	char          SHIP_STATUS[3];
	char          SHIP_TO_LOCATION[41];
	int           PICK_CONFIRM_ID;
	char          ORIG_SYS_LINE_REF[51];
	int           DATE_SEQ;
	char          SALESPERSON[241];
	int           SHIP_CONFIRM_ID;
	double        PALLET_UNIT_QTY;
	double        ITEM_UNIT_WEIGHT;
	double        PALLET_WEIGHT;
	int           PALLET_CNT;
	double        TOTAL_WEIGHT;
	char          ATTRIBUTE1[151];
	char          ATTRIBUTE2[151];
	char          ATTRIBUTE3[151];
	char          ATTRIBUTE4[151];
	char          ATTRIBUTE5[151];
	char          DEALING_NUMBER[51];
	char          CUSTOMER_ITEM_CODE[51];
	char          CUSTOMER_ITEM_DESC[1001];
	char          DEMAND_CLASS[31];
	char          SHIPPING_DATE[15];
	int           ORDER_NUMBER;
	int           LINE_NUMBER;
	int           CREATED_BY;
	int           LAST_UPDATED_BY;
	int           LAST_UPDATE_LOGIN;
	char          TRAN_FLAG[2];
	char          CMF_1[51];
	char          CMF_2[51];
	char          CMF_3[51];
	char          CMF_4[51];
	char          CMF_5[51];
	char          CMF_6[51];
	char          CMF_7[51];
	char          CMF_8[51];
	char          CMF_9[51];
	char          CMF_10[51];
	char          CREATE_USER_ID[21];
	char          CREATE_TIME[15];
	char          UPDATE_USER_ID[21];
	char          UPDATE_TIME[15];
};


#endif               /* __DBU_IF_SO_DTL_N_LOADED */

