/*********************************************************************
**
**    File Name   : DBU_cqcmgrtsiv_n.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-03 12:22:27
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMGRTSIV_N_LOADED
#define __DBU_CQCMGRTSIV_N_LOADED


struct CQCMGRTSIV_N_TAG
{
    char          FACTORY[11];
    char          INSP_ID[31];
    char          INSP_DTL_TYPE[31];
    int           INSP_COUNT;
    int           INSP_SEQ;
    char          SIEVE_CODE[31];
    char          SIZES[31];
    double        SIEVE_VALUE;
    double        COUNT_1;
    double        NOT_SIEVE_1;
    double        EXIST_SIEVE_1;
    double        DIFF_SIEVE_1;
    double        TI_VALUE_1;
    double        COUNT_2;
    double        NOT_SIEVE_2;
    double        EXIST_SIEVE_2;
    double        DIFF_SIEVE_2;
    double        TI_VALUE_2;
    double        SUM_DIFF_SIEVE;
    double        RATIO_SIEVE;
    double        AVG_SIEVE;
    double        TI_CHANGE;
    char          CREATE_USER_ID[21];
    char          CREATE_TIME[15];
    char          UPDATE_USER_ID[21];
    char          UPDATE_TIME[15];
};


#endif               /* __DBU_CQCMGRTSIV_N_LOADED */

