/*********************************************************************
**
**    File Name   : DBU_if_pack_info_his.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-10-23 15:43:26
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_IF_PACK_INFO_HIS_LOADED
#define __DBU_IF_PACK_INFO_HIS_LOADED


struct IF_PACK_INFO_HIS_TAG
{
	int           IF_SEQ;
	char          IF_TIME[14];
	char          IF_CODE;
	char          IF_MSG[200];
	char          FACTORY[10];
	int           OU_ID;
	int           ORG_ID;
	char          ORG_CODE[3];
	int           ORDER_HEADER_ID;
	int           ORDER_NUMBER;
	int           LINE_NUMBER;
	int           ORDER_TYPE_ID;
	char          ORDERED_DATE[14];
	char          BOOKED_DATE[3];
	int           ITEM_ID;
	char          ITEM_CODE[40];
	char          ITEM_DESC[240];
	char          LABEL_NAME[1000];
	int           CUSTOMER_ID;
	char          CUSTOMER_NUMBER[30];
	char          CUSTOMER_NAME[50];
	int           SHIP_TO_SITE_USE_ID;
	char          SHIP_TO_NAME[40];
	int           END_SHIP_TO_ID;
	char          END_SHIP_TO_NAME[240];
	char          DRAWING_FLAG[2000];
	char          PACKING_INSTRUCTIONS[2000];
	char          ORDER_TYPE[30];
	char          REQUEST_DATE[14];
	char          SCHEDULE_SHIP_DATE[14];
	char          SCHEDULE_ARRIVAL_DATE[14];
	char          PROMISE_DATE[14];
	char          INCLUDE_INSPECTION[240];
	char          LABEL_TYPE[240];
	char          LABEL_MESH[240];
	char          LINE_DESC[240];
	char          ORDER_UNIT[3];
	char          CURRENCY_CODE[15];
	double        ORDERED_QTY;
	double        SHIPED_QTY;
	double        CANCELED_QTY;
	double        UNIT_SELLING_PRICE;
	double        UNIT_SELLING_PRICE_KR;
	char          ALLOCATE_FLAG[240];
	char          CUSTOMER_PO_NO[240];
	char          CUST_ITME_NAME[240];
	char          CUST_ITEM_TYPE[240];
	char          REST[240];
	char          CUSTOMER_PO_LINE[240];
	char          FORMAT_ID[240];
	char          CUSTOMER_PO[240];
	char          PO_GUBUN[240];
	char          TRAN_FLAG;
	int           IF_GROUP_ID;
	char          CMF_2[50];
	char          CMF_3[50];
	char          CMF_4[50];
	char          CMF_5[50];
	char          CMF_6[50];
	char          CMF_7[50];
	char          CMF_8[50];
	char          CMF_9[50];
	char          CMF_10[50];
	char          CREATE_USER_ID[20];
	char          CREATE_TIME[14];
	char          UPDATE_USER_ID[20];
	char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_if_pack_info_his(struct IF_PACK_INFO_HIS_TAG *IF_PACK_INFO_HIS);
extern void   DBU_select_if_pack_info_his(int sel_type, struct IF_PACK_INFO_HIS_TAG *IF_PACK_INFO_HIS);
extern void   DBU_select_if_pack_info_his_for_update(int sel_type, struct IF_PACK_INFO_HIS_TAG *IF_PACK_INFO_HIS);
extern double DBU_select_if_pack_info_his_scalar(int sel_type, struct IF_PACK_INFO_HIS_TAG *IF_PACK_INFO_HIS);
extern void   DBU_delete_if_pack_info_his(int sel_type, struct IF_PACK_INFO_HIS_TAG *IF_PACK_INFO_HIS);
extern void   DBU_insert_if_pack_info_his(struct IF_PACK_INFO_HIS_TAG *IF_PACK_INFO_HIS);
extern void   DBU_update_if_pack_info_his(int sel_type, struct IF_PACK_INFO_HIS_TAG *IF_PACK_INFO_HIS);
extern void   DBU_open_if_pack_info_his(int sel_type, struct IF_PACK_INFO_HIS_TAG *IF_PACK_INFO_HIS);
extern void   DBU_fetch_if_pack_info_his(int sel_type, struct IF_PACK_INFO_HIS_TAG *IF_PACK_INFO_HIS);
extern void   DBU_close_if_pack_info_his(int sel_type);


#endif               /* __DBU_IF_PACK_INFO_HIS_LOADED */

