/*********************************************************************
**
**    File Name   : DBU_cqcmrpthmm.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-11-02 15:46:49
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CQCMRPTHMM_LOADED
#define __DBU_CQCMRPTHMM_LOADED


struct CQCMRPTHMM_TAG
{
    char          FACTORY[10];
    char          REPORT_NO[20];
    char          PACK_LOT_ID[20];
    char          ORG_LOT_ID[25];
    char          GRADE[30];
    char          TYPES[50];
    char          PACK_ORDER_ID[20];
    char          CUSTOMER_ID[100];
    double        LOT_QTY;
    char          OD_METER[30];
    char          ID_METER[30];
    char          HEIGHT[30];
    char          DIA_METER[30];
    char          LENGTH[30];
    char          DENSITY[30];
    char          MAG_SAT[30];
    char          COER_FORCE[30];
    char          HARDNESS_HV20[30];
    char          HARDNESS_HRA[30];
    char          TRS[30];
    char          ATTRIBUTE01[100];
    char          ATTRIBUTE02[100];
    char          ATTRIBUTE03[100];
    char          ATTRIBUTE04[100];
    char          ATTRIBUTE05[100];
    char          COMMENTS[100];
    char          IMAGE_NUM1[20];
    char          IMAGE_NUM2[20];
    char          PITCH_AVG[20];
    char          ROUGHNESS_AVG[20];
    char          ROUGHNESS_STD[20];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
    char          GRAIN_SIZE[30];
    char          DENSITY_SPEC[50];
    char          MAG_SAT_SPEC[50];
    char          COER_FORCE_SPEC[50];
    char          HARDNESS_HV20_SPEC[50];
    char          TRS_SPEC[50];
    char          GRAIN_SIZE_SPEC[50];
    char          RPT_CMF_1[50];
    char          RPT_CMF_2[50];
    char          RPT_CMF_3[50];
    char          RPT_CMF_4[50];
    char          RPT_CMF_5[50];
    char          RPT_CMF_6[50];
    char          RPT_CMF_7[50];
    char          RPT_CMF_8[50];
    char          RPT_CMF_9[50];
    char          RPT_CMF_10[50];
    char          RPT_CMF_11[50];
    char          RPT_CMF_12[50];
    char          RPT_CMF_13[50];
    char          RPT_CMF_14[50];
    char          RPT_CMF_15[50];
};


/* Function Declaration */
extern void   DBU_init_cqcmrpthmm(struct CQCMRPTHMM_TAG *CQCMRPTHMM);
extern void   DBU_select_cqcmrpthmm(int sel_type, struct CQCMRPTHMM_TAG *CQCMRPTHMM);
extern void   DBU_select_cqcmrpthmm_for_update(int sel_type, struct CQCMRPTHMM_TAG *CQCMRPTHMM);
extern double DBU_select_cqcmrpthmm_scalar(int sel_type, struct CQCMRPTHMM_TAG *CQCMRPTHMM);
extern void   DBU_delete_cqcmrpthmm(int sel_type, struct CQCMRPTHMM_TAG *CQCMRPTHMM);
extern void   DBU_insert_cqcmrpthmm(struct CQCMRPTHMM_TAG *CQCMRPTHMM);
extern void   DBU_update_cqcmrpthmm(int sel_type, struct CQCMRPTHMM_TAG *CQCMRPTHMM);
extern void   DBU_open_cqcmrpthmm(int sel_type, struct CQCMRPTHMM_TAG *CQCMRPTHMM);
extern void   DBU_fetch_cqcmrpthmm(int sel_type, struct CQCMRPTHMM_TAG *CQCMRPTHMM);
extern void   DBU_close_cqcmrpthmm(int sel_type);


#endif               /* __DBU_CQCMRPTHMM_LOADED */

