/*********************************************************************
**
**    File Name   : DBU_csecusrdef.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2024-09-12 09:24:38
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2024 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_CSECUSRDEF_LOADED
#define __DBU_CSECUSRDEF_LOADED


struct CSECUSRDEF_TAG
{
    char          FACTORY[10];
    char          EOH_TIME[14];
    char          USER_ID[20];
    char          USER_DESC[200];
    char          PASSWORD[20];
    char          CHG_PASS_FLAG;
    char          USER_GRP_1[30];
    char          USER_GRP_2[30];
    char          USER_GRP_3[30];
    char          USER_GRP_4[30];
    char          USER_GRP_5[30];
    char          USER_GRP_6[30];
    char          USER_GRP_7[30];
    char          USER_GRP_8[30];
    char          USER_GRP_9[30];
    char          USER_GRP_10[30];
    char          USER_CMF_1[30];
    char          USER_CMF_2[30];
    char          USER_CMF_3[30];
    char          USER_CMF_4[30];
    char          USER_CMF_5[30];
    char          USER_CMF_6[30];
    char          USER_CMF_7[30];
    char          USER_CMF_8[30];
    char          USER_CMF_9[30];
    char          USER_CMF_10[30];
    char          SEC_GRP_ID[20];
    char          PHONE_OFFICE[20];
    char          PHONE_MOBILE[20];
    char          PHONE_HOME[20];
    char          PHONE_OTHER[20];
    char          EXPIRE_DATE[8];
    char          PASS_EXPIRE_DATE[8];
    char          ENTER_DATE[8];
    char          RETIRE_DATE[8];
    char          EMAIL_ID[50];
    char          BIRTHDAY[8];
    char          SEX_FLAG;
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};


/* Function Declaration */
extern void   DBU_init_csecusrdef(struct CSECUSRDEF_TAG *CSECUSRDEF);
extern void   DBU_select_csecusrdef(int sel_type, struct CSECUSRDEF_TAG *CSECUSRDEF);
extern void   DBU_select_csecusrdef_for_update(int sel_type, struct CSECUSRDEF_TAG *CSECUSRDEF);
extern double DBU_select_csecusrdef_scalar(int sel_type, struct CSECUSRDEF_TAG *CSECUSRDEF);
extern void   DBU_delete_csecusrdef(int sel_type, struct CSECUSRDEF_TAG *CSECUSRDEF);
extern void   DBU_insert_csecusrdef(struct CSECUSRDEF_TAG *CSECUSRDEF);
extern void   DBU_update_csecusrdef(int sel_type, struct CSECUSRDEF_TAG *CSECUSRDEF);
extern void   DBU_open_csecusrdef(int sel_type, struct CSECUSRDEF_TAG *CSECUSRDEF);
extern void   DBU_fetch_csecusrdef(int sel_type, struct CSECUSRDEF_TAG *CSECUSRDEF);
extern void   DBU_close_csecusrdef(int sel_type);


#endif               /* __DBU_CSECUSRDEF_LOADED */

