/*********************************************************************
**
**    File Name   : DBU_medccoldef.h
**    DB Type     : Unix Oracle
**    Description : Table Structure Definition Header File
**    Create date : 2020-09-08 16:50:24
**
**    Generated by DB Common Generator
**    Copyright (C) 1998-2020 MIRACOM,INC.
**
*********************************************************************/

#ifndef __DBU_MEDCCOLDEF_LOADED
#define __DBU_MEDCCOLDEF_LOADED

/*
struct MEDCCOLDEF_TAG
{
    char          FACTORY[10];
    char          COL_SET_ID[25];
    char          COL_SET_DESC[200];
    char          COL_GRP_1[30];
    char          COL_GRP_2[30];
    char          COL_GRP_3[30];
    char          COL_GRP_4[30];
    char          COL_GRP_5[30];
    char          COL_GRP_6[30];
    char          COL_GRP_7[30];
    char          COL_GRP_8[30];
    char          COL_GRP_9[30];
    char          COL_GRP_10[30];
    char          COL_CMF_1[30];
    char          COL_CMF_2[30];
    char          COL_CMF_3[30];
    char          COL_CMF_4[30];
    char          COL_CMF_5[30];
    char          COL_CMF_6[30];
    char          COL_CMF_7[30];
    char          COL_CMF_8[30];
    char          COL_CMF_9[30];
    char          COL_CMF_10[30];
    char          DEFAULT_COL_MODE_FLAG;
    char          LOT_OR_RES_FLAG;
    char          APPROVAL_REQUIRE_FLAG;
    char          APPROVAL_USER_ID[20];
    char          DELETE_FLAG;
    char          DELETE_USER_ID[20];
    char          DELETE_TIME[14];
    char          CREATE_USER_ID[20];
    char          CREATE_TIME[14];
    char          UPDATE_USER_ID[20];
    char          UPDATE_TIME[14];
};
*/

/* Function Declaration */
extern void   DBU_init_medccoldef(struct MEDCCOLDEF_TAG *MEDCCOLDEF);
extern void   DBU_select_medccoldef(int sel_type, struct MEDCCOLDEF_TAG *MEDCCOLDEF);
extern void   DBU_select_medccoldef_for_update(int sel_type, struct MEDCCOLDEF_TAG *MEDCCOLDEF);
extern double DBU_select_medccoldef_scalar(int sel_type, struct MEDCCOLDEF_TAG *MEDCCOLDEF);
extern void   DBU_delete_medccoldef(int sel_type, struct MEDCCOLDEF_TAG *MEDCCOLDEF);
extern void   DBU_insert_medccoldef(struct MEDCCOLDEF_TAG *MEDCCOLDEF);
extern void   DBU_update_medccoldef(int sel_type, struct MEDCCOLDEF_TAG *MEDCCOLDEF);
extern void   DBU_open_medccoldef(int sel_type, struct MEDCCOLDEF_TAG *MEDCCOLDEF);
extern void   DBU_fetch_medccoldef(int sel_type, struct MEDCCOLDEF_TAG *MEDCCOLDEF);
extern void   DBU_close_medccoldef(int sel_type);


#endif               /* __DBU_MEDCCOLDEF_LOADED */

