/*
**
**  File Name    : MESplusV5_ORA_MES_Trigger_Script.sql
**  Description  : MES Database Trigger Creation SQL Script
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10
**
**
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
*/

-- For WIP Loader

/* 더이상 안씀. 2008.03.14. Aiden. MESServer Logic으로 들어감.
CREATE OR REPLACE TRIGGER MWIPLOTSTS_TRG
AFTER INSERT OR UPDATE OR DELETE 
ON MWIPLOTSTS FOR EACH ROW
BEGIN
    IF INSERTING OR UPDATING THEN

        INSERT INTO TWIPLOTSTS
        (
            TABLE_UPDATE_SEQ,        
            
            LOT_ID                      ,
            LOT_DESC                    ,
            FACTORY                     ,
            MAT_ID                      ,
            MAT_VER                     ,
            FLOW                        ,
            FLOW_SEQ_NUM                ,
            OPER                        ,
            QTY_1                       ,
            QTY_2                       ,
            QTY_3                       ,
            CRR_ID                      ,
            LOT_TYPE                    ,
            OWNER_CODE                  ,
            CREATE_CODE                 ,
            LOT_PRIORITY                ,
            LOT_STATUS                  ,
            HOLD_FLAG                   ,
            HOLD_CODE                   ,
            HOLD_PASSWORD               ,
            OPER_IN_QTY_1               ,
            OPER_IN_QTY_2               ,
            OPER_IN_QTY_3               ,
            CREATE_QTY_1                ,
            CREATE_QTY_2                ,
            CREATE_QTY_3                ,
            START_QTY_1                 ,
            START_QTY_2                 ,
            START_QTY_3                 ,
            INV_FLAG                    ,
            TRANSIT_FLAG                ,
            UNIT_EXIST_FLAG             ,
            INV_UNIT                    ,
            RWK_FLAG                    ,
            RWK_CODE                    ,
            RWK_COUNT                   ,
            RWK_RET_FLOW                ,
            RWK_RET_FLOW_SEQ_NUM        ,
            RWK_RET_OPER                ,
            RWK_END_FLOW                ,
            RWK_END_FLOW_SEQ_NUM        ,
            RWK_END_OPER                ,
            RWK_RET_CLEAR_FLAG          ,
            RWK_TIME                    ,
            NSTD_FLAG                   ,
            NSTD_RET_FLOW               ,
            NSTD_RET_FLOW_SEQ_NUM       ,
            NSTD_RET_OPER               ,
            NSTD_TIME                   ,
            REP_FLAG                    ,
            REP_RET_OPER                ,
            START_FLAG                  ,
            START_TIME                  ,
            START_RES_ID                ,
            END_FLAG                    ,
            END_TIME                    ,
            END_RES_ID                  ,
            SAMPLE_FLAG                 ,
            SAMPLE_WAIT_FLAG            ,
            SAMPLE_RESULT               ,
            FROM_TO_FLAG                ,
            FROM_TO_LOT_ID              ,
            SHIP_CODE                   ,
            SHIP_TIME                   ,
            ORG_DUE_TIME                ,
            SCH_DUE_TIME                ,
            CREATE_TIME                 ,
            FAC_IN_TIME                 ,
            FLOW_IN_TIME                ,
            OPER_IN_TIME                ,
            RESERVE_RES_ID              ,
            BATCH_ID                    ,
            BATCH_SEQ                   ,
            ORDER_ID                    ,
            ADD_ORDER_ID_1              ,
            ADD_ORDER_ID_2              ,
            ADD_ORDER_ID_3              ,
            LOT_LOCATION                ,
            LOT_CMF_1                   ,
            LOT_CMF_2                   ,
            LOT_CMF_3                   ,
            LOT_CMF_4                   ,
            LOT_CMF_5                   ,
            LOT_CMF_6                   ,
            LOT_CMF_7                   ,
            LOT_CMF_8                   ,
            LOT_CMF_9                   ,
            LOT_CMF_10                  ,
            LOT_CMF_11                  ,
            LOT_CMF_12                  ,
            LOT_CMF_13                  ,
            LOT_CMF_14                  ,
            LOT_CMF_15                  ,
            LOT_CMF_16                  ,
            LOT_CMF_17                  ,
            LOT_CMF_18                  ,
            LOT_CMF_19                  ,
            LOT_CMF_20                  ,
            LOT_DEL_FLAG                ,
            LOT_DEL_CODE                ,
            LOT_DEL_TIME                ,
            BOM_SET_ID                  ,
            BOM_SET_VERSION             ,
            BOM_ACTIVE_HIST_SEQ         ,
            BOM_HIST_SEQ                ,
            LAST_TRAN_CODE              ,
            LAST_TRAN_TIME              ,
            LAST_COMMENT                ,
            LAST_ACTIVE_HIST_SEQ        ,
            LAST_HIST_SEQ               ,
            CRITICAL_RES_ID             ,
            CRITICAL_RES_GROUP_ID       ,
            SAVE_RES_ID_1               ,
            SAVE_RES_ID_2               ,
            SUBRES_ID                   ,
            LOT_GROUP_ID_1              ,
            LOT_GROUP_ID_2              ,
            LOT_GROUP_ID_3              ,
            
            
            UPDATE_CATEGORY, UPDATE_VALUE_1, UPDATE_VALUE_2, UPDATE_VALUE_3, UPDATE_VALUE_4, UPDATE_VALUE_5  
        )
        VALUES
        (
            TWIPLOTSTS_SEQ.NEXTVAL,
          
            :NEW.LOT_ID                      ,
            :NEW.LOT_DESC                    ,
            :NEW.FACTORY                     ,
            :NEW.MAT_ID                      ,
            :NEW.MAT_VER                     ,
            :NEW.FLOW                        ,
            :NEW.FLOW_SEQ_NUM                ,
            :NEW.OPER                        ,
            :NEW.QTY_1                       ,
            :NEW.QTY_2                       ,
            :NEW.QTY_3                       ,
            :NEW.CRR_ID                      ,
            :NEW.LOT_TYPE                    ,
            :NEW.OWNER_CODE                  ,
            :NEW.CREATE_CODE                 ,
            :NEW.LOT_PRIORITY                ,
            :NEW.LOT_STATUS                  ,
            :NEW.HOLD_FLAG                   ,
            :NEW.HOLD_CODE                   ,
            :NEW.HOLD_PASSWORD               ,
            :NEW.OPER_IN_QTY_1               ,
            :NEW.OPER_IN_QTY_2               ,
            :NEW.OPER_IN_QTY_3               ,
            :NEW.CREATE_QTY_1                ,
            :NEW.CREATE_QTY_2                ,
            :NEW.CREATE_QTY_3                ,
            :NEW.START_QTY_1                 ,
            :NEW.START_QTY_2                 ,
            :NEW.START_QTY_3                 ,
            :NEW.INV_FLAG                    ,
            :NEW.TRANSIT_FLAG                ,
            :NEW.UNIT_EXIST_FLAG             ,
            :NEW.INV_UNIT                    ,
            :NEW.RWK_FLAG                    ,
            :NEW.RWK_CODE                    ,
            :NEW.RWK_COUNT                   ,
            :NEW.RWK_RET_FLOW                ,
            :NEW.RWK_RET_FLOW_SEQ_NUM        ,
            :NEW.RWK_RET_OPER                ,
            :NEW.RWK_END_FLOW                ,
            :NEW.RWK_END_FLOW_SEQ_NUM        ,
            :NEW.RWK_END_OPER                ,
            :NEW.RWK_RET_CLEAR_FLAG          ,
            :NEW.RWK_TIME                    ,
            :NEW.NSTD_FLAG                   ,
            :NEW.NSTD_RET_FLOW               ,
            :NEW.NSTD_RET_FLOW_SEQ_NUM       ,
            :NEW.NSTD_RET_OPER               ,
            :NEW.NSTD_TIME                   ,
            :NEW.REP_FLAG                    ,
            :NEW.REP_RET_OPER                ,
            :NEW.START_FLAG                  ,
            :NEW.START_TIME                  ,
            :NEW.START_RES_ID                ,
            :NEW.END_FLAG                    ,
            :NEW.END_TIME                    ,
            :NEW.END_RES_ID                  ,
            :NEW.SAMPLE_FLAG                 ,
            :NEW.SAMPLE_WAIT_FLAG            ,
            :NEW.SAMPLE_RESULT               ,
            :NEW.FROM_TO_FLAG                ,
            :NEW.FROM_TO_LOT_ID              ,
            :NEW.SHIP_CODE                   ,
            :NEW.SHIP_TIME                   ,
            :NEW.ORG_DUE_TIME                ,
            :NEW.SCH_DUE_TIME                ,
            :NEW.CREATE_TIME                 ,
            :NEW.FAC_IN_TIME                 ,
            :NEW.FLOW_IN_TIME                ,
            :NEW.OPER_IN_TIME                ,
            :NEW.RESERVE_RES_ID              ,
            :NEW.BATCH_ID                    ,
            :NEW.BATCH_SEQ                   ,
            :NEW.ORDER_ID                    ,
            :NEW.ADD_ORDER_ID_1              ,
            :NEW.ADD_ORDER_ID_2              ,
            :NEW.ADD_ORDER_ID_3              ,
            :NEW.LOT_LOCATION                ,
            :NEW.LOT_CMF_1                   ,
            :NEW.LOT_CMF_2                   ,
            :NEW.LOT_CMF_3                   ,
            :NEW.LOT_CMF_4                   ,
            :NEW.LOT_CMF_5                   ,
            :NEW.LOT_CMF_6                   ,
            :NEW.LOT_CMF_7                   ,
            :NEW.LOT_CMF_8                   ,
            :NEW.LOT_CMF_9                   ,
            :NEW.LOT_CMF_10                  ,
            :NEW.LOT_CMF_11                  ,
            :NEW.LOT_CMF_12                  ,
            :NEW.LOT_CMF_13                  ,
            :NEW.LOT_CMF_14                  ,
            :NEW.LOT_CMF_15                  ,
            :NEW.LOT_CMF_16                  ,
            :NEW.LOT_CMF_17                  ,
            :NEW.LOT_CMF_18                  ,
            :NEW.LOT_CMF_19                  ,
            :NEW.LOT_CMF_20                  ,
            :NEW.LOT_DEL_FLAG                ,
            :NEW.LOT_DEL_CODE                ,
            :NEW.LOT_DEL_TIME                ,
            :NEW.BOM_SET_ID                  ,
            :NEW.BOM_SET_VERSION             ,
            :NEW.BOM_ACTIVE_HIST_SEQ         ,
            :NEW.BOM_HIST_SEQ                ,
            :NEW.LAST_TRAN_CODE              ,
            :NEW.LAST_TRAN_TIME              ,
            :NEW.LAST_COMMENT                ,
            :NEW.LAST_ACTIVE_HIST_SEQ        ,
            :NEW.LAST_HIST_SEQ               ,
            :NEW.CRITICAL_RES_ID             ,
            :NEW.CRITICAL_RES_GROUP_ID       ,
            :NEW.SAVE_RES_ID_1               ,
            :NEW.SAVE_RES_ID_2               ,
            :NEW.SUBRES_ID                   ,
            :NEW.LOT_GROUP_ID_1              ,
            :NEW.LOT_GROUP_ID_2              ,
            :NEW.LOT_GROUP_ID_3              ,
                   
               
            ' ',' ',' ',' ',' ',' '
        );
        
    ELSIF DELETING THEN
    
        INSERT INTO TWIPLOTSTS
        (
            TABLE_UPDATE_SEQ,
            
            
            LOT_ID                      ,
            LOT_DESC                    ,
            FACTORY                     ,
            MAT_ID                      ,
            MAT_VER                     ,
            FLOW                        ,
            FLOW_SEQ_NUM                ,
            OPER                        ,
            QTY_1                       ,
            QTY_2                       ,
            QTY_3                       ,
            CRR_ID                      ,
            LOT_TYPE                    ,
            OWNER_CODE                  ,
            CREATE_CODE                 ,
            LOT_PRIORITY                ,
            LOT_STATUS                  ,
            HOLD_FLAG                   ,
            HOLD_CODE                   ,
            HOLD_PASSWORD               ,
            OPER_IN_QTY_1               ,
            OPER_IN_QTY_2               ,
            OPER_IN_QTY_3               ,
            CREATE_QTY_1                ,
            CREATE_QTY_2                ,
            CREATE_QTY_3                ,
            START_QTY_1                 ,
            START_QTY_2                 ,
            START_QTY_3                 ,
            INV_FLAG                    ,
            TRANSIT_FLAG                ,
            UNIT_EXIST_FLAG             ,
            INV_UNIT                    ,
            RWK_FLAG                    ,
            RWK_CODE                    ,
            RWK_COUNT                   ,
            RWK_RET_FLOW                ,
            RWK_RET_FLOW_SEQ_NUM        ,
            RWK_RET_OPER                ,
            RWK_END_FLOW                ,
            RWK_END_FLOW_SEQ_NUM        ,
            RWK_END_OPER                ,
            RWK_RET_CLEAR_FLAG          ,
            RWK_TIME                    ,
            NSTD_FLAG                   ,
            NSTD_RET_FLOW               ,
            NSTD_RET_FLOW_SEQ_NUM       ,
            NSTD_RET_OPER               ,
            NSTD_TIME                   ,
            REP_FLAG                    ,
            REP_RET_OPER                ,
            START_FLAG                  ,
            START_TIME                  ,
            START_RES_ID                ,
            END_FLAG                    ,
            END_TIME                    ,
            END_RES_ID                  ,
            SAMPLE_FLAG                 ,
            SAMPLE_WAIT_FLAG            ,
            SAMPLE_RESULT               ,
            FROM_TO_FLAG                ,
            FROM_TO_LOT_ID              ,
            SHIP_CODE                   ,
            SHIP_TIME                   ,
            ORG_DUE_TIME                ,
            SCH_DUE_TIME                ,
            CREATE_TIME                 ,
            FAC_IN_TIME                 ,
            FLOW_IN_TIME                ,
            OPER_IN_TIME                ,
            RESERVE_RES_ID              ,
            BATCH_ID                    ,
            BATCH_SEQ                   ,
            ORDER_ID                    ,
            ADD_ORDER_ID_1              ,
            ADD_ORDER_ID_2              ,
            ADD_ORDER_ID_3              ,
            LOT_LOCATION                ,
            LOT_CMF_1                   ,
            LOT_CMF_2                   ,
            LOT_CMF_3                   ,
            LOT_CMF_4                   ,
            LOT_CMF_5                   ,
            LOT_CMF_6                   ,
            LOT_CMF_7                   ,
            LOT_CMF_8                   ,
            LOT_CMF_9                   ,
            LOT_CMF_10                  ,
            LOT_CMF_11                  ,
            LOT_CMF_12                  ,
            LOT_CMF_13                  ,
            LOT_CMF_14                  ,
            LOT_CMF_15                  ,
            LOT_CMF_16                  ,
            LOT_CMF_17                  ,
            LOT_CMF_18                  ,
            LOT_CMF_19                  ,
            LOT_CMF_20                  ,
            LOT_DEL_FLAG                ,
            LOT_DEL_CODE                ,
            LOT_DEL_TIME                ,
            BOM_SET_ID                  ,
            BOM_SET_VERSION             ,
            BOM_ACTIVE_HIST_SEQ         ,
            BOM_HIST_SEQ                ,
            LAST_TRAN_CODE              ,
            LAST_TRAN_TIME              ,
            LAST_COMMENT                ,
            LAST_ACTIVE_HIST_SEQ        ,
            LAST_HIST_SEQ               ,
            CRITICAL_RES_ID             ,
            CRITICAL_RES_GROUP_ID       ,
            SAVE_RES_ID_1               ,
            SAVE_RES_ID_2               ,
            SUBRES_ID                   ,
            LOT_GROUP_ID_1              ,
            LOT_GROUP_ID_2              ,
            LOT_GROUP_ID_3              ,
            
            
            UPDATE_CATEGORY, UPDATE_VALUE_1, UPDATE_VALUE_2, UPDATE_VALUE_3, UPDATE_VALUE_4, UPDATE_VALUE_5  
        )
        VALUES(
        
            TWIPLOTSTS_SEQ.NEXTVAL,
          
            :OLD.LOT_ID                      ,
            :OLD.LOT_DESC                    ,
            :OLD.FACTORY                     ,
            :OLD.MAT_ID                      ,
            :OLD.MAT_VER                     ,
            :OLD.FLOW                        ,
            :OLD.FLOW_SEQ_NUM                ,
            :OLD.OPER                        ,
            :OLD.QTY_1                       ,
            :OLD.QTY_2                       ,
            :OLD.QTY_3                       ,
            :OLD.CRR_ID                      ,
            :OLD.LOT_TYPE                    ,
            :OLD.OWNER_CODE                  ,
            :OLD.CREATE_CODE                 ,
            :OLD.LOT_PRIORITY                ,
            :OLD.LOT_STATUS                  ,
            :OLD.HOLD_FLAG                   ,
            :OLD.HOLD_CODE                   ,
            :OLD.HOLD_PASSWORD               ,
            :OLD.OPER_IN_QTY_1               ,
            :OLD.OPER_IN_QTY_2               ,
            :OLD.OPER_IN_QTY_3               ,
            :OLD.CREATE_QTY_1                ,
            :OLD.CREATE_QTY_2                ,
            :OLD.CREATE_QTY_3                ,
            :OLD.START_QTY_1                 ,
            :OLD.START_QTY_2                 ,
            :OLD.START_QTY_3                 ,
            :OLD.INV_FLAG                    ,
            :OLD.TRANSIT_FLAG                ,
            :OLD.UNIT_EXIST_FLAG             ,
            :OLD.INV_UNIT                    ,
            :OLD.RWK_FLAG                    ,
            :OLD.RWK_CODE                    ,
            :OLD.RWK_COUNT                   ,
            :OLD.RWK_RET_FLOW                ,
            :OLD.RWK_RET_FLOW_SEQ_NUM        ,
            :OLD.RWK_RET_OPER                ,
            :OLD.RWK_END_FLOW                ,
            :OLD.RWK_END_FLOW_SEQ_NUM        ,
            :OLD.RWK_END_OPER                ,
            :OLD.RWK_RET_CLEAR_FLAG          ,
            :OLD.RWK_TIME                    ,
            :OLD.NSTD_FLAG                   ,
            :OLD.NSTD_RET_FLOW               ,
            :OLD.NSTD_RET_FLOW_SEQ_NUM       ,
            :OLD.NSTD_RET_OPER               ,
            :OLD.NSTD_TIME                   ,
            :OLD.REP_FLAG                    ,
            :OLD.REP_RET_OPER                ,
            :OLD.START_FLAG                  ,
            :OLD.START_TIME                  ,
            :OLD.START_RES_ID                ,
            :OLD.END_FLAG                    ,
            :OLD.END_TIME                    ,
            :OLD.END_RES_ID                  ,
            :OLD.SAMPLE_FLAG                 ,
            :OLD.SAMPLE_WAIT_FLAG            ,
            :OLD.SAMPLE_RESULT               ,
            :OLD.FROM_TO_FLAG                ,
            :OLD.FROM_TO_LOT_ID              ,
            :OLD.SHIP_CODE                   ,
            :OLD.SHIP_TIME                   ,
            :OLD.ORG_DUE_TIME                ,
            :OLD.SCH_DUE_TIME                ,
            :OLD.CREATE_TIME                 ,
            :OLD.FAC_IN_TIME                 ,
            :OLD.FLOW_IN_TIME                ,
            :OLD.OPER_IN_TIME                ,
            :OLD.RESERVE_RES_ID              ,
            :OLD.BATCH_ID                    ,
            :OLD.BATCH_SEQ                   ,
            :OLD.ORDER_ID                    ,
            :OLD.ADD_ORDER_ID_1              ,
            :OLD.ADD_ORDER_ID_2              ,
            :OLD.ADD_ORDER_ID_3              ,
            :OLD.LOT_LOCATION                ,
            :OLD.LOT_CMF_1                   ,
            :OLD.LOT_CMF_2                   ,
            :OLD.LOT_CMF_3                   ,
            :OLD.LOT_CMF_4                   ,
            :OLD.LOT_CMF_5                   ,
            :OLD.LOT_CMF_6                   ,
            :OLD.LOT_CMF_7                   ,
            :OLD.LOT_CMF_8                   ,
            :OLD.LOT_CMF_9                   ,
            :OLD.LOT_CMF_10                  ,
            :OLD.LOT_CMF_11                  ,
            :OLD.LOT_CMF_12                  ,
            :OLD.LOT_CMF_13                  ,
            :OLD.LOT_CMF_14                  ,
            :OLD.LOT_CMF_15                  ,
            :OLD.LOT_CMF_16                  ,
            :OLD.LOT_CMF_17                  ,
            :OLD.LOT_CMF_18                  ,
            :OLD.LOT_CMF_19                  ,
            :OLD.LOT_CMF_20                  ,
            :OLD.LOT_DEL_FLAG                ,
            :OLD.LOT_DEL_CODE                ,
            :OLD.LOT_DEL_TIME                ,
            :OLD.BOM_SET_ID                  ,
            :OLD.BOM_SET_VERSION             ,
            :OLD.BOM_ACTIVE_HIST_SEQ         ,
            :OLD.BOM_HIST_SEQ                ,
            :OLD.LAST_TRAN_CODE              ,
            :OLD.LAST_TRAN_TIME              ,
            :OLD.LAST_COMMENT                ,
            :OLD.LAST_ACTIVE_HIST_SEQ        ,
            :OLD.LAST_HIST_SEQ               ,
            :OLD.CRITICAL_RES_ID             ,
            :OLD.CRITICAL_RES_GROUP_ID       ,
            :OLD.SAVE_RES_ID_1               ,
            :OLD.SAVE_RES_ID_2               ,
            :OLD.SUBRES_ID                   ,
            :OLD.LOT_GROUP_ID_1              ,
            :OLD.LOT_GROUP_ID_2              ,
            :OLD.LOT_GROUP_ID_3              ,
                   
               
            ' ',' ',' ',' ',' ',' '
        );
                    
    END IF;
      
   EXCEPTION
     WHEN OTHERS THEN
        --Consider logging the error and then re-raise
     RAISE;
END ;
/









-- For RAS Loader
CREATE OR REPLACE TRIGGER MRASRESHIS_TRG
AFTER DELETE OR INSERT OR UPDATE
ON MRASRESHIS 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
     IF INSERTING OR UPDATING THEN
     
        INSERT INTO TRASRESHIS
        (
            TABLE_UPDATE_SEQ, 
            
            FACTORY                     ,
            RES_ID                      ,
            HIST_SEQ                    ,
            EVENT_ID                    ,
            TRAN_TIME                   ,
            SYS_TRAN_TIME               ,
            OLD_EVENT_ID                ,
            OLD_HIST_SEQ                ,
            OLD_TRAN_TIME               ,
            OLD_SYS_TRAN_TIME           ,
            OLD_UP_DOWN_FLAG            ,
            OLD_PRI_STS                 ,
            OLD_STS_1                   ,
            OLD_STS_2                   ,
            OLD_STS_3                   ,
            OLD_STS_4                   ,
            OLD_STS_5                   ,
            OLD_STS_6                   ,
            OLD_STS_7                   ,
            OLD_STS_8                   ,
            OLD_STS_9                   ,
            OLD_STS_10                  ,
            NEW_UP_DOWN_FLAG            ,
            NEW_PRI_STS                 ,
            NEW_STS_1                   ,
            NEW_STS_2                   ,
            NEW_STS_3                   ,
            NEW_STS_4                   ,
            NEW_STS_5                   ,
            NEW_STS_6                   ,
            NEW_STS_7                   ,
            NEW_STS_8                   ,
            NEW_STS_9                   ,
            NEW_STS_10                  ,
            LOT_ID                      ,
            SUBLOT_ID                   ,
            CRR_ID                      ,
            RES_CTRL_MODE               ,
            RES_PROC_MODE               ,
            LOT_EXIST_FLAG              ,
            COL_SET_ID                  ,
            COL_SET_VERSION             ,
            TRAN_CMF_1                  ,
            TRAN_CMF_2                  ,
            TRAN_CMF_3                  ,
            TRAN_CMF_4                  ,
            TRAN_CMF_5                  ,
            TRAN_CMF_6                  ,
            TRAN_CMF_7                  ,
            TRAN_CMF_8                  ,
            TRAN_CMF_9                  ,
            TRAN_CMF_10                 ,
            TRAN_CMF_11                 ,
            TRAN_CMF_12                 ,
            TRAN_CMF_13                 ,
            TRAN_CMF_14                 ,
            TRAN_CMF_15                 ,
            TRAN_CMF_16                 ,
            TRAN_CMF_17                 ,
            TRAN_CMF_18                 ,
            TRAN_CMF_19                 ,
            TRAN_CMF_20                 ,
            TRAN_USER_ID                ,
            TRAN_COMMENT                ,
            LAST_DOWN_TIME              ,
            LAST_DOWN_HIST_SEQ          ,
            HIST_START_SEQ              ,
            HIST_DEL_FLAG               ,
            HIST_DEL_TIME               ,
            HIST_DEL_USER_ID            ,
            HIST_DEL_COMMENT
            
        )
        VALUES 
        (
            TRASRESHIS_SEQ.NEXTVAL,
            
            
            :NEW.FACTORY                     ,
            :NEW.RES_ID                      ,
            :NEW.HIST_SEQ                    ,
            :NEW.EVENT_ID                    ,
            :NEW.TRAN_TIME                   ,
            :NEW.SYS_TRAN_TIME               ,
            :NEW.OLD_EVENT_ID                ,
            :NEW.OLD_HIST_SEQ                ,
            :NEW.OLD_TRAN_TIME               ,
            :NEW.OLD_SYS_TRAN_TIME           ,
            :NEW.OLD_UP_DOWN_FLAG            ,
            :NEW.OLD_PRI_STS                 ,
            :NEW.OLD_STS_1                   ,
            :NEW.OLD_STS_2                   ,
            :NEW.OLD_STS_3                   ,
            :NEW.OLD_STS_4                   ,
            :NEW.OLD_STS_5                   ,
            :NEW.OLD_STS_6                   ,
            :NEW.OLD_STS_7                   ,
            :NEW.OLD_STS_8                   ,
            :NEW.OLD_STS_9                   ,
            :NEW.OLD_STS_10                  ,
            :NEW.NEW_UP_DOWN_FLAG            ,
            :NEW.NEW_PRI_STS                 ,
            :NEW.NEW_STS_1                   ,
            :NEW.NEW_STS_2                   ,
            :NEW.NEW_STS_3                   ,
            :NEW.NEW_STS_4                   ,
            :NEW.NEW_STS_5                   ,
            :NEW.NEW_STS_6                   ,
            :NEW.NEW_STS_7                   ,
            :NEW.NEW_STS_8                   ,
            :NEW.NEW_STS_9                   ,
            :NEW.NEW_STS_10                  ,
            :NEW.LOT_ID                      ,
            :NEW.SUBLOT_ID                   ,
            :NEW.CRR_ID                      ,
            :NEW.RES_CTRL_MODE               ,
            :NEW.RES_PROC_MODE               ,
            :NEW.LOT_EXIST_FLAG              ,
            :NEW.COL_SET_ID                  ,
            :NEW.COL_SET_VERSION             ,
            :NEW.TRAN_CMF_1                  ,
            :NEW.TRAN_CMF_2                  ,
            :NEW.TRAN_CMF_3                  ,
            :NEW.TRAN_CMF_4                  ,
            :NEW.TRAN_CMF_5                  ,
            :NEW.TRAN_CMF_6                  ,
            :NEW.TRAN_CMF_7                  ,
            :NEW.TRAN_CMF_8                  ,
            :NEW.TRAN_CMF_9                  ,
            :NEW.TRAN_CMF_10                 ,
            :NEW.TRAN_CMF_11                 ,
            :NEW.TRAN_CMF_12                 ,
            :NEW.TRAN_CMF_13                 ,
            :NEW.TRAN_CMF_14                 ,
            :NEW.TRAN_CMF_15                 ,
            :NEW.TRAN_CMF_16                 ,
            :NEW.TRAN_CMF_17                 ,
            :NEW.TRAN_CMF_18                 ,
            :NEW.TRAN_CMF_19                 ,
            :NEW.TRAN_CMF_20                 ,
            :NEW.TRAN_USER_ID                ,
            :NEW.TRAN_COMMENT                ,
            :NEW.LAST_DOWN_TIME              ,
            :NEW.LAST_DOWN_HIST_SEQ          ,
            :NEW.HIST_START_SEQ              ,
            :NEW.HIST_DEL_FLAG               ,
            :NEW.HIST_DEL_TIME               ,
            :NEW.HIST_DEL_USER_ID            ,
            :NEW.HIST_DEL_COMMENT            
            
        );
                
    ELSE
    
        INSERT INTO TRASRESHIS
        (
        
            TABLE_UPDATE_SEQ, 
            
            FACTORY                     ,
            RES_ID                      ,
            HIST_SEQ                    ,
            EVENT_ID                    ,
            TRAN_TIME                   ,
            SYS_TRAN_TIME               ,
            OLD_EVENT_ID                ,
            OLD_HIST_SEQ                ,
            OLD_TRAN_TIME               ,
            OLD_SYS_TRAN_TIME           ,
            OLD_UP_DOWN_FLAG            ,
            OLD_PRI_STS                 ,
            OLD_STS_1                   ,
            OLD_STS_2                   ,
            OLD_STS_3                   ,
            OLD_STS_4                   ,
            OLD_STS_5                   ,
            OLD_STS_6                   ,
            OLD_STS_7                   ,
            OLD_STS_8                   ,
            OLD_STS_9                   ,
            OLD_STS_10                  ,
            NEW_UP_DOWN_FLAG            ,
            NEW_PRI_STS                 ,
            NEW_STS_1                   ,
            NEW_STS_2                   ,
            NEW_STS_3                   ,
            NEW_STS_4                   ,
            NEW_STS_5                   ,
            NEW_STS_6                   ,
            NEW_STS_7                   ,
            NEW_STS_8                   ,
            NEW_STS_9                   ,
            NEW_STS_10                  ,
            LOT_ID                      ,
            SUBLOT_ID                   ,
            CRR_ID                      ,
            RES_CTRL_MODE               ,
            RES_PROC_MODE               ,
            LOT_EXIST_FLAG              ,
            COL_SET_ID                  ,
            COL_SET_VERSION             ,
            TRAN_CMF_1                  ,
            TRAN_CMF_2                  ,
            TRAN_CMF_3                  ,
            TRAN_CMF_4                  ,
            TRAN_CMF_5                  ,
            TRAN_CMF_6                  ,
            TRAN_CMF_7                  ,
            TRAN_CMF_8                  ,
            TRAN_CMF_9                  ,
            TRAN_CMF_10                 ,
            TRAN_CMF_11                 ,
            TRAN_CMF_12                 ,
            TRAN_CMF_13                 ,
            TRAN_CMF_14                 ,
            TRAN_CMF_15                 ,
            TRAN_CMF_16                 ,
            TRAN_CMF_17                 ,
            TRAN_CMF_18                 ,
            TRAN_CMF_19                 ,
            TRAN_CMF_20                 ,
            TRAN_USER_ID                ,
            TRAN_COMMENT                ,
            LAST_DOWN_TIME              ,
            LAST_DOWN_HIST_SEQ          ,
            HIST_START_SEQ              ,
            HIST_DEL_FLAG               ,
            HIST_DEL_TIME               ,
            HIST_DEL_USER_ID            ,
            HIST_DEL_COMMENT
                    
        )
        VALUES 
        (
            TRASRESHIS_SEQ.NEXTVAL,
            
            :OLD.FACTORY                     ,
            :OLD.RES_ID                      ,
            :OLD.HIST_SEQ                    ,
            :OLD.EVENT_ID                    ,
            :OLD.TRAN_TIME                   ,
            :OLD.SYS_TRAN_TIME               ,
            :OLD.OLD_EVENT_ID                ,
            :OLD.OLD_HIST_SEQ                ,
            :OLD.OLD_TRAN_TIME               ,
            :OLD.OLD_SYS_TRAN_TIME           ,
            :OLD.OLD_UP_DOWN_FLAG            ,
            :OLD.OLD_PRI_STS                 ,
            :OLD.OLD_STS_1                   ,
            :OLD.OLD_STS_2                   ,
            :OLD.OLD_STS_3                   ,
            :OLD.OLD_STS_4                   ,
            :OLD.OLD_STS_5                   ,
            :OLD.OLD_STS_6                   ,
            :OLD.OLD_STS_7                   ,
            :OLD.OLD_STS_8                   ,
            :OLD.OLD_STS_9                   ,
            :OLD.OLD_STS_10                  ,
            :OLD.NEW_UP_DOWN_FLAG            ,
            :OLD.NEW_PRI_STS                 ,
            :OLD.NEW_STS_1                   ,
            :OLD.NEW_STS_2                   ,
            :OLD.NEW_STS_3                   ,
            :OLD.NEW_STS_4                   ,
            :OLD.NEW_STS_5                   ,
            :OLD.NEW_STS_6                   ,
            :OLD.NEW_STS_7                   ,
            :OLD.NEW_STS_8                   ,
            :OLD.NEW_STS_9                   ,
            :OLD.NEW_STS_10                  ,
            :OLD.LOT_ID                      ,
            :OLD.SUBLOT_ID                   ,
            :OLD.CRR_ID                      ,
            :OLD.RES_CTRL_MODE               ,
            :OLD.RES_PROC_MODE               ,
            :OLD.LOT_EXIST_FLAG              ,
            :OLD.COL_SET_ID                  ,
            :OLD.COL_SET_VERSION             ,
            :OLD.TRAN_CMF_1                  ,
            :OLD.TRAN_CMF_2                  ,
            :OLD.TRAN_CMF_3                  ,
            :OLD.TRAN_CMF_4                  ,
            :OLD.TRAN_CMF_5                  ,
            :OLD.TRAN_CMF_6                  ,
            :OLD.TRAN_CMF_7                  ,
            :OLD.TRAN_CMF_8                  ,
            :OLD.TRAN_CMF_9                  ,
            :OLD.TRAN_CMF_10                 ,
            :OLD.TRAN_CMF_11                 ,
            :OLD.TRAN_CMF_12                 ,
            :OLD.TRAN_CMF_13                 ,
            :OLD.TRAN_CMF_14                 ,
            :OLD.TRAN_CMF_15                 ,
            :OLD.TRAN_CMF_16                 ,
            :OLD.TRAN_CMF_17                 ,
            :OLD.TRAN_CMF_18                 ,
            :OLD.TRAN_CMF_19                 ,
            :OLD.TRAN_CMF_20                 ,
            :OLD.TRAN_USER_ID                ,
            :OLD.TRAN_COMMENT                ,
            :OLD.LAST_DOWN_TIME              ,
            :OLD.LAST_DOWN_HIST_SEQ          ,
            :OLD.HIST_START_SEQ              ,
            :OLD.HIST_DEL_FLAG               ,
            :OLD.HIST_DEL_TIME               ,
            :OLD.HIST_DEL_USER_ID            ,
            :OLD.HIST_DEL_COMMENT            
            
        );
                    
    END IF;     
    
     EXCEPTION
     WHEN OTHERS THEN
        --Consider logging the error and then re-raise
     RAISE;                                                                                       
END;
/
*/

