/*
**
**  File Name    : 8.MESplusV5_ORA_MES_Remote_Shipping.sql
**  Description  : MES Remote Shipping Sample Procedure
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10
**
**
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
*/

/* Create Database Link */
create database link AR01_TO_CR01 connect to MESMGR identified by MESMGR using 'ORAMES';




CREATE OR REPLACE Procedure PR_REMOTE_SHIPPING as
BEGIN

/*******************************************************************

	Program : PR_REMOTE_SHIPPING
	Desc    : Copy data A -> B
	Located : A
	Created : 2009. 03. 105
	By      : J.S.

*******************************************************************/

DECLARE


	T_MWIPRSHLOT	MWIPRSHLOT%ROWTYPE ;
	T_MWIPLOTHIS	MWIPLOTHIS%ROWTYPE ;


	TYPE t_ClassesREF IS REF CURSOR;
	LOT_ROWS t_ClassesREF;


	V_SHIP_FACTORY	    VARCHAR2(10) DEFAULT 'CR01';
	V_LOT_ID			MWIPLOTSTS.LOT_ID%TYPE;
	V_IS_LOT_EXIST	    CHAR(1)      DEFAULT 'N';


BEGIN

	OPEN LOT_ROWS FOR

		SELECT * FROM MWIPRSHLOT ORDER BY TRAN_TIME ;


	LOOP FETCH LOT_ROWS INTO T_MWIPRSHLOT ;
	EXIT WHEN  LOT_ROWS%NOTFOUND;

	BEGIN

		--LOT 이력이 있는지 확인
		BEGIN
			SELECT * INTO T_MWIPLOTHIS
			FROM MWIPLOTHIS
			WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID AND HIST_SEQ = T_MWIPRSHLOT.HIST_SEQ;

			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 DELETE MWIPRSHLOT WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID AND HIST_SEQ = T_MWIPRSHLOT.HIST_SEQ;
				 COMMIT;
			     GOTO SKIP_THIS_LOT;
			WHEN OTHERS THEN
			     GOTO SKIP_THIS_LOT;
		END ;

		-- 이력이 지워 졌으면 삭제하고 SKIP
		IF T_MWIPLOTHIS.HIST_DEL_FLAG = 'Y' THEN
			DELETE MWIPRSHLOT WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID AND HIST_SEQ = T_MWIPRSHLOT.HIST_SEQ;
			COMMIT;
			GOTO SKIP_THIS_LOT;
		END IF;



		-- TO FACTORY 별로 다른 DB로 복사하는 경우를 대비 하여...
		IF T_MWIPRSHLOT.FACTORY_TO = V_SHIP_FACTORY THEN
		
			-- TO DB에  LOT_ID가 있는지 확인한다.
	
			V_IS_LOT_EXIST := 'Y';
			BEGIN
				SELECT LOT_ID INTO V_LOT_ID
				FROM MWIPLOTSTS@AR01_TO_CR01
				WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID ;
	
				EXCEPTION
				WHEN NO_DATA_FOUND THEN
					 V_IS_LOT_EXIST := 'N';
				WHEN OTHERS THEN
				     GOTO SKIP_THIS_LOT;
			END ;
			
			
			IF V_IS_LOT_EXIST = 'Y' THEN
			    dbms_output.put_line('LOT EIXST = ' || V_LOT_ID);		
				GOTO SKIP_THIS_LOT;
			END IF;
	
		
			-- FROM FACTORY의 LOT을 TO FACTORY로 복사한다.
		
			-- MOVING MWIPLOTSTS
			BEGIN
				INSERT INTO MWIPLOTSTS@AR01_TO_CR01
				SELECT * FROM MWIPLOTSTS
				WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID ;
	
				EXCEPTION
				WHEN OTHERS THEN
				     GOTO SKIP_THIS_LOT;
			END ;
	
			BEGIN
				UPDATE MWIPLOTSTS@AR01_TO_CR01 SET
					LOT_DEL_FLAG = ' ',
					LOT_DEL_CODE = ' ',
					LOT_DEL_TIME = ' ',
					LAST_TRAN_CODE = 'TRANSIT',
					LAST_HIST_SEQ = LAST_HIST_SEQ + 1,
					LAST_ACTIVE_HIST_SEQ = LAST_ACTIVE_HIST_SEQ + 1					
				WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID ;
				
				EXCEPTION
				WHEN OTHERS THEN
				     GOTO SKIP_THIS_LOT;
			END ;

			BEGIN
				INSERT INTO MWIPLOTHIS@AR01_TO_CR01
				SELECT * FROM MWIPLOTHIS
				WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID AND HIST_SEQ = T_MWIPRSHLOT.HIST_SEQ ;

				EXCEPTION
				WHEN OTHERS THEN
				     GOTO SKIP_THIS_LOT;
			END ;
	
			BEGIN
				UPDATE MWIPLOTHIS@AR01_TO_CR01 SET
					LOT_DEL_FLAG = ' ',
					LOT_DEL_CODE = ' ',
					LOT_DEL_TIME = ' ',
					TRAN_CODE = 'TRANSIT',
					HIST_SEQ = HIST_SEQ + 1
				WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID AND HIST_SEQ = T_MWIPRSHLOT.HIST_SEQ ;
				
				EXCEPTION
				WHEN OTHERS THEN
				     GOTO SKIP_THIS_LOT;
			END ;
	
						
			-- MOVING MWIPSLTSTS
			BEGIN
				INSERT INTO MWIPSLTSTS@AR01_TO_CR01
				SELECT * FROM MWIPSLTSTS
				WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID ;

				EXCEPTION
				WHEN OTHERS THEN
				     GOTO SKIP_THIS_LOT;
			END ;
	
			BEGIN
				UPDATE MWIPSLTSTS@AR01_TO_CR01 SET
					UNIT_EXIST_FLAG = 'Y',
					SUBLOT_DEL_FLAG = ' ',
					SUBLOT_DEL_CODE = ' ',
					SUBLOT_DEL_TIME = ' ',
					LAST_TRAN_CODE = 'TRANSIT',
					LOT_HIST_SEQ = LOT_HIST_SEQ + 1,
					LAST_HIST_SEQ = LAST_HIST_SEQ + 1,
					LAST_ACTIVE_HIST_SEQ = LAST_ACTIVE_HIST_SEQ + 1					
				WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID ;

				EXCEPTION
				WHEN OTHERS THEN
				     GOTO SKIP_THIS_LOT;
			END ;

		
			BEGIN
				INSERT INTO MWIPSLTHIS@AR01_TO_CR01
				SELECT * FROM MWIPSLTHIS
				WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID AND LOT_HIST_SEQ = T_MWIPRSHLOT.HIST_SEQ ;

				EXCEPTION
				WHEN OTHERS THEN
				     GOTO SKIP_THIS_LOT;
			END ;
	
	
			BEGIN
				UPDATE MWIPSLTHIS@AR01_TO_CR01 SET
					UNIT_EXIST_FLAG = 'Y',
					SUBLOT_DEL_FLAG = ' ',
					SUBLOT_DEL_CODE = ' ',
					SUBLOT_DEL_TIME = ' ',
					TRAN_CODE = 'TRANSIT',
					LOT_HIST_SEQ = LOT_HIST_SEQ + 1,
					HIST_SEQ = HIST_SEQ + 1
				WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID AND LOT_HIST_SEQ = T_MWIPRSHLOT.HIST_SEQ ;
	
				EXCEPTION
				WHEN OTHERS THEN
				     GOTO SKIP_THIS_LOT;
			END ;
	
	
			DELETE MWIPRSHLOT WHERE LOT_ID = T_MWIPRSHLOT.LOT_ID AND HIST_SEQ = T_MWIPRSHLOT.HIST_SEQ ;
	
			COMMIT ;
			
		END IF;

		<<SKIP_THIS_LOT>>
		    ROLLBACK;

	END ;

	END LOOP ;

	CLOSE LOT_ROWS ;


END;

END PR_REMOTE_SHIPPING ;
/