/*
**
**  File Name    : MESplusV5-Table-Migration_Table.sql
**  Description  : MESplus V5 Release for Table Migration
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10g / 11g
**
**  Period       : 2014.12.01 ~ ****
**  Release Date : ****
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
**
**  1. 2014.12.01   Aiden   Create
*/



ALTER TABLE MRTDRULITM ADD RULE_ITEM_DESC     VARCHAR2(200)    DEFAULT (' ')   NOT NULL;


/* MRTDRULEXT: Rule-Item Definition Table (Extended) */
CREATE TABLE MRTDRULEXT
(
    FACTORY                     VARCHAR2(10)     DEFAULT(' ')      NOT NULL,
    RULE_ID                     VARCHAR2(20)     DEFAULT(' ')      NOT NULL,
    RULE_TYPE                   CHAR(1)          DEFAULT(' ')      NOT NULL,
    PRIO_LEVEL                  NUMBER(6)        DEFAULT(0)        NOT NULL,
    PRIO_KEY                    VARCHAR2(20)     DEFAULT(' ')      NOT NULL,
    KEY_VALUE_1                 VARCHAR2(100)    DEFAULT(' ')      NOT NULL,
    KEY_VALUE_2                 VARCHAR2(100)    DEFAULT(' ')      NOT NULL,
    OPERATOR                    VARCHAR2(10)     DEFAULT(' ')      NOT NULL,
    TABLE_NAME                  VARCHAR2(20)     DEFAULT(' ')      NOT NULL,
    CREATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')      NOT NULL,
    CREATE_TIME                 VARCHAR2(14)     DEFAULT(' ')      NOT NULL,
    UPDATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')      NOT NULL,
    UPDATE_TIME                 VARCHAR2(14)     DEFAULT(' ')      NOT NULL
)
TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MRTDRULEXT
ADD CONSTRAINT MRTDRULEXT_PK PRIMARY KEY
(
    FACTORY,
    RULE_ID,
    RULE_TYPE,
    PRIO_LEVEL,
    PRIO_KEY,
    KEY_VALUE_1,
    KEY_VALUE_2
) USING INDEX TABLESPACE MESPLUS_IDX_TS;




ALTER TABLE MBASCHKQRY MODIFY ANSWER_FMT           CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKQRY MODIFY VALID_TBL_TYPE       CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY LOT_OR_RES_FLAG      CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_1_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_1_FMT            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_2_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_2_FMT            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_3_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_3_FMT            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_4_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_4_FMT            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_5_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_5_FMT            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_6_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_6_FMT            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_7_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_7_FMT            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_8_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_8_FMT            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_9_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_9_FMT            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_10_REQ           CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLST MODIFY KEY_10_FMT           CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSQ MODIFY REQUIRE_FLAG         CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY REL_LEVEL            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY BA_POINT             CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY REQ_COMPLETE_FLAG    CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY INHERIT_CHILD_FLAG   CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_1_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_2_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_3_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_4_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_5_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_6_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_7_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_8_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_9_REQ            CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSR MODIFY KEY_10_REQ           CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSH MODIFY COMPLETE_FLAG        CHAR(1)     DEFAULT (' ');
ALTER TABLE MBASCHKLSH MODIFY DELETE_FLAG          CHAR(1)     DEFAULT (' ');



