/*
**
**  File Name    : MESplusV5-Report-Migration_Data.sql
**  Description  : MESplus V5 Release for Report Data Migration
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10g / 11g
**
**  Period       : 2013.04.30 ~ ****
**  Release Date : ****
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
**
*/
CREATE TABLE RATRNAMSTS_OLD AS SELECT * FROM RATRNAMSTS;
DROP TABLE RATRNAMSTS CASCADE CONSTRAINT PURGE;

CREATE TABLE RATRNAMSTS
(
    FACTORY                     VARCHAR2(10)    DEFAULT (' ')   NOT NULL,
    ATTR_TYPE                   VARCHAR2(20)    DEFAULT (' ')   NOT NULL,               
    ATTR_NAME                   VARCHAR2(100)   DEFAULT (' ')   NOT NULL,
    ATTR_KEY                    VARCHAR2(100)    DEFAULT (' ')   NOT NULL,               
    KEY_HIST_SEQ                NUMBER(10)      DEFAULT (0)     ,
    ATTR_FMT          		VARCHAR2(1)	 DEFAULT (' ')	,
    ATTR_SIZE          		NUMBER(6) 	DEFAULT (0)	,                
    ATTR_VALUE                  VARCHAR2(1000)  DEFAULT (' ')   ,               
    NULL_FLAG                   CHAR(1)         DEFAULT (' ')   ,
    LAST_TRAN_TIME              DATE,
    LAST_ACTIVE_HIST_SEQ        NUMBER(10)      DEFAULT (0)     ,
    LAST_HIST_SEQ               NUMBER(10)      DEFAULT (0)      
) TABLESPACE REPORT_DATA_TS;

ALTER TABLE RATRNAMSTS
ADD CONSTRAINT RATRNAMSTS_PK PRIMARY KEY
(
    FACTORY,
    ATTR_TYPE,
    ATTR_NAME,
    ATTR_KEY
) USING INDEX TABLESPACE REPORT_IDX_TS;

CREATE INDEX RATRNAMSTS_IDX_1 ON RATRNAMSTS
(
    FACTORY,
    ATTR_KEY,
    ATTR_TYPE,
    ATTR_NAME
) TABLESPACE REPORT_IDX_TS;

INSERT INTO RATRNAMSTS VALUE ( 
SELECT 
    FACTORY              ,
    ATTR_TYPE            ,
    ATTR_NAME            ,
    ATTR_KEY             ,
    KEY_HIST_SEQ         ,
    ATTR_FMT		 ,
    ATTR_SIZE		 ,
    ATTR_VALUE           ,
    ' '                  ,
    LAST_TRAN_TIME       ,
    LAST_ACTIVE_HIST_SEQ ,
    LAST_HIST_SEQ
FROM RATRNAMSTS_OLD);

CREATE TABLE MTMPATRHIS_BAK_OLD AS SELECT * FROM MTMPATRHIS_BAK;
DROP TABLE MTMPATRHIS_BAK CASCADE CONSTRAINT PURGE;

CREATE TABLE MTMPATRHIS_BAK 
(
    TABLE_UPDATE_SEQ            NUMBER(12)       DEFAULT(0)      NOT NULL,
    CM_KEY_1                    VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    CM_KEY_2                    VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    CM_KEY_3                    VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    CM_KEY_4                    VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    CM_KEY_5                    VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    FACTORY                     VARCHAR2(10)    DEFAULT (' ')   NOT NULL,
    ATTR_TYPE                   VARCHAR2(20)    DEFAULT (' ')   NOT NULL,
    ATTR_NAME                   VARCHAR2(100)    DEFAULT (' ')   NOT NULL,
    ATTR_KEY                    VARCHAR2(100)    DEFAULT (' ')   NOT NULL,
    HIST_SEQ                    NUMBER(10)      DEFAULT (0)     NOT NULL,
    ATTR_OLD_VALUE              VARCHAR2(1000)    DEFAULT (' ')   NOT NULL,
    ATTR_NEW_VALUE              VARCHAR2(1000)    DEFAULT (' ')   NOT NULL,
    NULL_FLAG                   CHAR(1)         DEFAULT (' ')   NOT NULL,
    TRAN_TIME                   VARCHAR2(14)    DEFAULT (' ')   NOT NULL,
    SYS_TRAN_TIME               VARCHAR2(14)    DEFAULT (' ')   NOT NULL,
    KEY_HIST_SEQ                NUMBER(10)      DEFAULT (0)     NOT NULL,                
    PREV_ACTIVE_HIST_SEQ        NUMBER(10)      DEFAULT (0)     NOT NULL,
    HIST_START_SEQ              NUMBER(10)      DEFAULT (0)     NOT NULL,
    HIST_DEL_FLAG               CHAR(1)         DEFAULT (' ')   NOT NULL,
    HIST_DEL_TIME               VARCHAR2(14)    DEFAULT (' ')   NOT NULL,
    HIST_DEL_USER_ID            VARCHAR2(20)    DEFAULT (' ')   NOT NULL,
    HIST_DEL_COMMENT            VARCHAR2(400)   DEFAULT (' ')   NOT NULL,
    PROCESS_FLAG                CHAR(1)          DEFAULT (' ')   NOT NULL,
    TRAN_USER_ID                VARCHAR2(20)     DEFAULT(' ')
) TABLESPACE REPORT_DATA_TS;

ALTER TABLE MTMPATRHIS_BAK
ADD CONSTRAINT MTMPATRHIS_BAK_PK PRIMARY KEY
(
    TABLE_UPDATE_SEQ
) USING INDEX TABLESPACE HISTORY_IDX_TS;

INSERT INTO MTMPATRHIS_BAK VALUE ( 
SELECT 
    TABLE_UPDATE_SEQ,
    CM_KEY_1,
    CM_KEY_2,
    CM_KEY_3,
    CM_KEY_4,
    CM_KEY_5,
    FACTORY,
    ATTR_TYPE,
    ATTR_NAME,
    ATTR_KEY,
    HIST_SEQ,
    ATTR_OLD_VALUE,
    ATTR_NEW_VALUE,
    ' ',
    TRAN_TIME,
    SYS_TRAN_TIME,
    KEY_HIST_SEQ,                
    PREV_ACTIVE_HIST_SEQ,
    HIST_START_SEQ,
    HIST_DEL_FLAG,
    HIST_DEL_TIME,
    HIST_DEL_USER_ID,
    HIST_DEL_COMMENT,
    PROCESS_FLAG,
    ' '
FROM MTMPATRHIS_BAK_OLD);


/* Change Description Column Size & Add Short Description Column For Report*/

ALTER TABLE RRASRESDEF ADD RES_SHORT_DESC VARCHAR2(50) DEFAULT (' ');
COMMENT ON COLUMN RRASRESDEF.RES_SHORT_DESC       IS 'Resource Short Description';

ALTER TABLE RRASRESDEF MODIFY RES_DESC VARCHAR2(200)   DEFAULT (' ');

ALTER TABLE RRASRESDEF MODIFY RES_GRP_1         VARCHAR2(30)    DEFAULT (' ');
ALTER TABLE RRASRESDEF MODIFY RES_GRP_2         VARCHAR2(30)    DEFAULT (' ');
ALTER TABLE RRASRESDEF MODIFY RES_GRP_3         VARCHAR2(30)    DEFAULT (' ');
ALTER TABLE RRASRESDEF MODIFY RES_GRP_4         VARCHAR2(30)    DEFAULT (' ');
ALTER TABLE RRASRESDEF MODIFY RES_GRP_5         VARCHAR2(30)    DEFAULT (' ');
ALTER TABLE RRASRESDEF MODIFY RES_GRP_6         VARCHAR2(30)    DEFAULT (' ');
ALTER TABLE RRASRESDEF MODIFY RES_GRP_7         VARCHAR2(30)    DEFAULT (' ');
ALTER TABLE RRASRESDEF MODIFY RES_GRP_8         VARCHAR2(30)    DEFAULT (' ');
ALTER TABLE RRASRESDEF MODIFY RES_GRP_9         VARCHAR2(30)    DEFAULT (' ');
ALTER TABLE RRASRESDEF MODIFY RES_GRP_10        VARCHAR2(30)    DEFAULT (' ');

ALTER TABLE RRASCRRDEF MODIFY CRR_DESC VARCHAR2(200)   DEFAULT (' ');
ALTER TABLE RRASCRRDEF ADD USAGE_LIMIT_ALARM VARCHAR2(20 BYTE) DEFAULT (' ');
ALTER TABLE RRASCRRDEF ADD CLEAN_LIMIT_ALARM VARCHAR2(20 BYTE) DEFAULT (' ');

ALTER TABLE RRASSRSDEF MODIFY SUBRES_DESC VARCHAR2(200)   DEFAULT (' ');

ALTER TABLE RATRNAMHIS ADD TRAN_USER_ID             VARCHAR2(20)     DEFAULT(' ');
ALTER TABLE RATRNAMHIS MODIFY ATTR_KEY          VARCHAR2(100)   DEFAULT (' ');

ALTER TABLE RWIPLOTDEL MODIFY LOT_DESC VARCHAR2(200)   DEFAULT (' ');
ALTER TABLE RWIPLOTHIS MODIFY LOT_DESC VARCHAR2(200)   DEFAULT (' ');
ALTER TABLE RWIPLOTSTS MODIFY LOT_DESC VARCHAR2(200)   DEFAULT (' ');

ALTER TABLE MTMPLOTHIS_BAK MODIFY LOT_DESC          VARCHAR2(200)   DEFAULT (' ');
