/*
**
**  File Name    : MESplusV5-Report-Migration_Data.sql
**  Description  : MESplus V5 Release for Report Data Migration
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10g / 11g
**
**  Period       : 2010.12.11 ~ ****
**  Release Date : ****
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
**
*/

CREATE TABLE RRASRESLTH_OLD AS SELECT * FROM RRASRESLTH;
DROP TABLE RRASRESLTH CASCADE CONSTRAINT PURGE;

CREATE TABLE RRASRESLTH
(
    FACTORY                     VARCHAR2(10)     DEFAULT(' ')    NOT NULL,
    RES_ID                      VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    RES_HIST_SEQ                NUMBER(10)       DEFAULT(0)      NOT NULL,
    LOT_ID                      VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    RES_HIST_DEL_FLAG           CHAR(1),
    EVENT_ID                    VARCHAR2(12),
    TRAN_TIME                   VARCHAR2(14),
    LOT_HIST_SEQ                NUMBER(10),
    LOT_HIST_DEL_FLAG           CHAR(1),
    MAT_ID                      VARCHAR2(30),
    MAT_VER                     NUMBER(6),
    FLOW                        VARCHAR2(20),
    OPER                        VARCHAR2(10),
    LOT_TYPE                    CHAR(1),
    RWK_FLAG                    CHAR(1),
    QTY_1                       NUMBER(10,3),
    QTY_2                       NUMBER(10,3),
    QTY_3                       NUMBER(10,3),
	RES_SEQ                     NUMBER(10)
) TABLESPACE REPORT_DATA_TS;

ALTER TABLE RRASRESLTH
ADD CONSTRAINT RRASRESLTH_PK PRIMARY KEY
(
    FACTORY, 
    RES_ID, 
    RES_HIST_SEQ, 
    LOT_ID
) USING INDEX TABLESPACE REPORT_IDX_TS;

INSERT INTO RRASRESLTH VALUE ( 
SELECT 
    FACTORY             ,
    RES_ID              ,
    RES_HIST_SEQ        ,
    LOT_ID              ,
    RES_HIST_DEL_FLAG   ,
    EVENT_ID            ,
    TRAN_TIME           ,
    LOT_HIST_SEQ        ,
    LOT_HIST_DEL_FLAG   ,
    MAT_ID              ,
    MAT_VER             ,
    FLOW                ,
    OPER                ,
    LOT_TYPE            ,
    RWK_FLAG            ,
    QTY_1               ,
    QTY_2               ,
    QTY_3               ,
	0
FROM RRASRESLTH_OLD);

CREATE TABLE RWIPSLTHIS_OLD AS SELECT * FROM RWIPSLTHIS;
DROP TABLE RWIPSLTHIS CASCADE CONSTRAINT PURGE;

CREATE TABLE RWIPSLTHIS
(
    SUBLOT_ID              VARCHAR2(30 BYTE)      DEFAULT (' ')                 NOT NULL,
    HIST_SEQ               NUMBER(10)             DEFAULT (0)                   NOT NULL,
    TRAN_TIME              DATE,
    SYS_TRAN_TIME          DATE,
    TRAN_CODE              VARCHAR2(12 BYTE),
    LOT_ID                 VARCHAR2(25 BYTE),
    FACTORY                VARCHAR2(10 BYTE),
    MAT_ID                 VARCHAR2(30 BYTE),
    MAT_VER                NUMBER(6),
    FLOW                   VARCHAR2(20 BYTE),
    FLOW_SEQ_NUM           NUMBER(6),
    OPER                   VARCHAR2(10 BYTE),
    SLOT_NO                NUMBER(6),
    QTY_2                  NUMBER(10,3),
    QTY_3                  NUMBER(10,3),
    CRR_ID                 VARCHAR2(20 BYTE),
    OWNER_CODE             VARCHAR2(10 BYTE),
    CREATE_CODE            VARCHAR2(10 BYTE),
    SUBLOT_STATUS          VARCHAR2(10 BYTE),
    HOLD_FLAG              VARCHAR2(1 BYTE),
    HOLD_CODE              VARCHAR2(10 BYTE),
    HOLD_PASSWORD          VARCHAR2(20 BYTE),
    HOLD_PRV_GRP_ID        VARCHAR2(20 BYTE),
    OPER_IN_QTY_2          NUMBER(10,3),
    OPER_IN_QTY_3          NUMBER(10,3),
    CREATE_QTY_2           NUMBER(10,3),
    CREATE_QTY_3           NUMBER(10,3),
    START_QTY_2            NUMBER(10,3),
    START_QTY_3            NUMBER(10,3),
    INV_FLAG               VARCHAR2(1 BYTE),
    TRANSIT_FLAG           VARCHAR2(1 BYTE),
    UNIT_EXIST_FLAG        VARCHAR2(1 BYTE),
    INV_UNIT               VARCHAR2(10 BYTE),
    RWK_FLAG               VARCHAR2(1 BYTE),
    RWK_CODE               VARCHAR2(10 BYTE),
    RWK_COUNT              NUMBER(6),
    RWK_RET_FLOW           VARCHAR2(20 BYTE),
    RWK_RET_FLOW_SEQ_NUM   NUMBER(6),
    RWK_RET_OPER           VARCHAR2(10 BYTE),
    RWK_END_FLOW           VARCHAR2(20 BYTE),
    RWK_END_FLOW_SEQ_NUM   NUMBER(6),
    RWK_END_OPER           VARCHAR2(10 BYTE),
    RWK_RET_CLEAR_FLAG     VARCHAR2(1 BYTE),
    RWK_TIME               DATE,
    NSTD_FLAG              VARCHAR2(1 BYTE),
    NSTD_RET_FLOW          VARCHAR2(20 BYTE),
    NSTD_RET_FLOW_SEQ_NUM  NUMBER(6),
    NSTD_RET_OPER          VARCHAR2(10 BYTE),
    NSTD_TIME              DATE,
    REP_FLAG               VARCHAR2(1 BYTE),
    REP_RET_OPER           VARCHAR2(10 BYTE),
    STR_RET_FLOW           VARCHAR2(20 BYTE),
    STR_RET_FLOW_SEQ_NUM   NUMBER(6),
    STR_RET_OPER           VARCHAR2(10 BYTE),
    CREATE_TIME            DATE,
    FAC_IN_TIME            DATE,
    FLOW_IN_TIME           DATE,
    OPER_IN_TIME           DATE,
    START_FLAG             VARCHAR2(1 BYTE),
    START_TIME             DATE,
    START_RES_ID           VARCHAR2(20 BYTE),
    END_FLAG               VARCHAR2(1 BYTE),
    END_TIME               DATE,
    END_RES_ID             VARCHAR2(20 BYTE),
    SAMPLE_FLAG            VARCHAR2(1 BYTE),
    SAMPLE_WAIT_FLAG       VARCHAR2(1 BYTE),
    SAMPLE_RESULT          VARCHAR2(1 BYTE),
    RESERVE_RES_ID         VARCHAR2(20 BYTE),
    PORT_ID                VARCHAR2(10 BYTE),
    SUBLOT_LOCATION_1      VARCHAR2(20 BYTE),
    SUBLOT_LOCATION_2      VARCHAR2(20 BYTE),
    SUBLOT_LOCATION_3      VARCHAR2(20 BYTE),
    SUBRES_ID              VARCHAR2(20 BYTE),
    SUBLOT_CMF_1           VARCHAR2(30 BYTE),
    SUBLOT_CMF_2           VARCHAR2(30 BYTE),
    SUBLOT_CMF_3           VARCHAR2(30 BYTE),
    SUBLOT_CMF_4           VARCHAR2(30 BYTE),
    SUBLOT_CMF_5           VARCHAR2(30 BYTE),
    SUBLOT_CMF_6           VARCHAR2(30 BYTE),
    SUBLOT_CMF_7           VARCHAR2(30 BYTE),
    SUBLOT_CMF_8           VARCHAR2(30 BYTE),
    SUBLOT_CMF_9           VARCHAR2(30 BYTE),
    SUBLOT_CMF_10          VARCHAR2(30 BYTE),
    SUBLOT_CMF_11          VARCHAR2(30 BYTE),
    SUBLOT_CMF_12          VARCHAR2(30 BYTE),
    SUBLOT_CMF_13          VARCHAR2(30 BYTE),
    SUBLOT_CMF_14          VARCHAR2(30 BYTE),
    SUBLOT_CMF_15          VARCHAR2(30 BYTE),
    SUBLOT_CMF_16          VARCHAR2(30 BYTE),
    SUBLOT_CMF_17          VARCHAR2(30 BYTE),
    SUBLOT_CMF_18          VARCHAR2(30 BYTE),
    SUBLOT_CMF_19          VARCHAR2(30 BYTE),
    SUBLOT_CMF_20          VARCHAR2(30 BYTE),
    SUBLOT_DEL_FLAG        VARCHAR2(1 BYTE),
    SUBLOT_DEL_CODE        VARCHAR2(10 BYTE),
    SUBLOT_DEL_TIME        DATE,
    GRADE                  VARCHAR2(1 BYTE),
    GRADE_CODE             VARCHAR2(10 BYTE),
    CELL_GRADE             VARCHAR2(500 BYTE),
    CELL_JUDGE             VARCHAR2(500 BYTE),
    LOT_BASE               VARCHAR2(1 BYTE),
    LOT_HIST_SEQ           NUMBER(10),
    OLD_FACTORY            VARCHAR2(10 BYTE),
    OLD_MAT_ID             VARCHAR2(30 BYTE),
    OLD_MAT_VER            NUMBER(6),
    OLD_FLOW               VARCHAR2(20 BYTE),
    OLD_FLOW_SEQ_NUM       NUMBER(6),
    OLD_OPER               VARCHAR2(10 BYTE),
    OLD_QTY_2              NUMBER(10,3),
    OLD_QTY_3              NUMBER(10,3),
    OLD_CRR_ID             VARCHAR2(20 BYTE),
    OLD_OWNER_CODE         VARCHAR2(10 BYTE),
    OLD_CREATE_CODE        VARCHAR2(10 BYTE),
    OLD_FAC_IN_TIME        DATE,
    OLD_FLOW_IN_TIME       DATE,
    OLD_OPER_IN_TIME       DATE,
    TRAN_CMF_1             VARCHAR2(30 BYTE),
    TRAN_CMF_2             VARCHAR2(30 BYTE),
    TRAN_CMF_3             VARCHAR2(30 BYTE),
    TRAN_CMF_4             VARCHAR2(30 BYTE),
    TRAN_CMF_5             VARCHAR2(30 BYTE),
    TRAN_CMF_6             VARCHAR2(30 BYTE),
    TRAN_CMF_7             VARCHAR2(30 BYTE),
    TRAN_CMF_8             VARCHAR2(30 BYTE),
    TRAN_CMF_9             VARCHAR2(30 BYTE),
    TRAN_CMF_10            VARCHAR2(30 BYTE),
    TRAN_CMF_11            VARCHAR2(30 BYTE),
    TRAN_CMF_12            VARCHAR2(30 BYTE),
    TRAN_CMF_13            VARCHAR2(30 BYTE),
    TRAN_CMF_14            VARCHAR2(30 BYTE),
    TRAN_CMF_15            VARCHAR2(30 BYTE),
    TRAN_CMF_16            VARCHAR2(30 BYTE),
    TRAN_CMF_17            VARCHAR2(30 BYTE),
    TRAN_CMF_18            VARCHAR2(30 BYTE),
    TRAN_CMF_19            VARCHAR2(30 BYTE),
    TRAN_CMF_20            VARCHAR2(30 BYTE),
    TRAN_USER_ID           VARCHAR2(20 BYTE),
    TRAN_COMMENT           VARCHAR2(400 BYTE),
    PREV_ACTIVE_HIST_SEQ   NUMBER(10),
    MULTI_TR_KEY           VARCHAR2(30 BYTE),
    MULTI_TR_SEQ           NUMBER(10),
    EXT_HIST_SEQ           NUMBER(10),
    HIST_DEL_FLAG          VARCHAR2(1 BYTE),
    HIST_DEL_TIME          DATE,
    HIST_DEL_USER_ID       VARCHAR2(20 BYTE),
    HIST_DEL_COMMENT       VARCHAR2(400 BYTE),
    OLD_GRADE              VARCHAR2(1 BYTE),
    OLD_LOT_ID             VARCHAR2(25 BYTE),
    OLD_SLOT_NO            NUMBER(6),
    SUBLOT_TYPE            CHAR(1),
    RESV_FIELD_1           VARCHAR2(30),
    RESV_FIELD_2           VARCHAR2(30),
    RESV_FIELD_3           VARCHAR2(30),
    RESV_FIELD_4           VARCHAR2(30),
    RESV_FIELD_5           VARCHAR2(30),
    RESV_FLAG_1            CHAR(1),
    RESV_FLAG_2            CHAR(1),
    RESV_FLAG_3            CHAR(1),
    RESV_FLAG_4            CHAR(1),
    RESV_FLAG_5            CHAR(1)
) TABLESPACE REPORT_DATA_TS;

ALTER TABLE RWIPSLTHIS
ADD CONSTRAINT RWIPSLTHIS_PK PRIMARY KEY
(
    SUBLOT_ID,
    HIST_SEQ
) USING INDEX TABLESPACE REPORT_IDX_TS;

CREATE INDEX RWIPSLTHIS_IDX_1 ON RWIPSLTHIS
(SUBLOT_ID, HIST_DEL_FLAG, TRAN_CODE)
TABLESPACE REPORT_IDX_TS;


CREATE INDEX RWIPSLTHIS_IDX_2 ON RWIPSLTHIS
(TRAN_TIME, SUBLOT_ID, HIST_DEL_FLAG, TRAN_CODE)
TABLESPACE REPORT_IDX_TS;


CREATE INDEX RWIPSLTHIS_IDX_3 ON RWIPSLTHIS
(LOT_ID, LOT_HIST_SEQ, LOT_BASE)
TABLESPACE REPORT_IDX_TS;

INSERT INTO RWIPSLTHIS VALUE ( 
SELECT 
    SUBLOT_ID              ,
    HIST_SEQ               ,
    TRAN_TIME              ,
    SYS_TRAN_TIME          ,
    TRAN_CODE              ,
    LOT_ID                 ,
    FACTORY                ,
    MAT_ID                 ,
    MAT_VER                ,
    FLOW                   ,
    FLOW_SEQ_NUM           ,
    OPER                   ,
    SLOT_NO                ,
    QTY_2                  ,
    QTY_3                  ,
    CRR_ID                 ,
    OWNER_CODE             ,
    CREATE_CODE            ,
    SUBLOT_STATUS          ,
    HOLD_FLAG              ,
    HOLD_CODE              ,
    HOLD_PASSWORD          ,
    HOLD_PRV_GRP_ID        ,
    OPER_IN_QTY_2          ,
    OPER_IN_QTY_3          ,
    CREATE_QTY_2           ,
    CREATE_QTY_3           ,
    START_QTY_2            ,
    START_QTY_3            ,
    INV_FLAG               ,
    TRANSIT_FLAG           ,
    UNIT_EXIST_FLAG        ,
    INV_UNIT               ,
    RWK_FLAG               ,
    RWK_CODE               ,
    RWK_COUNT              ,
    RWK_RET_FLOW           ,
    RWK_RET_FLOW_SEQ_NUM   ,
    RWK_RET_OPER           ,
    RWK_END_FLOW           ,
    RWK_END_FLOW_SEQ_NUM   ,
    RWK_END_OPER           ,
    RWK_RET_CLEAR_FLAG     ,
    RWK_TIME               ,
    NSTD_FLAG              ,
    NSTD_RET_FLOW          ,
    NSTD_RET_FLOW_SEQ_NUM  ,
    NSTD_RET_OPER          ,
    NSTD_TIME              ,
    REP_FLAG               ,
    REP_RET_OPER           ,
    STR_RET_FLOW           ,
    STR_RET_FLOW_SEQ_NUM   ,
    STR_RET_OPER           ,
    CREATE_TIME            ,
    FAC_IN_TIME            ,
    FLOW_IN_TIME           ,
    OPER_IN_TIME           ,
    START_FLAG             ,
    START_TIME             ,
    START_RES_ID           ,
    END_FLAG               ,
    END_TIME               ,
    END_RES_ID             ,
    SAMPLE_FLAG            ,
    SAMPLE_WAIT_FLAG       ,
    SAMPLE_RESULT          ,
    RESERVE_RES_ID         ,
    PORT_ID                ,
    SUBLOT_LOCATION_1      ,
    SUBLOT_LOCATION_2      ,
    SUBLOT_LOCATION_3      ,
    SUBRES_ID              ,
    SUBLOT_CMF_1           ,
    SUBLOT_CMF_2           ,
    SUBLOT_CMF_3           ,
    SUBLOT_CMF_4           ,
    SUBLOT_CMF_5           ,
    SUBLOT_CMF_6           ,
    SUBLOT_CMF_7           ,
    SUBLOT_CMF_8           ,
    SUBLOT_CMF_9           ,
    SUBLOT_CMF_10          ,
    SUBLOT_CMF_11          ,
    SUBLOT_CMF_12          ,
    SUBLOT_CMF_13          ,
    SUBLOT_CMF_14          ,
    SUBLOT_CMF_15          ,
    SUBLOT_CMF_16          ,
    SUBLOT_CMF_17          ,
    SUBLOT_CMF_18          ,
    SUBLOT_CMF_19          ,
    SUBLOT_CMF_20          ,
    SUBLOT_DEL_FLAG        ,
    SUBLOT_DEL_CODE        ,
    SUBLOT_DEL_TIME        ,
    GRADE                  ,
    GRADE_CODE             ,
    CELL_GRADE             ,
    CELL_JUDGE             ,
    LOT_BASE               ,
    LOT_HIST_SEQ           ,
    OLD_FACTORY            ,
    OLD_MAT_ID             ,
    OLD_MAT_VER            ,
    OLD_FLOW               ,
    OLD_FLOW_SEQ_NUM       ,
    OLD_OPER               ,
    OLD_QTY_2              ,
    OLD_QTY_3              ,
    OLD_CRR_ID             ,
    OLD_OWNER_CODE         ,
    OLD_CREATE_CODE        ,
    OLD_FAC_IN_TIME        ,
    OLD_FLOW_IN_TIME       ,
    OLD_OPER_IN_TIME       ,
    TRAN_CMF_1             ,
    TRAN_CMF_2             ,
    TRAN_CMF_3             ,
    TRAN_CMF_4             ,
    TRAN_CMF_5             ,
    TRAN_CMF_6             ,
    TRAN_CMF_7             ,
    TRAN_CMF_8             ,
    TRAN_CMF_9             ,
    TRAN_CMF_10            ,
    TRAN_CMF_11            ,
    TRAN_CMF_12            ,
    TRAN_CMF_13            ,
    TRAN_CMF_14            ,
    TRAN_CMF_15            ,
    TRAN_CMF_16            ,
    TRAN_CMF_17            ,
    TRAN_CMF_18            ,
    TRAN_CMF_19            ,
    TRAN_CMF_20            ,
    TRAN_USER_ID           ,
    TRAN_COMMENT           ,
    PREV_ACTIVE_HIST_SEQ   ,
    MULTI_TR_KEY           ,
    MULTI_TR_SEQ           ,
    EXT_HIST_SEQ           ,
    HIST_DEL_FLAG          ,
    HIST_DEL_TIME          ,
    HIST_DEL_USER_ID       ,
    HIST_DEL_COMMENT       ,
    OLD_GRADE              ,
    OLD_LOT_ID             ,
    OLD_SLOT_NO            ,
    ' '            ,
    ' '           ,
    ' '           ,
    ' '           ,
    ' '           ,
    ' '           ,
    ' '            ,
    ' '            ,
    ' '            ,
    ' '            ,
    ' '            
FROM RWIPSLTHIS_OLD);

CREATE TABLE RWIPSLTSTS_OLD AS SELECT * FROM RWIPSLTSTS;
DROP TABLE RWIPSLTSTS CASCADE CONSTRAINT PURGE;

CREATE TABLE RWIPSLTSTS
(
    SUBLOT_ID              VARCHAR2(30 BYTE)      DEFAULT (' ')                 NOT NULL,
    LOT_ID                 VARCHAR2(25 BYTE),
    FACTORY                VARCHAR2(10 BYTE),
    MAT_ID                 VARCHAR2(30 BYTE),
    MAT_VER                NUMBER(6),
    FLOW                   VARCHAR2(20 BYTE),
    FLOW_SEQ_NUM           NUMBER(6),
    OPER                   VARCHAR2(10 BYTE),
    SLOT_NO                NUMBER(6),
    QTY_2                  NUMBER(10,3),
    QTY_3                  NUMBER(10,3),
    CRR_ID                 VARCHAR2(20 BYTE),
    OWNER_CODE             VARCHAR2(10 BYTE),
    CREATE_CODE            VARCHAR2(10 BYTE),
    SUBLOT_STATUS          VARCHAR2(10 BYTE),
    HOLD_FLAG              VARCHAR2(1 BYTE),
    HOLD_CODE              VARCHAR2(10 BYTE),
    HOLD_PASSWORD          VARCHAR2(20 BYTE),
    HOLD_PRV_GRP_ID        VARCHAR2(20 BYTE),
    OPER_IN_QTY_2          NUMBER(10,3),
    OPER_IN_QTY_3          NUMBER(10,3),
    CREATE_QTY_2           NUMBER(10,3),
    CREATE_QTY_3           NUMBER(10,3),
    START_QTY_2            NUMBER(10,3),
    START_QTY_3            NUMBER(10,3),
    INV_FLAG               VARCHAR2(1 BYTE),
    TRANSIT_FLAG           VARCHAR2(1 BYTE),
    UNIT_EXIST_FLAG        VARCHAR2(1 BYTE),
    INV_UNIT               VARCHAR2(10 BYTE),
    RWK_FLAG               VARCHAR2(1 BYTE),
    RWK_CODE               VARCHAR2(10 BYTE),
    RWK_COUNT              NUMBER(6),
    RWK_RET_FLOW           VARCHAR2(20 BYTE),
    RWK_RET_FLOW_SEQ_NUM   NUMBER(6),
    RWK_RET_OPER           VARCHAR2(10 BYTE),
    RWK_END_FLOW           VARCHAR2(20 BYTE),
    RWK_END_FLOW_SEQ_NUM   NUMBER(6),
    RWK_END_OPER           VARCHAR2(10 BYTE),
    RWK_RET_CLEAR_FLAG     VARCHAR2(1 BYTE),
    RWK_TIME               DATE,
    NSTD_FLAG              VARCHAR2(1 BYTE),
    NSTD_RET_FLOW          VARCHAR2(20 BYTE),
    NSTD_RET_FLOW_SEQ_NUM  NUMBER(6),
    NSTD_RET_OPER          VARCHAR2(10 BYTE),
    NSTD_TIME              DATE,
    REP_FLAG               VARCHAR2(1 BYTE),
    REP_RET_OPER           VARCHAR2(10 BYTE),
    STR_RET_FLOW           VARCHAR2(20 BYTE),
    STR_RET_FLOW_SEQ_NUM   NUMBER(6),
    STR_RET_OPER           VARCHAR2(10 BYTE),
    CREATE_TIME            DATE,
    FAC_IN_TIME            DATE,
    FLOW_IN_TIME           DATE,
    OPER_IN_TIME           DATE,
    START_FLAG             VARCHAR2(1 BYTE),
    START_TIME             DATE,
    START_RES_ID           VARCHAR2(20 BYTE),
    END_FLAG               VARCHAR2(1 BYTE),
    END_TIME               DATE,
    END_RES_ID             VARCHAR2(20 BYTE),
    SAMPLE_FLAG            VARCHAR2(1 BYTE),
    SAMPLE_WAIT_FLAG       VARCHAR2(1 BYTE),
    SAMPLE_RESULT          VARCHAR2(1 BYTE),
    RESERVE_RES_ID         VARCHAR2(20 BYTE),
    PORT_ID                VARCHAR2(10 BYTE),
    SUBLOT_LOCATION_1      VARCHAR2(20 BYTE),
    SUBLOT_LOCATION_2      VARCHAR2(20 BYTE),
    SUBLOT_LOCATION_3      VARCHAR2(20 BYTE),
    SUBRES_ID              VARCHAR2(20 BYTE),
    SUBLOT_CMF_1           VARCHAR2(30 BYTE),
    SUBLOT_CMF_2           VARCHAR2(30 BYTE),
    SUBLOT_CMF_3           VARCHAR2(30 BYTE),
    SUBLOT_CMF_4           VARCHAR2(30 BYTE),
    SUBLOT_CMF_5           VARCHAR2(30 BYTE),
    SUBLOT_CMF_6           VARCHAR2(30 BYTE),
    SUBLOT_CMF_7           VARCHAR2(30 BYTE),
    SUBLOT_CMF_8           VARCHAR2(30 BYTE),
    SUBLOT_CMF_9           VARCHAR2(30 BYTE),
    SUBLOT_CMF_10          VARCHAR2(30 BYTE),
    SUBLOT_CMF_11          VARCHAR2(30 BYTE),
    SUBLOT_CMF_12          VARCHAR2(30 BYTE),
    SUBLOT_CMF_13          VARCHAR2(30 BYTE),
    SUBLOT_CMF_14          VARCHAR2(30 BYTE),
    SUBLOT_CMF_15          VARCHAR2(30 BYTE),
    SUBLOT_CMF_16          VARCHAR2(30 BYTE),
    SUBLOT_CMF_17          VARCHAR2(30 BYTE),
    SUBLOT_CMF_18          VARCHAR2(30 BYTE),
    SUBLOT_CMF_19          VARCHAR2(30 BYTE),
    SUBLOT_CMF_20          VARCHAR2(30 BYTE),
    SUBLOT_DEL_FLAG        VARCHAR2(1 BYTE),
    SUBLOT_DEL_CODE        VARCHAR2(10 BYTE),
    SUBLOT_DEL_TIME        DATE,
    GRADE                  VARCHAR2(1 BYTE),
    GRADE_CODE             VARCHAR2(10 BYTE),
    CELL_GRADE             VARCHAR2(500 BYTE),
    CELL_JUDGE             VARCHAR2(500 BYTE),
    LOT_BASE               VARCHAR2(1 BYTE),
    LOT_HIST_SEQ           NUMBER(10),
    LAST_TRAN_CODE         VARCHAR2(12 BYTE),
    LAST_TRAN_TIME         DATE,
    LAST_COMMENT           VARCHAR2(400 BYTE),
    LAST_ACTIVE_HIST_SEQ   NUMBER(10),
    LAST_HIST_SEQ          NUMBER(10),
    SUBLOT_TYPE            CHAR(1),
    RESV_FIELD_1           VARCHAR2(30),
    RESV_FIELD_2           VARCHAR2(30),
    RESV_FIELD_3           VARCHAR2(30),
    RESV_FIELD_4           VARCHAR2(30),
    RESV_FIELD_5           VARCHAR2(30),
    RESV_FLAG_1            CHAR(1),
    RESV_FLAG_2            CHAR(1),
    RESV_FLAG_3            CHAR(1),
    RESV_FLAG_4            CHAR(1),
    RESV_FLAG_5            CHAR(1)
) TABLESPACE REPORT_DATA_TS;

ALTER TABLE RWIPSLTSTS
ADD CONSTRAINT RWIPSLTSTS_PK PRIMARY KEY
(
    SUBLOT_ID
) USING INDEX TABLESPACE REPORT_IDX_TS;

INSERT INTO RWIPSLTSTS VALUE ( 
SELECT 
    SUBLOT_ID              ,
    LOT_ID                 ,
    FACTORY                ,
    MAT_ID                 ,
    MAT_VER                ,
    FLOW                   ,
    FLOW_SEQ_NUM           ,
    OPER                   ,
    SLOT_NO                ,
    QTY_2                  ,
    QTY_3                  ,
    CRR_ID                 ,
    OWNER_CODE             ,
    CREATE_CODE            ,
    SUBLOT_STATUS          ,
    HOLD_FLAG              ,
    HOLD_CODE              ,
    HOLD_PASSWORD          ,
    HOLD_PRV_GRP_ID        ,
    OPER_IN_QTY_2          ,
    OPER_IN_QTY_3          ,
    CREATE_QTY_2           ,
    CREATE_QTY_3           ,
    START_QTY_2            ,
    START_QTY_3            ,
    INV_FLAG               ,
    TRANSIT_FLAG           ,
    UNIT_EXIST_FLAG        ,
    INV_UNIT               ,
    RWK_FLAG               ,
    RWK_CODE               ,
    RWK_COUNT              ,
    RWK_RET_FLOW           ,
    RWK_RET_FLOW_SEQ_NUM   ,
    RWK_RET_OPER           ,
    RWK_END_FLOW           ,
    RWK_END_FLOW_SEQ_NUM   ,
    RWK_END_OPER           ,
    RWK_RET_CLEAR_FLAG     ,
    RWK_TIME               ,
    NSTD_FLAG              ,
    NSTD_RET_FLOW          ,
    NSTD_RET_FLOW_SEQ_NUM  ,
    NSTD_RET_OPER          ,
    NSTD_TIME              ,
    REP_FLAG               ,
    REP_RET_OPER           ,
    STR_RET_FLOW           ,
    STR_RET_FLOW_SEQ_NUM   ,
    STR_RET_OPER           ,
    CREATE_TIME            ,
    FAC_IN_TIME            ,
    FLOW_IN_TIME           ,
    OPER_IN_TIME           ,
    START_FLAG             ,
    START_TIME             ,
    START_RES_ID           ,
    END_FLAG               ,
    END_TIME               ,
    END_RES_ID             ,
    SAMPLE_FLAG            ,
    SAMPLE_WAIT_FLAG       ,
    SAMPLE_RESULT          ,
    RESERVE_RES_ID         ,
    PORT_ID                ,
    SUBLOT_LOCATION_1      ,
    SUBLOT_LOCATION_2      ,
    SUBLOT_LOCATION_3      ,
    SUBRES_ID              ,
    SUBLOT_CMF_1           ,
    SUBLOT_CMF_2           ,
    SUBLOT_CMF_3           ,
    SUBLOT_CMF_4           ,
    SUBLOT_CMF_5           ,
    SUBLOT_CMF_6           ,
    SUBLOT_CMF_7           ,
    SUBLOT_CMF_8           ,
    SUBLOT_CMF_9           ,
    SUBLOT_CMF_10          ,
    SUBLOT_CMF_11          ,
    SUBLOT_CMF_12          ,
    SUBLOT_CMF_13          ,
    SUBLOT_CMF_14          ,
    SUBLOT_CMF_15          ,
    SUBLOT_CMF_16          ,
    SUBLOT_CMF_17          ,
    SUBLOT_CMF_18          ,
    SUBLOT_CMF_19          ,
    SUBLOT_CMF_20          ,
    SUBLOT_DEL_FLAG        ,
    SUBLOT_DEL_CODE        ,
    SUBLOT_DEL_TIME        ,
    GRADE                  ,
    GRADE_CODE             ,
    CELL_GRADE             ,
    CELL_JUDGE             ,
    LOT_BASE               ,
    LOT_HIST_SEQ           ,
    LAST_TRAN_CODE         ,
    LAST_TRAN_TIME         ,
    LAST_COMMENT           ,
    LAST_ACTIVE_HIST_SEQ   ,
    LAST_HIST_SEQ          ,
    ' '            ,
    ' '           ,
    ' '           ,
    ' '           ,
    ' '           ,
    ' '           ,
    ' '            ,
    ' '            ,
    ' '            ,
    ' '            ,
    ' '            
FROM RWIPSLTSTS_OLD);
