/*
**
**  File Name    : MESplusV5-Table-Migration_Table.sql
**  Description  : MESplus V5 Release for Table Migration
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10g / 11g
**
**  Period       : 2012.06.30 ~ ****
**  Release Date : ****
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
**
**  1. 2012.06.29   Aiden   Create
*/




/* Add by DM KIM 2012.04.25 */
/* MMSGBBSHIS Add Column & Column Comment */

ALTER TABLE MMSGBBSHIS ADD (SYS_MSG_FLAG CHAR(1) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (POPUP_CYCLE  CHAR(1) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (PRIORITY     CHAR(1) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (APPLY_SHIFT  CHAR(1) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (APPLY_START_TIME VARCHAR2(14) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (APPLY_END_TIME VARCHAR2(14) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (AREA_ID VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (SUB_AREA_ID VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (RESG_ID VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (MAT_ID VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (FLOW VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (RCV_USER_ID VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (SEC_GRP_ID VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (PRV_GRP_ID VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (MODAL_FLAG  CHAR(1) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (AUTO_CLOSE_FLAG  CHAR(1) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (AUTO_CLOSE_TIME NUMBER(3, 0) DEFAULT (0) NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (ACK_FLAG  CHAR(1) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (ACK_TIME VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (ACK_USER_ID VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MMSGBBSHIS ADD (RCV_FACTORY VARCHAR2(10) DEFAULT (' ') NOT NULL);

COMMENT ON COLUMN MMSGBBSHIS.SYS_MSG_FLAG       IS 'System Message Flag (Y:System Message)';
COMMENT ON COLUMN MMSGBBSHIS.POPUP_CYCLE        IS 'E:Every time, O:Once and done';
COMMENT ON COLUMN MMSGBBSHIS.PRIORITY           IS 'N:Notice, 1~5';
COMMENT ON COLUMN MMSGBBSHIS.APPLY_SHIFT        IS 'N:No matter shift, 1~4';
COMMENT ON COLUMN MMSGBBSHIS.APPLY_START_TIME   IS 'Apply start time';
COMMENT ON COLUMN MMSGBBSHIS.APPLY_END_TIME     IS 'Apply end time';
COMMENT ON COLUMN MMSGBBSHIS.AREA_ID            IS 'Area';
COMMENT ON COLUMN MMSGBBSHIS.SUB_AREA_ID        IS 'Sub Area';
COMMENT ON COLUMN MMSGBBSHIS.RESG_ID            IS 'Resource Group';
COMMENT ON COLUMN MMSGBBSHIS.MAT_ID             IS 'Material';
COMMENT ON COLUMN MMSGBBSHIS.FLOW               IS 'Flow';
COMMENT ON COLUMN MMSGBBSHIS.RCV_USER_ID        IS 'Receive User ID';
COMMENT ON COLUMN MMSGBBSHIS.SEC_GRP_ID         IS 'Security Group ID';
COMMENT ON COLUMN MMSGBBSHIS.PRV_GRP_ID         IS 'Privilege Group ID';
COMMENT ON COLUMN MMSGBBSHIS.MODAL_FLAG         IS 'Y:Modal, '':Modaless';
COMMENT ON COLUMN MMSGBBSHIS.AUTO_CLOSE_FLAG    IS 'Y:Auto close';
COMMENT ON COLUMN MMSGBBSHIS.AUTO_CLOSE_TIME    IS 'Auto close time (Second)';
COMMENT ON COLUMN MMSGBBSHIS.ACK_FLAG           IS 'Acknowledge Flag';
COMMENT ON COLUMN MMSGBBSHIS.ACK_TIME           IS 'Acknowledge Time';
COMMENT ON COLUMN MMSGBBSHIS.ACK_USER_ID        IS 'Acknowledge User ID';
COMMENT ON COLUMN MMSGBBSHIS.RCV_FACTORY        IS 'Receive Factory';


/* Add by J.S. 2012.04.17 */
/* MMSGBBSFIL: Bulletin Board System Attached File Table */
CREATE TABLE MMSGBBSFIL
(
    FACTORY                  VARCHAR2(10)     DEFAULT(' ')    NOT NULL,
    MAIN_MENU_ID             VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    SUB_MENU_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    BBS_SEQ                  NUMBER(10)       DEFAULT(0)      NOT NULL,
    FILE_SEQ                 NUMBER(10)       DEFAULT(0)      NOT NULL,
    SAVE_FILE_NAME           VARCHAR2(100)    DEFAULT(' ')    NOT NULL,
    ORG_FILE_NAME            VARCHAR2(100)    DEFAULT(' ')    NOT NULL,
    /* Create/Update Info. */
    CREATE_USER_ID           VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_TIME              VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    UPDATE_USER_ID           VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    UPDATE_TIME              VARCHAR2(14)     DEFAULT(' ')    NOT NULL
) TABLESPACE HISTORY_DATA_TS;


ALTER TABLE MMSGBBSFIL
ADD CONSTRAINT MMSGBBSFIL_PK PRIMARY KEY
(
    FACTORY,
    MAIN_MENU_ID,
    SUB_MENU_ID,
    BBS_SEQ,
    FILE_SEQ
) USING INDEX TABLESPACE HISTORY_IDX_TS;

COMMENT ON TABLE MMSGBBSFIL                         IS 'Bulletin-Board-System File Definition Table';
COMMENT ON COLUMN MMSGBBSFIL.FACTORY                IS 'Factory';
COMMENT ON COLUMN MMSGBBSFIL.MAIN_MENU_ID           IS 'Main Menu ID';
COMMENT ON COLUMN MMSGBBSFIL.SUB_MENU_ID            IS 'Sub Menu ID';
COMMENT ON COLUMN MMSGBBSFIL.BBS_SEQ                IS 'Bulletin-Board-System Sequence';
COMMENT ON COLUMN MMSGBBSFIL.FILE_SEQ               IS 'File Sequence';
COMMENT ON COLUMN MMSGBBSFIL.SAVE_FILE_NAME         IS 'Saved File Name in repository';
COMMENT ON COLUMN MMSGBBSFIL.ORG_FILE_NAME          IS 'Original File Name';
COMMENT ON COLUMN MMSGBBSFIL.CREATE_USER_ID         IS 'The user who creates';
COMMENT ON COLUMN MMSGBBSFIL.CREATE_TIME            IS 'Create time';
COMMENT ON COLUMN MMSGBBSFIL.UPDATE_USER_ID         IS 'The user who updates last ';
COMMENT ON COLUMN MMSGBBSFIL.UPDATE_TIME            IS 'The time of last update ';


/*** #753 Use GCM Table Reference (2012.04.04 by JYPARK) ***/
ALTER TABLE MGCMTBLDEF ADD (KEY_1_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_1_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_2_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_2_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_3_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_3_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_4_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_4_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_5_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_5_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_6_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_6_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_7_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_7_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_8_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_8_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_9_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_9_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_10_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (KEY_10_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_1_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_1_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_2_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_2_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_3_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_3_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_4_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_4_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_5_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_5_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_6_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_6_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_7_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_7_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_8_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_8_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_9_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_9_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_10_TBL VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MGCMTBLDEF ADD (DATA_10_COL VARCHAR2(30) DEFAULT (' ') NOT NULL);

COMMENT ON COLUMN MGCMTBLDEF.KEY_1_TBL IS 'GCM table name of key 1';
COMMENT ON COLUMN MGCMTBLDEF.KEY_1_COL IS 'GCM table column of key 1';
COMMENT ON COLUMN MGCMTBLDEF.KEY_2_TBL IS 'GCM table name of key 2';
COMMENT ON COLUMN MGCMTBLDEF.KEY_2_COL IS 'GCM table column of key 2';
COMMENT ON COLUMN MGCMTBLDEF.KEY_3_TBL IS 'GCM table name of key 3';
COMMENT ON COLUMN MGCMTBLDEF.KEY_3_COL IS 'GCM table column of key 3';
COMMENT ON COLUMN MGCMTBLDEF.KEY_4_TBL IS 'GCM table name of key 4';
COMMENT ON COLUMN MGCMTBLDEF.KEY_4_COL IS 'GCM table column of key 4';
COMMENT ON COLUMN MGCMTBLDEF.KEY_5_TBL IS 'GCM table name of key 5';
COMMENT ON COLUMN MGCMTBLDEF.KEY_5_COL IS 'GCM table column of key 5';
COMMENT ON COLUMN MGCMTBLDEF.KEY_6_TBL IS 'GCM table name of key 6';
COMMENT ON COLUMN MGCMTBLDEF.KEY_6_COL IS 'GCM table column of key 6';
COMMENT ON COLUMN MGCMTBLDEF.KEY_7_TBL IS 'GCM table name of key 7';
COMMENT ON COLUMN MGCMTBLDEF.KEY_7_COL IS 'GCM table column of key 7';
COMMENT ON COLUMN MGCMTBLDEF.KEY_8_TBL IS 'GCM table name of key 8';
COMMENT ON COLUMN MGCMTBLDEF.KEY_8_COL IS 'GCM table column of key 8';
COMMENT ON COLUMN MGCMTBLDEF.KEY_9_TBL IS 'GCM table name of key 9';
COMMENT ON COLUMN MGCMTBLDEF.KEY_9_COL IS 'GCM table column of key 9';
COMMENT ON COLUMN MGCMTBLDEF.KEY_10_TBL IS 'GCM table name of key 10';
COMMENT ON COLUMN MGCMTBLDEF.KEY_10_COL IS 'GCM table column of key 10';
COMMENT ON COLUMN MGCMTBLDEF.DATA_1_TBL IS 'GCM table name of data 1';
COMMENT ON COLUMN MGCMTBLDEF.DATA_1_COL IS 'GCM table column of data 1';
COMMENT ON COLUMN MGCMTBLDEF.DATA_2_TBL IS 'GCM table name of data 2';
COMMENT ON COLUMN MGCMTBLDEF.DATA_2_COL IS 'GCM table column of data 2';
COMMENT ON COLUMN MGCMTBLDEF.DATA_3_TBL IS 'GCM table name of data 3';
COMMENT ON COLUMN MGCMTBLDEF.DATA_3_COL IS 'GCM table column of data 3';
COMMENT ON COLUMN MGCMTBLDEF.DATA_4_TBL IS 'GCM table name of data 4';
COMMENT ON COLUMN MGCMTBLDEF.DATA_4_COL IS 'GCM table column of data 4';
COMMENT ON COLUMN MGCMTBLDEF.DATA_5_TBL IS 'GCM table name of data 5';
COMMENT ON COLUMN MGCMTBLDEF.DATA_5_COL IS 'GCM table column of data 5';
COMMENT ON COLUMN MGCMTBLDEF.DATA_6_TBL IS 'GCM table name of data 6';
COMMENT ON COLUMN MGCMTBLDEF.DATA_6_COL IS 'GCM table column of data 6';
COMMENT ON COLUMN MGCMTBLDEF.DATA_7_TBL IS 'GCM table name of data 7';
COMMENT ON COLUMN MGCMTBLDEF.DATA_7_COL IS 'GCM table column of data 7';
COMMENT ON COLUMN MGCMTBLDEF.DATA_8_TBL IS 'GCM table name of data 8';
COMMENT ON COLUMN MGCMTBLDEF.DATA_8_COL IS 'GCM table column of data 8';
COMMENT ON COLUMN MGCMTBLDEF.DATA_9_TBL IS 'GCM table name of data 9';
COMMENT ON COLUMN MGCMTBLDEF.DATA_9_COL IS 'GCM table column of data 9';
COMMENT ON COLUMN MGCMTBLDEF.DATA_10_TBL IS 'GCM table name of data 10';
COMMENT ON COLUMN MGCMTBLDEF.DATA_10_COL IS 'GCM table column of data 10';
/*** End of Add (2012.04.04) ***/

/*** #995 Enhancement Attribute User Control (2012.04.13 by JYPARK) ***/
ALTER TABLE MATRNAMDEF ADD (NO_HISTORY_FLAG CHAR(1) DEFAULT (' ') NOT NULL);

COMMENT ON COLUMN MATRNAMDEF.NO_HISTORY_FLAG IS 'No History Flag';
/*** End of Add (2012.04.13) ***/

/*** #1017 System Attribute (2012.04.25 by JYPARK) ***/
ALTER TABLE MATRNAMDEF ADD (SYS_ATR_FLAG CHAR(1) DEFAULT (' ') NOT NULL);

COMMENT ON COLUMN MATRNAMDEF.SYS_ATR_FLAG IS 'System Attribute Flag';
/*** End of Add (2012.04.25) ***/

/*** #987 Start / End 시에 Multi Resource 지원(2012.04.11 by JYPARK) ***/
ALTER TABLE MRASRESLTH ADD (SUBRES_ID VARCHAR2(20) DEFAULT (' ') NOT NULL);
ALTER TABLE MRASRESLTH ADD (PORT_ID VARCHAR2(10) DEFAULT (' ') NOT NULL);
ALTER TABLE MRASRESLTH ADD (CRR_ID VARCHAR2(20) DEFAULT (' ') NOT NULL);

COMMENT ON COLUMN MRASRESLTH.SUBRES_ID IS 'Sub resource ID';
COMMENT ON COLUMN MRASRESLTH.PORT_ID IS 'Port ID';
COMMENT ON COLUMN MRASRESLTH.CRR_ID IS 'Carrier ID';
/*** End of Add (2012.04.11) ***/

/*** MEDCCOLCHR Add Column 'NO_USE_SPM_VALUE_FLAG' ***/
ALTER TABLE MEDCCOLCHR ADD (NO_USE_SPM_VALUE_FLAG CHAR(1) DEFAULT (' ') NOT NULL);

COMMENT ON COLUMN MEDCCOLCHR.NO_USE_SPM_VALUE_FLAG IS 'No Use SPM Value Flag';
/*** End of Add (2012.04.20) ***/

CREATE TABLE MBASDODDEF
(
    FACTORY               VARCHAR2(10)    DEFAULT (' ')    NOT NULL,
    DOF_ID                VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_ID                VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_SEQ               NUMBER(6)       DEFAULT (0)      NOT NULL,
    LEFT_POSITION         NUMBER(10)      DEFAULT (0)      NOT NULL,
    SPACE_COUNT           NUMBER(10)      DEFAULT (0)      NOT NULL,
    START_PAGE            NUMBER(10)      DEFAULT (0)      NOT NULL,
    STOP_PAGE             NUMBER(10)      DEFAULT (0)      NOT NULL,
    HEADER_FLAG           CHAR(1)         DEFAULT (' ')    NOT NULL,
    KEEP_LINE_FLAG        CHAR(1)         DEFAULT (' ')    NOT NULL,
    KEEP_LINE             NUMBER(10)      DEFAULT (0)      NOT NULL,
    PAGE_BREAK            CHAR(1)         DEFAULT (' ')    NOT NULL,
    ROW_DATA_INC          CHAR(1)         DEFAULT (' ')    NOT NULL,
    COL_DATA_INC          CHAR(1)         DEFAULT (' ')    NOT NULL,
    ARR_CELL_SIZE         CHAR(1)         DEFAULT (' ')    NOT NULL,
    ARR_CELL_FONT         CHAR(1)         DEFAULT (' ')    NOT NULL,
    CREATE_USER_ID        VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    CREATE_TIME           VARCHAR2(14)    DEFAULT (' ')    NOT NULL,
    UPDATE_USER_ID        VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    UPDATE_TIME           VARCHAR2(14)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_1          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_2          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_3          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_4          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_5          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FLAG_1           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_2           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_3           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_4           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_5           CHAR(1)         DEFAULT (' ')    NOT NULL
)
TABLESPACE MESPLUS_DATA_TS;

CREATE UNIQUE INDEX MBASDODDEF_PK ON MBASDODDEF
(FACTORY, DOF_ID, DOT_ID, DOT_SEQ)
LOGGING
TABLESPACE MESPLUS_IDX_TS;


CREATE TABLE MBASDOFDEF
(
    FACTORY               VARCHAR2(10)    DEFAULT (' ')    NOT NULL,
    DOF_ID                VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_DESC              VARCHAR2(100)   DEFAULT (' ')    NOT NULL,
    MODULE_NAME           VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    SERVICE_NAME          VARCHAR2(100)   DEFAULT (' ')    NOT NULL,
    PAGE_WIDTH            NUMBER(10)      DEFAULT (0)      NOT NULL,
    PAGE_HEIGHT           NUMBER(10)      DEFAULT (0)      NOT NULL,
    PAPER_TYPE            VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DIRECTION_TYPE        VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    TOP_SPACE             NUMBER(10,3)    DEFAULT (0)      NOT NULL,
    BOTTOM_SPACE          NUMBER(10,3)    DEFAULT (0)      NOT NULL,
    LEFT_SPACE            NUMBER(10,3)    DEFAULT (0)      NOT NULL,
    RIGHT_SPACE           NUMBER(10,3)    DEFAULT (0)      NOT NULL,
    DOF_GRP_1             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_GRP_2             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_GRP_3             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_GRP_4             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_GRP_5             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_GRP_6             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_GRP_7             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_GRP_8             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_GRP_9             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_GRP_10            VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_1             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_2             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_3             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_4             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_5             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_6             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_7             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_8             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_9             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOF_CMF_10            VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    CREATE_USER_ID        VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    CREATE_TIME           VARCHAR2(14)    DEFAULT (' ')    NOT NULL,
    UPDATE_USER_ID        VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    UPDATE_TIME           VARCHAR2(14)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_1          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_2          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_3          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_4          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_5          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FLAG_1           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_2           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_3           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_4           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_5           CHAR(1)         DEFAULT (' ')    NOT NULL
)
TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MBASDOFDEF ADD (
  CONSTRAINT MBASDOFDEF_PK
 PRIMARY KEY
 (FACTORY, DOF_ID)
    USING INDEX 
    TABLESPACE MESPLUS_IDX_TS);

CREATE TABLE MBASDOTDEF
(
    FACTORY               VARCHAR2(10)    DEFAULT (' ')    NOT NULL,
    DOT_ID                VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_DESC              VARCHAR2(100)   DEFAULT (' ')    NOT NULL,
    DOC_TYPE              VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    ROW_COUNT             NUMBER(10)      DEFAULT (0)      NOT NULL,
    ROW_HEIGHT            NUMBER(10)      DEFAULT (0)      NOT NULL,
    COLUMN_COUNT          NUMBER(10)      DEFAULT (0)      NOT NULL,
    COLUMN_WIDTH          NUMBER(10)      DEFAULT (0)      NOT NULL,
    DOT_GRP_1             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_GRP_2             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_GRP_3             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_GRP_4             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_GRP_5             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_GRP_6             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_GRP_7             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_GRP_8             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_GRP_9             VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_GRP_10            VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_1             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_2             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_3             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_4             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_5             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_6             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_7             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_8             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_9             VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    DOT_CMF_10            VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    CREATE_USER_ID        VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    CREATE_TIME           VARCHAR2(14)    DEFAULT (' ')    NOT NULL,
    UPDATE_USER_ID        VARCHAR2(20)    DEFAULT (' ')    NOT NULL,
    UPDATE_TIME           VARCHAR2(14)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_1          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_2          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_3          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_4          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FIELD_5          VARCHAR2(30)    DEFAULT (' ')    NOT NULL,
    RESV_FLAG_1           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_2           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_3           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_4           CHAR(1)         DEFAULT (' ')    NOT NULL,
    RESV_FLAG_5           CHAR(1)         DEFAULT (' ')    NOT NULL
)
TABLESPACE MESPLUS_DATA_TS;

CREATE INDEX MBASDOTDEF_IDX_1 ON MBASDOTDEF
(FACTORY, DOC_TYPE)
LOGGING
TABLESPACE MESPLUS_IDX_TS;

ALTER TABLE MBASDOTDEF ADD (
  CONSTRAINT MBASDOTDEF_PK
 PRIMARY KEY
 (FACTORY, DOT_ID)
    USING INDEX 
    TABLESPACE MESPLUS_IDX_TS);

/*** Add SPM Module (2012.04.20 by JYPARK) ***/
/*==== SPM(SPecification Management Module) ====*/
/* MSPMRELDEF : SPM Relation Definition */
CREATE TABLE MSPMRELDEF
(
    FACTORY                  VARCHAR2(10)     DEFAULT(' ')    NOT NULL,
    REL_LEVEL                CHAR(1)          DEFAULT(' ')    NOT NULL,
    MAT_ID                   VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    MAT_VER                  NUMBER(6,0)      DEFAULT(0)      NOT NULL,
    FLOW                     VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    OPER                     VARCHAR2(10)     DEFAULT(' ')    NOT NULL,
    SPEC_REL_ID              VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    CREATE_USER_ID           VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_TIME              VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    UPDATE_USER_ID           VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    UPDATE_TIME              VARCHAR2(14)     DEFAULT(' ')    NOT NULL
) TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MSPMRELDEF
ADD CONSTRAINT MSPMRELDEF_PK PRIMARY KEY
(
    FACTORY,
    REL_LEVEL,
    MAT_ID,
    MAT_VER,
    FLOW,
    OPER
) USING INDEX TABLESPACE MESPLUS_IDX_TS;


/* MSPMRELVER : SPM Relation Version */
CREATE TABLE MSPMRELVER
(
    SPEC_REL_ID                 VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    SPEC_REL_VER                NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    APPLY_START_TIME            VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    APPLY_END_TIME              VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    APPROVAL_FLAG               CHAR(1)          DEFAULT(' ')    NOT NULL,
    APPROVAL_USER_ID            VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    APPROVAL_TIME               VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    RELEASE_FLAG                CHAR(1)          DEFAULT(' ')    NOT NULL,
    RELEASE_USER_ID             VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    RELEASE_TIME                VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    CREATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    UPDATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    UPDATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL
) TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MSPMRELVER
ADD CONSTRAINT MSPMRELVER_PK PRIMARY KEY
(
    SPEC_REL_ID,
    SPEC_REL_VER
) USING INDEX TABLESPACE MESPLUS_IDX_TS;


/* MSPMRELCHR : SPM Relation Characters */
CREATE TABLE MSPMRELCHR
(
    SPEC_REL_ID                 VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    SPEC_REL_VER                NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    CHAR_ID                     VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    SPEC_REF_TYPE               CHAR(1)          DEFAULT(' ')    NOT NULL,
    SPEC_TYPE                   CHAR(1)          DEFAULT(' ')    NOT NULL,
    VALID_TABLE                 VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    TARGET_VALUE                VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    SPEC_OUT_COUNT              NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    UPPER_SPEC_LIMIT            VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    LOWER_SPEC_LIMIT            VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    UPPER_WARN_LIMIT            VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    LOWER_WARN_LIMIT            VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    SPEC_OUT_ALARM              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    WARN_OUT_ALARM              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CUST_SPEC_TYPE              CHAR(1)          DEFAULT(' ')    NOT NULL,
    CUST_VALID_TABLE            VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CUST_TARGET_VALUE           VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    CUST_SPEC_OUT_COUNT         NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    CUST_UPPER_SPEC_LIMIT       VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    CUST_LOWER_SPEC_LIMIT       VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    CUST_UPPER_WARN_LIMIT       VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    CUST_LOWER_WARN_LIMIT       VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    CUST_SPEC_OUT_ALARM         VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CUST_WARN_OUT_ALARM         VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    UPDATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    UPDATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL
) TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MSPMRELCHR
ADD CONSTRAINT MSPMRELCHR_PK PRIMARY KEY
(
    SPEC_REL_ID,
    SPEC_REL_VER,
    CHAR_ID
) USING INDEX TABLESPACE MESPLUS_IDX_TS;


/* MSPMCHRDSV : SPM Character Default Specification Limit by Valid Table */
CREATE TABLE MSPMCHRDSV
(
    SPEC_REL_ID                 VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    SPEC_REL_VER                NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    CHAR_ID                     VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    SPEC_REF_TYPE               CHAR(1)          DEFAULT(' ')    NOT NULL,
    VALUE                       VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    LIMIT_TYPE                  CHAR(1)          DEFAULT(' ')    NOT NULL,
    CREATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    UPDATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    UPDATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL
) TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MSPMCHRDSV
ADD CONSTRAINT MSPMCHRDSV_PK PRIMARY KEY
(
    SPEC_REL_ID,
    SPEC_REL_VER,
    CHAR_ID,
    SPEC_REF_TYPE,
    VALUE
) USING INDEX TABLESPACE MESPLUS_IDX_TS;


/* MSPMDOCIMG : SPM Document and Image store Table */
CREATE TABLE MSPMDOCIMG
(
    SPEC_REL_ID                 VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    SPEC_REL_VER                NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    DOC_NAME_1                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    DOC_NAME_2                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    DOC_NAME_3                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    DOC_NAME_4                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    DOC_NAME_5                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    IMG_NAME_1                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    IMG_NAME_2                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    IMG_NAME_3                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    IMG_NAME_4                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    IMG_NAME_5                  VARCHAR2(50)     DEFAULT(' ')    NOT NULL,
    CREATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    UPDATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    UPDATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL
) TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MSPMDOCIMG
ADD CONSTRAINT MSPMDOCIMG_PK PRIMARY KEY
(
    SPEC_REL_ID,
    SPEC_REL_VER
) USING INDEX TABLESPACE MESPLUS_IDX_TS;


/* MEDCSPMVER : SPM Character Default Specification Limit by Valid Table */
CREATE TABLE MEDCSPMVER
(
    FACTORY                     VARCHAR2(10)     DEFAULT(' ')    NOT NULL,
    OBJ_ID                      VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    OBJ_HIST_SEQ                NUMBER(10,0)     DEFAULT(0)      NOT NULL,
    COL_SET_ID                  VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    COL_SET_VER                 NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    COL_SEQ                     NUMBER(10,0)     DEFAULT(0)      NOT NULL,
    SPEC_REL_ID                 VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    SPEC_REL_VER                NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    CHAR_ID                     VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    CREATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    UPDATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    UPDATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL
) TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MEDCSPMVER
ADD CONSTRAINT MEDCSPMVER_PK PRIMARY KEY
(
    FACTORY,
    OBJ_ID,
    OBJ_HIST_SEQ,
    COL_SET_ID,
    COL_SET_VER,
    COL_SEQ,
    SPEC_REL_ID,
    SPEC_REL_VER,
    CHAR_ID
) USING INDEX TABLESPACE MESPLUS_IDX_TS;


/* MSPMATRSTS : Specification Attribute Value Status */
CREATE TABLE MSPMATRSTS
(
    SPEC_REL_ID                 VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    SPEC_REL_VER                NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    CHAR_ID                     VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    ATTR_NAME                   VARCHAR2(100)    DEFAULT(' ')    NOT NULL,
    ATTR_VALUE                  VARCHAR2(1000)   DEFAULT(' ')    NOT NULL,
    NULL_FLAG                   CHAR(1)          DEFAULT(' ')    NOT NULL,
    LAST_TRAN_TIME              VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    LAST_ACTIVE_HIST_SEQ        NUMBER(10,0)     DEFAULT(0)      NOT NULL,
    LAST_HIST_SEQ               NUMBER(10,0)     DEFAULT(0)      NOT NULL,
    CREATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    UPDATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    UPDATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL
) TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MSPMATRSTS
ADD CONSTRAINT MSPMATRSTS_PK PRIMARY KEY
(
    SPEC_REL_ID,
    SPEC_REL_VER,
    CHAR_ID,
    ATTR_NAME
) USING INDEX TABLESPACE MESPLUS_IDX_TS;


/* MSPMATRHIS : Specification Attribute Value History */
CREATE TABLE MSPMATRHIS
(
    SPEC_REL_ID                 VARCHAR2(30)     DEFAULT(' ')    NOT NULL,
    SPEC_REL_VER                NUMBER(3,0)      DEFAULT(0)      NOT NULL,
    CHAR_ID                     VARCHAR2(25)     DEFAULT(' ')    NOT NULL,
    ATTR_NAME                   VARCHAR2(100)    DEFAULT(' ')    NOT NULL,
    HIST_SEQ                    NUMBER(10,0)     DEFAULT(0)      NOT NULL,
    ATTR_OLD_VALUE              VARCHAR2(1000)   DEFAULT(' ')    NOT NULL,
    ATTR_VALUE                  VARCHAR2(1000)   DEFAULT(' ')    NOT NULL,
    NULL_FLAG                   CHAR(1)          DEFAULT(' ')    NOT NULL,
    TRAN_TIME                   VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    SYS_TRAN_TIME               VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    PREV_ACTIVE_HIST_SEQ        NUMBER(10,0)     DEFAULT(0)      NOT NULL,
    HIST_DEL_FLAG               CHAR(1)          DEFAULT(' ')    NOT NULL,
    HIST_DEL_TIME               VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    HIST_DEL_USER_ID            VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    HIST_DEL_COMMENT            VARCHAR2(400)    DEFAULT(' ')    NOT NULL,
    CREATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    CREATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL,
    UPDATE_USER_ID              VARCHAR2(20)     DEFAULT(' ')    NOT NULL,
    UPDATE_TIME                 VARCHAR2(14)     DEFAULT(' ')    NOT NULL
) TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MSPMATRHIS
ADD CONSTRAINT MSPMATRHIS_PK PRIMARY KEY
(
    SPEC_REL_ID,
    SPEC_REL_VER,
    CHAR_ID,
    ATTR_NAME,
    HIST_SEQ
) USING INDEX TABLESPACE HISTORY_IDX_TS;


CREATE TABLE MWIPELTSTS
(
    LOT_ID                  VARCHAR2(25)    DEFAULT(' ')        NOT NULL,
    LAST_HIST_SEQ           NUMBER(10)      DEFAULT(0)          NOT NULL
)TABLESPACE MESPLUS_DATA_TS;

ALTER TABLE MWIPELTSTS ADD (
CONSTRAINT MWIPELTSTS_PK
PRIMARY KEY
(
    LOT_ID
)USING INDEX TABLESPACE MESPLUS_IDX_TS); 


CREATE TABLE MWIPELTHIS
(
    LOT_ID                  VARCHAR2(25)    DEFAULT(' ')        NOT NULL,
    HIST_SEQ                NUMBER(10)      DEFAULT(0)          NOT NULL
)TABLESPACE HISTORY_DATA_TS;

ALTER TABLE MWIPELTHIS ADD (
CONSTRAINT MWIPELTHIS_PK
PRIMARY KEY
(
    LOT_ID,
    HIST_SEQ
)USING INDEX TABLESPACE HISTORY_IDX_TS); 



ALTER TABLE MWIPORDSTS ADD (ORDER_DESC VARCHAR2(50) DEFAULT (' ') NOT NULL);
COMMENT ON COLUMN MWIPORDSTS.ORDER_DESC IS 'Production order description';   

ALTER TABLE MSECUSREXT MODIFY (ENCODE_PASSWORD VARCHAR2(200) DEFAULT (' '));
ALTER TABLE MSECUSREXT MODIFY (OLD_PASSWORD_1 VARCHAR2(200) DEFAULT (' '));
ALTER TABLE MSECUSREXT MODIFY (OLD_PASSWORD_2 VARCHAR2(200) DEFAULT (' '));
ALTER TABLE MSECUSREXT MODIFY (OLD_PASSWORD_3 VARCHAR2(200) DEFAULT (' '));
ALTER TABLE MSECUSREXT MODIFY (OLD_PASSWORD_4 VARCHAR2(200) DEFAULT (' '));
ALTER TABLE MSECUSREXT MODIFY (OLD_PASSWORD_5 VARCHAR2(200) DEFAULT (' '));

