/*
**
**  File Name    : MESplusV5-Table-Migration.sql
**  Description  : MESplus V5 Release Script
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10g
**
**  Period       : 2009.03.20 ~ 2009.04.01
**  Release Date : 2009.04.01
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
**
**
**  Revision History
**  Seq   Date        Modifier      Description                        
**  ---------------------------------------------------------------------------
**  1     2009.03.20  Aiden         Make file
**  2     2009.03.20  Aiden         Fix GCM Data value length
**  3     2009.03.24  J.S           Add RTD-0022
**  3     2009.03.31  Fred Min      Modify RTD service member
   
*/

UPDATE MGCMTBLDEF SET KEY_1_SIZE = 20 WHERE TABLE_NAME = 'AREA';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 20 WHERE TABLE_NAME = 'SUB_AREA';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 10 WHERE TABLE_NAME = 'EDC_UNIT';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 30 WHERE TABLE_NAME = 'FUT_ACT_TABLES';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 12 WHERE TABLE_NAME = 'ID_GEN_TRAN_CODE';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 6  WHERE TABLE_NAME = 'PM_PERIOD';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 10 WHERE TABLE_NAME = 'PRINTER_TYPE';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 20 WHERE TABLE_NAME = 'QCM_DEFECT_GRP';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 30 WHERE TABLE_NAME = 'QCM_VENDOR';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 20 WHERE TABLE_NAME = 'SHEET_DATA_TYPE';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 20 WHERE TABLE_NAME = 'SHEET_QUERY_TYPE';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 20 WHERE TABLE_NAME = 'SHEET_SHEET_TYPE';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 30 WHERE TABLE_NAME = 'SPC_ACTION_CODE';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 30 WHERE TABLE_NAME = 'SPC_TROUBLE_CODE';
UPDATE MGCMTBLDEF SET KEY_1_SIZE = 10 WHERE TABLE_NAME = 'UNIT';

/* Add by J.S. 2009.03.24 */
Insert into MMSGMSGDEF
   (MSG_ID, MSG_GRP, MSG_1, MSG_2, MSG_3, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD-0022', 'RTD', 'RTD-0022 : This lot status is already unseleted or uncapable.', 'RTD-0022 : 이 Lot의 상태가 이미 Unselected 이거나 Uncapable입니다.', ' ', 'ADMIN', '20081219094711', ' ', ' ');



/* Add by Fred Min, 2009.03.31 */
Delete from MSVMSVCMBR where service_name = 'RTD_Update_Dispatcher_Event';
Delete from MSVMSVCMBR where service_name = 'RTD_Adjust_Lot_Priority';
Delete from MSVMSVCMBR where service_name = 'RTD_View_Dispatched_Lot_List';
Delete from MSVMSVCMBR where service_name = 'RTD_View_Dispatcher_Event';

Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'PASSPORT', 0, ' ', ' ', ' ', ' ', 0, 'PASSPORT', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'LANGUAGE', 1, ' ', ' ', ' ', ' ', 0, 'LANGUAGE', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'FACTORY', 2, ' ', ' ', ' ', ' ', 0, 'FACTORY', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'USERID', 3, ' ', ' ', ' ', ' ', 0, 'USER_ID', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'PASSWORD', 4, ' ', ' ', ' ', ' ', 0, 'PASSWORD', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'PROCSTEP', 5, 'Process Step. Option for expansion (''I'': Create, ''U'': Modify, ''D'': Delete)', ' ', ' ', 'Char', 1, 'PROC_STEP', ' ', 'M', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'SERVICE_NAME', 6, ' ', ' ', ' ', ' ', 0, 'SERVICE_NAME', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'SERVICE_SEQ', 7, ' ', ' ', ' ', ' ', 0, 'SERVICE_SEQ', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'SERVICE_DESC', 8, ' ', ' ', ' ', ' ', 0, 'SERVICE_DESC', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'CHK_MEMBER', 9, ' ', ' ', ' ', ' ', 0, 'CHK_MEMBER', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'CHK_FLAG', 10, 'Indication of whether or how to validate Check Member with Check Status or Check Table. (''='': Equal, ''!'': Not Equal, ''N'': Not Check, ''>'': Greater than, ''<'': Less than, ''T'': Check GCM Table)', ' ', ' ', 'Char', 1, 'CHK_FLAG', ' ', 'O', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'CHK_STS', 11, ' ', ' ', ' ', ' ', 0, 'CHK_STS', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'CHK_TBL', 12, ' ', ' ', ' ', ' ', 0, 'CHK_TBL', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'CHK_SQL', 13, ' ', ' ', ' ', ' ', 0, 'CHK_SQL', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'DEPENDENT_SEQ', 14, ' ', ' ', ' ', ' ', 0, 'DEPENDENT_SEQ', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'DEPENDENT_COMBINATION', 15, ' ', ' ', ' ', ' ', 0, 'DEPENDENT_COMBINATION', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'ACTION_ARRAY_1', 16, ' ', ' ', ' ', ' ', 0, 'ACTION_ARRAY_1', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'ACTION_ARRAY_2', 17, ' ', ' ', ' ', ' ', 0, 'ACTION_ARRAY_2', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'ACTION_MEMBER_1', 18, ' ', ' ', ' ', ' ', 0, 'ACTION_MEMBER_1', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'ACTION_MEMBER_2', 19, ' ', ' ', ' ', ' ', 0, 'ACTION_MEMBER_2', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'ACTION_MEMBER_3', 20, ' ', ' ', ' ', ' ', 0, 'ACTION_MEMBER_3', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'ACTION_MEMBER_4', 21, ' ', ' ', ' ', ' ', 0, 'ACTION_MEMBER_4', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'ACTION_FLAG', 22, ' ', ' ', ' ', ' ', 0, 'ACTION_FLAG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'CUSTOM_ACTION_KEY', 23, ' ', ' ', ' ', ' ', 0, 'CUSTOM_ACTION_KEY', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'I', 0, 'UNSELECT_CAPABLE_ONLY_FLAG', 24, 'If this flag is set, RTD calculate unselect, capable rule item only. Without re-dispatching', ' ', ' ', 'Char', 0, 'UNSELECT_CAPABLE_ONLY_FLAG', ' ', 'O', ' ', 'Y', ' ', 0, 0, 'ADMIN', '20090317142616', 'ADMIN', '20090317142721');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'O', 0, 'STATUSVALUE', 0, ' ', ' ', ' ', ' ', 0, 'STATUS_VALUE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'O', 0, 'MSGCODE', 1, ' ', ' ', ' ', ' ', 0, 'MSG_CODE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'O', 0, 'MSG', 2, ' ', ' ', ' ', ' ', 0, 'MSG', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'O', 0, 'MSGCATE', 3, ' ', ' ', ' ', ' ', 0, 'MSG_CATE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'O', 0, 'FIELDMSG', 4, ' ', ' ', ' ', ' ', 0, 'FIELD_MSG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'O', 0, 'DBERRMSG', 5, ' ', ' ', ' ', ' ', 0, 'DB_ERR_MSG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Update_Dispatcher_Event', 'O', 0, 'CSTATUS', 6, ' ', ' ', ' ', ' ', 0, 'CSTATUS', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');

Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'PASSPORT', 0, ' ', ' ', ' ', ' ', 0, 'PASSPORT', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'LANGUAGE', 1, ' ', ' ', ' ', ' ', 0, 'LANGUAGE', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'FACTORY', 2, ' ', ' ', ' ', ' ', 0, 'FACTORY', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'USERID', 3, ' ', ' ', ' ', ' ', 0, 'USER_ID', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'PASSWORD', 4, ' ', ' ', ' ', ' ', 0, 'PASSWORD', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'PROCSTEP', 5, 'Process Step. Option for expansion (''1'': Priority Up, ''2'': Priority Down, ''3'': Adjust to Unselectable status. Unselected_Flag to ''Y'', ''4'': Cancel Adjustment of Lot Priority, ''5'': Adjust to Uncapable status. Capable_Flag to ''N'')', ' ', ' ', 'Char', 1, 'PROC_STEP', ' ', 'M', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'RES_OPER_FLAG', 6, ' ', ' ', ' ', ' ', 0, 'RES_OPER_FLAG', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'RES_OPER_ID', 7, ' ', ' ', ' ', ' ', 0, 'RES_OPER_ID', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'LOT_ID', 8, 'Lot ID to change Dispatch Priority', ' ', ' ', 'String', 25, 'LOT_ID', ' ', 'M', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'PRIORITY_SCORE', 9, ' ', ' ', ' ', ' ', 0, 'PRIORITY_SCORE', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'I', 0, 'PRI_ADJUST_REASON', 10, ' ', ' ', ' ', ' ', 0, 'PRI_ADJUST_REASON', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'O', 0, 'STATUSVALUE', 0, ' ', ' ', ' ', ' ', 0, 'STATUS_VALUE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'O', 0, 'MSGCODE', 1, ' ', ' ', ' ', ' ', 0, 'MSG_CODE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'O', 0, 'MSG', 2, ' ', ' ', ' ', ' ', 0, 'MSG', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'O', 0, 'MSGCATE', 3, ' ', ' ', ' ', ' ', 0, 'MSG_CATE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'O', 0, 'FIELDMSG', 4, ' ', ' ', ' ', ' ', 0, 'FIELD_MSG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'O', 0, 'DBERRMSG', 5, ' ', ' ', ' ', ' ', 0, 'DB_ERR_MSG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_Adjust_Lot_Priority', 'O', 0, 'CSTATUS', 6, ' ', ' ', ' ', ' ', 0, 'CSTATUS', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');

Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'PASSPORT', 0, ' ', ' ', ' ', ' ', 0, 'PASSPORT', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'LANGUAGE', 1, ' ', ' ', ' ', ' ', 0, 'LANGUAGE', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'FACTORY', 2, ' ', ' ', ' ', ' ', 0, 'FACTORY', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'USERID', 3, ' ', ' ', ' ', ' ', 0, 'USER_ID', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'PASSWORD', 4, ' ', ' ', ' ', ' ', 0, 'PASSWORD', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'PROCSTEP', 5, 'Process Step. Option for expansion (''1''-View Pre-dispatched Lot List)', ' ', ' ', 'Char', 1, 'PROC_STEP', ' ', 'M', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'RES_OPER_FLAG', 6, 'Indication of Resource or Operation (''R''-Resource, ''O''-Operation)', ' ', ' ', 'Char', 0, 'RES_OPER_FLAG', ' ', 'M', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'RES_OPER_ID', 7, 'Resource or Operation ID. When RES_OPER_FLAG is''R'', then Resource ID and  when RES_OPER_FLAG is ''O'', then Operation ID.', ' ', ' ', 'String', 20, 'RES_OPER_ID', ' ', 'M', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'MAX_COUNT', 8, ' ', ' ', ' ', ' ', 0, 'MAX_COUNT', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'INCLUDE_UNSELECT', 9, 'Indication of whether including Unseletable Item in Dispatch Result or not (''Y''-Including Unseletable Item)', ' ', ' ', 'Char', 0, 'INCLUDE_UNSELECT', ' ', 'O', ' ', 'Y', ' ', 0, 0, 'ADMIN', '20090317143144', 'ADMIN', '20090317143439');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'I', 0, 'INCLUDE_UNCAPABLE', 10, 'Indication of whether including Uncapable Item in Dispatch Result or not (''Y''-Including Uncapable Item)', ' ', ' ', 'Char', 0, 'INCLUDE_UNCAPABLE', ' ', 'O', ' ', 'Y', ' ', 0, 0, 'ADMIN', '20090317143208', 'ADMIN', '20090317143403');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 0, 'STATUSVALUE', 0, ' ', ' ', ' ', ' ', 0, 'STATUS_VALUE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 0, 'MSGCODE', 1, ' ', ' ', ' ', ' ', 0, 'MSG_CODE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 0, 'MSG', 2, ' ', ' ', ' ', ' ', 0, 'MSG', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 0, 'MSGCATE', 3, ' ', ' ', ' ', ' ', 0, 'MSG_CATE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 0, 'FIELDMSG', 4, ' ', ' ', ' ', ' ', 0, 'FIELD_MSG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 0, 'DBERRMSG', 5, ' ', ' ', ' ', ' ', 0, 'DB_ERR_MSG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 0, 'LIST', 6, ' ', ' ', ' ', 'List', 0, ' ', ' ', 'O', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'LOT_ID', 0, ' ', ' ', ' ', ' ', 0, 'LOT_ID', ' ', 'O', 'LIST', ' ', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090312093234');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'SET_OPER', 1, ' ', ' ', ' ', ' ', 0, 'SET_OPER', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'SET_RESG_ID', 2, ' ', ' ', ' ', ' ', 0, 'SET_RESG_ID', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'SET_RES_ID', 3, ' ', ' ', ' ', ' ', 0, 'SET_RES_ID', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'DSP_ID', 4, ' ', ' ', ' ', ' ', 0, 'DSP_ID', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'RULE_ID', 5, ' ', ' ', ' ', ' ', 0, 'RULE_ID', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'TEMP_BATCH_ID', 6, ' ', ' ', ' ', ' ', 0, 'TEMP_BATCH_ID', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'CUR_OPER', 7, ' ', ' ', ' ', ' ', 0, 'CUR_OPER', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'REFERENCE_OPER', 8, ' ', ' ', ' ', ' ', 0, 'REFERENCE_OPER', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'UNSELECTED_FLAG', 9, ' ', ' ', ' ', ' ', 0, 'UNSELECTED_FLAG', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'LOT_RESV_FLAG', 10, ' ', ' ', ' ', ' ', 0, 'LOT_RESV_FLAG', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'LOT_RESV_TIME', 11, ' ', ' ', ' ', ' ', 0, 'LOT_RESV_TIME', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'CAPABLE_FLAG', 12, ' ', ' ', ' ', ' ', 0, 'CAPABLE_FLAG', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PRI_ADJUST_FLAG', 13, ' ', ' ', ' ', ' ', 0, 'PRI_ADJUST_FLAG', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PRIORITY_SCORE', 14, ' ', ' ', ' ', ' ', 0, 'PRIORITY_SCORE', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PRIORITY_SUPPORT', 15, ' ', ' ', ' ', ' ', 0, 'PRIORITY_SUPPORT', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'HIST_SEQ', 16, ' ', ' ', ' ', ' ', 0, 'HIST_SEQ', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PRI_ADJUST_REASON', 17, ' ', ' ', ' ', ' ', 0, 'PRI_ADJUST_REASON', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'TRIGGER_BY', 18, ' ', ' ', ' ', ' ', 0, 'TRIGGER_BY', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'DSP_REASON', 19, ' ', ' ', ' ', ' ', 0, 'DSP_REASON', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'UNSELECT_REASON', 20, 'Information of Dispatch calculation result. It shows unseleted reason.', ' ', ' ', 'String', 1000, 'UNSELECT_REASON', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317143910', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'CAPABLE_REASON', 21, 'Information of Dispatch calculation result. It shows capable or uncapable reason.', ' ', ' ', 'String', 1000, 'CAPABLE_REASON', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317143943', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_1', 22, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_1', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_2', 23, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_2', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_3', 24, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_3', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_4', 25, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_4', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_5', 26, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_5', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_6', 27, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_6', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_7', 28, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_7', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_8', 29, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_8', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_9', 30, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_9', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'PDS_CMF_10', 31, 'Customized field', ' ', ' ', 'String', 30, 'PDS_CMF_10', ' ', 'O', 'LIST', 'Y', ' ', 0, 0, 'ADMIN', '20090317150938', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'CREATE_USER_ID', 32, ' ', ' ', ' ', ' ', 0, 'CREATE_USER_ID', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150937');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'CREATE_TIME', 33, ' ', ' ', ' ', ' ', 0, 'CREATE_TIME', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150937');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'UPDATE_USER_ID', 34, ' ', ' ', ' ', ' ', 0, 'UPDATE_USER_ID', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'UPDATE_TIME', 35, ' ', ' ', ' ', ' ', 0, 'UPDATE_TIME', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'MAT_ID', 36, ' ', ' ', ' ', ' ', 0, 'MAT_ID', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'MAT_VER', 37, ' ', ' ', ' ', ' ', 0, 'MAT_VER', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'FLOW', 38, ' ', ' ', ' ', ' ', 0, 'FLOW', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'FLOW_SEQ_NUM', 39, ' ', ' ', ' ', ' ', 0, 'FLOW_SEQ_NUM', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'OPER', 40, ' ', ' ', ' ', ' ', 0, 'OPER', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'QTY_1', 41, ' ', ' ', ' ', ' ', 0, 'QTY_1', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'QTY_2', 42, ' ', ' ', ' ', ' ', 0, 'QTY_2', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'QTY_3', 43, ' ', ' ', ' ', ' ', 0, 'QTY_3', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'LOT_TYPE', 44, ' ', ' ', ' ', ' ', 0, 'LOT_TYPE', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'CREATE_CODE', 45, ' ', ' ', ' ', ' ', 0, 'CREATE_CODE', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'OWNER_CODE', 46, ' ', ' ', ' ', ' ', 0, 'OWNER_CODE', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'LOT_PRIORITY', 47, ' ', ' ', ' ', ' ', 0, 'LOT_PRIORITY', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'LOT_STATUS', 48, ' ', ' ', ' ', ' ', 0, 'LOT_STATUS', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'HOLD_FLAG', 49, ' ', ' ', ' ', ' ', 0, 'HOLD_FLAG', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'RWK_FLAG', 50, ' ', ' ', ' ', ' ', 0, 'RWK_FLAG', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'NSTD_FLAG', 51, ' ', ' ', ' ', ' ', 0, 'NSTD_FLAG', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'START_FLAG', 52, ' ', ' ', ' ', ' ', 0, 'START_FLAG', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'REP_FLAG', 53, ' ', ' ', ' ', ' ', 0, 'REP_FLAG', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'ORG_DUE_TIME', 54, ' ', ' ', ' ', ' ', 0, 'ORG_DUE_TIME', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'SCH_DUE_TIME', 55, ' ', ' ', ' ', ' ', 0, 'SCH_DUE_TIME', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'OPER_IN_TIME', 56, ' ', ' ', ' ', ' ', 0, 'OPER_IN_TIME', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatched_Lot_List', 'O', 1, 'LAST_TRAN_CODE', 57, ' ', ' ', ' ', ' ', 0, 'LAST_TRAN_CODE', ' ', 'O', 'LIST', 'N', ' ', 0, 0, 'ADMIN', '200812010101', 'ADMIN', '20090317150938');

Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'I', 0, 'PASSPORT', 0, ' ', ' ', ' ', ' ', 0, 'PASSPORT', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'I', 0, 'LANGUAGE', 1, ' ', ' ', ' ', ' ', 0, 'LANGUAGE', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'I', 0, 'FACTORY', 2, ' ', ' ', ' ', ' ', 0, 'FACTORY', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'I', 0, 'USERID', 3, ' ', ' ', ' ', ' ', 0, 'USER_ID', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'I', 0, 'PASSWORD', 4, ' ', ' ', ' ', ' ', 0, 'PASSWORD', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'I', 0, 'PROCSTEP', 5, 'Process Step. Option for expansion (''1'': By Service Name and Service Sequence)', ' ', ' ', 'Char', 1, 'PROC_STEP', ' ', 'M', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'I', 0, 'SERVICE_NAME', 6, ' ', ' ', ' ', ' ', 0, 'SERVICE_NAME', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'I', 0, 'SERVICE_SEQ', 7, ' ', ' ', ' ', ' ', 0, 'SERVICE_SEQ', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'STATUSVALUE', 0, ' ', ' ', ' ', ' ', 0, 'STATUS_VALUE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'MSGCODE', 1, ' ', ' ', ' ', ' ', 0, 'MSG_CODE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'MSG', 2, ' ', ' ', ' ', ' ', 0, 'MSG', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'MSGCATE', 3, ' ', ' ', ' ', ' ', 0, 'MSG_CATE', ' ', 'M', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'FIELDMSG', 4, ' ', ' ', ' ', ' ', 0, 'FIELD_MSG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'DBERRMSG', 5, ' ', ' ', ' ', ' ', 0, 'DB_ERR_MSG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'FACTORY', 6, ' ', ' ', ' ', ' ', 0, 'FACTORY', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'SERVICE_NAME', 7, ' ', ' ', ' ', ' ', 0, 'SERVICE_NAME', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'SERVICE_SEQ', 8, ' ', ' ', ' ', ' ', 0, 'SERVICE_SEQ', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'SERVICE_DESC', 9, ' ', ' ', ' ', ' ', 0, 'SERVICE_DESC', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'CHK_MEMBER', 10, ' ', ' ', ' ', ' ', 0, 'CHK_MEMBER', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'CHK_FLAG', 11, 'Indication of whether or how to validate Check Member with Check Status or Check Table. (''='': Equal, ''!'': Not Equal, ''N'': Not Check, ''>'': Greater than, ''<'': Less than, ''T'': Check GCM Table)', ' ', ' ', 'Char', 1, 'CHK_FLAG', ' ', 'O', ' ', 'Y', 'N', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'CHK_STS', 12, ' ', ' ', ' ', ' ', 0, 'CHK_STS', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'CHK_TBL', 13, ' ', ' ', ' ', ' ', 0, 'CHK_TBL', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'CHK_SQL', 14, ' ', ' ', ' ', ' ', 0, 'CHK_SQL', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'DEPENDENT_SEQ', 15, ' ', ' ', ' ', ' ', 0, 'DEPENDENT_SEQ', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'DEPENDENT_COMBINATION', 16, ' ', ' ', ' ', ' ', 0, 'DEPENDENT_COMBINATION', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'ACTION_ARRAY_1', 17, ' ', ' ', ' ', ' ', 0, 'ACTION_ARRAY_1', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'ACTION_ARRAY_2', 18, ' ', ' ', ' ', ' ', 0, 'ACTION_ARRAY_2', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'ACTION_MEMBER_1', 19, ' ', ' ', ' ', ' ', 0, 'ACTION_MEMBER_1', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'ACTION_MEMBER_2', 20, ' ', ' ', ' ', ' ', 0, 'ACTION_MEMBER_2', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'ACTION_MEMBER_3', 21, ' ', ' ', ' ', ' ', 0, 'ACTION_MEMBER_3', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'ACTION_MEMBER_4', 22, ' ', ' ', ' ', ' ', 0, 'ACTION_MEMBER_4', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'ACTION_FLAG', 23, ' ', ' ', ' ', ' ', 0, 'ACTION_FLAG', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'CUSTOM_ACTION_KEY', 24, ' ', ' ', ' ', ' ', 0, 'CUSTOM_ACTION_KEY', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'CREATE_USER_ID', 25, ' ', ' ', ' ', ' ', 0, 'CREATE_USER_ID', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'CREATE_TIME', 26, ' ', ' ', ' ', ' ', 0, 'CREATE_TIME', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'UPDATE_USER_ID', 27, ' ', ' ', ' ', ' ', 0, 'UPDATE_USER_ID', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'UPDATE_TIME', 28, ' ', ' ', ' ', ' ', 0, 'UPDATE_TIME', ' ', 'O', ' ', 'N', ' ', 0, 0, 'ADMIN', '200812010101', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD', 'RTD_View_Dispatcher_Event', 'O', 0, 'UNSELECT_CAPABLE_ONLY_FLAG', 29, 'If this flag is set, RTD calculate unselect, capable rule item only. Without re-dispatching', ' ', ' ', 'Char', 0, 'UNSELECT_CAPABLE_ONLY_FLAG', ' ', 'O', ' ', 'Y', ' ', 0, 0, 'ADMIN', '20090317144827', ' ', ' ');


BEGIN
	FOR REC IN (
		SELECT DISTINCT FACTORY FROM MWIPFACDEF
		MINUS
		SELECT DISTINCT FACTORY FROM MGCMTBLDAT 
		WHERE TABLE_NAME = 'GLOBAL_OPTION'
		AND KEY_1 = 'IsStoreDspEventHistory'
		) 
	LOOP
        Insert into MGCMTBLDAT
           (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
        Values
           (REC.FACTORY, 'GLOBAL_OPTION', 'IsStoreDspEventHistory', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20081110135519', ' ', ' ');

	END LOOP;

	FOR REC IN (
		SELECT DISTINCT FACTORY FROM MWIPFACDEF
		MINUS
		SELECT DISTINCT FACTORY FROM MGCMTBLDAT 
		WHERE TABLE_NAME = 'GLOBAL_OPTION'
		AND KEY_1 = 'IsStoreDspResultHistory'
		) 
	LOOP
        Insert into MGCMTBLDAT
           (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
         Values
           (REC.FACTORY, 'GLOBAL_OPTION', 'IsStoreDspResultHistory', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20081110135519', 'ADMIN', '20081110144034');

	END LOOP;
END ;
/
