/*
**
**  File Name    : MESplusV5-Table-Migration.sql
**  Description  : MESplus V5 Release Script
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10g / 11g
**
**  Period       : 2010.09.06 ~ ****
**  Release Date : ****
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
**
*/

DROP TABLE MALMMSGDEF_OLD CASCADE CONSTRAINT PURGE;
DROP TABLE MATRNAMDEF_OLD CASCADE CONSTRAINT PURGE;
DROP TABLE MATRNAMHIS_OLD CASCADE CONSTRAINT PURGE;
DROP TABLE MWIPIDGDEF_OLD CASCADE CONSTRAINT PURGE;
DROP TABLE MWIPLOTSPL_OLD CASCADE CONSTRAINT PURGE;
DROP TABLE MWIPLOTMRG_OLD CASCADE CONSTRAINT PURGE;
DROP TABLE MWIPLOTCMB_OLD CASCADE CONSTRAINT PURGE;
DROP TABLE MWIPLOTRWK_OLD CASCADE CONSTRAINT PURGE;
DROP TABLE MWIPRWKDEF_OLD CASCADE CONSTRAINT PURGE;
DROP TABLE MTMPATRHIS_OLD CASCADE CONSTRAINT PURGE;

