/*
**
**  File Name    : MESplusV5-Table-Migration.sql
**  Description  : MESplus V5 Release Script
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10g
**
**  Period       : 2009.01.21 ~ ****
**  Release Date : ****
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
**
**
**  Revision History
**  Seq   Date        Modifier      Description                        
**  ---------------------------------------------------------------------------
**  1     2009.01.21  Aiden         Make file
**  2     2009.01.23  Aiden         Add SVM module function to ADMIN_GROUP in SYSTEM factory.
**  3     2009.02.06  Aiden         Add YESNO GCM table
**  4     2009.02.11  DanielJeong   add SEC_View_Group_By_Type_Privilege_List service
   
*/


DELETE FROM MSECGRPFUN WHERE FACTORY = 'SYSTEM' AND PROGRAM_ID = 'MESClient' AND SEC_GRP_ID = 'ADMIN_GROUP';

Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'TOP0001', '!', ' ', ' ', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SEC1000', '!.!', ' ', ' ', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SEC1001', '!.!.!', ' ', ' ', 'N', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SEC1002', '!.!."', ' ', ' ', 'N', 'Y', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SEC1003', '!.!.#', ' ', ' ', 'N', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SEC1004', '!.!.$', ' ', ' ', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'GCM1000', '!."', ' ', ' ', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'GCM1001', '!.".!', ' ', ' ', 'N', 'Y', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'GCM1002', '!."."', ' ', ' ', 'N', 'Y', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'MSG1000', '!.#', ' ', ' ', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'MSG1001', '!.#.!', ' ', ' ', 'N', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'WIP1000', '!.$', 'Y', ' ', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'WIP1001', '!.$.!', ' ', ' ', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'WIP1007', '!.$."', ' ', ' ', 'N', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SVM1000', '!.%', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SVM1002', '!.%.!', ' ', ' ', ' ', 'Y', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SVM1001', '!.%."', ' ', ' ', ' ', 'Y', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SVM1003', '!.%.#', ' ', ' ', ' ', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'SVM1004', '!.%.$', ' ', ' ', ' ', 'Y', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'TOP0005', '"', ' ', ' ', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'FAV1001', '".!', ' ', ' ', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'TOP0006', '#', ' ', ' ', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');
Insert into MSECGRPFUN
   (FACTORY, PROGRAM_ID, SEC_GRP_ID, FUNC_NAME, DISP_LEVEL, SEPARATOR, SHORT_CUT, ADD_TOOL_BAR, CTL_EN_FLAG_1, CTL_EN_FLAG_2, CTL_EN_FLAG_3, CTL_EN_FLAG_4, CTL_EN_FLAG_5, CTL_EN_FLAG_6, CTL_EN_FLAG_7, CTL_EN_FLAG_8, CTL_EN_FLAG_9, CTL_EN_FLAG_10, TAB_DS_FLAG_1, TAB_DS_FLAG_2, TAB_DS_FLAG_3, TAB_DS_FLAG_4, TAB_DS_FLAG_5, TAB_DS_FLAG_6, TAB_DS_FLAG_7, TAB_DS_FLAG_8, TAB_DS_FLAG_9, TAB_DS_FLAG_10, OPT_VALUE_1, OPT_VALUE_2, OPT_VALUE_3, OPT_VALUE_4, OPT_VALUE_5, OPT_VALUE_6, OPT_VALUE_7, OPT_VALUE_8, OPT_VALUE_9, OPT_VALUE_10, FLD_EN_ALL_FLAG, FLD_EN_MASK, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'MESClient', 'ADMIN_GROUP', 'UTL2001', '#.!', ' ', ' ', 'N', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20090123171051', ' ', ' ');

/* Add YESNO GCM Table */
Insert into MGCMTBLDEF
   (FACTORY, TABLE_NAME, TABLE_DESC, SYS_TBL_FLAG, CENTRAL_FLAG, TABLE_TYPE, USE_SQL_FLAG, TABLE_GROUP, KEY_1_PRT, KEY_1_FMT, KEY_1_SIZE, KEY_2_PRT, KEY_2_FMT, KEY_2_SIZE, KEY_3_PRT, KEY_3_FMT, KEY_3_SIZE, KEY_4_PRT, KEY_4_FMT, KEY_4_SIZE, KEY_5_PRT, KEY_5_FMT, KEY_5_SIZE, KEY_6_PRT, KEY_6_FMT, KEY_6_SIZE, KEY_7_PRT, KEY_7_FMT, KEY_7_SIZE, KEY_8_PRT, KEY_8_FMT, KEY_8_SIZE, KEY_9_PRT, KEY_9_FMT, KEY_9_SIZE, KEY_10_PRT, KEY_10_FMT, KEY_10_SIZE, DATA_1_PRT, DATA_1_FMT, DATA_1_SIZE, DATA_2_PRT, DATA_2_FMT, DATA_2_SIZE, DATA_3_PRT, DATA_3_FMT, DATA_3_SIZE, DATA_4_PRT, DATA_4_FMT, DATA_4_SIZE, DATA_5_PRT, DATA_5_FMT, DATA_5_SIZE, DATA_6_PRT, DATA_6_FMT, DATA_6_SIZE, DATA_7_PRT, DATA_7_FMT, DATA_7_SIZE, DATA_8_PRT, DATA_8_FMT, DATA_8_SIZE, DATA_9_PRT, DATA_9_FMT, DATA_9_SIZE, DATA_10_PRT, DATA_10_FMT, DATA_10_SIZE, SQL_1, SQL_2, SQL_3, SQL_4, SQL_5, TABLE_PASSWORD, SEC_CHK_FLAG, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'YESNO', 'Yes or No', 'Y', ' ', ' ', ' ', ' ', 'Yes or No', 'A', 1, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20080710102649', ' ', ' ');


Insert into MGCMTBLDAT
   (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'YESNO', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20080710102709', ' ', ' ');
Insert into MGCMTBLDAT
   (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'YESNO', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20080710102703', ' ', ' ');


BEGIN
	 FOR REC IN (
				SELECT FACTORY FROM MWIPFACDEF
				MINUS
				SELECT FACTORY FROM MGCMTBLDEF 
				WHERE TABLE_NAME = 'YESNO'
				) 
	  LOOP
			Insert into MGCMTBLDEF
			   (FACTORY, TABLE_NAME, TABLE_DESC, SYS_TBL_FLAG, CENTRAL_FLAG, TABLE_TYPE, USE_SQL_FLAG, TABLE_GROUP, KEY_1_PRT, KEY_1_FMT, KEY_1_SIZE, KEY_2_PRT, KEY_2_FMT, KEY_2_SIZE, KEY_3_PRT, KEY_3_FMT, KEY_3_SIZE, KEY_4_PRT, KEY_4_FMT, KEY_4_SIZE, KEY_5_PRT, KEY_5_FMT, KEY_5_SIZE, KEY_6_PRT, KEY_6_FMT, KEY_6_SIZE, KEY_7_PRT, KEY_7_FMT, KEY_7_SIZE, KEY_8_PRT, KEY_8_FMT, KEY_8_SIZE, KEY_9_PRT, KEY_9_FMT, KEY_9_SIZE, KEY_10_PRT, KEY_10_FMT, KEY_10_SIZE, DATA_1_PRT, DATA_1_FMT, DATA_1_SIZE, DATA_2_PRT, DATA_2_FMT, DATA_2_SIZE, DATA_3_PRT, DATA_3_FMT, DATA_3_SIZE, DATA_4_PRT, DATA_4_FMT, DATA_4_SIZE, DATA_5_PRT, DATA_5_FMT, DATA_5_SIZE, DATA_6_PRT, DATA_6_FMT, DATA_6_SIZE, DATA_7_PRT, DATA_7_FMT, DATA_7_SIZE, DATA_8_PRT, DATA_8_FMT, DATA_8_SIZE, DATA_9_PRT, DATA_9_FMT, DATA_9_SIZE, DATA_10_PRT, DATA_10_FMT, DATA_10_SIZE, SQL_1, SQL_2, SQL_3, SQL_4, SQL_5, TABLE_PASSWORD, SEC_CHK_FLAG, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
			 Values
			   (REC.FACTORY, 'YESNO', 'Yes or No', 'Y', ' ', ' ', ' ', ' ', 'Yes or No', 'A', 1, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20080710102649', ' ', ' ');

			Insert into MGCMTBLDAT
			   (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
			 Values
			   (REC.FACTORY, 'YESNO', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20080710102709', ' ', ' ');
			Insert into MGCMTBLDAT
			   (FACTORY, TABLE_NAME, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_10, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, DATA_8, DATA_9, DATA_10, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
			 Values
			   (REC.FACTORY, 'YESNO', 'Y', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20080710102703', ' ', ' ');

	  END LOOP;			
END ;
/

Insert into MGCMTBLDEF
   (FACTORY, TABLE_NAME, TABLE_DESC, SYS_TBL_FLAG, CENTRAL_FLAG, TABLE_TYPE, USE_SQL_FLAG, TABLE_GROUP, KEY_1_PRT, KEY_1_FMT, KEY_1_SIZE, KEY_2_PRT, KEY_2_FMT, KEY_2_SIZE, KEY_3_PRT, KEY_3_FMT, KEY_3_SIZE, KEY_4_PRT, KEY_4_FMT, KEY_4_SIZE, KEY_5_PRT, KEY_5_FMT, KEY_5_SIZE, KEY_6_PRT, KEY_6_FMT, KEY_6_SIZE, KEY_7_PRT, KEY_7_FMT, KEY_7_SIZE, KEY_8_PRT, KEY_8_FMT, KEY_8_SIZE, KEY_9_PRT, KEY_9_FMT, KEY_9_SIZE, KEY_10_PRT, KEY_10_FMT, KEY_10_SIZE, DATA_1_PRT, DATA_1_FMT, DATA_1_SIZE, DATA_2_PRT, DATA_2_FMT, DATA_2_SIZE, DATA_3_PRT, DATA_3_FMT, DATA_3_SIZE, DATA_4_PRT, DATA_4_FMT, DATA_4_SIZE, DATA_5_PRT, DATA_5_FMT, DATA_5_SIZE, DATA_6_PRT, DATA_6_FMT, DATA_6_SIZE, DATA_7_PRT, DATA_7_FMT, DATA_7_SIZE, DATA_8_PRT, DATA_8_FMT, DATA_8_SIZE, DATA_9_PRT, DATA_9_FMT, DATA_9_SIZE, DATA_10_PRT, DATA_10_FMT, DATA_10_SIZE, SQL_1, SQL_2, SQL_3, SQL_4, SQL_5, TABLE_PASSWORD, SEC_CHK_FLAG, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SYSTEM', 'FUT_ACT_TABLES', 'Future Action Tables', 'Y', ' ', ' ', ' ', 'WIP', 'DATABASE TABLE NAME', 'A', 20, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, 'DESCRIPTION', 'A', 50, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20071217162250', 'ADMIN', '20071217162505');

BEGIN
	 FOR REC IN (
				SELECT FACTORY FROM MWIPFACDEF
				MINUS
				SELECT FACTORY FROM MGCMTBLDEF 
				WHERE TABLE_NAME = 'FUT_ACT_TABLES'
				) 
	  LOOP
			Insert into MGCMTBLDEF
			   (FACTORY, TABLE_NAME, TABLE_DESC, SYS_TBL_FLAG, CENTRAL_FLAG, TABLE_TYPE, USE_SQL_FLAG, TABLE_GROUP, KEY_1_PRT, KEY_1_FMT, KEY_1_SIZE, KEY_2_PRT, KEY_2_FMT, KEY_2_SIZE, KEY_3_PRT, KEY_3_FMT, KEY_3_SIZE, KEY_4_PRT, KEY_4_FMT, KEY_4_SIZE, KEY_5_PRT, KEY_5_FMT, KEY_5_SIZE, KEY_6_PRT, KEY_6_FMT, KEY_6_SIZE, KEY_7_PRT, KEY_7_FMT, KEY_7_SIZE, KEY_8_PRT, KEY_8_FMT, KEY_8_SIZE, KEY_9_PRT, KEY_9_FMT, KEY_9_SIZE, KEY_10_PRT, KEY_10_FMT, KEY_10_SIZE, DATA_1_PRT, DATA_1_FMT, DATA_1_SIZE, DATA_2_PRT, DATA_2_FMT, DATA_2_SIZE, DATA_3_PRT, DATA_3_FMT, DATA_3_SIZE, DATA_4_PRT, DATA_4_FMT, DATA_4_SIZE, DATA_5_PRT, DATA_5_FMT, DATA_5_SIZE, DATA_6_PRT, DATA_6_FMT, DATA_6_SIZE, DATA_7_PRT, DATA_7_FMT, DATA_7_SIZE, DATA_8_PRT, DATA_8_FMT, DATA_8_SIZE, DATA_9_PRT, DATA_9_FMT, DATA_9_SIZE, DATA_10_PRT, DATA_10_FMT, DATA_10_SIZE, SQL_1, SQL_2, SQL_3, SQL_4, SQL_5, TABLE_PASSWORD, SEC_CHK_FLAG, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
			 Values
			   (REC.FACTORY, 'FUT_ACT_TABLES', 'Future Action Tables', 'Y', ' ', ' ', ' ', 'WIP', 'DATABASE TABLE NAME', 'A', 20, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, 'DESCRIPTION', 'A', 50, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', 0, ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'ADMIN', '20071217162250', 'ADMIN', '20071217162505');

	  END LOOP;			
END ;
/

Insert into MSVMSVCDEF
   (SERVICE_NAME, MODULE_NAME, SERVICE_MODE, SERVICE_CATEGORY, SERVICE_DESC_1, SERVICE_DESC_2, SERVICE_DESC_3, SEC_CHK_FLAG, SHARED_LIB_NAME, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM_Init_Shared_Pool', 'ADM', 'RN', 'T', 'Initial shared pool', ' ', ' ', ' ', ' ', 'ADMIN', '20090210203142', 'ADMIN', '20090210203237');
Insert into MSVMSVCDEF
   (SERVICE_NAME, MODULE_NAME, SERVICE_MODE, SERVICE_CATEGORY, SERVICE_DESC_1, SERVICE_DESC_2, SERVICE_DESC_3, SEC_CHK_FLAG, SHARED_LIB_NAME, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM_Change_EnvValues', 'ADM', 'RN', 'T', 'Change server environment values', ' ', ' ', ' ', ' ', 'ADMIN', '20090210203019', 'ADMIN', '20090210203105');

   
   
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Change_EnvValues', 'I', 0, 'PASSPORT', 0, ' ', ' ', ' ', ' ', 0, 'PASSPORT', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203019', 'ADMIN', '20090210203106');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Change_EnvValues', 'I', 0, 'LANGUAGE', 1, ' ', ' ', ' ', ' ', 0, 'LANGUAGE', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203019', 'ADMIN', '20090210203106');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Change_EnvValues', 'I', 0, 'FACTORY', 2, ' ', ' ', ' ', ' ', 0, 'FACTORY', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203019', 'ADMIN', '20090210203106');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Change_EnvValues', 'I', 0, 'USERID', 3, ' ', ' ', ' ', ' ', 0, 'USERID', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203019', 'ADMIN', '20090210203106');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Change_EnvValues', 'I', 0, 'PASSWORD', 4, ' ', ' ', ' ', ' ', 0, 'PASSWORD', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203019', 'ADMIN', '20090210203106');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Change_EnvValues', 'I', 0, 'PROCSTEP', 5, ' ', ' ', ' ', ' ', 0, 'PROCSTEP', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203019', 'ADMIN', '20090210203106');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Change_EnvValues', 'I', 0, 'LOGLEVEL', 6, ' ', ' ', ' ', ' ', 0, 'LOGLEVEL', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203106', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Init_Shared_Pool', 'I', 0, 'PASSPORT', 0, ' ', ' ', ' ', ' ', 0, 'PASSPORT', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203143', 'ADMIN', '20090210203238');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Init_Shared_Pool', 'I', 0, 'LANGUAGE', 1, ' ', ' ', ' ', ' ', 0, 'LANGUAGE', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203143', 'ADMIN', '20090210203238');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Init_Shared_Pool', 'I', 0, 'FACTORY', 2, ' ', ' ', ' ', ' ', 0, 'FACTORY', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203143', 'ADMIN', '20090210203238');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Init_Shared_Pool', 'I', 0, 'USERID', 3, ' ', ' ', ' ', ' ', 0, 'USERID', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203143', 'ADMIN', '20090210203238');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Init_Shared_Pool', 'I', 0, 'PASSWORD', 4, ' ', ' ', ' ', ' ', 0, 'PASSWORD', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203143', 'ADMIN', '20090210203238');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Init_Shared_Pool', 'I', 0, 'PROCSTEP', 5, ' ', ' ', ' ', ' ', 0, 'PROCSTEP', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203143', 'ADMIN', '20090210203238');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('ADM', 'ADM_Init_Shared_Pool', 'I', 0, 'SERVER_NAME', 6, ' ', ' ', ' ', ' ', 0, ' ', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20090210203238', ' ', ' ');
   
Insert into MMSGMSGDEF
   (MSG_ID, MSG_GRP, MSG_1, MSG_2, MSG_3, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('CMN-0007', 'CMN', 'CMN-0007 : This service is successful and SUBLOT is created.', 'CMN-0007 : 작업을 성공적으로 수행하고 SUBLOT을 생성하였습니다.', 'CMN-0007 :', 'ADMIN', '20090209142625', 'ADMIN', '20090209144617');

Insert into MSVMSVCDEF
   (SERVICE_NAME, MODULE_NAME, SERVICE_MODE, SERVICE_CATEGORY, SERVICE_DESC_1, SERVICE_DESC_2, SERVICE_DESC_3, SEC_CHK_FLAG, SHARED_LIB_NAME, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('RTD_Interface', 'RTD', 'RN', 'T', 'Interface Function', ' ', ' ', ' ', ' ', 'ADMIN', '20090129181440', ' ', ' ');
   
   
Insert into MSVMSVCDEF
   (MODULE_NAME, SERVICE_NAME, SERVICE_MODE, SERVICE_CATEGORY, SERVICE_DESC_1, SERVICE_DESC_2, SERVICE_DESC_3, SEC_CHK_FLAG, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'RR', 'I', 'Views List of Group By Type and Privilege', 'Views List of Group By Type and Privilege', 'Views List of Group By Type and Privilege', ' ', 'ADMIN', '20081217225935', 'ADMIN', '20081217230425');

Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'PASSPORT', 0, ' ', ' ', ' ', ' ', 0, 'PASSPORT', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'LANGUAGE', 1, ' ', ' ', ' ', ' ', 0, 'LANGUAGE', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'FACTORY', 2, ' ', ' ', ' ', ' ', 0, 'FACTORY', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'USERID', 3, ' ', ' ', ' ', ' ', 0, 'USERID', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'PASSWORD', 4, ' ', ' ', ' ', ' ', 0, 'PASSWORD', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'PROCSTEP', 5, 'Process Step. Option for expansion (''1'' Views group list by type and privilege )', ' ', ' ', 'Char', 0, 'PROCSTEP', ' ', 'M', ' ', 'Y', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230952');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'O', 0, 'STATUSVALUE', 0, ' ', ' ', ' ', ' ', 0, 'STATUSVALUE', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'O', 0, 'MSGCODE', 1, ' ', ' ', ' ', ' ', 0, 'MSGCODE', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'O', 0, 'MSG', 2, ' ', ' ', ' ', ' ', 0, 'MSG', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'O', 0, 'MSGCATE', 3, ' ', ' ', ' ', ' ', 0, 'MSGCATE', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'O', 0, 'FIELDMSG', 4, ' ', ' ', ' ', ' ', 0, 'FIELDMSG', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'O', 0, 'DBERRMSG', 5, ' ', ' ', ' ', ' ', 0, 'DBERRMSG', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217225935', 'ADMIN', '20081217230132');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'NEXT_PRV_TYPE', 6, ' ', ' ', ' ', ' ', 0, 'NEXT_PRV_TYPE', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217230252', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'NEXT_PRV_ITEM1', 7, ' ', ' ', ' ', ' ', 0, 'NEXT_PRV_ITEM1', ' ', 'M', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217230252', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'NEXT_PRV_ITEM2', 8, ' ', ' ', ' ', ' ', 0, 'NEXT_PRV_ITEM2', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217230252', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'I', 0, 'NEXT_PRV_ITEM3', 9, ' ', ' ', ' ', ' ', 0, 'NEXT_PRV_ITEM3', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217230252', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'O', 0, 'CSTATUS', 6, ' ', ' ', ' ', ' ', 0, 'CSTATUS', ' ', 'O', ' ', ' ', ' ', 0, 0, 'ADMIN', '20081217230427', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'O', 1, 'PRV_GRP_ID', 0, ' ', ' ', ' ', ' ', 0, 'PRV_GRP_ID', ' ', 'O', 'CSTATUS', ' ', ' ', 0, 0, 'ADMIN', '20081217230427', ' ', ' ');
Insert into MSVMSVCMBR
   (MODULE_NAME, SERVICE_NAME, DIRECTION, MEMBER_DEPTH, MEMBER_NAME, MEMBER_SEQ, MEMBER_DESC_1, MEMBER_DESC_2, MEMBER_DESC_3, MEMBER_TYPE, MEMBER_SIZE, MEMBER_PRT, ARRAY_TYPE, REQ_MEMBER_FLAG, PARENT_MEMBER_NAME, OVERRIDE_FLAG, USE_RANGE_FLAG, RANGE_MIN, RANGE_MAX, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
 Values
   ('SEC', 'SEC_View_Group_By_Type_Privilege_List', 'O', 1, 'PRV_GRP_DESC', 1, ' ', ' ', ' ', ' ', 0, 'PRV_GRP_DESC', ' ', 'O', 'CSTATUS', ' ', ' ', 0, 0, 'ADMIN', '20081217230427', ' ', ' ');

