/*
**
**  File Name    : MESplusV5-Table-Migration.sql
**  Description  : MESplus V5 Release Script
**
**  DB Type      : Oracle
**  DB Version   : Oracle 10g
**
**  Period       : 2009.06.23 ~ ****
**  Release Date : ****
**
**  Copyright(C) MIRACOM,INC. All rights reserved.
**
*/

DROP TABLE MEDCRESDAT_OLD CASCADE CONSTRAINT PURGE;

DROP TABLE MSPCCHTDEF_OLD CASCADE CONSTRAINT PURGE;

DROP TABLE MSPCCALDAT_OLD CASCADE CONSTRAINT PURGE;

DROP TABLE MRASSRSHIS_OLD CASCADE CONSTRAINT PURGE;

DROP TABLE MEDCLOTDAT_OLD CASCADE CONSTRAINT PURGE;

DROP TABLE MWIPFATDEF_OLD CASCADE CONSTRAINT PURGE;

DROP TABLE MWIPFATACT_OLD CASCADE CONSTRAINT PURGE;

DROP TABLE MRASCRRDEF_OLD CASCADE CONSTRAINT PURGE;

DROP TABLE MRASCRRHIS_OLD CASCADE CONSTRAINT PURGE;