/*******************************************************************************
' RPTBASSkeleton.vb
'
' Copyright (c) 2007 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2009-12-15 10:57:24
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
'******************************************************************************/

using System;

namespace RPTServer
{
    public class RPTBASSkeleton: RPTBASTuner
    {
        public RPTBASSkeleton(
				        h101stub instance
				        ) : base()
        {

        } 
        
        public override void RPT_SQL_Query_DataTable_Result(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out)
        {
            try
            {
                // TODO : User code

            }
            catch(Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }
        public override void RPT_View_Dynamic(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out)
        {
            try
            {
                // TODO : User code

            }
            catch (Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void RPT_Query_Definition_Setup(RPT_Query_Definition_Setup_In_Tag _In, ref Cmn_Out_Tag _Out)
        {
            try
            {
                // TODO : User code

            }
            catch (Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }

        public override void RPT_MySingle_Information(RPT_MySingle_Information_In_Tag _In, ref RPT_MySingle_Information_Out_Tag _Out)
        {
            try
            {
                // TODO : User code

            }
            catch (Exception e)
            {
                // TODO : Exception process
                throw e;
            }
        }
    
    }
}
