/*******************************************************************************
' RPTBASTuner.vb
'
' Copyright (c) 2007 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2009-12-15 10:57:24
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
'******************************************************************************/

using System;
using com.miracom.transceiverx;
using com.miracom.transceiverx.session;
using com.miracom.transceiverx.message;
using com.miracom.transceiverx.message.former;

namespace RPTServer
{
    public abstract class RPTBASTuner: h101dispatcher
    {
        #region h101dispatcher member
        public Exception dispatch(Session issuer, Message msg)
        {
            try 
            {
                GC.Collect();
                string operation = (string)msg.getProperty(h101stub.XGEN_TAG_OPERATION);
                if (operation.Equals("RPT_SQL_Query_DataTable_Result"))
                    recv_RPT_SQL_Query_DataTable_Result(issuer, msg);
                else if (operation.Equals("RPT_View_Dynamic"))
                    recv_RPT_View_Dynamic(issuer, msg);
                else if (operation.Equals("RPT_Query_Definition_Setup"))
                    recv_RPT_Query_Definition_Setup(issuer, msg);
                else if (operation.Equals("RPT_MySingle_Information"))
                    recv_RPT_MySingle_Information(issuer, msg);

                else
                {
                    if (DeliveryType.REQUEST == msg.getDeliveryMode())
                        h101stub.Instance.sendReply(issuer, msg, msg.createReply(), "-23", "Unexpected Operation!");
                    return new TrxException("Unexpected Operation!(Operation:" + operation + ")");
                }
                GC.Collect();
                return null;
            }
            catch(Exception e)
            {
                throw e;
            }
        }
        #endregion

        
        public abstract void RPT_SQL_Query_DataTable_Result(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out);
        private void recv_RPT_SQL_Query_DataTable_Result(Session issuer, Message msg)
        {
            StreamTransformer former = new StreamTransformerImpl((byte[])msg.getData());
            RPT_SQL_Query_In_Tag Sql_In = new RPT_SQL_Query_In_Tag();
            RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out = new RPT_SQL_Query_DataTable_Result_Out_Tag();

            RPTBASType.transform_RPT_SQL_Query_In_Tag(former, ref Sql_In);
            RPTServerTran.RPT_SQL_Query_DataTable_Result(Sql_In, ref Sql_Out); /* Call User Procedure */
            
            if (DeliveryType.isRequest(msg.getDeliveryMode())) /* Just RequestReply */
            {
                Message rep = msg.createReply();
                former = new StreamTransformerImpl("utf-8");
                RPTBASType.serialize_RPT_SQL_Query_DataTable_Result_Out_Tag(former, Sql_Out);
                rep.putData(former.getBytes());
                h101stub.Instance.sendReply(issuer, msg, rep, "000", "");
            }
        }
        public abstract void RPT_View_Dynamic(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out);
        private void recv_RPT_View_Dynamic(Session issuer, Message msg)
        {
            StreamTransformer former = new StreamTransformerImpl((byte[])msg.getData());
            RPT_SQL_Query_In_Tag Sql_In = new RPT_SQL_Query_In_Tag();
            RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out = new RPT_SQL_Query_DataTable_Result_Out_Tag();

            RPTBASType.transform_RPT_SQL_Query_In_Tag(former, ref Sql_In);
            RSGV.gfrmMain.SetViewIDEvent(Sql_In.view_id);
            RPTServerTran.RPT_View_Dynamic(Sql_In, ref Sql_Out); /* Call User Procedure */

            if (DeliveryType.isRequest(msg.getDeliveryMode())) /* Just RequestReply */
            {
                Message rep = msg.createReply();
                former = new StreamTransformerImpl("utf-8");
                RPTBASType.serialize_RPT_SQL_Query_DataTable_Result_Out_Tag(former, Sql_Out);
                rep.putData(former.getBytes());
                h101stub.Instance.sendReply(issuer, msg, rep, "000", "");
            }
        }

        public abstract void RPT_Query_Definition_Setup(RPT_Query_Definition_Setup_In_Tag _In, ref Cmn_Out_Tag _Out);
        private void recv_RPT_Query_Definition_Setup(Session issuer, Message msg)
        {
            StreamTransformer former = new StreamTransformerImpl((byte[])msg.getData());
            RPT_Query_Definition_Setup_In_Tag _In = new RPT_Query_Definition_Setup_In_Tag();
            Cmn_Out_Tag _Out = new Cmn_Out_Tag();

            RPTBASType.transform_RPT_Query_Definition_Setup_In_Tag(former, ref _In);
            RPTServerTran.RPT_Query_Definition_Setup(_In, ref _Out); /* Call User Procedure */
            
            if (DeliveryType.isRequest(msg.getDeliveryMode())) /* Just RequestReply */
            {
                Message rep = msg.createReply();
                former = new StreamTransformerImpl("utf-8");
                RPTBASType.serialize_Cmn_Out_Tag(former, _Out);
                rep.putData(former.getBytes());
                h101stub.Instance.sendReply(issuer, msg, rep, "000", "");
            }
        }

        public abstract void RPT_MySingle_Information(RPT_MySingle_Information_In_Tag _In, ref RPT_MySingle_Information_Out_Tag _Out);
        public void recv_RPT_MySingle_Information(Session issuer, Message msg)
        {
            StreamTransformer former = new StreamTransformerImpl((byte[])msg.getData());
            RPT_MySingle_Information_In_Tag _In = new RPT_MySingle_Information_In_Tag();
            RPT_MySingle_Information_Out_Tag _Out = new RPT_MySingle_Information_Out_Tag();

            RPTBASType.transform_RPT_MySingle_Information_In_Tag(former, ref _In);
            RPTServerTran.RPT_MySingle_Information(_In, ref _Out); /* Call User Procedure */

            if (DeliveryType.isRequest(msg.getDeliveryMode())) /* Just RequestReply */
            {
                Message rep = msg.createReply();
                former = new StreamTransformerImpl("utf-8");
                RPTBASType.serialize_RPT_MySingle_Information_Out_Tag(former, _Out);
                rep.putData(former.getBytes());
                h101stub.Instance.sendReply(issuer, msg, rep, "000", "");
            }
        }

    }
}

