/*==== INSERT SECURITY GROUP ====*/
INSERT INTO RWEBGRPDEF 
( FACTORY, SEC_GRP_ID, SEC_GRP_DESC, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME )
VALUES 
('SYSTEM','ADMIN_GROUP','Administartor Group',' ',' ',' ',' '); 

/*==== INSERT USER ====*/
/* WEBADMIN : kkRJUYmD3+bpBl0joxpNhA== */
INSERT INTO RWEBUSRDEF 
(FACTORY, USER_ID, USER_DESC, PASSWORD, CHG_PASS_FLAG, USER_GRP_1, USER_GRP_2, USER_GRP_3, USER_GRP_4, USER_GRP_5, USER_GRP_6, USER_GRP_7, USER_GRP_8, USER_GRP_9, USER_GRP_10, USER_CMF_1, USER_CMF_2, USER_CMF_3, USER_CMF_4, USER_CMF_5, USER_CMF_6, USER_CMF_7, USER_CMF_8, USER_CMF_9, USER_CMF_10, SEC_GRP_ID, PHONE_OFFICE, PHONE_MOBILE, PHONE_HOME, PHONE_OTHER, ENTER_DATE, RETIRE_DATE, EMAIL_ID, BIRTHDAY, SEX_FLAG, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
VALUES 
('SYSTEM','WEBADMIN',' ','WEBADMIN',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','ADMIN_GROUP',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');

/*==== INSERT SECURITY GROUP FUNCTION ====*/

INSERT INTO RWEBGRPFUN 
(FACTORY, SEC_GRP_ID, FUNC_GRP_ID, FUNC_GRP_SEQ, FUNC_NAME, FUNC_SEQ, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
VALUES 
('SYSTEM','ADMIN_GROUP','Security',1,' ',0,' ',' ',' ',' ');

INSERT INTO RWEBGRPFUN 
(FACTORY, SEC_GRP_ID, FUNC_GRP_ID, FUNC_GRP_SEQ, FUNC_NAME, FUNC_SEQ, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
VALUES 
('SYSTEM','ADMIN_GROUP','Security',1,'SEC1101',1,' ',' ',' ',' ');

INSERT INTO RWEBGRPFUN 
(FACTORY, SEC_GRP_ID, FUNC_GRP_ID, FUNC_GRP_SEQ, FUNC_NAME, FUNC_SEQ, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
VALUES 
('SYSTEM','ADMIN_GROUP','Security',1,'SEC1102',2,' ',' ',' ',' ');

INSERT INTO RWEBGRPFUN 
(FACTORY, SEC_GRP_ID, FUNC_GRP_ID, FUNC_GRP_SEQ, FUNC_NAME, FUNC_SEQ, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
VALUES 
('SYSTEM','ADMIN_GROUP','Security',1,'SEC1103',3,' ',' ',' ',' ');

INSERT INTO RWEBGRPFUN 
(FACTORY, SEC_GRP_ID, FUNC_GRP_ID, FUNC_GRP_SEQ, FUNC_NAME, FUNC_SEQ, CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME)
VALUES 
('SYSTEM','ADMIN_GROUP','Security',1,'SEC1104',4,' ',' ',' ',' ');
