INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1110', 'Operation WIP Status (Lot List)', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1209', 'Material Group Movement Trend', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1301', 'Plan vs. Actual Report', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1402', 'Material Productivity', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1405', 'Down Code Analysis', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'SEC1101', 'User Setup', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'SEC1102', 'Security Group Setup', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'SEC1103', 'Function Setup', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' '
, ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'SEC1104', 'Security Group-Function Setup', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1101', 'Operation WIP Status', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1102', 'Material WIP Status', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1103', 'Operation-Material WIP Status', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1104', 'Material-Operation WIP Status', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1105', 'Material Group WIP Status', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1106', 'Material Group Detail WIP Status', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1107', 'BOH/EOH Trend', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' '
, ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1108', 'Hold Lot BOH/EOH Trend', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1109', 'Rework Lot BOH/EOH Trend', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1201', 'Factory In/Out', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' '
, ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1202', 'Operation Movement', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1203', 'Material Movement', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' '
, '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1204', 'Operation-Material Movement', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1205', 'Material-Operation Movement', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1206', 'Material Group Movement', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1208', 'Material Movement Trend', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1601', 'Material Yield', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' '
, '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1602', 'Operation Yield', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' '
, '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1604', 'Loss Code Analysis', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1605', 'Rework Code Analysis', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1606', 'Hold Code Analysis', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1901', 'View Lot Status', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' '
, '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1902', 'View Lot History', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' '
, ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1903', 'View Resource Status', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1904', 'View Resource History', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1207', 'Operation Movement Trend', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1210', 'Multi Operation Movement Trend', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1401', 'Daily Production Report', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1404', 'Down Time Report', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' '
, ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1111', 'Material WIP Status (Lot List)', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', '  '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1302', 'Order Status Report', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1403', 'Resource Productivity', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1501', 'Resource-Operation Movement', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000'
, ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1607', 'Cycle Time', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' ', ' '); 
INSERT INTO RWEBFUNDEF ( FUNC_NAME, FUNC_DESC, FUNC_TYPE_FLAG, FUNC_FLEX_TYPE, FUNC_URL, HELP_URL,
CREATE_USER_ID, CREATE_TIME, UPDATE_USER_ID, UPDATE_TIME ) VALUES ( 
'STD1608', 'Lot Yield', ' ', ' ', ' ', ' ', 'WEBADMIN', '20080202000000', ' ', ' '); 
 
