-- 전일, 금일, 당월 실적
SELECT NVL(B.PRE_PLAN_QTY,0) PRE_PLAN_QTY,                                           -- 전일 계획
       NVL(A.PRE_PROD_QTY,0) PRE_PROD_QTY,                                           -- 전일 실적
       NVL(ROUND(A.PRE_PROD_QTY / B.PRE_PLAN_QTY * 100, 1),0) PRE_RATE, -- 전일 달성률
       NVL(B.TOD_PLAN_QTY,0) TOD_PLAN_QTY,                                           -- 금일 계획
       NVL(A.TOD_PROD_QTY,0) TOD_PROD_QTY,                                           -- 금일 실적
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100, 1),0) TOD_RATE, -- 금일 달성률
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100),0) MON_RATE -- 당월 달성률
  FROM (
        -- 생산량
        SELECT SUM(PROD_QTY) MONTH_PROD_QTY,
               SUM(TO_NUMBER(DECODE(WORK_DATE , F_GET_PRE_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(PROD_QTY), '0'))) PRE_PROD_QTY,
               SUM(TO_NUMBER(DECODE(WORK_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(PROD_QTY), '0'))) TOD_PROD_QTY
          FROM CSUMWIPOPR
         WHERE FACTORY = 'IJDK1'
           AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND AREA_ID = 'CTM'        
           AND OPER IN ('OC05060', 'OC05070', 'OC06020')
           -- 최종 검사, W/D급검사, 절단품 검사
       ) A,
       (
        -- 계획량
        SELECT SUM(QTY) MONTH_PLAN_QTY,        -- 당월 계획량
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_PRE_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) PRE_PLAN_QTY,
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'CTM'
		   AND OPER IN ('OC05060', 'OC05070', 'OC06020')
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
       ) B
;

-- 최근 7일간 누적계획 및 누적실적
SELECT TO_CHAR(TO_DATE(A.WORK_DATE),'MM-DD') AS WORK_DATE, 
        NVL(B.PROD_QTY,0) PROD_QTY, 
        NVL(C.PLAN_QTY,0) PRAN_QTY,
		CASE WHEN MAX(NVL(C.PLAN_QTY,0)) OVER() > MAX(NVL(B.PROD_QTY,0)) OVER() THEN ROUND(MAX(NVL(C.PLAN_QTY,0)) OVER(),0) 
			 WHEN MAX(NVL(B.PROD_QTY,0)) OVER() > MAX(NVL(C.PLAN_QTY,0)) OVER() THEN ROUND(MAX(NVL(B.PROD_QTY,0)) OVER(),0)
			 END
		AS MAX_VAL
  FROM (
        SELECT /*+ INDEX_DESC(A MWIPCALDEF_PK) */ SYS_DATE WORK_DATE
          FROM MWIPCALDEF A
         WHERE CALENDAR_ID = 'IJDK1'
           AND SYS_YEAR = TO_NUMBER(SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 4))
           AND HOLIDAY_FLAG = ' '
           AND SYS_DATE <= F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
        FETCH FIRST 7 ROW ONLY
       ) A,
       (
        SELECT WORK_DATE,
               SUM(PROD_QTY) OVER (ORDER BY WORK_DATE) PROD_QTY
          FROM (
                SELECT WORK_DATE,
                       SUM(PROD_QTY) PROD_QTY
                  FROM CSUMWIPOPR
                 WHERE FACTORY = 'IJDK1'
                   AND WORK_DATE BETWEEN TO_CHAR(TO_DATE(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 'YYYYMMDD') - 6, 'YYYYMMDD') AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
                   AND AREA_ID = 'CTM'                   
                   AND OPER IN ('OC05060', 'OC05070', 'OC06020')
                 GROUP BY WORK_DATE
               )
       ) B,
       (
        SELECT PLAN_DATE,
               SUM(PLAN_QTY) OVER (ORDER BY PLAN_DATE) PLAN_QTY
          FROM (
                SELECT PLAN_DATE, SUM(QTY) PLAN_QTY
                  FROM CORDPRDPLN
                 WHERE FACTORY = 'IJDK1'
                   AND AREA_ID = 'CTM'
				   AND OPER IN ('OC05060', 'OC05070', 'OC06020')
                   AND PLAN_DATE BETWEEN TO_CHAR(TO_DATE(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 'YYYYMMDD') - 6, 'YYYYMMDD') AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
                 GROUP BY PLAN_DATE
               )
       ) C
 WHERE A.WORK_DATE = B.WORK_DATE(+)
   AND A.WORK_DATE = C.PLAN_DATE(+)
 ORDER BY A.WORK_DATE
