-- 장비 현황
SELECT RES_TYPE, RES_TYPE_DESC, TOTAL_RES, IDLE, RUN, STOP, ROUND(RUN/ TOTAL_RES * 100, 1) RUN_RATE
  FROM (
        SELECT A.RES_GRP_2 RES_TYPE, B.DATA_1 RES_TYPE_DESC,
               COUNT(*) TOTAL_RES,
               SUM(DECODE(A.RES_PRI_STS, 'I', 1, 0)) IDLE,
               SUM(DECODE(A.RES_PRI_STS, 'R', 1, 0)) RUN,
               SUM(DECODE(A.RES_PRI_STS, 'D', 1, 0)) STOP
          FROM MRASRESDEF A, MGCMTBLDAT B
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.FACTORY = B.FACTORY
           AND B.TABLE_NAME = 'RES_GRP_2'
           AND B.KEY_1 = A.RES_GRP_2
         GROUP BY A.RES_GRP_2, B.DATA_1
       )
;

-- 생산현황
-- 전처리
SELECT NVL(A.MONTH_PROD_QTY,0) MONTH_PROD_QTY,                                          -- 당월실적
       NVL(B.MONTH_PLAN_QTY,0) MONTH_PLAN_QTY,                                          -- 당월계획
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100),0) MONTH_RATE,				-- 당월달성률
       NVL(A.TOD_PROD_QTY,0) TOD_PROD_QTY,                                              -- 당일실적
       NVL(B.TOD_PLAN_QTY,0) TOD_PLAN_QTY,												-- 당일계획
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100),0) TODAY_RATE,					-- 당일달성률
       NVL(C.WIP_QTY,0) WIP_QTY															-- 재공
	    ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
             WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
             ELSE MONTH_PLAN_QTY END
        AS MAX_VAL_M
       ,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
             WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
             ELSE TOD_PLAN_QTY END
        AS MAX_VAL_T
  FROM (
        -- 임팩트 Move량 
        SELECT SUM(PROD_QTY) MONTH_PROD_QTY,
               SUM(DECODE(WORK_DATE, F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), PROD_QTY, 0)) TOD_PROD_QTY -- 당일 실적
          FROM CSUMWIPOPR
         WHERE FACTORY = 'IJDK1'
           AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND AREA_ID = 'CTM'		 
           AND OPER IN ('OC03060')
       ) A,
       (
        -- 생산 계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,        
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY -- 당일 계획량
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'CTM'
		   AND OPER IN ('OC03060')
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
       ) B,
       (
        -- 재공
        SELECT SUM(QTY_1) WIP_QTY
          FROM MWIPLOTSTS
         WHERE OPER IN (
                        SELECT DISTINCT B.OPER
                          FROM MWIPFLWDEF A, MWIPFLWOPR B, MWIPOPRDEF C
                         WHERE B.FACTORY = 'IJDK1'
                           AND B.FLOW = A.FLOW
                           AND B.OPER = C.OPER
                           AND A.FLOW IN ('FC310', 'FC320', 'FC330', 'FC340', 'FC350')
                       )
           AND LOT_DEL_FLAG = ' '
       ) C
;

-- 생산 현황
-- Press
SELECT NVL(A.MONTH_PROD_QTY,0) MONTH_PROD_QTY,                                          -- 당월실적
       NVL(B.MONTH_PLAN_QTY,0) MONTH_PLAN_QTY,                                          -- 당월계획
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100),0) MONTH_RATE,				-- 당월달성률
       NVL(A.TOD_PROD_QTY,0) TOD_PROD_QTY,                                              -- 당일실적
       NVL(B.TOD_PLAN_QTY,0) TOD_PLAN_QTY,												-- 당일계획
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100),0) TODAY_RATE,					-- 당일달성률
       NVL(C.WIP_QTY,0) WIP_QTY															-- 재공
	    ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
             WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
             ELSE MONTH_PLAN_QTY END
        AS MAX_VAL_M
       ,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
             WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
             ELSE TOD_PLAN_QTY END
        AS MAX_VAL_T
  FROM (
        -- 프레스 Move량
        SELECT SUM(PROD_QTY) MONTH_PROD_QTY,  -- 당월 실적
               SUM(DECODE(WORK_DATE, F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), PROD_QTY, 0)) TOD_PROD_QTY -- 당일 실적
          FROM CSUMWIPOPR
         WHERE FACTORY = 'IJDK1'
           AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND AREA_ID = 'CTM'		 
           AND OPER IN ('OC03160')
       ) A,
       (
        -- 생산 계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,        -- 당월 계획량
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY -- 당일 계획량
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'CTM'
		    AND OPER IN ('OC03160')
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
       ) B,
       (
        -- 재공
        SELECT SUM(QTY_1) WIP_QTY
          FROM MWIPLOTSTS
         WHERE OPER = 'OC03160'
           AND LOT_DEL_FLAG = ' '
       ) C
;

-- 생산현황
-- Lapping
SELECT A.MONTH_PROD_QTY,                                            -- 당월실적
       B.MONTH_PLAN_QTY,                                            -- 당월계획
       ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100) MONTH_RATE, -- 당월달성률
       A.TOD_PROD_QTY,                                              -- 당일실적
       B.TOD_PLAN_QTY,                                              -- 당일계획
       ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100) TODAY_RATE,     -- 당일달성률
       C.WIP_QTY                                                    -- 재공
	    ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
             WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
             ELSE MONTH_PLAN_QTY END
        AS MAX_VAL_M
       ,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
             WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
             ELSE TOD_PLAN_QTY END
        AS MAX_VAL_T
  FROM (
        -- 3차래핑 공정 실적량
        SELECT SUM(PROD_QTY) MONTH_PROD_QTY,
               SUM(DECODE(WORK_DATE, F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), PROD_QTY, 0)) TOD_PROD_QTY -- 당일 실적
          FROM CSUMWIPOPR
         WHERE FACTORY = 'IJDK1'
           AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND AREA_ID = 'CTM'		  
           AND OPER IN ('OC04070')
       ) A,
       (
        -- 생산 계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,       
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY -- 당일 계획량
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'CTM'
		   AND OPER IN ('OC04070')
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
       ) B,
       (
        -- 재공
        SELECT SUM(QTY_1) WIP_QTY
          FROM MWIPLOTSTS
         WHERE OPER IN (
                        SELECT DISTINCT B.OPER
                          FROM MWIPFLWDEF A, MWIPFLWOPR B, MWIPOPRDEF C
                         WHERE B.FACTORY = 'IJDK1'
                           AND B.FLOW = A.FLOW
                           AND B.OPER = C.OPER
                           AND A.FLOW IN ('FC410', 'FC420', 'FC421', 'FC430', 'FC440', 'FC450', 'FC460', 'FC470')
                           AND B.OPER NOT IN ('OC04090', 'OC04100', 'OC04120')
                           AND C.INV_FLAG = ' '
                       )
           AND LOT_DEL_FLAG = ' '
       ) C
;

-- 생산현황
-- Polishing
SELECT NVL(A.MONTH_PROD_QTY,0) MONTH_PROD_QTY,                                          -- 당월실적
       NVL(B.MONTH_PLAN_QTY,0) MONTH_PLAN_QTY,                                          -- 당월계획
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100),0) MONTH_RATE,				-- 당월달성률
       NVL(A.TOD_PROD_QTY,0) TOD_PROD_QTY,                                              -- 당일실적
       NVL(B.TOD_PLAN_QTY,0) TOD_PLAN_QTY,												-- 당일계획
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100),0) TODAY_RATE,					-- 당일달성률
       NVL(C.WIP_QTY,0) WIP_QTY															-- 재공
	    ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
             WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
             ELSE MONTH_PLAN_QTY END
        AS MAX_VAL_M
       ,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
             WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
             ELSE TOD_PLAN_QTY END
        AS MAX_VAL_T
  FROM (
        -- 폴리싱-정삭 공정 실적량
        SELECT SUM(PROD_QTY) MONTH_PROD_QTY,  -- 당월 실적
               SUM(DECODE(WORK_DATE, F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), PROD_QTY, 0)) TOD_PROD_QTY -- 당일 실적
          FROM CSUMWIPOPR
         WHERE FACTORY = 'IJDK1'
           AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND AREA_ID = 'CTM'		 
           AND OPER IN ('OC04100')
       ) A,
       (
        -- 생산 계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,        -- 당월 계획량
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY -- 당일 계획량
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'CTM'
		   AND OPER IN ('OC04100')
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
       ) B,
       (
        -- 재공
        SELECT SUM(QTY_1) WIP_QTY
          FROM MWIPLOTSTS
         WHERE OPER IN (
                        SELECT DISTINCT B.OPER
                          FROM MWIPFLWDEF A, MWIPFLWOPR B, MWIPOPRDEF C
                         WHERE B.FACTORY = 'IJDK1'
                           AND B.FLOW = A.FLOW
                           AND B.OPER = C.OPER
                           AND A.FLOW IN ('FC410', 'FC420', 'FC421')
                           AND B.OPER IN ('OC04090', 'OC04100', 'OC04120')
                           AND C.INV_FLAG = ' '
                       )
           AND LOT_DEL_FLAG = ' '
       ) C
;

-- 생산현황
-- 두께가공
SELECT NVL(A.MONTH_PROD_QTY,0) MONTH_PROD_QTY,                                          -- 당월실적
       NVL(B.MONTH_PLAN_QTY,0) MONTH_PLAN_QTY,                                          -- 당월계획
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100),0) MONTH_RATE,				-- 당월달성률
       NVL(A.TOD_PROD_QTY,0) TOD_PROD_QTY,                                              -- 당일실적
       NVL(B.TOD_PLAN_QTY,0) TOD_PLAN_QTY,												-- 당일계획
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100),0) TODAY_RATE,					-- 당일달성률
       NVL(C.WIP_QTY,0) WIP_QTY															-- 재공
	    ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
             WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
             ELSE MONTH_PLAN_QTY END
        AS MAX_VAL_M
       ,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
             WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
             ELSE TOD_PLAN_QTY END
        AS MAX_VAL_T
  FROM (
        -- 정삭 실적 공정 실적량
        SELECT SUM(PROD_QTY) MONTH_PROD_QTY, 
               SUM(DECODE(WORK_DATE, F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), PROD_QTY, 0)) TOD_PROD_QTY -- 당일 실적
          FROM CSUMWIPOPR
         WHERE FACTORY = 'IJDK1'
           AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND AREA_ID = 'CTM'		   
           AND OPER IN ('OC05030')
       ) A,
       (
        -- 생산 계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,       
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY -- 당일 계획량
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'CTM'
		   AND OPER IN ('OC05030')
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
       ) B,
       (
        -- 재공
        SELECT SUM(QTY_1) WIP_QTY
          FROM MWIPLOTSTS
         WHERE OPER IN (
                        SELECT DISTINCT OPER
                          FROM MWIPFLWOPR
                         WHERE FACTORY = 'IJDK1'
                           AND FLOW IN ('FC510','FC520','FC530','FC540','FC550')
                       )
           AND LOT_DEL_FLAG = ' '
       ) C
;

-- 생산성
-- 전처리
WITH CAL AS (
			SELECT PLAN_WEEK, CAL_CMF_1  WEEK_OF_MONTH
			  FROM MWIPCALDEF
			 WHERE CALENDAR_ID = 'IJDK1'
			   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
)
SELECT NVL(GOAL_YEAR,0) GOAL_M,																        -- 월계획
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2),0) MONTH_PROD_RESULT,								-- 월실적
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) / GOAL_YEAR,0) MONTH_PROD_RATE,						-- 월달성률
       NVL(GOAL_WEEK,0) GOAL_W,																		-- 주계획
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2),0) WEEK_PROD_RESULT,						-- 주실적
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) / GOAL_WEEK,0)  WEEK_PROD_RATE					-- 주달성률
	   ,CASE WHEN GOAL_YEAR > ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN GOAL_YEAR
	         WHEN GOAL_YEAR < ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2)
			 ELSE GOAL_YEAR END
		AS MAX_VAL_MON
	   ,CASE WHEN GOAL_WEEK > ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN GOAL_WEEK
	         WHEN GOAL_WEEK < ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2)
			 ELSE GOAL_WEEK END
		AS MAX_VAL_WEEK	
  FROM (
        -- 전처리 생산 실적
        -- (임팩트 Move량 + CELL조립 Move량)
        SELECT SUM(PROD_QTY) PROD_QTY,
               SUM(CASE WHEN A.WEEK_OF_YEAR = B.PLAN_WEEK THEN A.PROD_QTY END) PROD_QTY_W
          FROM CSUMWIPOPR A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND A.AREA_ID = 'CTM'		   
           AND A.OPER IN ('OC03060', 'OC03150')
       ) A,
       (
        -- 전처리 투입 공수
        SELECT SUM(A.TOTAL_WORK_TIME) TOTAL_WORK_TIME,
               SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN A.TOTAL_WORK_TIME END) TOTAL_WORK_TIME_W
          FROM CWIPWRKINP A, MWIPCALDEF B, CAL C
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.OPER IN ('CP002', 'CP003')  -- 컵조립, 셀조립
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND A.FACTORY = B.CALENDAR_ID
		   AND A.WORK_DATE = B.SYS_DATE
       ) B,
       (
        -- 전처리 목표 생산성
        SELECT MAX(CASE WHEN A.CLASS = 'MONTH' AND A.WEEK_OF_MONTH = '1' THEN A.GOAL_PRODUCTVITY END) GOAL_YEAR,
               MAX(CASE WHEN A.CLASS = 'WEEK' AND A.WEEK_OF_MONTH = B.WEEK_OF_MONTH THEN A.GOAL_PRODUCTVITY END) GOAL_WEEK
          FROM CWIPPRDGOL A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.SHOP = 'CL001'      -- 전처리
           AND A.OPER_GRP = 'CP003'  -- 셀조립
           AND A.WORK_MONTH = SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 6)
       ) C
;

-- 생산성
-- Press
WITH CAL AS (
			SELECT PLAN_WEEK, CAL_CMF_1  WEEK_OF_MONTH
			  FROM MWIPCALDEF
			 WHERE CALENDAR_ID = 'IJDK1'
			   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
)
SELECT NVL(GOAL_YEAR,0) GOAL_M,																        -- 월계획
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2),0) MONTH_PROD_RESULT,								-- 월실적
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) / GOAL_YEAR,0) MONTH_PROD_RATE,						-- 월달성률
       NVL(GOAL_WEEK,0) GOAL_W,																		-- 주계획
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2),0) WEEK_PROD_RESULT,						-- 주실적
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) / GOAL_WEEK,0)  WEEK_PROD_RATE					-- 주달성률
	   ,CASE WHEN GOAL_YEAR > ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN GOAL_YEAR
	         WHEN GOAL_YEAR < ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2)
			 ELSE GOAL_YEAR END
		AS MAX_VAL_MON
	   ,CASE WHEN GOAL_WEEK > ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN GOAL_WEEK
	         WHEN GOAL_WEEK < ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2)
			 ELSE GOAL_WEEK END
		AS MAX_VAL_WEEK	
  FROM (
        -- 프레스 생산 실적
        -- 프레스
        SELECT SUM(PROD_QTY) PROD_QTY,
               SUM(CASE WHEN A.WEEK_OF_YEAR = B.PLAN_WEEK THEN A.PROD_QTY END) PROD_QTY_W
          FROM CSUMWIPOPR A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND A.AREA_ID = 'CTM'		     
           AND A.OPER IN ('OC03160')
       ) A,
       (
        --  프레스 투입 공수
        SELECT SUM(A.TOTAL_WORK_TIME) TOTAL_WORK_TIME,
               SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN A.TOTAL_WORK_TIME END) TOTAL_WORK_TIME_W
          FROM CWIPWRKINP A, MWIPCALDEF B, CAL C
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.OPER IN ('CP004')  -- 프레스
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND A.FACTORY = B.CALENDAR_ID
		   AND A.WORK_DATE = B.SYS_DATE
       ) B,
       (
        -- 전처리 목표 생산성
        SELECT MAX(CASE WHEN A.CLASS = 'MONTH' AND A.WEEK_OF_MONTH = '1' THEN A.GOAL_PRODUCTVITY END) GOAL_YEAR,
               MAX(CASE WHEN A.CLASS = 'WEEK' AND A.WEEK_OF_MONTH = B.WEEK_OF_MONTH THEN A.GOAL_PRODUCTVITY END) GOAL_WEEK
          FROM CWIPPRDGOL A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.SHOP = 'CL002'      -- 소결
           AND A.OPER_GRP = 'CP004'  -- 프레스
           AND A.WORK_MONTH = SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 6)
       ) C
;

-- 생산성
-- Lapping
WITH CAL AS (
			SELECT PLAN_WEEK, CAL_CMF_1  WEEK_OF_MONTH
			  FROM MWIPCALDEF
			 WHERE CALENDAR_ID = 'IJDK1'
			   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
)
SELECT NVL(GOAL_YEAR,0) GOAL_M,																        -- 월계획
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2),0) MONTH_PROD_RESULT,								-- 월실적
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) / GOAL_YEAR,0) MONTH_PROD_RATE,						-- 월달성률
       NVL(GOAL_WEEK,0) GOAL_W,																		-- 주계획
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2),0) WEEK_PROD_RESULT,						-- 주실적
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) / GOAL_WEEK,0)  WEEK_PROD_RATE					-- 주달성률
	   ,CASE WHEN GOAL_YEAR > ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN GOAL_YEAR
	         WHEN GOAL_YEAR < ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2)
			 ELSE GOAL_YEAR END
		AS MAX_VAL_MON
	   ,CASE WHEN GOAL_WEEK > ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN GOAL_WEEK
	         WHEN GOAL_WEEK < ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2)
			 ELSE GOAL_WEEK END
		AS MAX_VAL_WEEK	
  FROM (
        -- 1차래핑 Move량 + 2차래핑 Move량 + 3차래핑 Move량
        SELECT SUM(PROD_QTY) PROD_QTY,
               SUM(CASE WHEN A.WEEK_OF_YEAR = B.PLAN_WEEK THEN A.PROD_QTY END) PROD_QTY_W
          FROM CSUMWIPOPR A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND A.AREA_ID = 'CTM'		  
           AND A.OPER IN ('OC04030', 'OC04060', 'OC04070')
       ) A,
       (
        --  Lapping (PCD), Lapping (PCBN) 투입공수
        SELECT SUM(A.TOTAL_WORK_TIME) TOTAL_WORK_TIME,
               SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN A.TOTAL_WORK_TIME END) TOTAL_WORK_TIME_W
          FROM CWIPWRKINP A, MWIPCALDEF B, CAL C
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.OPER IN ('CP006', 'CP007')
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND A.FACTORY = B.CALENDAR_ID
		   AND A.WORK_DATE = B.SYS_DATE
       ) B,
       (
        --  목표 생산성
        SELECT MAX(CASE WHEN A.CLASS = 'MONTH' AND A.WEEK_OF_MONTH = '1' THEN A.GOAL_PRODUCTVITY END) GOAL_YEAR,
               MAX(CASE WHEN A.CLASS = 'WEEK' AND A.WEEK_OF_MONTH = B.WEEK_OF_MONTH THEN A.GOAL_PRODUCTVITY END) GOAL_WEEK
          FROM CWIPPRDGOL A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.SHOP = 'CL003'      -- 가공
           AND A.OPER_GRP IN ('CP006', 'CP007')  -- Lapping (PCD), Lapping (PCBN)
           AND A.WORK_MONTH = SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 6)
       ) C
;

-- 생산성
-- Polishing
WITH CAL AS (
			SELECT PLAN_WEEK, CAL_CMF_1  WEEK_OF_MONTH
			  FROM MWIPCALDEF
			 WHERE CALENDAR_ID = 'IJDK1'
			   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
)
SELECT NVL(GOAL_YEAR,0) GOAL_M,																        -- 월계획
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2),0) MONTH_PROD_RESULT,								-- 월실적
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) / GOAL_YEAR,0) MONTH_PROD_RATE,						-- 월달성률
       NVL(GOAL_WEEK,0) GOAL_W,																		-- 주계획
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2),0) WEEK_PROD_RESULT,						-- 주실적
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) / GOAL_WEEK,0)  WEEK_PROD_RATE					-- 주달성률
	   ,CASE WHEN GOAL_YEAR > ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN GOAL_YEAR
	         WHEN GOAL_YEAR < ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2)
			 ELSE GOAL_YEAR END
		AS MAX_VAL_MON
	   ,CASE WHEN GOAL_WEEK > ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN GOAL_WEEK
	         WHEN GOAL_WEEK < ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2)
			 ELSE GOAL_WEEK END
		AS MAX_VAL_WEEK	
  FROM (
        -- 폴리싱-정삭
        SELECT SUM(PROD_QTY) PROD_QTY,
               SUM(CASE WHEN A.WEEK_OF_YEAR = B.PLAN_WEEK THEN A.PROD_QTY END) PROD_QTY_W
          FROM CSUMWIPOPR A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND A.AREA_ID = 'CTM'		 
           AND A.OPER IN ('OC04100')
       ) A,
       (
        --  Polishing 투입공수
        SELECT SUM(A.TOTAL_WORK_TIME) TOTAL_WORK_TIME,
               SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN A.TOTAL_WORK_TIME END) TOTAL_WORK_TIME_W
          FROM CWIPWRKINP A, MWIPCALDEF B, CAL C
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.OPER IN ('CP009')
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND A.FACTORY = B.CALENDAR_ID
		   AND A.WORK_DATE = B.SYS_DATE
       ) B,
       (
        -- 전처리 목표 생산성
        SELECT MAX(CASE WHEN A.CLASS = 'MONTH' AND A.WEEK_OF_MONTH = '1' THEN A.GOAL_PRODUCTVITY END) GOAL_YEAR,
               MAX(CASE WHEN A.CLASS = 'WEEK' AND A.WEEK_OF_MONTH = B.WEEK_OF_MONTH THEN A.GOAL_PRODUCTVITY END) GOAL_WEEK
          FROM CWIPPRDGOL A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.SHOP = 'CL003'      -- 가공
           AND A.OPER_GRP IN ('CP009')  -- Polishing
           AND A.WORK_MONTH = SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 6)
       ) C
;

-- 생산성
-- 두께가공
WITH CAL AS (
			SELECT PLAN_WEEK, CAL_CMF_1  WEEK_OF_MONTH
			  FROM MWIPCALDEF
			 WHERE CALENDAR_ID = 'IJDK1'
			   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
)
SELECT NVL(GOAL_YEAR,0) GOAL_M,																        -- 월계획
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2),0) MONTH_PROD_RESULT,								-- 월실적
       NVL(ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) / GOAL_YEAR,0) MONTH_PROD_RATE,						-- 월달성률
       NVL(GOAL_WEEK,0) GOAL_W,																		-- 주계획
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2),0) WEEK_PROD_RESULT,						-- 주실적
       NVL(ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) / GOAL_WEEK,0)  WEEK_PROD_RATE					-- 주달성률
	   ,CASE WHEN GOAL_YEAR > ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN GOAL_YEAR
	         WHEN GOAL_YEAR < ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2) THEN ROUND(A.PROD_QTY / B.TOTAL_WORK_TIME * 100, 2)
			 ELSE GOAL_YEAR END
		AS MAX_VAL_MON
	   ,CASE WHEN GOAL_WEEK > ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN GOAL_WEEK
	         WHEN GOAL_WEEK < ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2) THEN ROUND(A.PROD_QTY_W / B.TOTAL_WORK_TIME_W * 100, 2)
			 ELSE GOAL_WEEK END
		AS MAX_VAL_WEEK	
  FROM (
        -- 황삭, 열처리, 정삭 실적
        SELECT SUM(PROD_QTY) PROD_QTY,
               SUM(CASE WHEN A.WEEK_OF_YEAR = B.PLAN_WEEK THEN A.PROD_QTY END) PROD_QTY_W
          FROM CSUMWIPOPR A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND A.AREA_ID = 'CTM'		 
           AND A.OPER IN ('OC05010', 'OC05020', 'OC05030')
       ) A,
       (
        --  두께 투입공수
        SELECT SUM(A.TOTAL_WORK_TIME) TOTAL_WORK_TIME,
               SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN A.TOTAL_WORK_TIME END) TOTAL_WORK_TIME_W
          FROM CWIPWRKINP A, MWIPCALDEF B, CAL C
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.OPER IN ('CP011')
           AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND A.FACTORY = B.CALENDAR_ID
		   AND A.WORK_DATE = B.SYS_DATE
       ) B,
       (
        -- 전처리 목표 생산성
        SELECT MAX(CASE WHEN A.CLASS = 'MONTH' AND A.WEEK_OF_MONTH = '1' THEN A.GOAL_PRODUCTVITY END) GOAL_YEAR,
               MAX(CASE WHEN A.CLASS = 'WEEK' AND A.WEEK_OF_MONTH = B.WEEK_OF_MONTH THEN A.GOAL_PRODUCTVITY END) GOAL_WEEK
          FROM CWIPPRDGOL A, CAL B
         WHERE A.FACTORY = 'IJDK1'
           AND A.AREA_ID = 'CTM'
           AND A.SHOP = 'CL003'      -- 가공
           AND A.OPER_GRP IN ('CP011')  -- 두께
           AND A.WORK_MONTH = SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 6)
       ) C
;

