
/*공정현황_장비현황(전체)*/
SELECT AREA_ID,
       RES_GRP_2 AS OPER_ID,
       RES_GRP_2_DESC AS OPER_DESC,
       STOP_CNT,
       WAIT_CNT,
       RUN_CNT,  
       RES_TOT_CNT, --총수량
       (CASE WHEN RES_TOT_CNT>0 THEN ROUND(RUN_CNT / RES_TOT_CNT *100,1) END)AS RUN_RATE  --가동현황
FROM (
    SELECT  RES.AREA_ID, RES.RES_GRP_2, GRP.DATA_1 AS RES_GRP_2_DESC,  
            COUNT(RES_ID) AS RES_TOT_CNT,
            SUM(CASE WHEN RES_PRI_STS='D' THEN 1 ELSE 0 END) AS STOP_CNT ,   --정지
            SUM(CASE WHEN RES_PRI_STS IN ('I','WAIT') THEN 1 ELSE 0 END) AS WAIT_CNT ,   --대기
            SUM(CASE WHEN RES_PRI_STS='R' THEN 1 ELSE 0 END) AS RUN_CNT     --가동
    FROM MRASRESDEF RES,
         MGCMTBLDAT GRP       
    WHERE RES.FACTORY=GRP.FACTORY(+)
         AND TABLE_NAME(+)='RES_GRP_2' 
         AND RES.RES_GRP_2=GRP.KEY_1(+) 
         AND RES.FACTORY='IJDK1'
        -- AND RES.AREA_ID='GRT'      --AREA:GRT,CTM,HM,PDC
         --AND RES.RES_GRP_2='F008' -- F014:합성, F015:후처리, F009:분류/준비, F007:Ti-Coating, F001:CP
         AND RES.RES_GRP_2 != ' '  AND RES.RES_GRP_2 IS NOT NULL AND RES.RES_GRP_2 <> '*'
    GROUP BY RES.AREA_ID, RES.RES_GRP_2, GRP.DATA_1 
	)
;

/*공정현황_생산현황_합성*/
SELECT 
       ROUND(NVL(MONTH_PLAN_QTY,0)/1000,0) MONTH_PLAN_QTY,										
       ROUND(NVL(A.MONTH_PROD_QTY,0)/1000,0) MONTH_PROD_QTY,		
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100, 2),0) MONTH_RATE,					
       ROUND(NVL(TOD_PLAN_QTY,0)/1000,0) TOD_PLAN_QTY,											
       ROUND(NVL(TOD_PROD_QTY,0)/1000,0) TOD_PROD_QTY,
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100, 2),0) TOD_RATE,				
       ROUND(NVL(WIP_QTY,0)/1000,0) WIP_QTY                				
	   ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
             WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
             ELSE MONTH_PLAN_QTY END
        AS MAX_VAL_M
       ,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
             WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
             ELSE TOD_PLAN_QTY END
        AS MAX_VAL_T
  FROM 
       (
	     --생산실적 : (합성(L) 실적량 + 500) ÷798 × 400
        SELECT 
               ((MONTH_PROD_QTY + 500) / 798 * 400) AS MONTH_PROD_QTY,
               ((TOD_PROD_QTY + 500) / 798 * 400) AS TOD_PROD_QTY
        FROM (
           
            SELECT                 
                SUM(PROD_QTY) MONTH_PROD_QTY,
                SUM(TO_NUMBER(DECODE(WORK_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(PROD_QTY), '0'))) TOD_PROD_QTY --당일 실적
              FROM CSUMWIPOPR                            
             WHERE FACTORY = 'IJDK1'
               AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               AND AREA_ID = 'GRT'              
               AND OPER IN ('OG03010')
             )                
        ) A,
       (
        -- 생산계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,                    
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'GRT'
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND OPER IN ('OG03010')--합성(L)
       ) B,
       (
        -- 공정 재공
      SELECT SUM(QTY_1) WIP_QTY
          FROM MWIPLOTSTS
         WHERE OPER  IN ('OG03010')
           AND LOT_DEL_FLAG = ' '
       ) C
 ;
 
/*공정현황_생산현황_후처리*/
SELECT 
       ROUND(NVL(MONTH_PLAN_QTY,0)/1000,0) MONTH_PLAN_QTY,                                        
       ROUND(NVL(A.MONTH_PROD_QTY,0)/1000,0) MONTH_PROD_QTY,        
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100, 2),0) MONTH_RATE,					
       ROUND(NVL(TOD_PLAN_QTY,0)/1000,0) TOD_PLAN_QTY,											
       ROUND(NVL(TOD_PROD_QTY,0)/1000,0) TOD_PROD_QTY,
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100, 2),0) TOD_RATE,		            
       ROUND(NVL(WIP_QTY,0)/1000,0) WIP_QTY                                                    
       ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
             WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
             ELSE MONTH_PLAN_QTY END
        AS MAX_VAL_M
       ,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
             WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
             ELSE TOD_PLAN_QTY END
        AS MAX_VAL_T
  FROM 
       (        
        --생산실적:건조 실적량 + Dia-건조 실적량 + cBN-건조 실적량 + MP-건조 실적량 + 표면개진-2차 산처리 실적량 
        SELECT                 
            SUM(PROD_QTY) MONTH_PROD_QTY,  --당월 실적
            SUM(TO_NUMBER(DECODE(WORK_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(PROD_QTY), '0'))) TOD_PROD_QTY --당일 실적
          FROM CSUMWIPOPR                            
         WHERE FACTORY = 'IJDK1'
           AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND AREA_ID = 'GRT'          
           AND OPER IN ('OG04050','OG06060','OG06330','OG06440','OG07470')
                          
        ) A,
       (
        -- 생산계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,                 
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'GRT'
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
           AND OPER IN ('OG04050','OG06060','OG06330','OG06440','OG07470')
       ) B,
       (
        -- 공정 전체 재공 재고 합계
        SELECT SUM(QTY_1) AS WIP_QTY
          FROM MWIPLOTSTS
         WHERE FACTORY = 'IJDK1'
           AND FLOW = 'FG410' -- (GRIT-후처리)
           AND LOT_DEL_FLAG<>'Y'
       ) C
 ;
 
/*공정현황_생산현황_분류/준비*/
SELECT 
      ROUND(NVL(MONTH_PLAN_QTY,0)/1000,0) MONTH_PLAN_QTY,                                        
       ROUND(NVL(A.MONTH_PROD_QTY,0)/1000,0) MONTH_PROD_QTY,        
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100, 2),0) MONTH_RATE,					
       ROUND(NVL(TOD_PLAN_QTY,0)/1000,0) TOD_PLAN_QTY,											
       ROUND(NVL(TOD_PROD_QTY,0)/1000,0) TOD_PROD_QTY,
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100, 2),0) TOD_RATE,		            
       ROUND(NVL(WIP_QTY,0)/1000,0) WIP_QTY                                                    
       ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
             WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
             ELSE MONTH_PLAN_QTY END
        AS MAX_VAL_M
       ,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
             WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
             ELSE TOD_PLAN_QTY END
        AS MAX_VAL_T   									
  FROM 
       (        
		 /*분류/준비 생산 실적 :  제품검사 양품수량 + 제품검사-Coat 양품수량 + CP-제품검사 양품수량*/
		SELECT                 
			SUM(PROD_QTY) MONTH_PROD_QTY, 
			SUM(TO_NUMBER(DECODE(WORK_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(PROD_QTY), '0'))) TOD_PROD_QTY --당일 실적
		  FROM CSUMWIPOPR                            
		 WHERE FACTORY = 'IJDK1'
		   AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND AREA_ID = 'GRT'		 
		   AND OPER IN ('OG09010', 'OG09020', 'OG09030')
                          
        ) A,
       (
        -- 생산계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,                    
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'GRT'
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND OPER IN ('OG09010', 'OG09020', 'OG09030') 
       ) B,
       (
        -- 공정 전체 재공 재고 합계
        SELECT SUM(QTY_1) AS WIP_QTY
          FROM MWIPLOTSTS
         WHERE FACTORY = 'IJDK1'
           AND FLOW IN ('FG510','FG515','FG516','FG517','FG518','FG520','FG521','FG522','FG530','FG540','FG550','FG610')
           AND LOT_DEL_FLAG<>'Y'
       ) C
 ;
 
/*공정현황_생산현황_Ti Coating*/ 
SELECT 
      ROUND(NVL(MONTH_PLAN_QTY,0)/1000,0) MONTH_PLAN_QTY,										
       ROUND(NVL(A.MONTH_PROD_QTY,0)/1000,0) MONTH_PROD_QTY,		
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100, 1),0) MONTH_RATE,					
       ROUND(NVL(TOD_PLAN_QTY,0)/1000,0) TOD_PLAN_QTY,											
       ROUND(NVL(TOD_PROD_QTY,0)/1000,0) TOD_PROD_QTY,
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100, 1),0) TOD_RATE,				
       ROUND(NVL(WIP_QTY,0)/1000,0) WIP_QTY                				
	   ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
            WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
            ELSE MONTH_PLAN_QTY END
		AS MAX_VAL_M
		,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
				WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
				ELSE TOD_PLAN_QTY END
		AS MAX_VAL_T   
  FROM 
       (        
		--생산실적:제품검사-Coat 양품수량
		SELECT                 
			SUM(PROD_QTY) MONTH_PROD_QTY,  --당월 실적
			SUM(TO_NUMBER(DECODE(WORK_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(PROD_QTY), '0'))) TOD_PROD_QTY --당일 실적
		  FROM CSUMWIPOPR                            
		 WHERE FACTORY = 'IJDK1'
		   AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND AREA_ID = 'GRT'		  
		   AND OPER IN ('OG09030')
                          
        ) A,
       (
        -- 생산계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,                
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'GRT'
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND OPER IN ('OG09030')
       ) B,
       (
        -- 공정 전체 재공 재고 합계
        SELECT SUM(QTY_1) AS WIP_QTY
          FROM MWIPLOTSTS
         WHERE FACTORY = 'IJDK1'
           AND FLOW IN ('FG710','FG720','FG730','FG740')
           AND LOT_DEL_FLAG<>'Y'
       ) C
 ;
/*공정현황_생산현황_CP */ 
SELECT 
      ROUND(NVL(MONTH_PLAN_QTY,0)/1000,0) MONTH_PLAN_QTY,										
       ROUND(NVL(A.MONTH_PROD_QTY,0)/1000,0) MONTH_PROD_QTY,		
       NVL(ROUND(A.MONTH_PROD_QTY / B.MONTH_PLAN_QTY * 100, 1),0) MONTH_RATE,					
       ROUND(NVL(TOD_PLAN_QTY,0)/1000,0) TOD_PLAN_QTY,											
       ROUND(NVL(TOD_PROD_QTY,0)/1000,0) TOD_PROD_QTY,
       NVL(ROUND(A.TOD_PROD_QTY / B.TOD_PLAN_QTY * 100, 1),0) TOD_RATE,				
       ROUND(NVL(WIP_QTY,0)/1000,0) WIP_QTY                				
	   ,CASE WHEN MONTH_PLAN_QTY > MONTH_PROD_QTY THEN MONTH_PLAN_QTY
             WHEN MONTH_PLAN_QTY < MONTH_PROD_QTY THEN MONTH_PROD_QTY
             ELSE MONTH_PLAN_QTY END
        AS MAX_VAL_M
       ,CASE WHEN TOD_PLAN_QTY > TOD_PROD_QTY THEN TOD_PLAN_QTY
             WHEN TOD_PLAN_QTY < TOD_PROD_QTY THEN TOD_PROD_QTY
             ELSE TOD_PLAN_QTY END
        AS MAX_VAL_T
  FROM 
       (        
		--생산실적:CP-제품검사 양품수량
		SELECT                 
			SUM(PROD_QTY) MONTH_PROD_QTY, 
			SUM(TO_NUMBER(DECODE(WORK_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(PROD_QTY), '0'))) TOD_PROD_QTY --당일 실적
		  FROM CSUMWIPOPR                            
		 WHERE FACTORY = 'IJDK1'
		   AND WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND AREA_ID = 'GRT'		 
		   AND OPER IN ('OG09010')
                          
        ) A,
       (
        -- 생산계획
        SELECT SUM(QTY) MONTH_PLAN_QTY,                   
               SUM(TO_NUMBER(DECODE(PLAN_DATE , F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), TO_CHAR(QTY)))) TOD_PLAN_QTY
          FROM CORDPRDPLN
         WHERE FACTORY = 'IJDK1'
           AND AREA_ID = 'GRT'
           AND PLAN_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_LAST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
		   AND OPER IN ('OG09010')
       ) B,
       (
        -- 공정 전체 재공 재고 합계
        SELECT SUM(QTY_1) AS WIP_QTY
          FROM MWIPLOTSTS
         WHERE FACTORY = 'IJDK1'
           AND FLOW IN ('FG740')
           AND LOT_DEL_FLAG<>'Y'
       ) C
 ;
 
/*생산성_합성*/
SELECT ROUND(NVL(PROD_GOAL_PROD,0)/1000,2) GOAL_M,                                                    
       ROUND(NVL(WEEK_GOAL_PROD,0)/1000,2) GOAL_W,                                    
       NVL(ROUND((A.MOM_PROD_QTY/1000) / B.TOTAL_WORK_TIME, 2),0) AS MONTH_PROD_RESULT,                
       NVL(ROUND((A.MOM_PROD_QTY/1000) / B.TOTAL_WORK_TIME, 2) / (PROD_GOAL_PROD/1000),0) AS MONTH_PROD_RATE,  
       NVL(ROUND((A.WEEK_PROD_QTY/1000) / B.WEEK_WORK_TIME, 2),0) AS WEEK_PROD_RESULT,                 
       NVL(ROUND((A.WEEK_PROD_QTY/1000) / B.WEEK_WORK_TIME, 2) / (WEEK_GOAL_PROD/1000),0) AS WEEK_PROD_RATE   
	  ,CASE WHEN NVL(PROD_GOAL_PROD,0) > ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
			WHEN NVL(PROD_GOAL_PROD,0) < ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND((NVL(A.MOM_PROD_QTY,0)/1000) / B.TOTAL_WORK_TIME, 2)
			ELSE ROUND(NVL(PROD_GOAL_PROD,0)/1000,2) END
	   AS MAX_VAL_MON
	  ,CASE WHEN NVL(WEEK_GOAL_PROD,0) > ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
			WHEN NVL(WEEK_GOAL_PROD,0) < ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND((NVL(A.WEEK_PROD_QTY,0)/1000) / B.WEEK_WORK_TIME, 2)
			ELSE ROUND(NVL(WEEK_GOAL_PROD,0)/1000,2) END
	   AS MAX_VAL_WEEK     
  FROM (
        -- 합성 생산 실적 : 셀조립(D10) Move량 × 400
         SELECT (SUM(PROD_QTY) * 400) MOM_PROD_QTY,
				(SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN PROD_QTY END) * 400) WEEK_PROD_QTY -- 주간  
        FROM CSUMWIPOPR A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
        WHERE A.FACTORY = 'IJDK1'
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.AREA_ID = 'GRT'
            AND A.OPER IN ('OG02010')  
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) A,
       (
        -- 투입 공수
        SELECT SUM(TOTAL_WORK_TIME) TOTAL_WORK_TIME,
            SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN TOTAL_WORK_TIME END) WEEK_WORK_TIME  
          FROM CWIPWRKINP A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
         WHERE A.FACTORY = 'IJDK1'
            AND A.AREA_ID = 'GRT'
            AND A.OPER = 'GP002'  -- 합성
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) B,
       (
        -- 목표 생산성
         SELECT MAX(CASE WHEN CLASS='MONTH' AND WEEK_OF_MONTH=1 THEN A.GOAL_PRODUCTVITY END) AS PROD_GOAL_PROD,
                MAX(CASE WHEN CLASS='WEEK' AND WEEK_OF_MONTH = CAL_CMF_1 THEN A.GOAL_PRODUCTVITY END) AS WEEK_GOAL_PROD            
         FROM CWIPPRDGOL A, (
                SELECT CAL_CMF_1
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) B        
         WHERE A.FACTORY = 'IJDK1'
           AND A.KIND='P'          
		   AND A.CLASS='MONTH'
		   AND A.WEEK_OF_MONTH = 1   
           AND A.AREA_ID = 'GRT'                      
           AND A.SHOP = 'GL002'      -- 합성
           AND A.OPER_GRP = 'GP002'  -- 합성
           AND A.WORK_MONTH = SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 6) 
          
       ) C
;   
	
/*생산성_후처리*/
SELECT ROUND(NVL(PROD_GOAL_PROD,0)/1000,2) GOAL_M,                                                    -- 계획    
       ROUND(NVL(WEEK_GOAL_PROD,0)/1000,2) GOAL_W,                                   
       NVL(ROUND((A.MOM_PROD_QTY/1000) / B.TOTAL_WORK_TIME, 2),0) AS MONTH_PROD_RESULT,                -- 당월 실적
       NVL(ROUND((A.MOM_PROD_QTY)*100 / B.TOTAL_WORK_TIME / (PROD_GOAL_PROD),1),0) AS MONTH_PROD_RATE,  -- 당월 달성률
       NVL(ROUND((A.WEEK_PROD_QTY/1000) / B.WEEK_WORK_TIME, 2),0) AS WEEK_PROD_RESULT,                  -- 주간 실적
       NVL(ROUND((A.WEEK_PROD_QTY)*100 / B.WEEK_WORK_TIME / (WEEK_GOAL_PROD),1),0) AS WEEK_PROD_RATE    -- 주간 달성률
      ,CASE WHEN NVL(PROD_GOAL_PROD,0) > ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
            WHEN NVL(PROD_GOAL_PROD,0) < ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND((NVL(A.MOM_PROD_QTY,0)/1000) / B.TOTAL_WORK_TIME, 2)
            ELSE ROUND(NVL(PROD_GOAL_PROD,0)/1000,2) END
       AS MAX_VAL_MON
      ,CASE WHEN NVL(WEEK_GOAL_PROD,0) > ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
            WHEN NVL(WEEK_GOAL_PROD,0) < ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND((NVL(A.WEEK_PROD_QTY,0)/1000) / B.WEEK_WORK_TIME, 2)
            ELSE ROUND(NVL(WEEK_GOAL_PROD,0)/1000,2) END
       AS MAX_VAL_WEEK                     
  FROM (        
        -- 건조 실적량 + Dia-건조 실적량 + cBN-건조 실적량  실적량 
         SELECT SUM(PROD_QTY) MOM_PROD_QTY, 
           SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN PROD_QTY END) WEEK_PROD_QTY 
        FROM CSUMWIPOPR A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
        WHERE A.FACTORY = 'IJDK1'
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.AREA_ID = 'GRT'
            AND A.OPER IN ('OG04050','OG06060','OG06330')            
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) A,
       (
        -- 투입 공수
        SELECT SUM(TOTAL_WORK_TIME) TOTAL_WORK_TIME, 
            SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN TOTAL_WORK_TIME END) WEEK_WORK_TIME 
          FROM CWIPWRKINP A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
         WHERE A.FACTORY = 'IJDK1'
            AND A.AREA_ID = 'GRT'
            AND A.OPER = 'GP003'  -- 후처리
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) B,
       (
        -- 목표 생산성
         SELECT MAX(CASE WHEN CLASS='MONTH' AND WEEK_OF_MONTH=1 THEN A.GOAL_PRODUCTVITY END) AS PROD_GOAL_PROD,
                MAX(CASE WHEN CLASS='WEEK' AND WEEK_OF_MONTH = PLAN_WEEK THEN A.GOAL_PRODUCTVITY END) AS WEEK_GOAL_PROD            
         FROM CWIPPRDGOL A, (
                SELECT SUBSTR(SYS_DATE,1,6) PLAN_MONTH, PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) B        
         WHERE A.FACTORY = 'IJDK1'
           AND A.KIND='P'              
           AND A.AREA_ID = 'GRT'                      
           AND A.SHOP = 'GL003'      -- 후처리
           AND A.OPER_GRP = 'GP003'  -- 후처리
           AND A.WORK_MONTH=B.PLAN_MONTH          
       ) C
       
;   
 
/*생산성_분류/준비*/
SELECT ROUND(NVL(PROD_GOAL_PROD,0)/1000,0) GOAL_M,                                                    -- 계획    
       ROUND(NVL(WEEK_GOAL_PROD,0)/1000,0) GOAL_W,                             
       NVL(ROUND((A.MOM_PROD_QTY/1000) / B.TOTAL_WORK_TIME, 2),0) AS MONTH_PROD_RESULT,                -- 당월 실적
       NVL(ROUND((A.MOM_PROD_QTY/1000) / B.TOTAL_WORK_TIME, 2) / (PROD_GOAL_PROD/1000),0) AS MONTH_PROD_RATE,  -- 당월 달성률
       NVL(ROUND((A.WEEK_PROD_QTY/1000) / B.WEEK_WORK_TIME, 2),0) AS WEEK_PROD_RESULT,                  -- 주간 실적
       NVL(ROUND((A.WEEK_PROD_QTY/1000) / B.WEEK_WORK_TIME, 2) / (WEEK_GOAL_PROD/1000),0) AS WEEK_PROD_RATE    -- 주간 달성률
	  ,CASE WHEN NVL(PROD_GOAL_PROD,0) > ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
			WHEN NVL(PROD_GOAL_PROD,0) < ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND((NVL(A.MOM_PROD_QTY,0)/1000) / B.TOTAL_WORK_TIME, 2)
			ELSE ROUND(NVL(PROD_GOAL_PROD,0)/1000,2) END
	   AS MAX_VAL_MON
	  ,CASE WHEN NVL(WEEK_GOAL_PROD,0) > ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
			WHEN NVL(WEEK_GOAL_PROD,0) < ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND((NVL(A.WEEK_PROD_QTY,0)/1000) / B.WEEK_WORK_TIME, 2)
			ELSE ROUND(NVL(WEEK_GOAL_PROD,0)/1000,2) END
	   AS MAX_VAL_WEEK                                  
  FROM (
         /* 생산 실적:
			(SAW-Blending + IMD-Blending + T-Blending + cBN-Blending
			+ SAW-사이즈 + T-사이즈 분류 + K-사이즈 분류 +
			+ SAW-손체질 + IMD-손체질 + T-손체질 + cBN-손체질 + IMD-사이즈 분류(RECYCLE)) Move량*/
         SELECT SUM(PROD_QTY) MOM_PROD_QTY, --당월실적
           SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN PROD_QTY END) WEEK_PROD_QTY -- 주간 실적   
        FROM CSUMWIPOPR A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
        WHERE A.FACTORY = 'IJDK1'
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.AREA_ID = 'GRT'
			AND A.OPER IN ('OG06130', 'OG06210', 'OG06010', 'OG06140', 'OG06310', 'OG05020', 'OG05220', 'OG06170', 'OG06230', 'OG06070', 'OG06340','OG05410')    
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) A,
       (
        -- 투입 공수
        SELECT SUM(TOTAL_WORK_TIME) TOTAL_WORK_TIME, --월간
            SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN TOTAL_WORK_TIME END) WEEK_WORK_TIME -- 주간 
          FROM CWIPWRKINP A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
         WHERE A.FACTORY = 'IJDK1'
            AND A.AREA_ID = 'GRT'
            AND A.OPER = 'GP004'  -- 분류/준비
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) B,
       (
        -- 목표 생산성
         SELECT MAX(CASE WHEN CLASS='MONTH' AND WEEK_OF_MONTH=1 THEN A.GOAL_PRODUCTVITY END) AS PROD_GOAL_PROD,
                MAX(CASE WHEN CLASS='WEEK' AND WEEK_OF_MONTH = CAL_CMF_1 THEN A.GOAL_PRODUCTVITY END) AS WEEK_GOAL_PROD            
         FROM CWIPPRDGOL A, (
                SELECT CAL_CMF_1
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) B        
         WHERE A.FACTORY = 'IJDK1'
           AND A.KIND='P'          
		   AND A.CLASS='MONTH'
		   AND A.WEEK_OF_MONTH = 1       
           AND A.AREA_ID = 'GRT'                      
           AND A.SHOP = 'GL004'      -- 분류/준비
           AND A.OPER_GRP = 'GP004'  -- 분류/준비
           AND A.WORK_MONTH = SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 6) 
          
       ) C
;

/*생산성_Ti Coating*/
SELECT ROUND(NVL(PROD_GOAL_PROD,0)/1000,0) GOAL_M,                                                    -- 계획    
       ROUND(NVL(WEEK_GOAL_PROD,0)/1000,0) GOAL_W,                                 
       NVL(ROUND((A.MOM_PROD_QTY/1000) / B.TOTAL_WORK_TIME, 2),0) AS MONTH_PROD_RESULT,                -- 당월 실적
       NVL(ROUND((A.MOM_PROD_QTY/1000) / B.TOTAL_WORK_TIME, 2) / (PROD_GOAL_PROD/1000),0) AS MONTH_PROD_RATE,  -- 당월 달성률
       NVL(ROUND((A.WEEK_PROD_QTY/1000) / B.WEEK_WORK_TIME, 2),0) AS WEEK_PROD_RESULT,                  -- 주간 실적
       NVL(ROUND((A.WEEK_PROD_QTY/1000) / B.WEEK_WORK_TIME, 2) / (WEEK_GOAL_PROD/1000),0) AS WEEK_PROD_RATE    -- 주간 달성률
	  ,CASE WHEN NVL(PROD_GOAL_PROD,0) > ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
			WHEN NVL(PROD_GOAL_PROD,0) < ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND((NVL(A.MOM_PROD_QTY,0)/1000) / B.TOTAL_WORK_TIME, 2)
			ELSE ROUND(NVL(PROD_GOAL_PROD,0)/1000,2) END
	   AS MAX_VAL_MON
	  ,CASE WHEN NVL(WEEK_GOAL_PROD,0) > ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
			WHEN NVL(WEEK_GOAL_PROD,0) < ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND((NVL(A.WEEK_PROD_QTY,0)/1000) / B.WEEK_WORK_TIME, 2)
			ELSE ROUND(NVL(WEEK_GOAL_PROD,0)/1000,2) END
	   AS MAX_VAL_WEEK               
  FROM (
        -- Ti Coating 생산 실적
        -- Sputter-코팅 Move량 + MVD-코팅 Move량 + CVD-코팅 Move량   
         SELECT SUM(PROD_QTY) MOM_PROD_QTY, --당월실적
           SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN PROD_QTY END) WEEK_PROD_QTY -- 주간 실적   
        FROM CSUMWIPOPR A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
        WHERE A.FACTORY = 'IJDK1'
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.AREA_ID = 'GRT'
            AND A.OPER IN ('OG07120', 'OG07220', 'OG07320')          
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) A,
       (
        -- 투입 공수
        SELECT SUM(TOTAL_WORK_TIME) TOTAL_WORK_TIME, --월간
            SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN TOTAL_WORK_TIME END) WEEK_WORK_TIME -- 주간
          FROM CWIPWRKINP A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
         WHERE A.FACTORY = 'IJDK1'
            AND A.AREA_ID = 'GRT'
            AND A.OPER = 'GP006'  -- MP-Ti/Ti Coating
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) B,
       (
        -- 목표 생산성
         SELECT MAX(CASE WHEN CLASS='MONTH' AND WEEK_OF_MONTH=1 THEN A.GOAL_PRODUCTVITY END) AS PROD_GOAL_PROD,
                MAX(CASE WHEN CLASS='WEEK' AND WEEK_OF_MONTH = CAL_CMF_1 THEN A.GOAL_PRODUCTVITY END) AS WEEK_GOAL_PROD            
         FROM CWIPPRDGOL A, (
                SELECT CAL_CMF_1
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) B        
         WHERE A.FACTORY = 'IJDK1'
           AND A.KIND='P'          
		   AND A.CLASS='MONTH'
		   AND A.WEEK_OF_MONTH = 1          
           AND A.AREA_ID = 'GRT'                      
           AND A.SHOP = 'GL006'      -- Ti Coating
           AND A.OPER_GRP = 'GP006'  -- Ti Coating
           AND A.WORK_MONTH = SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 6) 
          
       ) C
;   
/*생산성_CP*/
SELECT ROUND(NVL(PROD_GOAL_PROD,0)/1000,0) GOAL_M,                                                    -- 계획    
       ROUND(NVL(WEEK_GOAL_PROD,0)/1000,0) GOAL_W,                                   
       NVL(ROUND((A.MOM_PROD_QTY/1000) / B.TOTAL_WORK_TIME, 2),0) AS MONTH_PROD_RESULT,                -- 당월 실적
       NVL(ROUND((A.MOM_PROD_QTY/1000) / B.TOTAL_WORK_TIME, 2) / (PROD_GOAL_PROD/1000),0) AS MONTH_PROD_RATE,  -- 당월 달성률
       NVL(ROUND((A.WEEK_PROD_QTY/1000) / B.WEEK_WORK_TIME, 2),0) AS WEEK_PROD_RESULT,                  -- 주간 실적
       NVL(ROUND((A.WEEK_PROD_QTY/1000) / B.WEEK_WORK_TIME, 2) / (WEEK_GOAL_PROD/1000),0) AS WEEK_PROD_RATE    -- 주간 달성률
	  ,CASE WHEN NVL(PROD_GOAL_PROD,0) > ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
			WHEN NVL(PROD_GOAL_PROD,0) < ROUND(NVL(A.MOM_PROD_QTY,0) / B.TOTAL_WORK_TIME, 2) THEN ROUND((NVL(A.MOM_PROD_QTY,0)/1000) / B.TOTAL_WORK_TIME, 2)
			ELSE ROUND(NVL(PROD_GOAL_PROD,0)/1000,2) END
	   AS MAX_VAL_MON
	  ,CASE WHEN NVL(WEEK_GOAL_PROD,0) > ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND(NVL(PROD_GOAL_PROD,0)/1000,2)
			WHEN NVL(WEEK_GOAL_PROD,0) < ROUND(NVL(A.WEEK_PROD_QTY,0) / B.WEEK_WORK_TIME, 2) THEN ROUND((NVL(A.WEEK_PROD_QTY,0)/1000) / B.WEEK_WORK_TIME, 2)
			ELSE ROUND(NVL(WEEK_GOAL_PROD,0)/1000,2) END
	   AS MAX_VAL_WEEK                  
  FROM (
        -- CP 생산 실적
        -- 도금 Move량 ÷ CP (Ni Coating) 투입 공수 시간
         SELECT SUM(PROD_QTY) MOM_PROD_QTY, --당월실적
           SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN PROD_QTY END) WEEK_PROD_QTY -- 주간 실적   
        FROM CSUMWIPOPR A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
        WHERE A.FACTORY = 'IJDK1'
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.AREA_ID = 'GRT'
            AND A.OPER IN ('OG07020')          
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) A,
       (
        -- 투입 공수
        SELECT SUM(TOTAL_WORK_TIME) TOTAL_WORK_TIME, --월간 투입공수
            SUM(CASE WHEN C.PLAN_WEEK = B.PLAN_WEEK THEN TOTAL_WORK_TIME END) WEEK_WORK_TIME -- 주간 투입공수  
          FROM CWIPWRKINP A, MWIPCALDEF B,
               (
                SELECT PLAN_WEEK
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) C         
         WHERE A.FACTORY = 'IJDK1'
            AND A.AREA_ID = 'GRT'
            AND A.OPER = 'GP007'  -- CP (Ni Coating)
            AND A.WORK_DATE BETWEEN F_GET_FIRST_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')) AND F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
            AND A.FACTORY=B.CALENDAR_ID
            AND A.WORK_DATE=B.SYS_DATE
       ) B,
       (
        -- 목표 생산성
         SELECT MAX(CASE WHEN CLASS='MONTH' AND WEEK_OF_MONTH=1 THEN A.GOAL_PRODUCTVITY END) AS PROD_GOAL_PROD,
                MAX(CASE WHEN CLASS='WEEK' AND WEEK_OF_MONTH = CAL_CMF_1 THEN A.GOAL_PRODUCTVITY END) AS WEEK_GOAL_PROD            
         FROM CWIPPRDGOL A, (
                SELECT CAL_CMF_1
                  FROM MWIPCALDEF
                 WHERE CALENDAR_ID = 'IJDK1'
                   AND SYS_DATE = F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'))
               ) B        
         WHERE A.FACTORY = 'IJDK1'
           AND A.KIND='P'          
		   AND A.CLASS='MONTH'
		   AND A.WEEK_OF_MONTH = 1         
           AND A.AREA_ID = 'GRT'                      
		   AND A.SHOP = 'GL007'      -- CP (Ni Coating)
           AND A.OPER_GRP = 'GP007'  -- CP (Ni Coating)
           AND A.WORK_MONTH = SUBSTR(F_GET_WORK_DATE(TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS')), 1, 6) 
          
       ) C
;   
       
       